.ifndef SCR_SEQ_R35_H_
.definelabel SCR_SEQ_R35_H_, 0

.equ _EV_scr_seq_R35_000, 0
.equ _EV_scr_seq_R35_001, 1
.equ _EV_scr_seq_R35_002, 2
.equ _EV_scr_seq_R35_003, 3
.equ _EV_scr_seq_R35_004, 4

.equ obj_R35_policeman, 0
.equ obj_R35_picnicgirl_2, 1
.equ obj_R35_campboy_2, 2
.equ obj_R35_picnicgirl_2_2, 3
.equ obj_R35_campboy_2_2, 4
.equ obj_R35_juggrer, 5
.equ obj_R35_gsboy3, 6
.equ obj_R35_gsman2, 7
.equ obj_R35_policeman_2, 8
.equ obj_R35_monstarball, 9
.equ obj_R35_tree, 10
.equ obj_R35_bonguri, 11
.equ obj_R35_gsmiddleman1, 12
.equ obj_R35_fire, 13
.equ obj_R35_monstarball_2, 14

.endif //SCR_SEQ_R35_H_
