.ifndef SCR_SEQ_W21_H_
.definelabel SCR_SEQ_W21_H_, 0

.equ _EV_scr_seq_W21_000, 0
.equ _EV_scr_seq_W21_001, 1

.equ obj_W21_fishing_2, 0
.equ obj_W21_fishing_2_2, 1
.equ obj_W21_fishing_2_3, 2
.equ obj_W21_fishing_2_4, 3
.equ obj_W21_gsswimmerw, 4
.equ obj_W21_gsswimmerw_2, 5
.equ obj_W21_gsswimmerw_3, 6
.equ obj_W21_gsswimmerm, 7
.equ obj_W21_gsswimmerm_2, 8
.equ obj_W21_gsswimmerm_3, 9
.equ obj_W21_gsman2, 10
.equ obj_W21_gsman2_2, 11
.equ obj_W21_gsmiddleman1, 12
.equ obj_W21_gsbigman, 1

.endif //SCR_SEQ_W21_H_
