.ifndef SCR_SEQ_T20_H_
.definelabel SCR_SEQ_T20_H_, 0

.equ _EV_scr_seq_T20_000, 0
.equ _EV_scr_seq_T20_001, 1
.equ _EV_scr_seq_T20_002, 2
.equ _EV_scr_seq_T20_003, 3
.equ _EV_scr_seq_T20_004, 4
.equ _EV_scr_seq_T20_005, 5
.equ _EV_scr_seq_T20_006, 6
.equ _EV_scr_seq_T20_007, 7
.equ _EV_scr_seq_T20_008, 8
.equ _EV_scr_seq_T20_009, 9
.equ _EV_scr_seq_T20_010, 10
.equ _EV_scr_seq_T20_011, 11
.equ _EV_scr_seq_T20_012, 12
.equ _EV_scr_seq_T20_013, 13
.equ _EV_scr_seq_T20_014, 14
.equ _EV_scr_seq_T20_015, 15
.equ _EV_scr_seq_T20_016, 16
.equ _EV_scr_seq_T20_017, 17

.equ obj_T20_gsrivel, 0
.equ obj_T20_gswoman1, 1
.equ obj_T20_gsbigman, 2
.equ obj_T20_follower_mon_static_marill, 3
.equ obj_T20_var_1, 4
.equ obj_T20_doctor, 5
.equ obj_T20_gsmiddleman1, 6
.equ obj_T20_gsmama, 7
.equ obj_T20_var_1_2, 8
.equ obj_T20_follower_mon_static_marill_2, 9

.endif //SCR_SEQ_T20_H_
