.ifndef SCR_SEQ_D35R0104_H_
.definelabel SCR_SEQ_D35R0104_H_, 0

.equ _EV_scr_seq_D35R0104_000, 0
.equ _EV_scr_seq_D35R0104_001, 1
.equ _EV_scr_seq_D35R0104_002, 2
.equ _EV_scr_seq_D35R0104_003, 3
.equ _EV_scr_seq_D35R0104_004, 4
.equ _EV_scr_seq_D35R0104_005, 5
.equ _EV_scr_seq_D35R0104_006, 6
.equ _EV_scr_seq_D35R0104_007, 7
.equ _EV_scr_seq_D35R0104_008, 8

.equ obj_D35R0104_rocketm, 0
.equ obj_D35R0104_assistantm, 1
.equ obj_D35R0104_assistantm_2, 2
.equ obj_D35R0104_rocketm_2, 3
.equ obj_D35R0104_rocketw, 4
.equ obj_D35R0104_wataru, 5
.equ obj_D35R0104_follower_mon_static_dragonite, 6
.equ obj_D35R0104_gsrivel, 7
.equ obj_D35R0104_rkanbum2, 8
.equ obj_D35R0104_follower_mon_static_murkrow, 9
.equ obj_D35R0104_babyboy1_9, 10
.equ obj_D35R0104_babyboy1_9_2, 11
.equ obj_D35R0104_monstarball, 12
.equ obj_D35R0104_monstarball_2, 13
.equ obj_D35R0104_monstarball_3, 14
.equ obj_D35R0104_monstarball_4, 15
.equ obj_D35R0104_follower_mon_static_murkrow_2, 16
.equ obj_D35R0104_monstarball_5, 17
.equ obj_D35R0104_sakaki, 18

.endif //SCR_SEQ_D35R0104_H_
