.ifndef SCR_SEQ_T22GYM0101_H_
.definelabel SCR_SEQ_T22GYM0101_H_, 0

.equ _EV_scr_seq_T22GYM0101_000, 0
.equ _EV_scr_seq_T22GYM0101_001, 1
.equ _EV_scr_seq_T22GYM0101_002, 2
.equ _EV_scr_seq_T22GYM0101_003, 3
.equ _EV_scr_seq_T22GYM0101_004, 4
.equ _EV_scr_seq_T22GYM0101_005, 5

.equ obj_T22GYM0101_gsleader1, 0
.equ obj_T22GYM0101_gsman2, 1
.equ obj_T22GYM0101_gsman2_2, 2
.equ obj_T22GYM0101_sunglasses, 3
.equ obj_T22GYM0101_sunglasses_2, 4

.endif //SCR_SEQ_T22GYM0101_H_
