.ifndef SCR_SEQ_R08_H_
.definelabel SCR_SEQ_R08_H_, 0

.equ _EV_scr_seq_R08_000, 0
.equ _EV_scr_seq_R08_001, 1

.equ obj_R08_gang, 0
.equ obj_R08_gang_2, 1
.equ obj_R08_gang_3, 2
.equ obj_R08_gsassistantm, 3
.equ obj_R08_gsassistantm_2, 4
.equ obj_R08_gsman2, 5
.equ obj_R08_gswoman2, 6
.equ obj_R08_gsgentleman, 7
.equ obj_R08_tree, 8
.equ obj_R08_tree_2, 9
.equ obj_R08_bonguri, 10
.equ obj_R08_monstarball, 11
.equ obj_R08_gsboy1, 1

.endif //SCR_SEQ_R08_H_
