.ifndef SCR_SEQ_T05R0201_H_
.definelabel SCR_SEQ_T05R0201_H_, 0

.equ _EV_scr_seq_T05R0201_000, 0
.equ _EV_scr_seq_T05R0201_001, 1
.equ _EV_scr_seq_T05R0201_002, 2
.equ _EV_scr_seq_T05R0201_003, 3
.equ _EV_scr_seq_T05R0201_004, 4

.equ obj_T05R0201_gsman1, 0
.equ obj_T05R0201_gsgirl1, 1
.equ obj_T05R0201_follower_mon_static_pidgey, 2
.equ obj_T05R0201_follower_mon_static_psyduck, 3
.equ obj_T05R0201_follower_mon_static_nidorino, 4

.endif //SCR_SEQ_T05R0201_H_
