.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0

.equ obj_EVERYWHERE_rock, 0
.equ obj_EVERYWHERE_monstarball, 1
.equ obj_EVERYWHERE_monstarball_2, 2
.equ obj_EVERYWHERE_monstarball_3, 3
.equ obj_EVERYWHERE_monstarball_4, 4
.equ obj_EVERYWHERE_monstarball_5, 5
.equ obj_EVERYWHERE_monstarball_6, 6
.equ obj_EVERYWHERE_monstarball_7, 7
.equ obj_EVERYWHERE_mania, 8
.equ obj_EVERYWHERE_gsassistantm, 9
.equ obj_EVERYWHERE_monstarball_8, 10
.equ obj_EVERYWHERE_monstarball_9, 11

.endif //SCR_SEQ_EVERYWHERE_H_
