.ifndef SCR_SEQ_R39R0201_H_
.definelabel SCR_SEQ_R39R0201_H_, 0

.equ _EV_scr_seq_R39R0201_000, 0
.equ _EV_scr_seq_R39R0201_001, 1
.equ _EV_scr_seq_R39R0201_002, 2
.equ _EV_scr_seq_R39R0201_003, 3
.equ _EV_scr_seq_R39R0201_004, 4

.equ obj_R39R0201_gsbabygirl1, 0
.equ obj_R39R0201_follower_mon_static_miltank, 1
.equ obj_R39R0201_gsbabygirl1_2, 2
.equ obj_R39R0201_follower_mon_static_miltank_2, 3
.equ obj_R39R0201_follower_mon_static_miltank_3, 4
.equ obj_R39R0201_follower_mon_static_miltank_4, 5
.equ obj_R39R0201_follower_mon_static_miltank_5, 6

.endif //SCR_SEQ_R39R0201_H_
