.ifndef SCR_SEQ_W41_H_
.definelabel SCR_SEQ_W41_H_, 0

.equ _EV_scr_seq_W41_000, 0
.equ _EV_scr_seq_W41_001, 1
.equ _EV_scr_seq_W41_002, 2
.equ _EV_scr_seq_W41_003, 3
.equ _EV_scr_seq_W41_004, 4
.equ _EV_scr_seq_W41_005, 5
.equ _EV_scr_seq_W41_006, 6
.equ _EV_scr_seq_W41_007, 7
.equ _EV_scr_seq_W41_008, 8
.equ _EV_scr_seq_W41_009, 9
.equ _EV_scr_seq_W41_010, 10

.equ obj_W41_gsswimmerm, 0
.equ obj_W41_gsswimmerm_2, 1
.equ obj_W41_gsswimmerm_3, 2
.equ obj_W41_gsswimmerm_4, 3
.equ obj_W41_gsswimmerm_5, 4
.equ obj_W41_gsswimmerw, 5
.equ obj_W41_gsswimmerw_2, 6
.equ obj_W41_gsswimmerw_3, 7
.equ obj_W41_gsswimmerw_4, 8
.equ obj_W41_gsswimmerw_5, 9

.endif //SCR_SEQ_W41_H_
