.ifndef SCR_SEQ_T04GYM0101_H_
.definelabel SCR_SEQ_T04GYM0101_H_, 0

.equ _EV_scr_seq_T04GYM0101_000, 0
.equ _EV_scr_seq_T04GYM0101_001, 1
.equ _EV_scr_seq_T04GYM0101_002, 2
.equ _EV_scr_seq_T04GYM0101_003, 3
.equ _EV_scr_seq_T04GYM0101_004, 4
.equ _EV_scr_seq_T04GYM0101_005, 5
.equ _EV_scr_seq_T04GYM0101_006, 6
.equ _EV_scr_seq_T04GYM0101_007, 7

.equ obj_T04GYM0101_sunglasses, 0
.equ obj_T04GYM0101_gsswimmerw, 1
.equ obj_T04GYM0101_gsswimmerw_2, 2
.equ obj_T04GYM0101_gsswimmerw_3, 3
.equ obj_T04GYM0101_seaman_2, 4
.equ obj_T04GYM0101_seaman_2_2, 5
.equ obj_T04GYM0101_gsleader11, 6
.equ obj_T04GYM0101_rocketm, 7
.equ obj_T04GYM0101_stop, 8
.equ obj_T04GYM0101_stop_2, 9

.endif //SCR_SEQ_T04GYM0101_H_
