.ifndef SCR_SEQ_T27_H_
.definelabel SCR_SEQ_T27_H_, 0

.equ _EV_scr_seq_T27_000, 0
.equ _EV_scr_seq_T27_001, 1
.equ _EV_scr_seq_T27_002, 2
.equ _EV_scr_seq_T27_003, 3
.equ _EV_scr_seq_T27_004, 4
.equ _EV_scr_seq_T27_005, 5
.equ _EV_scr_seq_T27_006, 6
.equ _EV_scr_seq_T27_007, 7
.equ _EV_scr_seq_T27_008, 8
.equ _EV_scr_seq_T27_009, 9
.equ _EV_scr_seq_T27_010, 10
.equ _EV_scr_seq_T27_011, 11
.equ _EV_scr_seq_T27_012, 12
.equ _EV_scr_seq_T27_013, 13
.equ _EV_scr_seq_T27_014, 14
.equ _EV_scr_seq_T27_015, 15
.equ _EV_scr_seq_T27_016, 16

.equ obj_T27_gsgirl1, 0
.equ obj_T27_gsboy1, 1
.equ obj_T27_gsbigman, 2
.equ obj_T27_gsoldman1, 3
.equ obj_T27_gsoldman1_2, 4
.equ obj_T27_gsgirl2, 5
.equ obj_T27_gsrivel, 6
.equ obj_T27_gsoldman1_3, 7
.equ obj_T27_gsmiddleman1, 8

.endif //SCR_SEQ_T27_H_
