.ifndef SCR_SEQ_R39_H_
.definelabel SCR_SEQ_R39_H_, 0

.equ _EV_scr_seq_R39_000, 0
.equ _EV_scr_seq_R39_001, 1
.equ _EV_scr_seq_R39_002, 2
.equ _EV_scr_seq_R39_003, 3
.equ _EV_scr_seq_R39_004, 4
.equ _EV_scr_seq_R39_005, 5
.equ _EV_scr_seq_R39_006, 6
.equ _EV_scr_seq_R39_007, 7

.equ obj_R39_seaman_2, 0
.equ obj_R39_gsmiddleman1, 1
.equ obj_R39_middlewoman1_2, 2
.equ obj_R39_mystery_2, 3
.equ obj_R39_follower_mon_static_miltank, 4
.equ obj_R39_follower_mon_static_miltank_2, 5
.equ obj_R39_follower_mon_static_miltank_3, 6
.equ obj_R39_follower_mon_static_miltank_4, 7
.equ obj_R39_gsgentleman, 8
.equ obj_R39_bonguri, 9
.equ obj_R39_monstarball, 10
.equ obj_R39_gsmiddleman1_2, 11
.equ obj_R39_gsleader9, 12

.endif //SCR_SEQ_R39_H_
