.ifndef SCR_SEQ_D27R0107_H_
.definelabel SCR_SEQ_D27R0107_H_, 0

.equ _EV_scr_seq_D27R0107_000, 0
.equ _EV_scr_seq_D27R0107_001, 1
.equ _EV_scr_seq_D27R0107_002, 2
.equ _EV_scr_seq_D27R0107_003, 3
.equ _EV_scr_seq_D27R0107_004, 4

.equ obj_D27R0107_babyboy1_8, 0
.equ obj_D27R0107_gsleader6, 1
.equ obj_D27R0107_follower_mon_static_ampharos, 2
.equ obj_D27R0107_monstarball, 3
.equ obj_D27R0107_stop, 4

.endif //SCR_SEQ_D27R0107_H_
