.ifndef SCR_SEQ_T30_H_
.definelabel SCR_SEQ_T30_H_, 0

.equ _EV_scr_seq_T30_000, 0
.equ _EV_scr_seq_T30_001, 1
.equ _EV_scr_seq_T30_002, 2
.equ _EV_scr_seq_T30_003, 3
.equ _EV_scr_seq_T30_004, 4
.equ _EV_scr_seq_T30_005, 5
.equ _EV_scr_seq_T30_006, 6
.equ _EV_scr_seq_T30_007, 7
.equ _EV_scr_seq_T30_008, 8
.equ _EV_scr_seq_T30_009, 9
.equ _EV_scr_seq_T30_010, 10
.equ _EV_scr_seq_T30_011, 11
.equ _EV_scr_seq_T30_012, 12
.equ _EV_scr_seq_T30_013, 13
.equ _EV_scr_seq_T30_014, 14
.equ _EV_scr_seq_T30_015, 15
.equ _EV_scr_seq_T30_016, 16

.equ obj_T30_gsman1, 0
.equ obj_T30_gsoldman1, 1
.equ obj_T30_gsfighter, 2
.equ obj_T30_gswoman3, 3
.equ obj_T30_gsboy1, 4
.equ obj_T30_gswoman3_2, 5
.equ obj_T30_gsman1_2, 6
.equ obj_T30_gsoldman1_2, 7
.equ obj_T30_gsboy2, 8
.equ obj_T30_gsmiddleman1, 9

.endif //SCR_SEQ_T30_H_
