.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0

.equ obj_EVERYWHERE_monstarball, 0
.equ obj_EVERYWHERE_monstarball_2, 1
.equ obj_EVERYWHERE_monstarball_3, 2
.equ obj_EVERYWHERE_monstarball_4, 3
.equ obj_EVERYWHERE_breakrock, 4
.equ obj_EVERYWHERE_breakrock_2, 5
.equ obj_EVERYWHERE_breakrock_3, 6
.equ obj_EVERYWHERE_breakrock_4, 7
.equ obj_EVERYWHERE_breakrock_5, 8
.equ obj_EVERYWHERE_breakrock_6, 9
.equ obj_EVERYWHERE_breakrock_7, 10
.equ obj_EVERYWHERE_breakrock_8, 11

.endif //SCR_SEQ_EVERYWHERE_H_
