.ifndef SCR_SEQ_R25_H_
.definelabel SCR_SEQ_R25_H_, 0

.equ _EV_scr_seq_R25_000, 0
.equ _EV_scr_seq_R25_001, 1
.equ _EV_scr_seq_R25_002, 2
.equ _EV_scr_seq_R25_003, 3
.equ _EV_scr_seq_R25_004, 4
.equ _EV_scr_seq_R25_005, 5
.equ _EV_scr_seq_R25_006, 6
.equ _EV_scr_seq_R25_007, 7
.equ _EV_scr_seq_R25_008, 8
.equ _EV_scr_seq_R25_009, 9

.equ obj_R25_gsboy1, 0
.equ obj_R25_gsgirl1, 1
.equ obj_R25_gsboy1_2, 2
.equ obj_R25_gsgirl1_2, 3
.equ obj_R25_gsgirl1_3, 4
.equ obj_R25_campboy_2, 5
.equ obj_R25_gsassistantm, 6
.equ obj_R25_gsman3, 7
.equ obj_R25_gsleader11, 8
.equ obj_R25_gsman1, 9
.equ obj_R25_tree, 10
.equ obj_R25_monstarball, 11
.equ obj_R25_follower_mon_static_suicune, 12
.equ obj_R25_minaki, 13
.equ obj_R25_minaki_2, 14
.equ obj_R25_gsleader11_2, 15

.endif //SCR_SEQ_R25_H_
