.ifndef SCR_SEQ_D18R0102_H_
.definelabel SCR_SEQ_D18R0102_H_, 0

.equ _EV_scr_seq_D18R0102_000, 0
.equ _EV_scr_seq_D18R0102_001, 1
.equ _EV_scr_seq_D18R0102_002, 2

.equ obj_D18R0102_follower_mon_static_suicune, 0
.equ obj_D18R0102_follower_mon_static_entei, 1
.equ obj_D18R0102_follower_mon_static_raikou, 2
.equ obj_D18R0102_minaki, 3
.equ obj_D18R0102_rock, 4
.equ obj_D18R0102_rock_2, 5
.equ obj_D18R0102_rock_3, 6
.equ obj_D18R0102_rock_4, 7
.equ obj_D18R0102_breakrock, 8
.equ obj_D18R0102_breakrock_2, 9
.equ obj_D18R0102_rock_5, 10
.equ obj_D18R0102_monstarball, 11
.equ obj_D18R0102_follower_mon_static_suicune_2, 12

.endif //SCR_SEQ_D18R0102_H_
