.ifndef SCR_SEQ_T03PC0101_H_
.definelabel SCR_SEQ_T03PC0101_H_, 0

.equ _EV_scr_seq_T03PC0101_000, 0
.equ _EV_scr_seq_T03PC0101_001, 1
.equ _EV_scr_seq_T03PC0101_002, 2
.equ _EV_scr_seq_T03PC0101_003, 3
.equ _EV_scr_seq_T03PC0101_004, 4

.equ obj_T03PC0101_pcwoman1, 0
.equ obj_T03PC0101_pcwoman2, 1
.equ obj_T03PC0101_pcwoman2_2, 2
.equ obj_T03PC0101_pcwoman2_3, 3
.equ obj_T03PC0101_gsbabyboy1, 4
.equ obj_T03PC0101_follower_mon_static_jigglypuff, 5
.equ obj_T03PC0101_gsmiddleman1, 6
.equ obj_T03PC0101_gswoman1, 7

.endif //SCR_SEQ_T03PC0101_H_
