.ifndef SCR_SEQ_T24_H_
.definelabel SCR_SEQ_T24_H_, 0

.equ _EV_scr_seq_T24_000, 0
.equ _EV_scr_seq_T24_001, 1
.equ _EV_scr_seq_T24_002, 2
.equ _EV_scr_seq_T24_003, 3
.equ _EV_scr_seq_T24_004, 4
.equ _EV_scr_seq_T24_005, 5
.equ _EV_scr_seq_T24_006, 6
.equ _EV_scr_seq_T24_007, 7
.equ _EV_scr_seq_T24_008, 8
.equ _EV_scr_seq_T24_009, 9
.equ _EV_scr_seq_T24_010, 10
.equ _EV_scr_seq_T24_011, 11
.equ _EV_scr_seq_T24_012, 12
.equ _EV_scr_seq_T24_013, 13
.equ _EV_scr_seq_T24_014, 14
.equ _EV_scr_seq_T24_015, 15

.equ obj_T24_middlewoman1_2, 0
.equ obj_T24_gsboy1, 1
.equ obj_T24_gsmiddleman1, 2
.equ obj_T24_gsgirl1, 3
.equ obj_T24_middlewoman1_2_2, 4
.equ obj_T24_follower_mon_static_suicune, 5
.equ obj_T24_minaki, 6
.equ obj_T24_breakrock, 7
.equ obj_T24_breakrock_2, 8
.equ obj_T24_breakrock_3, 9
.equ obj_T24_breakrock_4, 10
.equ obj_T24_breakrock_5, 11

.endif //SCR_SEQ_T24_H_
