.ifndef SCR_SEQ_R36_H_
.definelabel SCR_SEQ_R36_H_, 0

.equ _EV_scr_seq_R36_000, 0
.equ _EV_scr_seq_R36_001, 1
.equ _EV_scr_seq_R36_002, 2
.equ _EV_scr_seq_R36_003, 3
.equ _EV_scr_seq_R36_004, 4
.equ _EV_scr_seq_R36_005, 5
.equ _EV_scr_seq_R36_006, 6
.equ _EV_scr_seq_R36_007, 7
.equ _EV_scr_seq_R36_008, 8
.equ _EV_scr_seq_R36_009, 9
.equ _EV_scr_seq_R36_010, 10

.equ obj_R36_gsbigman, 0
.equ obj_R36_gsgirl1, 1
.equ obj_R36_mystery_2, 2
.equ obj_R36_gsboy1, 3
.equ obj_R36_usokky, 4
.equ obj_R36_gsgirl1_2, 5
.equ obj_R36_gsboy1_2, 6
.equ obj_R36_bonguri, 7
.equ obj_R36_monstarball, 8

.endif //SCR_SEQ_R36_H_
