.ifndef SCR_SEQ_R47_H_
.definelabel SCR_SEQ_R47_H_, 0

.equ _EV_scr_seq_R47_000, 0
.equ _EV_scr_seq_R47_001, 1
.equ _EV_scr_seq_R47_002, 2
.equ _EV_scr_seq_R47_003, 3
.equ _EV_scr_seq_R47_004, 4

.equ obj_R47_monstarball, 0
.equ obj_R47_monstarball_2, 1
.equ obj_R47_monstarball_3, 2
.equ obj_R47_monstarball_4, 3
.equ obj_R47_mount_2, 4
.equ obj_R47_leader3, 5
.equ obj_R47_gsman3, 6
.equ obj_R47_gswoman3, 7
.equ obj_R47_campboy_2, 8
.equ obj_R47_gsman2, 9
.equ obj_R47_gswoman2, 10
.equ obj_R47_mount_2_2, 11
.equ obj_R47_gsleader5, 12

.endif //SCR_SEQ_R47_H_
