.ifndef SCR_SEQ_R03_H_
.definelabel SCR_SEQ_R03_H_, 0

.equ _EV_scr_seq_R03_000, 0
.equ _EV_scr_seq_R03_001, 1
.equ _EV_scr_seq_R03_002, 2
.equ _EV_scr_seq_R03_003, 3
.equ _EV_scr_seq_R03_004, 4

.equ obj_R03_gsboy2, 0
.equ obj_R03_fire, 1
.equ obj_R03_gsboy2_2, 2
.equ obj_R03_gsman3, 3
.equ obj_R03_gswoman3, 4
.equ obj_R03_fire_2, 5
.equ obj_R03_mount_2, 6
.equ obj_R03_gsfighter, 7
.equ obj_R03_gsfighter_2, 8
.equ obj_R03_mount_2_2, 9
.equ obj_R03_gsboy2_3, 10
.equ obj_R03_monstarball, 11
.equ obj_R03_breakrock, 12
.equ obj_R03_breakrock_2, 13
.equ obj_R03_breakrock_3, 14
.equ obj_R03_breakrock_4, 15
.equ obj_R03_breakrock_5, 16
.equ obj_R03_breakrock_6, 17
.equ obj_R03_breakrock_7, 18

.endif //SCR_SEQ_R03_H_
