.ifndef SCR_SEQ_T25GYM0101_H_
.definelabel SCR_SEQ_T25GYM0101_H_, 0

.equ _EV_scr_seq_T25GYM0101_000, 0
.equ _EV_scr_seq_T25GYM0101_001, 1
.equ _EV_scr_seq_T25GYM0101_002, 2
.equ _EV_scr_seq_T25GYM0101_003, 3
.equ _EV_scr_seq_T25GYM0101_004, 4

.equ obj_T25GYM0101_gsleader3, 0
.equ obj_T25GYM0101_gsgirl1, 1
.equ obj_T25GYM0101_gsgirl1_2, 2
.equ obj_T25GYM0101_gswoman2, 3
.equ obj_T25GYM0101_gswoman2_2, 4
.equ obj_T25GYM0101_sunglasses, 5

.endif //SCR_SEQ_T25GYM0101_H_
