.ifndef SCR_SEQ_T07GYM0101_H_
.definelabel SCR_SEQ_T07GYM0101_H_, 0

.equ _EV_scr_seq_T07GYM0101_000, 0
.equ _EV_scr_seq_T07GYM0101_001, 1
.equ _EV_scr_seq_T07GYM0101_002, 2

.equ obj_T07GYM0101_tree, 0
.equ obj_T07GYM0101_tree_2, 1
.equ obj_T07GYM0101_tree_3, 2
.equ obj_T07GYM0101_gsbabygirl1, 3
.equ obj_T07GYM0101_gsbabygirl1_2, 4
.equ obj_T07GYM0101_gsgirl1, 5
.equ obj_T07GYM0101_picnicgirl_2, 6
.equ obj_T07GYM0101_gswoman2, 7
.equ obj_T07GYM0101_gsleader12, 8

.endif //SCR_SEQ_T07GYM0101_H_
