.ifndef SCR_SEQ_T27GYM0101_H_
.definelabel SCR_SEQ_T27GYM0101_H_, 0

.equ _EV_scr_seq_T27GYM0101_000, 0
.equ _EV_scr_seq_T27GYM0101_001, 1
.equ _EV_scr_seq_T27GYM0101_002, 2
.equ _EV_scr_seq_T27GYM0101_003, 3
.equ _EV_scr_seq_T27GYM0101_004, 4
.equ _EV_scr_seq_T27GYM0101_005, 5

.equ obj_T27GYM0101_sunglasses, 0
.equ obj_T27GYM0101_gsleader4, 1
.equ obj_T27GYM0101_itako, 2
.equ obj_T27GYM0101_itako_2, 3
.equ obj_T27GYM0101_itako_3, 4
.equ obj_T27GYM0101_itako_4, 5
.equ obj_T27GYM0101_gsoldman1, 6

.endif //SCR_SEQ_T27GYM0101_H_
