.ifndef SCR_SEQ_T28_H_
.definelabel SCR_SEQ_T28_H_, 0

.equ _EV_scr_seq_T28_000, 0
.equ _EV_scr_seq_T28_001, 1
.equ _EV_scr_seq_T28_002, 2
.equ _EV_scr_seq_T28_003, 3
.equ _EV_scr_seq_T28_004, 4
.equ _EV_scr_seq_T28_005, 5
.equ _EV_scr_seq_T28_006, 6
.equ _EV_scr_seq_T28_007, 7
.equ _EV_scr_seq_T28_008, 8

.equ obj_T28_gsmiddleman1, 0
.equ obj_T28_gsoldman1, 1
.equ obj_T28_gsbigman, 2
.equ obj_T28_gsgirl1, 3

.endif //SCR_SEQ_T28_H_
