.ifndef SCR_SEQ_T08_H_
.definelabel SCR_SEQ_T08_H_, 0

.equ _EV_scr_seq_T08_000, 0
.equ _EV_scr_seq_T08_001, 1
.equ _EV_scr_seq_T08_002, 2
.equ _EV_scr_seq_T08_003, 3
.equ _EV_scr_seq_T08_004, 4
.equ _EV_scr_seq_T08_005, 5
.equ _EV_scr_seq_T08_006, 6
.equ _EV_scr_seq_T08_007, 7
.equ _EV_scr_seq_T08_008, 8
.equ _EV_scr_seq_T08_009, 9

.equ obj_T08_gsmiddleman1, 0
.equ obj_T08_gswoman1, 1
.equ obj_T08_gsboy2, 2
.equ obj_T08_tree, 3
.equ obj_T08_bonguri, 4
.equ obj_T08_gsmiddleman1_2, 5
.equ obj_T08_juggrer, 6

.endif //SCR_SEQ_T08_H_
