.ifndef SCR_SEQ_T08R0601_H_
.definelabel SCR_SEQ_T08R0601_H_, 0

.equ _EV_scr_seq_T08R0601_000, 0
.equ _EV_scr_seq_T08R0601_001, 1
.equ _EV_scr_seq_T08R0601_002, 2
.equ _EV_scr_seq_T08R0601_003, 3

.equ obj_T08R0601_gsgirl1, 0
.equ obj_T08R0601_follower_mon_static_aipom, 1
.equ obj_T08R0601_follower_mon_static_aipom_2, 2
.equ obj_T08R0601_follower_mon_static_aipom_3, 3

.endif //SCR_SEQ_T08R0601_H_
