.ifndef SCR_SEQ_R29_H_
.definelabel SCR_SEQ_R29_H_, 0

.equ _EV_scr_seq_R29_000, 0
.equ _EV_scr_seq_R29_001, 1
.equ _EV_scr_seq_R29_002, 2
.equ _EV_scr_seq_R29_003, 3
.equ _EV_scr_seq_R29_004, 4
.equ _EV_scr_seq_R29_005, 5
.equ _EV_scr_seq_R29_006, 6
.equ _EV_scr_seq_R29_007, 7
.equ _EV_scr_seq_R29_008, 8

.equ obj_R29_gsboy2, 0
.equ obj_R29_gsbigman, 1
.equ obj_R29_gsman1, 2
.equ obj_R29_gswoman2, 3
.equ obj_R29_tree, 4
.equ obj_R29_tree_2, 5
.equ obj_R29_var_2, 6
.equ obj_R29_follower_mon_static_marill, 7
.equ obj_R29_monstarball, 8
.equ obj_R29_bonguri, 9
.equ obj_R29_gswoman2_2, 10

.endif //SCR_SEQ_R29_H_
