.ifndef SCR_SEQ_T04_H_
.definelabel SCR_SEQ_T04_H_, 0

.equ _EV_scr_seq_T04_000, 0
.equ _EV_scr_seq_T04_001, 1
.equ _EV_scr_seq_T04_002, 2
.equ _EV_scr_seq_T04_003, 3
.equ _EV_scr_seq_T04_004, 4
.equ _EV_scr_seq_T04_005, 5
.equ _EV_scr_seq_T04_006, 6
.equ _EV_scr_seq_T04_007, 7
.equ _EV_scr_seq_T04_008, 8
.equ _EV_scr_seq_T04_009, 9
.equ _EV_scr_seq_T04_010, 10
.equ _EV_scr_seq_T04_011, 11
.equ _EV_scr_seq_T04_012, 12
.equ _EV_scr_seq_T04_013, 13

.equ obj_T04_gsman1, 0
.equ obj_T04_gswoman1, 1
.equ obj_T04_follower_mon_static_slowbro, 2
.equ obj_T04_gsbigman, 3
.equ obj_T04_gsman2, 4
.equ obj_T04_gsboy1, 5
.equ obj_T04_gsmiddleman1, 6
.equ obj_T04_gsman1_2, 7

.endif //SCR_SEQ_T04_H_
