.ifndef SCR_SEQ_R14_H_
.definelabel SCR_SEQ_R14_H_, 0

.equ _EV_scr_seq_R14_000, 0
.equ _EV_scr_seq_R14_001, 1
.equ _EV_scr_seq_R14_002, 2
.equ _EV_scr_seq_R14_003, 3
.equ _EV_scr_seq_R14_004, 4
.equ _EV_scr_seq_R14_005, 5

.equ obj_R14_gsmiddleman1, 0
.equ obj_R14_middlewoman1_2, 1
.equ obj_R14_gsman2, 2
.equ obj_R14_gsmiddleman1_2, 3
.equ obj_R14_gsman2_2, 4
.equ obj_R14_gsboy1, 5
.equ obj_R14_gsboy1_2, 6
.equ obj_R14_gsboy1_3, 7
.equ obj_R14_tree, 8
.equ obj_R14_tree_2, 9
.equ obj_R14_gsmiddleman1_3, 10
.equ obj_R14_follower_mon_static_suicune, 11
.equ obj_R14_minaki, 12
.equ obj_R14_minaki_2, 13
.equ obj_R14_tree_3, 14
.equ obj_R14_tree_4, 15
.equ obj_R14_tree_5, 16
.equ obj_R14_gswoman1, 17

.endif //SCR_SEQ_R14_H_
