.ifndef SCR_SEQ_R42_H_
.definelabel SCR_SEQ_R42_H_, 0

.equ _EV_scr_seq_R42_000, 0
.equ _EV_scr_seq_R42_001, 1
.equ _EV_scr_seq_R42_002, 2
.equ _EV_scr_seq_R42_003, 3
.equ _EV_scr_seq_R42_004, 4
.equ _EV_scr_seq_R42_005, 5

.equ obj_R42_fishing_2, 0
.equ obj_R42_mania, 1
.equ obj_R42_mount_2, 2
.equ obj_R42_bonguri, 3
.equ obj_R42_bonguri_2, 4
.equ obj_R42_bonguri_3, 5
.equ obj_R42_monstarball, 6
.equ obj_R42_monstarball_2, 7
.equ obj_R42_monstarball_3, 8
.equ obj_R42_tree, 9
.equ obj_R42_mount_2_2, 10
.equ obj_R42_follower_mon_static_suicune, 11
.equ obj_R42_minaki, 12

.endif //SCR_SEQ_R42_H_
