.ifndef SCR_SEQ_T23_H_
.definelabel SCR_SEQ_T23_H_, 0

.equ _EV_scr_seq_T23_000, 0
.equ _EV_scr_seq_T23_001, 1
.equ _EV_scr_seq_T23_002, 2
.equ _EV_scr_seq_T23_003, 3
.equ _EV_scr_seq_T23_004, 4
.equ _EV_scr_seq_T23_005, 5
.equ _EV_scr_seq_T23_006, 6
.equ _EV_scr_seq_T23_007, 7
.equ _EV_scr_seq_T23_008, 8
.equ _EV_scr_seq_T23_009, 9
.equ _EV_scr_seq_T23_010, 10
.equ _EV_scr_seq_T23_011, 11
.equ _EV_scr_seq_T23_012, 12
.equ _EV_scr_seq_T23_013, 13
.equ _EV_scr_seq_T23_014, 14
.equ _EV_scr_seq_T23_015, 15
.equ _EV_scr_seq_T23_016, 16

.equ obj_T23_rocketm, 0
.equ obj_T23_rocketm_2, 1
.equ obj_T23_gsoldman1, 2
.equ obj_T23_gswoman1, 3
.equ obj_T23_gsman1, 4
.equ obj_T23_follower_mon_static_slowpoke, 5
.equ obj_T23_follower_mon_static_slowpoke_2, 6
.equ obj_T23_follower_mon_static_slowpoke_3, 7
.equ obj_T23_follower_mon_static_slowpoke_4, 8
.equ obj_T23_gsrivel, 9
.equ obj_T23_bonguri, 10
.equ obj_T23_gsmiddleman1, 11
.equ obj_T23_rocketm_3, 12
.equ obj_T23_gsmiddleman1_2, 13

.endif //SCR_SEQ_T23_H_
