# pokegra handled in data/graphics/pokegra.mk

# NARC_FILES handles prereqs for move_narc
# MSGDATA_COMPILETIME_DEPENDENCIES handles prereqs for msgdata

BABYMONS_TARGET := $(FILESYS)/poketool/personal/pms.narc
BABYMONS_DEPENDENCIES := data/BabyMons.c
BABYMONS_OBJS := $(patsubst data/%.c,build/%.o,$(BABYMONS_DEPENDENCIES))
BABYMONS_BIN := $(patsubst data/%.c,build/%.bin,$(BABYMONS_DEPENDENCIES))

$(BABYMONS_BIN): $(BABYMONS_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $< -o $(BABYMONS_OBJS)
	$(OBJCOPY) -O binary $(BABYMONS_OBJS) $@

NARC_FILES += $(BABYMONS_BIN)

MSGDATA_DIR := $(BUILD)/text
MSGDATA_NARC := $(BUILD_NARC)/msg_data.narc
MSGDATA_TARGET := $(FILESYS)/a/0/2/7
MSGDATA_DEPENDENCIES_DIR := data/text
MSGDATA_DEPENDENCIES := $(wildcard $(MSGDATA_DEPENDENCIES_DIR)/*)
MSGDATA_COMPILETIME_DEPENDENCIES_DIR := $(BUILD)/rawtext
#MSGDATA_COMPILETIME_DEPENDENCIES := $(wildcard $(MSGDATA_COMPILETIME_DEPENDENCIES_DIR)/*.txt)
CHARMAP := charmap.txt


$(BUILD)/rawtext/%.txt: $(BUILD_NARC)/a011.narc $(BUILD_NARC)/a055.narc $(BUILD_NARC)/personal.narc $(BUILD_NARC)/trainer_text_map.narc scripts/msg_cat.py
	$(PYTHON) scripts/msg_cat.py $(BUILD)/rawtext

# actual msgdata rule at bottom to allow MSGDATA_COMPILETIME_DEPENDENCIES to be fully defined
NARC_FILES += $(MSGDATA_NARC)
REQUIRED_DIRECTORIES += $(MSGDATA_DIR) $(MSGDATA_COMPILETIME_DEPENDENCIES_DIR)


BATTLEHUD_DIR := $(BUILD)/a007
BATTLEHUD_NARC := $(BUILD_NARC)/a007.narc
BATTLEHUD_TARGET := $(FILESYS)/a/0/0/7
BATTLEHUD_DEPENDENCIES_DIR := rawdata/battle_sprite
BATTLEHUD_DEPENDENCIES := $(wildcard $(BATTLEHUD_DEPENDENCIES_DIR)/*)

$(BATTLEHUD_NARC): $(BATTLEHUD_DEPENDENCIES)
	$(NARCHIVE) extract $(BATTLEHUD_TARGET) -o $(BATTLEHUD_DIR) -nf
	for file in $(BATTLEHUD_DEPENDENCIES_DIR)/*.png; do \
		$(GFX) $$file $(BATTLEHUD_DEPENDENCIES_DIR)/$$(basename $$file .png).NCGR -bitdepth 8; \
		$(GFX) $(BATTLEHUD_DEPENDENCIES_DIR)/$$(basename $$file .png).NCGR $(BATTLEHUD_DEPENDENCIES_DIR)/$$(basename $$file .png).NCGR.lz; \
		$(GFX) $$file $(BATTLEHUD_DEPENDENCIES_DIR)/$$(basename $$file .png).NCLR -bitdepth 8; \
		mv $(BATTLEHUD_DEPENDENCIES_DIR)/$$(basename $$file .png).NCGR.lz $(BATTLEHUD_DIR)/$$(basename $$file .png); \
		export FILENAME_TEMP=$$(basename $$file); \
		mv $(BATTLEHUD_DEPENDENCIES_DIR)/$$(basename $$file .png).NCLR $(BATTLEHUD_DIR)/7_$$(($$(basename $${FILENAME_TEMP#*_} .png)+1)); \
	done
	for file in $(BATTLEHUD_DEPENDENCIES_DIR)/*.pal; do \
		$(GFX) $$file $(BATTLEHUD_DEPENDENCIES_DIR)/$$(basename $$file .pal).NCLR; \
		mv $(BATTLEHUD_DEPENDENCIES_DIR)/$$(basename $$file .pal).NCLR $(BATTLEHUD_DIR)/$$(basename $$file .pal); \
	done
	for file in $(BATTLEHUD_DEPENDENCIES_DIR)/*.NSCR; do \
		cp $$file $(BATTLEHUD_DIR)/$$(basename $$file .NSCR); \
	done
	rm $(BATTLEHUD_DEPENDENCIES_DIR)/*.NCGR
	$(NARCHIVE) create $@ $(BATTLEHUD_DIR) -nf

NARC_FILES += $(BATTLEHUD_NARC)


MOVEDATA_DIR := $(BUILD)/a011
MOVEDATA_NARC := $(BUILD_NARC)/a011.narc
MOVEDATA_TARGET := $(FILESYS)/a/0/1/1
MOVEDATA_BUILD := $(BUILD)/moves
MOVEDATA_DEPENDENCIES := data/Moves.c include/move_data.h include/config.h $(MOVEDATAGEN)
MOVEDATA_NAMES_DIR := $(BUILD)/rawtext/750 $(BUILD)/rawtext/751 $(BUILD)/rawtext/003 $(BUILD)/rawtext/749

$(MOVEDATA_NARC): $(MOVEDATA_DEPENDENCIES)
	mkdir -p $(MOVEDATA_BUILD)
	mkdir -p $(BUILD_NARC)
	rm -rf $(MOVEDATA_DIR)
	mkdir -p $(MOVEDATA_DIR)
	rm -rf $(BUILD)/rawtext/750 $(BUILD)/rawtext/751 $(BUILD)/rawtext/003 $(BUILD)/rawtext/749
	mkdir -p $(MOVEDATA_NAMES_DIR)
	$(MOVEDATAGEN) $(MOVEDATA_DIR) $(BUILD)/rawtext
	$(NARCHIVE) create $@ $(MOVEDATA_DIR) -nf

NARC_FILES += $(MOVEDATA_NARC)
REQUIRED_DIRECTORIES += $(MOVEDATA_DIR) $(MOVEDATA_NAMES_DIR) $(MOVEDATA_BUILD)
MSGDATA_COMPILETIME_DEPENDENCIES += $(BUILD)/rawtext/750.txt $(BUILD)/rawtext/751.txt $(BUILD)/rawtext/003.txt $(BUILD)/rawtext/749.txt

MOVEPARTICLES_DIR := $(BUILD)/a029
MOVEPARTICLES_NARC := $(BUILD_NARC)/a029.narc
MOVEPARTICLES_TARGET := $(FILESYS)/a/0/2/9
MOVEPARTICLES_DEPENDENCIES_DIR := rawdata/move_spa
MOVEPARTICLES_DEPENDENCIES := $(wildcard $(MOVEPARTICLES_DEPENDENCIES_DIR)/*)

$(MOVEPARTICLES_NARC): $(MOVEPARTICLES_DEPENDENCIES)
	$(NARCHIVE) extract $(MOVEPARTICLES_TARGET) -o $(MOVEPARTICLES_DIR) -nf
	cp -r $(MOVEPARTICLES_DEPENDENCIES_DIR)/. $(MOVEPARTICLES_DIR)
	$(NARCHIVE) create $@ $(MOVEPARTICLES_DIR) -nf

NARC_FILES += $(MOVEPARTICLES_NARC)


OPENDEMO_DIR := $(BUILD)/a262
OPENDEMO_NARC := $(BUILD_NARC)/a262.narc
OPENDEMO_TARGET := $(FILESYS)/a/2/6/2
OPENDEMO_DEPENDENCIES_DIR := rawdata/op_demo
OPENDEMO_DEPENDENCIES := $(wildcard $(OPENDEMO_DEPENDENCIES_DIR)/*)

$(OPENDEMO_NARC): $(OPENDEMO_DEPENDENCIES)
	$(NARCHIVE) extract $(OPENDEMO_TARGET) -o $(OPENDEMO_DIR) -nf
	cp -r $(OPENDEMO_DEPENDENCIES_DIR)/. $(OPENDEMO_DIR)
	$(NARCHIVE) create $@ $(OPENDEMO_DIR) -nf

NARC_FILES += $(OPENDEMO_NARC)


MONDATA_DIR := $(BUILD)/a002
MONDATA_NARC := $(BUILD_NARC)/personal.narc
MONDATA_TARGET := $(FILESYS)/a/0/0/2
MONDATA_DEPENDENCIES := data/Species.c include/species_data.h include/config.h $(SPECIESDATAGEN)
MONDATA_NAMES_DIR := $(BUILD)/rawtext/237 $(BUILD)/rawtext/238 $(BUILD)/rawtext/817
MONDATA_DESCRIPTIONS_DIR := $(BUILD)/rawtext/803
MONDATA_CLASSIFICATIONS_DIR := $(BUILD)/rawtext/816 $(BUILD)/rawtext/823
MONDATA_HEIGHTS_DIR := $(BUILD)/rawtext/814 $(BUILD)/rawtext/815
MONDATA_WEIGHTS_DIR := $(BUILD)/rawtext/812 $(BUILD)/rawtext/813

$(MONDATA_NARC): $(MONDATA_DEPENDENCIES)
	mkdir -p $(BUILD_NARC)
	rm -rf $(MONDATA_DIR)
	mkdir -p $(MONDATA_DIR)
	rm -rf $(MONDATA_NAMES_DIR) $(MONDATA_DESCRIPTIONS_DIR) $(MONDATA_CLASSIFICATIONS_DIR) $(MONDATA_HEIGHTS_DIR) $(MONDATA_WEIGHTS_DIR)
	mkdir -p $(MONDATA_NAMES_DIR) $(MONDATA_DESCRIPTIONS_DIR) $(MONDATA_CLASSIFICATIONS_DIR) $(MONDATA_HEIGHTS_DIR) $(MONDATA_WEIGHTS_DIR)
	$(SPECIESDATAGEN) $(MONDATA_DIR) $(BUILD)/rawtext
	$(NARCHIVE) create $@ $(MONDATA_DIR) -nf

NARC_FILES += $(MONDATA_NARC)
REQUIRED_DIRECTORIES += $(MONDATA_DIR) $(MONDATA_NAMES_DIR) $(MONDATA_DESCRIPTIONS_DIR) $(MONDATA_CLASSIFICATIONS_DIR) $(MONDATA_HEIGHTS_DIR) $(MONDATA_WEIGHTS_DIR)
MSGDATA_COMPILETIME_DEPENDENCIES += $(BUILD)/rawtext/237.txt $(BUILD)/rawtext/238.txt $(BUILD)/rawtext/803.txt $(BUILD)/rawtext/812.txt $(BUILD)/rawtext/813.txt $(BUILD)/rawtext/814.txt $(BUILD)/rawtext/815.txt $(BUILD)/rawtext/816.txt $(BUILD)/rawtext/817.txt $(BUILD)/rawtext/823.txt


SPRITEOFFSETS_DIR := $(BUILD)/a180
SPRITEOFFSETS_NARC := $(BUILD_NARC)/spriteoffsets.narc
SPRITEOFFSETS_TARGET := $(FILESYS)/a/1/8/0
SPRITEOFFSETS_DEPENDENCIES := data/SpriteOffsets.c
SPRITEOFFSETS_OBJS := $(patsubst data/%.c,build/%.o,$(SPRITEOFFSETS_DEPENDENCIES))

$(SPRITEOFFSETS_NARC): $(SPRITEOFFSETS_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $(SPRITEOFFSETS_DEPENDENCIES) -o $(SPRITEOFFSETS_OBJS)
	$(O2NARC) $(SPRITEOFFSETS_OBJS) $@ -n

NARC_FILES += $(SPRITEOFFSETS_NARC)


HEIGHT_DIR := $(BUILD)/a005
HEIGHT_NARC := $(BUILD_NARC)/heighttable.narc
HEIGHT_TARGET := $(FILESYS)/a/0/0/5
HEIGHT_DEPENDENCIES := data/HeightTable.c
HEIGHT_OBJS := $(patsubst data/%.c,build/%.o,$(HEIGHT_DEPENDENCIES))

$(HEIGHT_NARC): $(HEIGHT_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $(HEIGHT_DEPENDENCIES) -o $(HEIGHT_OBJS)
	$(O2NARC) $(HEIGHT_OBJS) $@ -n

NARC_FILES += $(HEIGHT_NARC)
REQUIRED_DIRECTORIES += $(HEIGHT_DIR)


DEXAREA_DIR := $(BUILD)/a133
DEXAREA_NARC := $(BUILD_NARC)/dexareas.narc
DEXAREA_TARGET := $(FILESYS)/a/1/3/3
DEXAREA_DEPENDENCIES := data/PokedexArea.c include/pokedex_archive_data.h include/constants/pokedex.h $(POKEDEXDATAGEN)

$(DEXAREA_NARC): $(DEXAREA_DEPENDENCIES)
	mkdir -p $(BUILD_NARC)
	rm -rf $(DEXAREA_DIR)
	mkdir -p $(DEXAREA_DIR)
	$(POKEDEXDATAGEN) a133 $(DEXAREA_DIR)
	$(NARCHIVE) create $@ $(DEXAREA_DIR) -nf

NARC_FILES += $(DEXAREA_NARC)
REQUIRED_DIRECTORIES += $(DEXAREA_DIR)


DEXSORT_DIR := $(BUILD)/a214
DEXSORT_NARC := $(BUILD_NARC)/a214.narc
DEXSORT_TARGET := $(FILESYS)/a/2/1/4
DEXSORT_DEPENDENCIES := data/PokedexSort.c include/pokedex_archive_data.h $(POKEDEXDATAGEN) $(SPECIESDATAGEN) data/Species.c include/species_data.h

$(DEXSORT_NARC): $(DEXSORT_DEPENDENCIES)
	mkdir -p $(BUILD_NARC)
	rm -rf $(DEXSORT_DIR)
	mkdir -p $(DEXSORT_DIR)
	$(SPECIESDATAGEN) --pokedex-sort $(DEXSORT_DIR)
	$(POKEDEXDATAGEN) a214 $(DEXSORT_DIR)
	$(NARCHIVE) create $@ $(DEXSORT_DIR) -nf

NARC_FILES += $(DEXSORT_NARC)
REQUIRED_DIRECTORIES += $(DEXSORT_DIR)


EVOS_DIR := $(BUILD)/a034
EVOS_NARC := $(BUILD_NARC)/a034.narc
EVOS_TARGET := $(FILESYS)/a/0/3/4
EVOS_DEPENDENCIES := data/Evolutions.c
EVOS_OBJS := $(patsubst data/%.c,$(BUILD)/%.o,$(EVOS_DEPENDENCIES))

$(EVOS_NARC): $(EVOS_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $(EVOS_DEPENDENCIES) -o $(EVOS_OBJS)
	$(O2NARC) $(EVOS_OBJS) $@ -n

NARC_FILES += $(EVOS_NARC)
REQUIRED_DIRECTORIES += $(EVOS_DIR)


REGIONALDEX_DIR := $(BUILD)/a138
REGIONALDEX_NARC := $(BUILD_NARC)/a138.narc
REGIONALDEX_TARGET := $(FILESYS)/a/1/3/8
REGIONALDEX_DEPENDENCIES := data/RegionalDex.c
REGIONALDEX_OBJS := $(patsubst data/%.c,build/%.o,$(REGIONALDEX_DEPENDENCIES))
REGIONALDEX_BIN := $(REGIONALDEX_DIR)/pokezukan.bin

$(REGIONALDEX_NARC): $(REGIONALDEX_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $(REGIONALDEX_DEPENDENCIES) -o $(REGIONALDEX_OBJS)
	$(OBJCOPY) -O binary $(REGIONALDEX_OBJS) $(REGIONALDEX_BIN)
	$(NARCHIVE) create $@ $(REGIONALDEX_DIR) -nf

NARC_FILES += $(REGIONALDEX_NARC)
REQUIRED_DIRECTORIES += $(REGIONALDEX_DIR)


TRAINERDATA_DIR := $(BUILD)/a055
TRAINERDATA_DIR_2 := $(BUILD)/a056
TRAINERDATA_NARC := $(BUILD_NARC)/a055.narc
TRAINERDATA_NARC_2 := $(BUILD_NARC)/a056.narc
TRAINERDATA_TARGET := $(FILESYS)/a/0/5/5
TRAINERDATA_TARGET_2 := $(FILESYS)/a/0/5/6
TRAINERDATA_DEPENDENCIES := $(BUILD)/trainers/.generated
TRAINERDATA_TRAINER_NAMES_DIR := $(BUILD)/rawtext/729

$(TRAINERDATA_NARC): $(TRAINERDATA_DEPENDENCIES)
	$(NARCHIVE) create $@ $(TRAINERDATA_DIR) -nf
	$(NARCHIVE) create $(TRAINERDATA_NARC_2) $(TRAINERDATA_DIR_2) -nf

NARC_FILES += $(TRAINERDATA_NARC)
REQUIRED_DIRECTORIES += $(TRAINERDATA_DIR) $(TRAINERDATA_DIR_2) $(TRAINERDATA_TRAINER_NAMES_DIR)
MSGDATA_COMPILETIME_DEPENDENCIES += $(BUILD)/rawtext/729.txt


TRAINERTEXT_DIR := $(BUILD)/trainer_text_map
TRAINERTEXT_DIR_2 := $(BUILD)/trainer_text_offsets
TRAINERTEXT_NARC := $(BUILD_NARC)/trainer_text_map.narc
TRAINERTEXT_NARC_2 := $(BUILD_NARC)/trainer_text_offsets.narc
TRAINERTEXT_TARGET := $(FILESYS)/a/0/5/7
TRAINERTEXT_TARGET_2 := $(FILESYS)/a/1/3/1
TRAINERTEXT_DEPENDENCIES := $(BUILD)/trainers/.generated

$(TRAINERTEXT_NARC): $(TRAINERTEXT_DEPENDENCIES)
	$(NARCHIVE) create $(TRAINERTEXT_NARC) $(TRAINERTEXT_DIR)
	$(NARCHIVE) create $(TRAINERTEXT_NARC_2) $(TRAINERTEXT_DIR_2)

NARC_FILES += $(TRAINERTEXT_NARC)
REQUIRED_DIRECTORIES += $(TRAINERTEXT_DIR) $(TRAINERTEXT_DIR_2) $(BUILD)/rawtext/728
MSGDATA_COMPILETIME_DEPENDENCIES += $(BUILD)/rawtext/728.txt

$(BUILD)/trainers/.generated: data/Trainers.c include/trainer_data.h include/constants/trainerclass.h include/constants/pokemon.h $(TRAINERDATAGEN)
	mkdir -p $(BUILD)/trainers
	mkdir -p $(BUILD_NARC)
	rm -rf $(TRAINERDATA_DIR) $(TRAINERDATA_DIR_2) $(TRAINERTEXT_DIR) $(TRAINERTEXT_DIR_2) $(BUILD)/rawtext/728 $(BUILD)/rawtext/729
	mkdir -p $(TRAINERDATA_DIR) $(TRAINERDATA_DIR_2) $(TRAINERTEXT_DIR) $(TRAINERTEXT_DIR_2) $(BUILD)/rawtext/728 $(BUILD)/rawtext/729
	$(TRAINERDATAGEN) $(TRAINERDATA_DIR) $(TRAINERDATA_DIR_2) $(TRAINERTEXT_DIR) $(TRAINERTEXT_DIR_2) $(BUILD)/rawtext
	touch $@

#FOOTPRINTS_DIR := $(BUILD)/a069
FOOTPRINTS_NARC := $(BUILD_NARC)/a069.narc
FOOTPRINTS_TARGET := $(FILESYS)/a/0/6/9
FOOTPRINTS_DEPENDENCIES_DIR := rawdata/footprints
FOOTPRINTS_DEPENDENCIES := $(wildcard $(FOOTPRINTS_DEPENDENCIES_DIR)/*)

$(FOOTPRINTS_NARC): $(FOOTPRINTS_DEPENDENCIES)
	$(NARCHIVE) create $@ $(FOOTPRINTS_DEPENDENCIES_DIR) -nf

NARC_FILES += $(FOOTPRINTS_NARC)


MOVE_ANIM_SCRIPT_OUTPUT_DIR := $(BUILD)/move
REQUIRED_DIRECTORIES += $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)


MOVEANIM_DIR := $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)/move_anim
MOVEANIM_NARC := $(BUILD_NARC)/a010.narc
MOVEANIM_TARGET := $(FILESYS)/a/0/1/0
MOVEANIM_DEPENDENCIES_DIR := armips/move/move_anim

MOVEANIM_SRCS := $(wildcard $(MOVEANIM_DEPENDENCIES_DIR)/*.s)
MOVEANIM_OBJS := $(patsubst $(MOVEANIM_DEPENDENCIES_DIR)/%.s,$(MOVEANIM_DIR)/0_%,$(MOVEANIM_SRCS))

$(MOVEANIM_DIR)/0_%:$(MOVEANIM_DEPENDENCIES_DIR)/%.s
	$(ARMIPS) $<

$(MOVEANIM_NARC): $(MOVEANIM_OBJS)
	$(NARCHIVE) create $@ $(MOVEANIM_DIR) -nf

NARC_FILES += $(MOVEANIM_NARC)
REQUIRED_DIRECTORIES += $(MOVEANIM_DIR)


MOVESUBANIM_DIR := $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)/move_sub_anim
MOVESUBANIM_NARC := $(BUILD_NARC)/a061.narc
MOVESUBANIM_TARGET := $(FILESYS)/a/0/6/1
MOVESUBANIM_DEPENDENCIES_DIR := armips/move/move_sub_anim

MOVESUBANIM_SRCS := $(wildcard $(MOVESUBANIM_DEPENDENCIES_DIR)/*.s)
MOVESUBANIM_OBJS := $(patsubst $(MOVESUBANIM_DEPENDENCIES_DIR)/%.s,$(MOVESUBANIM_DIR)/1_%,$(MOVESUBANIM_SRCS))

$(MOVESUBANIM_DIR)/1_%:$(MOVESUBANIM_DEPENDENCIES_DIR)/%.s
	$(ARMIPS) $<

$(MOVESUBANIM_NARC): $(MOVESUBANIM_OBJS)
	$(NARCHIVE) create $@ $(MOVESUBANIM_DIR) -nf

NARC_FILES += $(MOVESUBANIM_NARC)
REQUIRED_DIRECTORIES += $(MOVESUBANIM_DIR)

clean_anim_scripts:
	rm -rf $(MOVE_ANIM_SCRIPT_OUTPUT_DIR) $(MOVEANIM_NARC) $(MOVESUBANIM_NARC)

MOVE_SEQ_DIR := $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)/battle_move_seq
MOVE_SEQ_OBJ_DIR := $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)/objects/battle_move_seq
MOVE_SEQ_NARC := $(BUILD_NARC)/a000.narc
MOVE_SEQ_TARGET := $(FILESYS)/a/0/0/0
MOVE_SEQ_DEPENDENCIES_DIR := data/battle_scripts/moves
MOVE_SEQ_CUSTOM_DIR := $(MOVE_SEQ_DEPENDENCIES_DIR)/custom

MOVE_SEQ_SRCS := $(wildcard $(MOVE_SEQ_DEPENDENCIES_DIR)/*.s)
MOVE_SEQ_CUSTOM_SRCS := $(wildcard $(MOVE_SEQ_CUSTOM_DIR)/*.s)
MOVE_SEQ_OBJS := $(patsubst $(MOVE_SEQ_DEPENDENCIES_DIR)/%.s,$(MOVE_SEQ_DIR)/0_%,$(MOVE_SEQ_SRCS))
MOVE_SEQ_OBJS += $(patsubst $(MOVE_SEQ_CUSTOM_DIR)/%.s,$(MOVE_SEQ_DIR)/1_%,$(MOVE_SEQ_CUSTOM_SRCS))

$(MOVE_SEQ_DIR)/0_%:$(MOVE_SEQ_DEPENDENCIES_DIR)/%.s
	$(AS) -c $< -o $(patsubst $(MOVE_SEQ_DEPENDENCIES_DIR)/%.s,$(MOVE_SEQ_OBJ_DIR)/0_%.o,$<)
	$(LD) -T $(C_SUBDIR)/linker.ld -o $(patsubst $(MOVE_SEQ_DEPENDENCIES_DIR)/%.s,$(MOVE_SEQ_OBJ_DIR)/0_%_linked.o,$<) $(patsubst $(MOVE_SEQ_DEPENDENCIES_DIR)/%.s,$(MOVE_SEQ_OBJ_DIR)/0_%.o,$<)
	$(OBJCOPY) -O binary $(patsubst $(MOVE_SEQ_DEPENDENCIES_DIR)/%.s,$(MOVE_SEQ_OBJ_DIR)/0_%_linked.o,$<) $@

$(MOVE_SEQ_DIR)/1_%:$(MOVE_SEQ_CUSTOM_DIR)/%.s
	$(AS) -c $< -o $(patsubst $(MOVE_SEQ_CUSTOM_DIR)/%.s,$(MOVE_SEQ_OBJ_DIR)/1_%.o,$<)
	$(LD) -T $(C_SUBDIR)/linker.ld -o $(patsubst $(MOVE_SEQ_CUSTOM_DIR)/%.s,$(MOVE_SEQ_OBJ_DIR)/1_%_linked.o,$<) $(patsubst $(MOVE_SEQ_CUSTOM_DIR)/%.s,$(MOVE_SEQ_OBJ_DIR)/1_%.o,$<)
	$(OBJCOPY) -O binary $(patsubst $(MOVE_SEQ_CUSTOM_DIR)/%.s,$(MOVE_SEQ_OBJ_DIR)/1_%_linked.o,$<) $@

$(MOVE_SEQ_NARC): $(MOVE_SEQ_OBJS)
	$(NARCHIVE) create $@ $(MOVE_SEQ_DIR) -nf

$(OUTPUT):$(LINK)

NARC_FILES += $(MOVE_SEQ_NARC)
REQUIRED_DIRECTORIES += $(MOVE_SEQ_DIR) $(MOVE_SEQ_OBJ_DIR)


BATTLE_EFF_DIR := $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)/battle_eff_seq
BATTLE_EFF_OBJ_DIR := $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)/objects/battle_eff_seq
BATTLE_EFF_NARC := $(BUILD_NARC)/a030.narc
BATTLE_EFF_TARGET := $(FILESYS)/a/0/3/0
BATTLE_EFF_DEPENDENCIES_DIR := data/battle_scripts/effects
BATTLE_EFF_CUSTOM_DIR := $(BATTLE_EFF_DEPENDENCIES_DIR)/custom

BATTLE_EFF_SRCS := $(wildcard $(BATTLE_EFF_DEPENDENCIES_DIR)/*.s)
BATTLE_EFF_CUSTOM_SRCS := $(wildcard $(BATTLE_EFF_CUSTOM_DIR)/*.s)
BATTLE_EFF_OBJS := $(patsubst $(BATTLE_EFF_DEPENDENCIES_DIR)/%.s,$(BATTLE_EFF_DIR)/0_%,$(BATTLE_EFF_SRCS))
BATTLE_EFF_OBJS += $(patsubst $(BATTLE_EFF_CUSTOM_DIR)/%.s,$(BATTLE_EFF_DIR)/1_%,$(BATTLE_EFF_CUSTOM_SRCS))

$(BATTLE_EFF_DIR)/0_%:$(BATTLE_EFF_DEPENDENCIES_DIR)/%.s
	$(AS) -c $< -o $(patsubst $(BATTLE_EFF_DEPENDENCIES_DIR)/%.s,$(BATTLE_EFF_OBJ_DIR)/0_%.o,$<)
	$(LD) -T $(C_SUBDIR)/linker.ld -o $(patsubst $(BATTLE_EFF_DEPENDENCIES_DIR)/%.s,$(BATTLE_EFF_OBJ_DIR)/0_%_linked.o,$<) $(patsubst $(BATTLE_EFF_DEPENDENCIES_DIR)/%.s,$(BATTLE_EFF_OBJ_DIR)/0_%.o,$<)
	$(OBJCOPY) -O binary $(patsubst $(BATTLE_EFF_DEPENDENCIES_DIR)/%.s,$(BATTLE_EFF_OBJ_DIR)/0_%_linked.o,$<) $@

$(BATTLE_EFF_DIR)/1_%:$(BATTLE_EFF_CUSTOM_DIR)/%.s
	$(AS) -c $< -o $(patsubst $(BATTLE_EFF_CUSTOM_DIR)/%.s,$(BATTLE_EFF_OBJ_DIR)/1_%.o,$<)
	$(LD) -T $(C_SUBDIR)/linker.ld -o $(patsubst $(BATTLE_EFF_CUSTOM_DIR)/%.s,$(BATTLE_EFF_OBJ_DIR)/1_%_linked.o,$<) $(patsubst $(BATTLE_EFF_CUSTOM_DIR)/%.s,$(BATTLE_EFF_OBJ_DIR)/1_%.o,$<)
	$(OBJCOPY) -O binary $(patsubst $(BATTLE_EFF_CUSTOM_DIR)/%.s,$(BATTLE_EFF_OBJ_DIR)/1_%_linked.o,$<) $@

$(BATTLE_EFF_NARC): $(BATTLE_EFF_OBJS)
	$(NARCHIVE) create $@ $(BATTLE_EFF_DIR) -nf

NARC_FILES += $(BATTLE_EFF_NARC)
REQUIRED_DIRECTORIES += $(BATTLE_EFF_DIR) $(BATTLE_EFF_OBJ_DIR)


BATTLE_SUB_DIR := $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)/battle_sub_seq
BATTLE_SUB_OBJ_DIR := $(MOVE_ANIM_SCRIPT_OUTPUT_DIR)/objects/battle_sub_seq
BATTLE_SUB_NARC := $(BUILD_NARC)/a001.narc
BATTLE_SUB_TARGET := $(FILESYS)/a/0/0/1
BATTLE_SUB_DEPENDENCIES_DIR := data/battle_scripts/subscripts
BATTLE_SUB_CUSTOM_DIR := $(BATTLE_SUB_DEPENDENCIES_DIR)/custom

BATTLE_SUB_SRCS := $(wildcard $(BATTLE_SUB_DEPENDENCIES_DIR)/*.s)
BATTLE_SUB_CUSTOM_SRCS += $(wildcard $(BATTLE_SUB_CUSTOM_DIR)/*.s)
BATTLE_SUB_OBJS := $(patsubst $(BATTLE_SUB_DEPENDENCIES_DIR)/%.s,$(BATTLE_SUB_DIR)/1_%,$(BATTLE_SUB_SRCS))
BATTLE_SUB_OBJS += $(patsubst $(BATTLE_SUB_CUSTOM_DIR)/%.s,$(BATTLE_SUB_DIR)/2_%,$(BATTLE_SUB_CUSTOM_SRCS))

$(BATTLE_SUB_DIR)/1_%:$(BATTLE_SUB_DEPENDENCIES_DIR)/%.s
	$(AS) -c $< -o $(patsubst $(BATTLE_SUB_DEPENDENCIES_DIR)/%.s,$(BATTLE_SUB_OBJ_DIR)/1_%.o,$<)
	$(LD) -T $(C_SUBDIR)/linker.ld -o $(patsubst $(BATTLE_SUB_DEPENDENCIES_DIR)/%.s,$(BATTLE_SUB_OBJ_DIR)/1_%_linked.o,$<) $(patsubst $(BATTLE_SUB_DEPENDENCIES_DIR)/%.s,$(BATTLE_SUB_OBJ_DIR)/1_%.o,$<)
	$(OBJCOPY) -O binary $(patsubst $(BATTLE_SUB_DEPENDENCIES_DIR)/%.s,$(BATTLE_SUB_OBJ_DIR)/1_%_linked.o,$<) $@

$(BATTLE_SUB_DIR)/2_%:$(BATTLE_SUB_CUSTOM_DIR)/%.s
	$(AS) -c $< -o $(patsubst $(BATTLE_SUB_CUSTOM_DIR)/%.s,$(BATTLE_SUB_OBJ_DIR)/2_%.o,$<)
	$(LD) -T $(C_SUBDIR)/linker.ld -o $(patsubst $(BATTLE_SUB_CUSTOM_DIR)/%.s,$(BATTLE_SUB_OBJ_DIR)/2_%_linked.o,$<) $(patsubst $(BATTLE_SUB_CUSTOM_DIR)/%.s,$(BATTLE_SUB_OBJ_DIR)/2_%.o,$<)
	$(OBJCOPY) -O binary $(patsubst $(BATTLE_SUB_CUSTOM_DIR)/%.s,$(BATTLE_SUB_OBJ_DIR)/2_%_linked.o,$<) $@

$(BATTLE_SUB_NARC): $(BATTLE_SUB_OBJS)
	$(NARCHIVE) create $@ $(BATTLE_SUB_DIR) -nf

NARC_FILES += $(BATTLE_SUB_NARC)
REQUIRED_DIRECTORIES += $(BATTLE_SUB_DIR) $(BATTLE_SUB_OBJ_DIR)

clean_battle_scripts:
	rm -rf $(MOVE_ANIM_SCRIPT_OUTPUT_DIR) $(MOVE_SEQ_NARC) $(BATTLE_SUB_NARC) $(BATTLE_EFF_NARC)

BAGGFX_DIR := $(BUILD)/a015
BAGGFX_NARC := $(BUILD_NARC)/a015.narc
BAGGFX_TARGET := $(FILESYS)/a/0/1/5
BAGGFX_DEPENDENCIES_DIR := data/graphics/bag

BAGGFX_SRCS := $(wildcard $(BAGGFX_DEPENDENCIES_DIR)/*.png)
BAGGFX_OBJS := $(patsubst $(BAGGFX_DEPENDENCIES_DIR)/%.png,$(BAGGFX_DIR)/5_%.NCGR,$(BAGGFX_SRCS))

$(BAGGFX_DIR)/5_%.NCGR:$(BAGGFX_DEPENDENCIES_DIR)/%.png
	$(GFX) $< $@ -clobbersize -version101 -bitdepth 4

$(BAGGFX_NARC): $(BAGGFX_OBJS) $(BAGGFX_PALS)
	$(NARCHIVE) extract $(BAGGFX_TARGET) -o $(BAGGFX_DIR) -nf
	for n in $$(seq 95 $$(expr $$(ls $(BAGGFX_DIR) | wc -l) - 1)); do rm -f $(BAGGFX_DIR)/5_$$n; done
	$(NARCHIVE) create $@ $(BAGGFX_DIR) -nf

NARC_FILES += $(BAGGFX_NARC)
REQUIRED_DIRECTORIES += $(BAGGFX_DIR)

OVERWORLDS_DIR := $(BUILD)/pokemonow
OVERWORLDS_NARC := $(BUILD_NARC)/pokemonow.narc
OVERWORLDS_TARGET := $(FILESYS)/a/0/8/1
OVERWORLDS_DEPENDENCIES_DIR := data/graphics/overworlds

OVERWORLDS_SRCS := $(wildcard $(OVERWORLDS_DEPENDENCIES_DIR)/*.png) $(wildcard $(OVERWORLDS_DEPENDENCIES_DIR)/*.bin) $(wildcard $(OVERWORLDS_DEPENDENCIES_DIR)/*.json) $(wildcard $(OVERWORLDS_DEPENDENCIES_DIR)/*.pal)
OVERWORLDS_OBJS := $(patsubst $(OVERWORLDS_DEPENDENCIES_DIR)/%.png,$(OVERWORLDS_DIR)/1_%.btx0,$(OVERWORLDS_SRCS)) $(patsubst $(OVERWORLDS_DEPENDENCIES_DIR)/%.bin,$(OVERWORLDS_DIR)/1_%.bin,$(OVERWORLDS_SRCS))

OVERWORLDS_CUSTOM_SRCS := $(wildcard $(OVERWORLDS_DEPENDENCIES_DIR)/custom/*.png) $(wildcard $(OVERWORLDS_DEPENDENCIES_DIR)/custom/*.json) $(wildcard $(OVERWORLDS_DEPENDENCIES_DIR)/custom/*.pal)
OVERWORLDS_CUSTOM_OBJS := $(patsubst $(OVERWORLDS_DEPENDENCIES_DIR)/custom/%.png,$(OVERWORLDS_DIR)/2_%.btx0,$(OVERWORLDS_CUSTOM_SRCS))

# add your own overworld sources here
ALL_OVERWORLDS_SRCS += $(OVERWORLDS_SRCS) $(OVERWORLDS_CUSTOM_SRCS)
ALL_OVERWORLDS_OBJS += $(OVERWORLDS_OBJS) $(OVERWORLDS_CUSTOM_OBJS)

$(OVERWORLDS_DIR)/1_%.btx0:$(OVERWORLDS_DEPENDENCIES_DIR)/%.png $(OVERWORLDS_DEPENDENCIES_DIR)/%.json $(OVERWORLDS_DEPENDENCIES_DIR)/%*.pal
	$(BTX) $< $@

$(OVERWORLDS_DIR)/1_%.bin:$(OVERWORLDS_DEPENDENCIES_DIR)/%.bin
	cp -f $< $@

$(OVERWORLDS_DIR)/2_%.btx0:$(OVERWORLDS_DEPENDENCIES_DIR)/custom/%.png $(OVERWORLDS_DEPENDENCIES_DIR)/custom/%.json $(OVERWORLDS_DEPENDENCIES_DIR)/custom/%*.pal
	$(BTX) $< $@

# and then followers are 3_

$(OVERWORLDS_NARC): $(ALL_OVERWORLDS_SRCS) $(ALL_OVERWORLDS_OBJS)
	$(NARCHIVE) create $@ $(OVERWORLDS_DIR) -nf

NARC_FILES += $(OVERWORLDS_NARC)
REQUIRED_DIRECTORIES += $(OVERWORLDS_DIR)


DEXGFX_DIR := $(BUILD)/dexgfx
DEXGFX_NARC := $(BUILD_NARC)/dexgfx.narc
DEXGFX_TARGET := $(FILESYS)/a/0/6/8
DEXGFX_DEPENDENCIES_DIR := rawdata/dex_gfx
DEXGFX_DEPENDENCIES := $(wildcard $(DEXGFX_DEPENDENCIES_DIR)/*)

$(DEXGFX_NARC): $(DEXGFX_DEPENDENCIES)
	$(NARCHIVE) extract $(DEXGFX_TARGET) -o $(DEXGFX_DIR) -nf
	cp -r $(DEXGFX_DEPENDENCIES_DIR)/. $(DEXGFX_DIR)
	$(NARCHIVE) create $@ $(DEXGFX_DIR) -nf

NARC_FILES += $(DEXGFX_NARC)


BATTLEGFX_DIR := $(BUILD)/battlegfx
BATTLEGFX_NARC := $(BUILD_NARC)/battlegfx.narc
BATTLEGFX_TARGET := $(FILESYS)/a/0/0/8
BATTLEGFX_DEPENDENCIES_DIR := rawdata/battle_gfx
BATTLEWEATHERGFX_DEPENDENCIES_DIR := rawdata/weather_icons
BATTLEGFX_DEPENDENCIES := $(wildcard $(BATTLEGFX_DEPENDENCIES_DIR)/*) $(wildcard $(BATTLEWEATHERGFX_DEPENDENCIES_DIR)/*)

ITEM_STYLE_DEPENDENCIES := $(wildcard $(BATTLEWEATHERGFX_DEPENDENCIES_DIR)/*_hud.png)
BATTLEGFX_NOITEM_DEPENDENCIES := $(filter-out $(wildcard $(BATTLEGFX_DEPENDENCIES_DIR)/*),$(filter-out $(ITEM_STYLE_DEPENDENCIES),$(BATTLEGFX_DEPENDENCIES)))

$(BATTLEGFX_NARC): $(BATTLEGFX_DEPENDENCIES)
	$(NARCHIVE) extract $(BATTLEGFX_TARGET) -o $(BATTLEGFX_DIR) -nf
	find $(BATTLEGFX_DIR) -maxdepth 1 -type f -name '8_*' \
	| awk -F'[/_-]' '{n=$$NF; sub(/[^0-9].*/,"",n); if (n >= 346) print $$0}' \
	| xargs -r rm -f
	cp -r $(BATTLEGFX_DEPENDENCIES_DIR)/. $(BATTLEGFX_DIR)
	for file in $(ITEM_STYLE_DEPENDENCIES); do $(GFX) $$file $(BATTLEGFX_DIR)/$$(basename $$file .png)-00.NCGR -clobbersize -version101 -bitdepth 4; $(GFX) $$file $(BATTLEGFX_DIR)/$$(basename $$file .png)-01.NCLR -ir -bitdepth 4; done
	for file in $(BATTLEGFX_NOITEM_DEPENDENCIES); do $(GFX) $$file $(BATTLEGFX_DIR)/$$(basename $$file .png)-00.NCGR; $(GFX) $$file $(BATTLEGFX_DIR)/$$(basename $$file .png)-01.NCLR -bitdepth 8 -nopad -comp 10; done
	for file in $(BATTLEWEATHERGFX_DEPENDENCIES_DIR)/*_terrain.png; do $(GFX) $(BATTLEGFX_DIR)/$$(basename $$file .png)-00.NCGR $(BATTLEGFX_DIR)/$$(basename $$file .png)-00.NCGR.lz; rm $(BATTLEGFX_DIR)/$$(basename $$file .png)-00.NCGR; done
	$(NARCHIVE) create $@ $(BATTLEGFX_DIR) -nf

NARC_FILES += $(BATTLEGFX_NARC)


OTHERPOKE_DIR := $(BUILD)/otherpoke
OTHERPOKE_NARC := $(BUILD_NARC)/otherpoke.narc
OTHERPOKE_TARGET := $(FILESYS)/a/1/1/4
OTHERPOKE_DEPENDENCIES_DIR := rawdata/otherpoke
OTHERPOKE_DEPENDENCIES := $(wildcard $(OTHERPOKE_DEPENDENCIES_DIR)/*)

$(OTHERPOKE_NARC): $(OTHERPOKE_DEPENDENCIES)
	$(NARCHIVE) extract $(OTHERPOKE_TARGET) -o $(OTHERPOKE_DIR) -nf
	@rm -f $(OTHERPOKE_DIR)/4_212 $(OTHERPOKE_DIR)/4_213
	$(GFX) $(OTHERPOKE_DEPENDENCIES_DIR)/arceus-fairy-normal.pal $(OTHERPOKE_DIR)/4_212.NCLR -bitdepth 8 -nopad -comp 10
	$(GFX) $(OTHERPOKE_DEPENDENCIES_DIR)/arceus-fairy-shiny.pal $(OTHERPOKE_DIR)/4_213.NCLR -bitdepth 8 -nopad -comp 10
	$(NARCHIVE) create $@ $(OTHERPOKE_DIR) -nf

NARC_FILES += $(OTHERPOKE_NARC)


ENCOUNTER_DIR := $(BUILD)/a037
ENCOUNTER_NARC := $(BUILD_NARC)/encounters.narc
ENCOUNTER_TARGET := $(FILESYS)/a/0/3/7
ENCOUNTER_DEPENDENCIES := data/Encounters.c
ENCOUNTER_OBJS := $(patsubst data/%.c,$(BUILD)/%.o,$(ENCOUNTER_DEPENDENCIES))

$(ENCOUNTER_NARC): $(ENCOUNTER_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $(ENCOUNTER_DEPENDENCIES) -o $(ENCOUNTER_OBJS)
	$(O2NARC) $(ENCOUNTER_OBJS) $@ -n

NARC_FILES += $(ENCOUNTER_NARC)
REQUIRED_DIRECTORIES += $(ENCOUNTER_DIR)


SAFARI_ENCOUNTER_DIR := $(BUILD)/a230
SAFARI_ENCOUNTER_NARC := $(BUILD_NARC)/safari.narc
SAFARI_ENCOUNTER_TARGET := $(FILESYS)/a/2/3/0
SAFARI_ENCOUNTER_DEPENDENCIES := data/SafariEncounters.c
SAFARI_ENCOUNTER_OBJS := $(patsubst data/%.c,$(BUILD)/%.o,$(SAFARI_ENCOUNTER_DEPENDENCIES))

$(SAFARI_ENCOUNTER_NARC): $(SAFARI_ENCOUNTER_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $(SAFARI_ENCOUNTER_DEPENDENCIES) -o $(SAFARI_ENCOUNTER_OBJS)
	$(O2NARC) $(SAFARI_ENCOUNTER_OBJS) $@

NARC_FILES += $(SAFARI_ENCOUNTER_NARC)
REQUIRED_DIRECTORIES += $(SAFARI_ENCOUNTER_DIR)


SDAT_DIR := $(BUILD)/sdat
SDAT_OBJ_DIR := $(SDAT_DIR)/build
SDAT_FILES_DIR := $(SDAT_DIR)/Files
SDAT_BUILD := $(BUILD_NARC)/gs_sound_data.sdat
SDAT_TARGET := $(FILESYS)/data/sound/gs_sound_data.sdat
SDAT_DEPENDENCIES_DIR := sound/cries

SDAT_SRCS := $(wildcard $(SDAT_DEPENDENCIES_DIR)/*.wav)
SDAT_SWAR_OBJS := $(patsubst $(SDAT_DEPENDENCIES_DIR)/%.wav,$(SDAT_OBJ_DIR)/WAVARC/WAVE_ARC_PV%/00.swav,$(SDAT_SRCS))

$(SDAT_OBJ_DIR)/WAVARC/WAVE_ARC_PV%/00.swav:$(SDAT_DEPENDENCIES_DIR)/%.wav
	mkdir -p $(SDAT_OBJ_DIR)/WAVARC/WAVE_ARC_PV$$(basename "$<" .wav)
	$(NTRWAVTOOL) $< $@ 16384 --adpcm-xq $(ADPCMXQ) --temp-file-dir build/sdat/temp

# we need to unpack the sdat
# move the swav/sbnk over
# swar rebuilding is handled by sdattool
# reorder cries 387+ to be numerical order in the FileBlock.json and InfoBlock.json
$(SDAT_BUILD):$(SDAT_SWAR_OBJS)
	$(SDATTOOL) -u $(SDAT_TARGET) $(SDAT_DIR)
	cp -rf $(SDAT_OBJ_DIR)/* $(SDAT_FILES_DIR)
	@# trigger rebuild here
	rm -rf $(SDAT_FILES_DIR)/WAVARC/*.swar
	$(PYTHON) scripts/rebuild_json.py
	$(SDATTOOL) -b $@ $(SDAT_DIR)

NARC_FILES += $(SDAT_BUILD)
REQUIRED_DIRECTORIES += $(SDAT_DIR) $(SDAT_OBJ_DIR) $(SDAT_OBJ_DIR)/BANK build/sdat/temp

FONT_DIR := $(BUILD)/font
FONT_NARC := $(BUILD_NARC)/font.narc
FONT_TARGET := $(FILESYS)/a/0/1/6
FONT_DEPENDENCIES_DIR := rawdata/font
FONT_DEPENDENCIES := $(wildcard $(FONT_DEPENDENCIES_DIR)/*)

$(FONT_NARC): $(FONT_DEPENDENCIES)
	$(NARCHIVE) extract $(FONT_TARGET) -o $(FONT_DIR) -nf
	cp -r $(FONT_DEPENDENCIES_DIR)/. $(FONT_DIR)
	$(NARCHIVE) create $@ $(FONT_DIR) -nf

NARC_FILES += $(FONT_NARC)

TEXTBOX_DIR := $(BUILD)/textbox
TEXTBOX_NARC := $(BUILD_NARC)/textbox.narc
TEXTBOX_TARGET := $(FILESYS)/a/0/3/8
TEXTBOX_DEPENDENCIES_DIR := rawdata/textbox
TEXTBOX_DEPENDENCIES := $(wildcard $(TEXTBOX_DEPENDENCIES_DIR)/*)

$(TEXTBOX_NARC): $(TEXTBOX_DEPENDENCIES)
	$(NARCHIVE) extract $(TEXTBOX_TARGET) -o $(TEXTBOX_DIR) -nf
	cp -r $(TEXTBOX_DEPENDENCIES_DIR)/. $(TEXTBOX_DIR)
	$(NARCHIVE) create $@ $(TEXTBOX_DIR) -nf

NARC_FILES += $(TEXTBOX_NARC)


BALL_SPA_DIR := $(BUILD)/ball_spa
BALL_SPA_NARC := $(BUILD_NARC)/ball_spa.narc
BALL_SPA_TARGET := $(FILESYS)/a/0/9/5
BALL_SPA_DEPENDENCIES_DIR := rawdata/ball_spa
BALL_SPA_DEPENDENCIES := $(wildcard $(BALL_SPA_DEPENDENCIES_DIR)/*)

$(BALL_SPA_NARC): $(BALL_SPA_DEPENDENCIES)
	$(NARCHIVE) extract $(BALL_SPA_TARGET) -o $(BALL_SPA_DIR) -nf
	cp -r $(BALL_SPA_DEPENDENCIES_DIR)/. $(BALL_SPA_DIR)
	$(NARCHIVE) create $@ $(BALL_SPA_DIR) -nf

NARC_FILES += $(BALL_SPA_NARC)


PW_POKEGRA_DIR := $(BUILD)/pw_pokegra
PW_POKEGRA_ART_DIR := $(BUILD)/pw_pokegra_int
PW_POKEGRA_NARC := $(BUILD_NARC)/pw_pokegra.narc
PW_POKEGRA_TARGET := $(FILESYS)/a/2/5/6
PW_POKEGRA_DEPENDENCIES_DIR := data/graphics/pokewalker/sprites
PW_POKEGRA_DEPENDENCIES := $(wildcard $(PW_POKEGRA_DEPENDENCIES_DIR)/*)
PW_POKEGRA_OBJS := $(patsubst $(PW_POKEGRA_DEPENDENCIES_DIR)/%.png,$(PW_POKEGRA_DIR)/%.lz,$(PW_POKEGRA_DEPENDENCIES))

$(PW_POKEGRA_ART_DIR)/%.2bpp: $(PW_POKEGRA_DEPENDENCIES_DIR)/%.png
	$(ENCODEPWIMG) 0x600 $< $@

$(PW_POKEGRA_DIR)/%.lz: $(PW_POKEGRA_ART_DIR)/%.2bpp
	$(GFX) $< $@

$(PW_POKEGRA_NARC): $(PW_POKEGRA_OBJS)
	$(NARCHIVE) create $@ $(PW_POKEGRA_DIR) -nf

NARC_FILES += $(PW_POKEGRA_NARC)
REQUIRED_DIRECTORIES += $(PW_POKEGRA_DIR) $(PW_POKEGRA_ART_DIR)


PW_POKEICON_DIR := $(BUILD)/pw_pokeicon
PW_POKEICON_ART_DIR := $(BUILD)/pw_pokeicon_int
PW_POKEICON_NARC := $(BUILD_NARC)/pw_pokeicon.narc
PW_POKEICON_TARGET := $(FILESYS)/a/2/4/8
PW_POKEICON_DEPENDENCIES_DIR := data/graphics/pokewalker/icons
PW_POKEICON_DEPENDENCIES := $(wildcard $(PW_POKEICON_DEPENDENCIES_DIR)/*)
PW_POKEICON_OBJS := $(patsubst $(PW_POKEICON_DEPENDENCIES_DIR)/%.png,$(PW_POKEICON_DIR)/%.lz,$(PW_POKEICON_DEPENDENCIES))

$(PW_POKEICON_ART_DIR)/%.2bpp: $(PW_POKEICON_DEPENDENCIES_DIR)/%.png
	$(ENCODEPWIMG) 0x180 $< $@

$(PW_POKEICON_DIR)/%.lz: $(PW_POKEICON_ART_DIR)/%.2bpp
	$(GFX) $< $@

$(PW_POKEICON_NARC): $(PW_POKEICON_OBJS)
	$(NARCHIVE) create $@ $(PW_POKEICON_DIR) -nf

NARC_FILES += $(PW_POKEICON_NARC)
REQUIRED_DIRECTORIES += $(PW_POKEICON_DIR) $(PW_POKEICON_ART_DIR)


SCR_SEQ_DIR := $(BUILD)/a012
SCR_SEQ_NARC := $(BUILD_NARC)/scr_seq.narc
SCR_SEQ_TARGET := $(FILESYS)/a/0/1/2
SCR_SEQ_DEPENDENCIES_DIR := armips/scr_seq
SCR_SEQ_DEPENDENCIES := $(SCR_SEQ_DEPENDENCIES_DIR)/*

$(SCR_SEQ_NARC): $(SCR_SEQ_DEPENDENCIES)
	$(NARCHIVE) extract $(SCR_SEQ_TARGET) -o $(SCR_SEQ_DIR) -nf
	for file in $^; do $(ARMIPS) $$file; done
	$(NARCHIVE) create $@ $(SCR_SEQ_DIR) -nf

# for convenience, rebuild SCR_SEQ_NARC every build so that DSPRE changes are not overwritten
.PHONY: $(SCR_SEQ_NARC)

NARC_FILES += $(SCR_SEQ_NARC)

HEADBUTT_NARC := $(BUILD_NARC)/headbutt.narc
HEADBUTT_TARGET := $(FILESYS)/a/2/5/2
HEADBUTT_DEPENDENCIES := data/Headbutt.c
HEADBUTT_OBJS := $(patsubst data/%.c,build/%.o,$(HEADBUTT_DEPENDENCIES))

$(HEADBUTT_NARC): $(HEADBUTT_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $(HEADBUTT_DEPENDENCIES) -o $(HEADBUTT_OBJS)
	$(O2NARC) $(HEADBUTT_OBJS) $@ -n

NARC_FILES += $(HEADBUTT_NARC)


OVERWORLD_DATA_NARC := $(BUILD_NARC)/overworld_properties.narc
OVERWORLD_DATA_TARGET := $(FILESYS)/a/1/4/1
OVERWORLD_DATA_DEPENDENCIES := data/FollowerProperties.c
OVERWORLD_DATA_OBJS :=  $(patsubst data/%.c,build/%.o,$(OVERWORLD_DATA_DEPENDENCIES))

$(OVERWORLD_DATA_NARC):$(OVERWORLD_DATA_DEPENDENCIES)
	$(CC) $(CFLAGS) -c $(OVERWORLD_DATA_DEPENDENCIES) -o $(OVERWORLD_DATA_OBJS)
	$(O2NARC) $(OVERWORLD_DATA_OBJS) $@ -n

NARC_FILES += $(OVERWORLD_DATA_NARC)


TRAINER_GFX_DIR := $(BUILD)/trainer_gfx
TRAINER_GFX_NARC := $(BUILD_NARC)/trainer_gfx.narc
TRAINER_GFX_TARGET := $(FILESYS)/a/0/5/8
TRAINER_GFX_DEPENDENCIES_DIR := data/graphics/trainer_gfx
TRAINER_GFX_DEPENDENCIES := $(TRAINER_GFX_DEPENDENCIES_DIR)/*

TRAINER_GFX_PICS := $(wildcard $(TRAINER_GFX_DEPENDENCIES_DIR)/*_enc.png)
TRAINER_GFX_NCGR := $(patsubst $(TRAINER_GFX_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_DIR)/8_%-00.NCGR,$(TRAINER_GFX_PICS))
TRAINER_GFX_PALS := $(patsubst $(TRAINER_GFX_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_DIR)/8_%-01.NCLR,$(TRAINER_GFX_PICS))
TRAINER_GFX_NCER := $(patsubst $(TRAINER_GFX_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_DIR)/8_%-02.NCER,$(TRAINER_GFX_PICS))
TRAINER_GFX_NANR := $(patsubst $(TRAINER_GFX_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_DIR)/8_%-03.NANR,$(TRAINER_GFX_PICS))
TRAINER_GFX_NCBR := $(patsubst $(TRAINER_GFX_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_DIR)/8_%-04.NCGR,$(TRAINER_GFX_PICS))
TRAINER_GFX_OBJS := $(TRAINER_GFX_NCGR) $(TRAINER_GFX_PALS) $(TRAINER_GFX_NCER) $(TRAINER_GFX_NANR) $(TRAINER_GFX_NCBR)

$(TRAINER_GFX_DIR)/8_%-00.NCGR:$(TRAINER_GFX_DEPENDENCIES_DIR)/%.png
	$(GFX) $< $@ -clobbersize -version101 -bitdepth 4 -vram -mappingtype 64

$(TRAINER_GFX_DIR)/8_%-01.NCLR:$(TRAINER_GFX_DEPENDENCIES_DIR)/%.png
	$(GFX) $< $@ -ir -bitdepth 4

$(TRAINER_GFX_DIR)/8_%-02.NCER:$(TRAINER_GFX_DEPENDENCIES_DIR)/%_cell.json
	$(GFX) $< $@

$(TRAINER_GFX_DIR)/8_%-03.NANR:$(TRAINER_GFX_DEPENDENCIES_DIR)/%_anim.json
	$(GFX) $< $@

$(TRAINER_GFX_DIR)/8_%-04.NCGR:$(TRAINER_GFX_DEPENDENCIES_DIR)/%_enc.png
	$(GFX) $< $@ -bitdepth 4 -scanned -mwidth 20

$(TRAINER_GFX_NARC): $(TRAINER_GFX_DEPENDENCIES) $(TRAINER_GFX_OBJS)
	$(NARCHIVE) create $@ $(TRAINER_GFX_DIR) -nf

NARC_FILES += $(TRAINER_GFX_NARC)
REQUIRED_DIRECTORIES += $(TRAINER_GFX_DIR)


TRAINER_GFX_BACK_DIR := $(BUILD)/trainer_back_gfx
TRAINER_GFX_BACK_NARC := $(BUILD_NARC)/trainer_back_gfx.narc
TRAINER_GFX_BACK_TARGET := $(FILESYS)/a/0/0/6
TRAINER_GFX_BACK_DEPENDENCIES_DIR := data/graphics/trainer_back_gfx
TRAINER_GFX_BACK_DEPENDENCIES := $(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/*

TRAINER_GFX_BACK_PICS := $(wildcard $(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/*_enc.png)
TRAINER_GFX_BACK_NCGR := $(patsubst $(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_BACK_DIR)/6_%-00.NCGR,$(TRAINER_GFX_BACK_PICS))
TRAINER_GFX_BACK_PALS := $(patsubst $(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_BACK_DIR)/6_%-01.NCLR,$(TRAINER_GFX_BACK_PICS))
TRAINER_GFX_BACK_NCER := $(patsubst $(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_BACK_DIR)/6_%-02.NCER,$(TRAINER_GFX_BACK_PICS))
TRAINER_GFX_BACK_NANR := $(patsubst $(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_BACK_DIR)/6_%-03.NANR,$(TRAINER_GFX_BACK_PICS))
TRAINER_GFX_BACK_NCBR := $(patsubst $(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%_enc.png,$(TRAINER_GFX_BACK_DIR)/6_%-04.NCGR,$(TRAINER_GFX_BACK_PICS))
TRAINER_GFX_BACK_OBJS := $(TRAINER_GFX_BACK_NCGR) $(TRAINER_GFX_BACK_PALS) $(TRAINER_GFX_BACK_NCER) $(TRAINER_GFX_BACK_NANR) $(TRAINER_GFX_BACK_NCBR)

$(TRAINER_GFX_BACK_DIR)/6_%-00.NCGR:$(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%.png
	$(GFX) $< $@ -clobbersize -version101 -bitdepth 4 -vram -mappingtype 64

$(TRAINER_GFX_BACK_DIR)/6_%-01.NCLR:$(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%.png
	$(GFX) $< $@ -ir -bitdepth 4

$(TRAINER_GFX_BACK_DIR)/6_%-02.NCER:$(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%_cell.json
	$(GFX) $< $@

$(TRAINER_GFX_BACK_DIR)/6_%-03.NANR:$(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%_anim.json
	$(GFX) $< $@

$(TRAINER_GFX_BACK_DIR)/6_%-04.NCGR:$(TRAINER_GFX_BACK_DEPENDENCIES_DIR)/%_enc.png
	$(GFX) $< $@ -bitdepth 4 -scanned -mwidth 20

$(TRAINER_GFX_BACK_NARC): $(TRAINER_GFX_BACK_DEPENDENCIES) $(TRAINER_GFX_BACK_OBJS)
	$(NARCHIVE) create $@ $(TRAINER_GFX_BACK_DIR) -nf

NARC_FILES += $(TRAINER_GFX_BACK_NARC)
REQUIRED_DIRECTORIES += $(TRAINER_GFX_BACK_DIR)


clean_trgfx:
	rm -rf $(TRAINER_GFX_DIR) $(TRAINER_GFX_NARC) $(TRAINER_GFX_BACK_DIR) $(TRAINER_GFX_BACK_NARC)


$(MSGDATA_NARC): $(MSGDATA_DEPENDENCIES) $(MSGDATA_COMPILETIME_DEPENDENCIES)
	$(NARCHIVE) extract $(MSGDATA_TARGET) -o $(MSGDATA_DIR) -nf
	for file in $(MSGDATA_DEPENDENCIES); do $(PYTHON) tools/source/dumptools/validate_text_archive.py $(CHARMAP) $$file || exit 1; done
	for file in $^; do $(MSGENC) -e -c $(CHARMAP) $$file $(MSGDATA_DIR)/7_$$(basename $$file .txt); done
	$(NARCHIVE) create $@ $(MSGDATA_DIR) -nf
