#ifndef CONSTANTS_BATTLE_SCRIPT_CONSTANTS_H
#define CONSTANTS_BATTLE_SCRIPT_CONSTANTS_H

#define MOVE_SEQUENCE_NO (22)


// sub sequence defines
#define SUB_SEQ_STAT_STAGE_CHANGE (12)

#define SUB_SEQ_HANDLE_MOLD_BREAKER (177)
#define SUB_SEQ_ABILITY_RECOVERED_HP (178)
#define SUB_SEQ_HANDLE_FLASH_FIRE (179)
#define SUB_SEQ_HANDLE_SOUNDPROOF (181)
#define SUB_SEQ_HANDLE_MOTOR_DRIVE (182)
#define SUB_SEQ_HANDLE_DRIZZLE (183)
#define SUB_SEQ_HANDLE_SAND_STREAM (184)
#define SUB_SEQ_HANDLE_DROUGHT (185)
#define SUB_SEQ_HANDLE_INTIMIDATE (186)
#define SUB_SEQ_HANDLE_TRACE (187)

#define SUB_SEQ_HANDLE_SHED_SKIN (190)

#define SUB_SEQ_HANDLE_ANTICIPATION (194)
#define SUB_SEQ_HANDLE_FOREWARN (195)
#define SUB_SEQ_HANDLE_SLOW_START (196)
#define SUB_SEQ_HANDLE_SLOW_START_END (197)

#define SUB_SEQ_HANDLE_STATUS_HEAL_ABILITIES (221)

#define SUB_SEQ_HANDLE_SNOW_WARNING (252)
#define SUB_SEQ_HANDLE_FRISK (253)

#define SUB_SEQ_OVERWORLD_RAIN (271)
#define SUB_SEQ_OVERWORLD_HAIL (272)
#define SUB_SEQ_OVERWORLD_SANDSTORM (273)
#define SUB_SEQ_OVERWORLD_FOG (274)

#define SUB_SEQ_HANDLE_PRESSURE (285)

#define SUB_SEQ_OVERWORLD_DROUGHT (294)
#define SUB_SEQ_OVERWORLD_TRICK_ROOM (295)

// new sub_seq entries:
#define SUB_SEQ_HANDLE_UNNERVE_MESSAGE (298)












// additional effect constants
#define ADD_STATUS_NONE (0)
#define ADD_STATUS_DIRECT (1)
#define ADD_STATUS_INDIRECT (2)
#define ADD_STATUS_ABILITY (3)
#define ADD_STATUS_WAZA_KOUKA (4)
#define ADD_STATUS_SOUBIITEM (5)
#define ADD_STATUS_DOKUBISI (6)
#define ADD_STATUS_IGNORE (7)

#define	ADD_STAGE_ATTACK_UP (15)
#define	ADD_STAGE_SP_ATK_UP (18)

#endif
