#ifndef CONSTANTS_BATTLE_SCRIPT_CONSTANTS_H
#define CONSTANTS_BATTLE_SCRIPT_CONSTANTS_H

// sub sequence defines
#define SUB_SEQ_ABILITY_RECOVERED_HP (178)
#define SUB_SEQ_HANDLE_FLASH_FIRE (179)
#define SUB_SEQ_HANDLE_SOUNDPROOF (181)
#define SUB_SEQ_HANDLE_MOTOR_DRIVE (182)

#endif
