#ifndef CONSTANTS_BATTLE_SCRIPT_CONSTANTS_H
#define CONSTANTS_BATTLE_SCRIPT_CONSTANTS_H

#define MOVE_SEQUENCE_NO (22)


// sub sequence defines
#define SUB_SEQ_HP_CALC (2)

#define SUB_SEQ_STAT_STAGE_CHANGE (12)

#define SUB_SEQ_HANDLE_FLINCH (14)

#define SUB_SEQ_PUT_MON_TO_SLEEP (18)

#define SUB_SEQ_POISON_MON (22)

#define SUB_SEQ_BURN_MON (25)

#define SUB_SEQ_THAW_WORK_BATTLER_BY_MOVE (29)
#define SUB_SEQ_THAW_ATTACKER_BY_MOVE (30)
#define SUB_SEQ_PARALYZE_MON (31)

#define SUB_SEQ_RECOIL (43)

#define SUB_SEQ_SUBSTITUTE_HIT (90)

#define SUB_SEQ_TRANSFORM (92)

#define SUB_SEQ_HANDLE_CUTE_CHARM (106)

#define SUB_SEQ_HANDLE_MAGIC_COAT_MESSAGE (139)

#define SUB_SEQ_HANDLE_SNATCH (146)

#define SUB_SEQ_HANDLE_MOLD_BREAKER (177)
#define SUB_SEQ_ABILITY_RECOVERED_HP (178)
#define SUB_SEQ_HANDLE_FLASH_FIRE (179)

#define SUB_SEQ_HANDLE_SOUNDPROOF (181)
#define SUB_SEQ_HANDLE_MOTOR_DRIVE (182)
#define SUB_SEQ_HANDLE_DRIZZLE (183)
#define SUB_SEQ_HANDLE_SAND_STREAM (184)
#define SUB_SEQ_HANDLE_DROUGHT (185)
#define SUB_SEQ_HANDLE_INTIMIDATE (186)
#define SUB_SEQ_HANDLE_TRACE (187)
#define SUB_SEQ_HANDLE_COLOR_CHANGE (188)
#define SUB_SEQ_HANDLE_ROUGH_SKIN (189)
#define SUB_SEQ_HANDLE_SHED_SKIN (190)

#define SUB_SEQ_HANDLE_AFTERMATH (193)
#define SUB_SEQ_HANDLE_ANTICIPATION (194)
#define SUB_SEQ_HANDLE_FOREWARN (195)
#define SUB_SEQ_HANDLE_SLOW_START (196)
#define SUB_SEQ_HANDLE_SLOW_START_END (197)

#define SUB_SEQ_HANDLE_ITEM_RESTORE_HP (198)

#define SUB_SEQ_SHELL_BELL_HEAL (213)
#define SUB_SEQ_LIFE_ORB (214)

#define SUB_SEQ_TRANSFER_STICKY_BARB (216)

#define SUB_SEQ_HANDLE_STATUS_HEAL_ABILITIES (221)

#define SUB_SEQ_HANDLE_FOCUS_PUNCH (232)

#define SUB_SEQ_HANDLE_SNOW_WARNING (252)
#define SUB_SEQ_HANDLE_FRISK (253)

#define SUB_SEQ_HANDLE_FORM_CHANGE (262)

#define SUB_SEQ_PHYSICAL_DMG_RECOIL (266)

#define SUB_SEQ_OVERWORLD_RAIN (271)
#define SUB_SEQ_OVERWORLD_HAIL (272)
#define SUB_SEQ_OVERWORLD_SANDSTORM (273)
#define SUB_SEQ_OVERWORLD_FOG (274)

#define SUB_SEQ_HANDLE_PRESSURE (285)

#define SUB_SEQ_MON_REAPPEAR (287)

#define SUB_SEQ_WAIT_FOR_UNPLAYED_ANIMATION (291)

#define SUB_SEQ_CHECK_FORM_CHANGE (293)
#define SUB_SEQ_OVERWORLD_DROUGHT (294)
#define SUB_SEQ_OVERWORLD_TRICK_ROOM (295)
#define SUB_SEQ_GIRATINA_FORM_CHANGE (296)

// new sub_seq entries:
#define SUB_SEQ_HANDLE_MEGA_EVOLUTION (297)
#define SUB_SEQ_HANDLE_UNNERVE_MESSAGE (298)
#define SUB_SEQ_HANDLE_PROTEAN_MESSAGE (299)
#define SUB_SEQ_HANDLE_DARK_AURA_MESSAGE (300)
#define SUB_SEQ_HANDLE_FAIRY_AURA_MESSAGE (301)
#define SUB_SEQ_HANDLE_AURA_BREAK_MESSAGE (302)
#define SUB_SEQ_HANDLE_TURBOBLAZE_MESSAGE (303)
#define SUB_SEQ_HANDLE_TERAVOLT_MESSAGE (304)
#define SUB_SEQ_HANDLE_INNARDS_OUT_MESSAGE (305)
#define SUB_SEQ_HANDLE_MUMMY_MESSAGE (306)
#define SUB_SEQ_HANDLE_WEAK_ARMOR (307)
#define SUB_SEQ_HANDLE_SAP_SIPPER (308)
#define SUB_SEQ_HANDLE_DEFIANT (309)
#define SUB_SEQ_HANDLE_HEALER (310)
#define SUB_SEQ_RAISE_ATTACK_AND_ACCURACY (311)
#define SUB_SEQ_GUARD_SPLIT (312)
#define SUB_SEQ_POWER_SPLIT (313)
#define SUB_SEQ_QUIVER_DANCE (314)
#define SUB_SEQ_CHANGE_TARGET_TO_WATER_TYPE (315)
#define SUB_SEQ_COIL (316)
#define SUB_SEQ_SHIFT_GEAR (317)
#define SUB_SEQ_SHELL_SMASH (318)
#define SUB_SEQ_V_CREATE (319)
#define SUB_SEQ_AUTOTOMIZE (320)
#define SUB_SEQ_HANDLE_HARVEST (321)
#define SUB_SEQ_HANDLE_MOODY (322)
#define SUB_SEQ_HANDLE_LIGHTNING_ROD_RAISE_SPATK (323)
#define SUB_SEQ_HANDLE_PICKPOCKET_DEF (324)
#define SUB_SEQ_HANDLE_PICKPOCKET_ATK (325)
#define SUB_SEQ_HANDLE_IMPOSTER (326)
#define SUB_SEQ_HANDLE_CURSED_BODY (327)
#define SUB_SEQ_HANDLE_PRIMAL_REVERSION (328)
#define SUB_SEQ_HANDLE_MOVE_MEGA_EVOLUTION (329)
#define SUB_SEQ_HANDLE_ILLUSION_FADED (330)
#define SUB_SEQ_HANDLE_GROWTH (331)
#define SUB_SEQ_HANDLE_DISGUISE_ICE_FACE (332)
#define SUB_SEQ_HANDLE_RESTORE_ICE_FACE (333)
#define SUB_SEQ_HANDLE_ZYGARDE_FORM_CHANGE (334)










// additional effect constants
#define ADD_STATUS_NONE (0)
#define ADD_STATUS_DIRECT (1)
#define ADD_STATUS_INDIRECT (2)
#define ADD_STATUS_ABILITY (3)
#define ADD_STATUS_WAZA_KOUKA (4)
#define ADD_STATUS_SOUBIITEM (5)
#define ADD_STATUS_DOKUBISI (6)
#define ADD_STATUS_IGNORE (7)

#define ADD_STAGE_ATTACK_UP (15)
#define ADD_STAGE_SP_ATK_UP (18)

#endif