#ifndef CONSTANTS_BATTLE_MESSAGE_CONSTANTS_H
#define CONSTANTS_BATTLE_MESSAGE_CONSTANTS_H

#define BATTLE_MSG_STAT_WONT_GO_HIGHER (142)
#define BATTLE_MSG_STAT_WONT_GO_LOWER (145)

#define BATTLE_MSG_PROTECTED_BY_MIST (273)

#define BATTLE_MSG_ABILITY_RAISED_STAT (622)

#define BATTLE_MSG_ATK_ABILITY_CUTS_MON_STAT (662)
#define BATTLE_MSG_PREVENTS_STAT_LOSS (669)

#define BATTLE_MSG_ITEM_PREVENTS_STAT_LOSS (704)

#define BATTLE_MSG_ABILITY_SUPPRESSES_STAT_LOSS (727)

#define BATTLE_MSG_STAT_RAISED (750)
#define BATTLE_MSG_STAT_RAISED_SHARPLY (753)
#define BATTLE_MSG_ITEM_RAISED_STAT (756)
#define BATTLE_MSG_ITEM_SHARPLY_RAISED_STAT (759)
#define BATTLE_MSG_STAT_FELL (762)
#define BATTLE_MSG_STAT_HARSHLY_FELL (765)




// new battle messages
#define BATTLE_MSG_ABILITY_RAISED_STAT_SHARPLY (1309)
#define BATTLE_MSG_ABILITY_RAISED_STAT_DRASTICALLY (1312)
#define BATTLE_MSG_STAT_RAISED_DRASTICALLY (1315)
#define BATTLE_MSG_ABILITY_LOWERED_ITS_OWN_STAT (1318)


#endif
