#ifndef CONSTANTS_BATTLE_MESSAGE_CONSTANTS_H
#define CONSTANTS_BATTLE_MESSAGE_CONSTANTS_H

#define BATTLE_MSG_PROTECTED_ITSELF (15)

#define BATTLE_MSG_BATTLER_PREVENTS_ESCAPE_WITH (39)

#define BATTLE_MSG_STAT_WONT_GO_HIGHER (142)
#define BATTLE_MSG_STAT_WONT_GO_LOWER (145)

#define BATTLE_MSG_PROTECTED_BY_MIST (273)

#define BATTLE_MSG_PROTECT_ITSELF (282)

#define BATTLE_MSG_SIDE_EFFECT_WORE_OFF (288)

#define BATTLE_MSG_LAID_A_CURSE (417)

#define BATTLE_MSG_BRACED_ITSELF (442)

#define BATTLE_MSG_TOOK_DOOM_DESIRE (475)

#define BATTLE_MSG_OBTAINED_ITEM (513)
#define BATTLE_MSG_OBTAINED_ITEM_OBTAINED_ITEM (516)

#define BATTLE_MSG_WISH_CAME_TRUE (533)

#define BATTLE_MSG_MON_KNOCKED_OFF_ITEM (552)

#define BATTLE_MSG_ITEMS_CANT_BE_USED_HERE (593)

#define BATTLE_MSG_CANNOT_USE_MOVE_DISABLED (609)
#define BATTLE_MSG_CANNOT_USE_MOVE_TORMENT (612)
#define BATTLE_MSG_CANNOT_USE_MOVE_TAUNT (613)
#define BATTLE_MSG_CANNOT_USE_MOVE_IMPRISON (616)

#define BATTLE_MSG_MOVE_IS_UNIMPLEMENTED (620)
#define BATTLE_MSG_ABILITY_RAISED_STAT (622)

#define BATTLE_MSG_ATK_ABILITY_CUTS_MON_STAT (662)
#define BATTLE_MSG_PREVENTS_STAT_LOSS (669)

#define BATTLE_MSG_ITEM_PREVENTS_STAT_LOSS (704)

#define BATTLE_MSG_ABILITY_MADE_MOVE_INEFFECTIVE (714)

#define BATTLE_MSG_ABILITY_SUPPRESSES_STAT_LOSS (727)

#define BATTLE_MSG_STAT_RAISED (750)
#define BATTLE_MSG_STAT_RAISED_SHARPLY (753)
#define BATTLE_MSG_ITEM_RAISED_STAT (756)
#define BATTLE_MSG_ITEM_SHARPLY_RAISED_STAT (759)
#define BATTLE_MSG_STAT_FELL (762)
#define BATTLE_MSG_STAT_HARSHLY_FELL (765)

#define BATTLE_MSG_NOT_VERY_EFFECTIVE (779)
#define BATTLE_MSG_SUPER_EFFECTIVE (780)

#define BATTLE_MSG_CANT_ESCAPE (794)

#define BATTLE_MSG_BUT_IT_FAILED (796)

#define BATTLE_MSG_RAIN_CONTINUES_TO_FALL (801)
#define BATTLE_MSG_SANDSTORM_RAGES (805)
#define BATTLE_MSG_SUNLIGHT_IS_STRONG (808)
#define BATTLE_MSG_HAIL_CONTINUES_TO_FALL (811)
#define BATTLE_MSG_FOG_IS_DEEP (813)

#define BATTLE_MSG_CANNOT_USE_MOVE_NO_PP (823)
#define BATTLE_MSG_CANNOT_USE_MOVE_CHOICED (911)

#define BATTLE_MSG_TRAINER_ENCOUNTER (969)
#define BATTLE_MSG_WIFI_TRAINER_ENCOUNTER (970)
#define BATTLE_MSG_WIFI_TRAINER_MULTI_ENCOUNTER (971)
#define BATTLE_MSG_SWITCH_IN_ENEMY_MSG (972)
#define BATTLE_MSG_ENEMY_SEND_OUT_DOUBLES (973)
#define BATTLE_MSG_SWITCH_IN_TITLELESS (974)
#define BATTLE_MSG_DOUBLE_BATTLE_SEND_OUT_WIRELESS (975)
#define BATTLE_MSG_MULTI_BATTLE_SEND_OUT_MESSAGE (976)
#define BATTLE_MSG_MULTI_BATTLE_PLAYER_SEND_OUT_MESSAGE (977)
#define BATTLE_MSG_SEND_OUT_DOUBLES (978)
#define BATTLE_MSG_SEND_IN_MON_0 (979)
#define BATTLE_MSG_SEND_IN_MON_1 (980)
#define BATTLE_MSG_SEND_IN_MON_2 (981)
#define BATTLE_MSG_SEND_IN_MON_3 (982)
#define BATTLE_MSG_SEND_IN_MON_4 (983)

#define BATTLE_MSG_DOUBLE_TOWER_BATTLE_SEND_OUT (991)
#define BATTLE_MSG_DOUBLE_BATTLE_ENCOUNTER (992)
#define BATTLE_MSG_MULTI_BATTLE_PLAYER_SIDE_SEND_OUT (993)

#define BATTLE_MSG_CANNOT_USE_MOVE_GRAVITY (1001)
#define BATTLE_MSG_CANNOT_USE_MOVE_HEAL_BLOCK (1057)
#define BATTLE_MSG_STOLE_BERRY (1141)

// new battle messages
#define BATTLE_MSG_MEGA_EVOLUTION (1276)
#define BATTLE_MSG_ABILITY_RAISED_STAT_SHARPLY (1309)
#define BATTLE_MSG_ABILITY_RAISED_STAT_DRASTICALLY (1312)
#define BATTLE_MSG_STAT_RAISED_DRASTICALLY (1315)
#define BATTLE_MSG_ABILITY_LOWERED_ITS_OWN_STAT (1318)

#define BATTLE_MSG_STARTED_TO_SNOW (1439)
#define BATTLE_MSG_SNOW_STOPPED (1440)

#define BATTLE_MSG_STRONG_WINDS_BLOW_ON (1456)

#define BATTLE_MSG_CANNOT_USE_MOVE_GORILLA_TACTICS (1457)
#define BATTLE_MSG_CANNOT_USE_MOVE_GIGATON_HAMMER (1458)
#define BATTLE_MSG_CANNOT_USE_MOVE_ASSAULT_VEST (1459)

#define BATTLE_MSG_FLOWER_VEIL_PETALS (1511)

#define BATTLE_MSG_STAT_LOWERED_SEVERELY (1519)
#define BATTLE_MSG_ITEM_DRASTICALLY_RAISED_STAT (1522)

#define BATTLE_MSG_PROTECT_USER_SIDE (1565)
#define BATTLE_MSG_MOVE_PROTECTED_SIDE (1567)

#define BATTLE_MSG_GEM_ACTIVATION (1570)

#define BATTLE_MSG_ITEM_INCINERATED (1573)
#define BATTLE_MSG_ITEM_CANNOT_BE_REMOVED (1576)

#define BATTLE_MSG_GRASS_TYPE_ADDED (1579)
#define BATTLE_MSG_GHOST_TYPE_ADDED (1582)

#define BATTLE_MSG_AURORA_VEIL (1588)
#define BATTLE_MSG_PICKED_UP_ITEM (1592)
#define BATTLE_MSG_GENERIC_PICKED_UP_ITEM (1593)

#define BATTLE_MSG_BURNED_ITSELF_OUT (1601)

#define BATTLE_MSG_USED_UP_ELECTRICITY (1604)

#endif
