#ifndef CONSTANTS_FILE_H
#define CONSTANTS_FILE_H

//NARC files
#define ARC_SUB_SEQ 1
#define ARC_PERSONAL 2
#define ARC_MON_PIC 4
#define ARC_MOVE_DATA 11
#define ARC_ITEM_DATA 17
#define ARC_ITEM_GFX_DATA 18
#define ARC_CODE_ADDONS 28
#define ARC_EVOLUTIONS 34
#define ARC_OTHER_MON_PIC 114
#define ARC_EGG_MOVES 231 // 229 because of the two random ones


//a028 file indexes
#define CODE_ADDON_SYNTHETIC_NARC_EXTENSION 0
#define CODE_ADDON_HIDDEN_ABILITY_LIST 7
#define CODE_ADDON_BASE_EXPERIENCE_LIST 8
#define CODE_ADDON_NUM_OF_OW_FORMS_PER_MON 9

//heap IDs
#define HEAPID_WORLD 11

#endif
