#ifndef CONSTANTS_FILE_H
#define CONSTANTS_FILE_H

//NARC files
#define ARC_SUB_SEQ 1
#define ARC_PERSONAL 2
#define ARC_MON_PIC 4
#define ARC_CODE_ADDONS 28
#define ARC_OTHER_MON_PIC 114


//a028 file indexes
#define CODE_ADDON_SYNTHETIC_NARC_EXTENSION 0
#define CODE_ADDON_HIDDEN_ABILITY_LIST 7
#define CODE_ADDON_BASE_EXPERIENCE_LIST 8

// TODO:  move these
//stat change
#define SEQ_STATE_CHANGE 12
#define SEQ_FORM_CHANGE 262

#define SERVER_WAZA_SEQUENCE_NO 22
#define SERVER_WAZA_OUT_AFTER_MESSAGE_NO 29

//heap IDs
#define HEAPID_WORLD 11

#endif
