#ifndef CONSTANTS_HOLD_ITEM_EFFECTS_H
#define CONSTANTS_HOLD_ITEM_EFFECTS_H

#define HOLD_EFFECT_GRISEOUS_ORB 2
#define HOLD_EFFECT_ADAMANT_ORB 3
#define HOLD_EFFECT_LUSTROUS_ORB 4
#define HOLD_EFFECT_CHOICE_BAND 55
#define HOLD_EFFECT_BOOST_BUG 57
#define HOLD_EFFECT_DOUBLE_MONEY_GAIN 58
#define HOLD_EFFECT_SOUL_DEW 60
#define HOLD_EFFECT_DEEP_SEA_TOOTH 61
#define HOLD_EFFECT_DEEP_SEA_SCALE 62
#define HOLD_EFFECT_BOOST_STEEL 68
#define HOLD_EFFECT_LIGHT_BALL 71
#define HOLD_EFFECT_BOOST_GROUND 72
#define HOLD_EFFECT_BOOST_ROCK 73
#define HOLD_EFFECT_BOOST_GRASS 74
#define HOLD_EFFECT_BOOST_DARK 75
#define HOLD_EFFECT_BOOST_FIGHTING 76
#define HOLD_EFFECT_BOOST_ELECTRIC 77
#define HOLD_EFFECT_BOOST_WATER 78
#define HOLD_EFFECT_BOOST_FLYING 79
#define HOLD_EFFECT_BOOST_POISON 80
#define HOLD_EFFECT_BOOST_ICE 81
#define HOLD_EFFECT_BOOST_GHOST 82
#define HOLD_EFFECT_BOOST_PSYCHIC 83
#define HOLD_EFFECT_BOOST_FIRE 84
#define HOLD_EFFECT_BOOST_DRAGON 85
#define HOLD_EFFECT_BOOST_NORMAL 86
#define HOLD_EFFECT_METAL_POWDER 90
#define HOLD_EFFECT_THICK_CLUB 91
#define HOLD_EFFECT_BOOST_PHYSICAL 94
#define HOLD_EFFECT_BOOST_SPECIAL 95
#define HOLD_EFFECT_CHOICE_SPECS 125
#define HOLD_EFFECT_PLATE_BOOST_FIRE 126
#define HOLD_EFFECT_PLATE_BOOST_WATER 127
#define HOLD_EFFECT_PLATE_BOOST_ELECTRIC 128
#define HOLD_EFFECT_PLATE_BOOST_GRASS 129
#define HOLD_EFFECT_PLATE_BOOST_ICE 130
#define HOLD_EFFECT_PLATE_BOOST_FIGHTING 131
#define HOLD_EFFECT_PLATE_BOOST_POISON 132
#define HOLD_EFFECT_PLATE_BOOST_GROUND 133
#define HOLD_EFFECT_PLATE_BOOST_FLYING 134
#define HOLD_EFFECT_PLATE_BOOST_PSYCHIC 135
#define HOLD_EFFECT_PLATE_BOOST_BUG 136
#define HOLD_EFFECT_PLATE_BOOST_ROCK 137
#define HOLD_EFFECT_PLATE_BOOST_GHOST 138
#define HOLD_EFFECT_PLATE_BOOST_DRAGON 139
#define HOLD_EFFECT_PLATE_BOOST_DARK 140
#define HOLD_EFFECT_PLATE_BOOST_STEEL 141

#endif
