#ifndef CONSTANTS_HOLD_ITEM_EFFECTS_H
#define CONSTANTS_HOLD_ITEM_EFFECTS_H

// steal some of these from pokeheartgold
#define HOLD_EFFECT_NONE                    0
#define HOLD_EFFECT_HP_RESTORE              1
#define HOLD_EFFECT_GRISEOUS_ORB 2
#define HOLD_EFFECT_ADAMANT_ORB 3
#define HOLD_EFFECT_LUSTROUS_ORB 4
#define HOLD_EFFECT_PRZ_RESTORE             5
#define HOLD_EFFECT_SLP_RESTORE             6
#define HOLD_EFFECT_PSN_RESTORE             7
#define HOLD_EFFECT_BRN_RESTORE             8
#define HOLD_EFFECT_FRZ_RESTORE             9
#define HOLD_EFFECT_PP_RESTORE             10
#define HOLD_EFFECT_CONFUSE_RESTORE        11
#define HOLD_EFFECT_STATUS_RESTORE         12
#define HOLD_EFFECT_HP_PCT_RESTORE         13
#define HOLD_EFFECT_HP_RESTORE_SPICY       14
#define HOLD_EFFECT_HP_RESTORE_DRY         15
#define HOLD_EFFECT_HP_RESTORE_SWEET       16
#define HOLD_EFFECT_HP_RESTORE_BITTER      17
#define HOLD_EFFECT_HP_RESTORE_SOUR        18
#define HOLD_EFFECT_WEAKEN_SE_FIRE         19
#define HOLD_EFFECT_WEAKEN_SE_WATER        20
#define HOLD_EFFECT_WEAKEN_SE_ELECTRIC     21
#define HOLD_EFFECT_WEAKEN_SE_GRASS        22
#define HOLD_EFFECT_WEAKEN_SE_ICE          23
#define HOLD_EFFECT_WEAKEN_SE_FIGHT        24
#define HOLD_EFFECT_WEAKEN_SE_POISON       25
#define HOLD_EFFECT_WEAKEN_SE_GROUND       26
#define HOLD_EFFECT_WEAKEN_SE_FLYING       27
#define HOLD_EFFECT_WEAKEN_SE_PSYCHIC      28
#define HOLD_EFFECT_WEAKEN_SE_BUG          29
#define HOLD_EFFECT_WEAKEN_SE_ROCK         30
#define HOLD_EFFECT_WEAKEN_SE_GHOST        31
#define HOLD_EFFECT_WEAKEN_SE_DRAGON       32
#define HOLD_EFFECT_WEAKEN_SE_DARK         33
#define HOLD_EFFECT_WEAKEN_SE_STEEL        34
#define HOLD_EFFECT_WEAKEN_NORMAL          35
#define HOLD_EFFECT_PINCH_ATK_UP           36
#define HOLD_EFFECT_PINCH_DEF_UP           37
#define HOLD_EFFECT_PINCH_SPEED_UP         38
#define HOLD_EFFECT_PINCH_SPATK_UP         39
#define HOLD_EFFECT_PINCH_SPDEF_UP         40
#define HOLD_EFFECT_PINCH_CRITRATE_UP      41
#define HOLD_EFFECT_PINCH_RANDOM_UP        42
#define HOLD_EFFECT_RESTORE_HP_ON_SE          43 //renamed from HOLD_EFFECT_HP_RESTORE_SE
#define HOLD_EFFECT_PINCH_ACC_UP           44
#define HOLD_EFFECT_PINCH_PRIORITY         45
#define HOLD_EFFECT_RAISE_SPEED_IN_PINCH 45
#define HOLD_EFFECT_RECOIL_PHYSICAL        46
#define HOLD_EFFECT_RECOIL_SPECIAL         47
#define HOLD_EFFECT_DECREASE_ACCURACY 48
#define HOLD_EFFECT_STATDOWN_RESTORE       49
#define HOLD_EFFECT_DOUBLE_EV_GAIN 50
#define HOLD_EFFECT_EXP_SHARE              51
#define HOLD_EFFECT_QUICK_CLAW 52
#define HOLD_EFFECT_FRIENDSHIP_UP          53
#define HOLD_EFFECT_HEAL_INFATUATION       54
#define HOLD_EFFECT_CHOICE_BAND 55
#define HOLD_EFFECT_INCREASE_FLINCH 56
#define HOLD_EFFECT_BOOST_BUG 57
#define HOLD_EFFECT_DOUBLE_MONEY_GAIN 58
#define HOLD_EFFECT_ENCOUNTERS_DOWN        59
#define HOLD_EFFECT_SOUL_DEW 60
#define HOLD_EFFECT_DEEP_SEA_TOOTH 61
#define HOLD_EFFECT_DEEP_SEA_SCALE 62
#define HOLD_EFFECT_FLEE                   63
#define HOLD_EFFECT_NO_EVOLVE              64
#define HOLD_EFFECT_FOCUS_BAND 65
#define HOLD_EFFECT_EXP_UP                 66
#define HOLD_EFFECT_BOOST_CRITICAL_RATE 67
#define HOLD_EFFECT_BOOST_STEEL 68
#define HOLD_EFFECT_HP_RESTORE_GRADUAL     69
#define HOLD_EFFECT_EVOLVE_SEADRA          70
#define HOLD_EFFECT_LIGHT_BALL 71
#define HOLD_EFFECT_BOOST_GROUND 72
#define HOLD_EFFECT_BOOST_ROCK 73
#define HOLD_EFFECT_BOOST_GRASS 74
#define HOLD_EFFECT_BOOST_DARK 75
#define HOLD_EFFECT_BOOST_FIGHTING 76
#define HOLD_EFFECT_BOOST_ELECTRIC 77
#define HOLD_EFFECT_BOOST_WATER 78
#define HOLD_EFFECT_BOOST_FLYING 79
#define HOLD_EFFECT_BOOST_POISON 80
#define HOLD_EFFECT_BOOST_ICE 81
#define HOLD_EFFECT_BOOST_GHOST 82
#define HOLD_EFFECT_BOOST_PSYCHIC 83
#define HOLD_EFFECT_BOOST_FIRE 84
#define HOLD_EFFECT_BOOST_DRAGON 85
#define HOLD_EFFECT_BOOST_NORMAL 86
#define HOLD_EFFECT_EVOLVE_PORYGON         87
#define HOLD_EFFECT_HP_RESTORE_ON_DMG      88
#define HOLD_EFFECT_BOOST_CHANSEY_CRITICAL 89
#define HOLD_EFFECT_METAL_POWDER 90
#define HOLD_EFFECT_THICK_CLUB 91
#define HOLD_EFFECT_BOOST_FARFETCHD_CRITICAL 92
#define HOLD_EFFECT_INCREASE_ACCURACY 93
#define HOLD_EFFECT_BOOST_PHYSICAL 94
#define HOLD_EFFECT_BOOST_SPECIAL 95
#define HOLD_EFFECT_POWER_UP_SE            96
#define HOLD_EFFECT_EXTEND_SCREENS         97
#define HOLD_EFFECT_HP_DRAIN_ON_ATK        98
#define HOLD_EFFECT_CHARGE_SKIP            99
#define HOLD_EFFECT_PSN_USER              100
#define HOLD_EFFECT_BRN_USER              101
#define HOLD_EFFECT_BOOST_DITTO_SPEED 102
#define HOLD_EFFECT_HP_MAX_SURVIVE_1_HP 103
#define HOLD_EFFECT_ZOOM_LENS 104
#define HOLD_EFFECT_BOOST_REPEATED        105
#define HOLD_EFFECT_HALVE_SPEED 106
#define HOLD_EFFECT_LAGGING_TAIL 107
#define HOLD_EFFECT_RECIPROCATE_INFAT     108
#define HOLD_EFFECT_HP_RESTORE_PSN_TYPE   109
#define HOLD_EFFECT_EXTEND_HAIL           110
#define HOLD_EFFECT_EXTEND_SANDSTORM      111
#define HOLD_EFFECT_EXTEND_SUN            112
#define HOLD_EFFECT_EXTEND_RAIN           113
#define HOLD_EFFECT_EXTEND_TRAPPING       114
#define HOLD_EFFECT_CHOICE_SPEED 115
#define HOLD_EFFECT_DAMAGE_HOLDER_TRANSFER_ON_CONTACT  116 //renamed from HOLD_EFFECT_DMG_USER_CONTACT_XFR
#define HOLD_EFFECT_GAIN_ATTACK_EVS 117
#define HOLD_EFFECT_GAIN_DEFENSE_EVS 118
#define HOLD_EFFECT_GAIN_SP_ATK_EVS 119
#define HOLD_EFFECT_GAIN_SP_DEF_EVS 120
#define HOLD_EFFECT_GAIN_SPEED_EVS 121
#define HOLD_EFFECT_GAIN_HP_EVS 122
#define HOLD_EFFECT_SWITCH                123
#define HOLD_EFFECT_LEECH_BOOST           124
#define HOLD_EFFECT_CHOICE_SPECS 125
#define HOLD_EFFECT_PLATE_BOOST_FIRE 126
#define HOLD_EFFECT_PLATE_BOOST_WATER 127
#define HOLD_EFFECT_PLATE_BOOST_ELECTRIC 128
#define HOLD_EFFECT_PLATE_BOOST_GRASS 129
#define HOLD_EFFECT_PLATE_BOOST_ICE 130
#define HOLD_EFFECT_PLATE_BOOST_FIGHTING 131
#define HOLD_EFFECT_PLATE_BOOST_POISON 132
#define HOLD_EFFECT_PLATE_BOOST_GROUND 133
#define HOLD_EFFECT_PLATE_BOOST_FLYING 134
#define HOLD_EFFECT_PLATE_BOOST_PSYCHIC 135
#define HOLD_EFFECT_PLATE_BOOST_BUG 136
#define HOLD_EFFECT_PLATE_BOOST_ROCK 137
#define HOLD_EFFECT_PLATE_BOOST_GHOST 138
#define HOLD_EFFECT_PLATE_BOOST_DRAGON 139
#define HOLD_EFFECT_PLATE_BOOST_DARK 140
#define HOLD_EFFECT_PLATE_BOOST_STEEL 141
#define HOLD_EFFECT_EVOLVE_RHYDON         142
#define HOLD_EFFECT_EVOLVE_ELECTABUZZ     143
#define HOLD_EFFECT_EVOLVE_MAGMAR         144
#define HOLD_EFFECT_EVOLVE_PORYGON2       145
#define HOLD_EFFECT_EVOLVE_DUSCLOPS       146


// EXPANSION
#define HOLD_EFFECT_PLATE_BOOST_FAIRY 147                         // Pixie Plate
#define HOLD_EFFECT_WEAKEN_SE_FAIRY 148                           // Roseli Berry
#define HOLD_EFFECT_BOOST_DEF_ON_PHYSICAL_HIT 149                 // Kee Berry
#define HOLD_EFFECT_BOOST_SPDEF_ON_SPECIAL_HIT 150                // Maranga Berry
#define HOLD_EFFECT_DAMAGE_ON_CONTACT 151                         // Rocky Helmet
#define HOLD_EFFECT_BOOST_SPECIAL_ATTACK_ON_WATER_HIT 152         // Absorb Bulb
#define HOLD_EFFECT_BOOST_SPECIAL_DEFENSE_ON_WATER_HIT 153        // Luminous Moss
#define HOLD_EFFECT_BOOST_ATK_ON_ICE_HIT   154                    // Snowball
#define HOLD_EFFECT_BOOST_ATK_ON_ELECTRIC_HIT 155                 // Cell Battery
#define HOLD_EFFECT_BOOST_ATK_AND_SPATK_ON_SE 156                 // Weakness Policy
#define HOLD_EFFECT_FORCE_SWITCH_ON_DAMAGE    157                 // Red Card
#define HOLD_EFFECT_SWITCH_OUT_WHEN_HIT       158                 // Eject Button
#define HOLD_EFFECT_UNGROUND_DESTROYED_ON_HIT 159                 // Air Balloon
#define HOLD_EFFECT_PLATE_BOOST_NORMAL 160                        // Blank Plate
#define HOLD_EFFECT_EVOLVE_SPRITZEE 161                           // Sachet
#define HOLD_EFFECT_EVOLVE_SWIRLIX  162                           // Whipped Dream
#define HOLD_EFFECT_EVIOLITE        163                           // Eviolite
#define HOLD_EFFECT_PREVENT_CONTACT_EFFECTS 164                   // Protective Pads

#define HOLD_EFFECT_BURN_DRIVE 165
#define HOLD_EFFECT_CHILL_DRIVE 166
#define HOLD_EFFECT_DOUSE_DRIVE 167
#define HOLD_EFFECT_SHOCK_DRIVE 168

#define HOLD_EFFECT_FIGHTING_MEMORY 169
#define HOLD_EFFECT_FLYING_MEMORY 170
#define HOLD_EFFECT_POISON_MEMORY 171
#define HOLD_EFFECT_GROUND_MEMORY 172
#define HOLD_EFFECT_ROCK_MEMORY 173
#define HOLD_EFFECT_BUG_MEMORY 174
#define HOLD_EFFECT_GHOST_MEMORY 175
#define HOLD_EFFECT_STEEL_MEMORY 176
#define HOLD_EFFECT_FIRE_MEMORY 177
#define HOLD_EFFECT_WATER_MEMORY 178
#define HOLD_EFFECT_GRASS_MEMORY 179
#define HOLD_EFFECT_ELECTRIC_MEMORY 180
#define HOLD_EFFECT_PSYCHIC_MEMORY 181
#define HOLD_EFFECT_ICE_MEMORY 182
#define HOLD_EFFECT_DRAGON_MEMORY 183
#define HOLD_EFFECT_DARK_MEMORY 184
#define HOLD_EFFECT_FAIRY_MEMORY 185

#endif
