#ifndef CONSTANTS_ITEM_H
#define CONSTANTS_ITEM_H

#include "../config.h"

#define ITEM_NONE            0
#define ITEM_MASTER_BALL     1
#define ITEM_ULTRA_BALL      2
#define ITEM_GREAT_BALL      3
#define ITEM_POKE_BALL       4
#define ITEM_SAFARI_BALL     5
#define ITEM_NET_BALL        6
#define ITEM_DIVE_BALL       7
#define ITEM_NEST_BALL       8
#define ITEM_REPEAT_BALL     9
#define ITEM_TIMER_BALL      10
#define ITEM_LUXURY_BALL     11
#define ITEM_PREMIER_BALL    12
#define ITEM_DUSK_BALL       13
#define ITEM_HEAL_BALL       14
#define ITEM_QUICK_BALL      15
#define ITEM_CHERISH_BALL    16
#define ITEM_POTION          17
#define ITEM_ANTIDOTE        18
#define ITEM_BURN_HEAL       19
#define ITEM_ICE_HEAL        20
#define ITEM_AWAKENING       21
#define ITEM_PARALYZE_HEAL   22
#define ITEM_FULL_RESTORE    23
#define ITEM_MAX_POTION      24
#define ITEM_HYPER_POTION    25
#define ITEM_SUPER_POTION    26
#define ITEM_FULL_HEAL       27
#define ITEM_REVIVE          28
#define ITEM_MAX_REVIVE      29
#define ITEM_FRESH_WATER     30
#define ITEM_SODA_POP        31
#define ITEM_LEMONADE        32
#define ITEM_MOOMOO_MILK     33
#define ITEM_ENERGY_POWDER   34
#define ITEM_ENERGY_ROOT     35
#define ITEM_HEAL_POWDER     36
#define ITEM_REVIVAL_HERB    37
#define ITEM_ETHER           38
#define ITEM_MAX_ETHER       39
#define ITEM_ELIXIR          40
#define ITEM_MAX_ELIXIR      41
#define ITEM_LAVA_COOKIE     42
#define ITEM_BERRY_JUICE     43
#define ITEM_SACRED_ASH      44
#define ITEM_HP_UP           45
#define ITEM_PROTEIN         46
#define ITEM_IRON            47
#define ITEM_CARBOS          48
#define ITEM_CALCIUM         49
#define ITEM_RARE_CANDY      50
#define ITEM_PP_UP           51
#define ITEM_ZINC            52
#define ITEM_PP_MAX          53
#define ITEM_OLD_GATEAU      54
#define ITEM_GUARD_SPEC      55
#define ITEM_DIRE_HIT        56
#define ITEM_X_ATTACK        57
#define ITEM_X_DEFENSE       58
#define ITEM_X_SPEED         59
#define ITEM_X_ACCURACY      60
#define ITEM_X_SPECIAL       61
#define ITEM_X_SP_DEF        62
#define ITEM_POKE_DOLL       63
#define ITEM_FLUFFY_TAIL     64
#define ITEM_BLUE_FLUTE      65
#define ITEM_YELLOW_FLUTE    66
#define ITEM_RED_FLUTE       67
#define ITEM_BLACK_FLUTE     68
#define ITEM_WHITE_FLUTE     69
#define ITEM_SHOAL_SALT      70
#define ITEM_SHOAL_SHELL     71
#define ITEM_RED_SHARD       72
#define ITEM_BLUE_SHARD      73
#define ITEM_YELLOW_SHARD    74
#define ITEM_GREEN_SHARD     75
#define ITEM_SUPER_REPEL     76
#define ITEM_MAX_REPEL       77
#define ITEM_ESCAPE_ROPE     78
#define ITEM_REPEL           79
#define ITEM_SUN_STONE       80
#define ITEM_MOON_STONE      81
#define ITEM_FIRE_STONE      82
#define ITEM_THUNDER_STONE   83
#define ITEM_WATER_STONE     84
#define ITEM_LEAF_STONE      85
#define ITEM_TINY_MUSHROOM   86
#define ITEM_BIG_MUSHROOM    87
#define ITEM_PEARL           88
#define ITEM_BIG_PEARL       89
#define ITEM_STARDUST        90
#define ITEM_STAR_PIECE      91
#define ITEM_NUGGET          92
#define ITEM_HEART_SCALE     93
#define ITEM_HONEY           94
#define ITEM_GROWTH_MULCH    95
#define ITEM_DAMP_MULCH      96
#define ITEM_STABLE_MULCH    97
#define ITEM_GOOEY_MULCH     98
#define ITEM_ROOT_FOSSIL     99
#define ITEM_CLAW_FOSSIL     100
#define ITEM_HELIX_FOSSIL    101
#define ITEM_DOME_FOSSIL     102
#define ITEM_OLD_AMBER       103
#define ITEM_ARMOR_FOSSIL    104
#define ITEM_SKULL_FOSSIL    105
#define ITEM_RARE_BONE       106
#define ITEM_SHINY_STONE     107
#define ITEM_DUSK_STONE      108
#define ITEM_DAWN_STONE      109
#define ITEM_OVAL_STONE      110
#define ITEM_ODD_KEYSTONE    111
#define ITEM_GRISEOUS_ORB    112
#define ITEM_UNKNOWN_71      113
#define ITEM_UNKNOWN_72      114
#define ITEM_UNKNOWN_73      115
#define ITEM_UNKNOWN_74      116
#define ITEM_UNKNOWN_75      117
#define ITEM_UNKNOWN_76      118
#define ITEM_UNKNOWN_77      119
#define ITEM_UNKNOWN_78      120
#define ITEM_UNKNOWN_79      121
#define ITEM_UNKNOWN_7A      122
#define ITEM_UNKNOWN_7B      123
#define ITEM_UNKNOWN_7C      124
#define ITEM_UNKNOWN_7D      125
#define ITEM_UNKNOWN_7E      126
#define ITEM_UNKNOWN_7F      127
#define ITEM_UNKNOWN_80      128
#define ITEM_UNKNOWN_81      129
#define ITEM_UNKNOWN_82      130
#define ITEM_UNKNOWN_83      131
#define ITEM_UNKNOWN_84      132
#define ITEM_UNKNOWN_85      133
#define ITEM_UNKNOWN_86      134
#define ITEM_ADAMANT_ORB     135
#define ITEM_LUSTROUS_ORB    136
#define ITEM_GRASS_MAIL      137
#define ITEM_FLAME_MAIL      138
#define ITEM_BUBBLE_MAIL     139
#define ITEM_BLOOM_MAIL      140
#define ITEM_TUNNEL_MAIL     141
#define ITEM_STEEL_MAIL      142
#define ITEM_HEART_MAIL      143
#define ITEM_SNOW_MAIL       144
#define ITEM_SPACE_MAIL      145
#define ITEM_AIR_MAIL        146
#define ITEM_MOSAIC_MAIL     147
#define ITEM_BRICK_MAIL      148
#define ITEM_CHERI_BERRY     149
#define ITEM_CHESTO_BERRY    150
#define ITEM_PECHA_BERRY     151
#define ITEM_RAWST_BERRY     152
#define ITEM_ASPEAR_BERRY    153
#define ITEM_LEPPA_BERRY     154
#define ITEM_ORAN_BERRY      155
#define ITEM_PERSIM_BERRY    156
#define ITEM_LUM_BERRY       157
#define ITEM_SITRUS_BERRY    158
#define ITEM_FIGY_BERRY      159
#define ITEM_WIKI_BERRY      160
#define ITEM_MAGO_BERRY      161
#define ITEM_AGUAV_BERRY     162
#define ITEM_IAPAPA_BERRY    163
#define ITEM_RAZZ_BERRY      164
#define ITEM_BLUK_BERRY      165
#define ITEM_NANAB_BERRY     166
#define ITEM_WEPEAR_BERRY    167
#define ITEM_PINAP_BERRY     168
#define ITEM_POMEG_BERRY     169
#define ITEM_KELPSY_BERRY    170
#define ITEM_QUALOT_BERRY    171
#define ITEM_HONDEW_BERRY    172
#define ITEM_GREPA_BERRY     173
#define ITEM_TAMATO_BERRY    174
#define ITEM_CORNN_BERRY     175
#define ITEM_MAGOST_BERRY    176
#define ITEM_RABUTA_BERRY    177
#define ITEM_NOMEL_BERRY     178
#define ITEM_SPELON_BERRY    179
#define ITEM_PAMTRE_BERRY    180
#define ITEM_WATMEL_BERRY    181
#define ITEM_DURIN_BERRY     182
#define ITEM_BELUE_BERRY     183
#define ITEM_OCCA_BERRY      184
#define ITEM_PASSHO_BERRY    185
#define ITEM_WACAN_BERRY     186
#define ITEM_RINDO_BERRY     187
#define ITEM_YACHE_BERRY     188
#define ITEM_CHOPLE_BERRY    189
#define ITEM_KEBIA_BERRY     190
#define ITEM_SHUCA_BERRY     191
#define ITEM_COBA_BERRY      192
#define ITEM_PAYAPA_BERRY    193
#define ITEM_TANGA_BERRY     194
#define ITEM_CHARTI_BERRY    195
#define ITEM_KASIB_BERRY     196
#define ITEM_HABAN_BERRY     197
#define ITEM_COLBUR_BERRY    198
#define ITEM_BABIRI_BERRY    199
#define ITEM_CHILAN_BERRY    200
#define ITEM_LIECHI_BERRY    201
#define ITEM_GANLON_BERRY    202
#define ITEM_SALAC_BERRY     203
#define ITEM_PETAYA_BERRY    204
#define ITEM_APICOT_BERRY    205
#define ITEM_LANSAT_BERRY    206
#define ITEM_STARF_BERRY     207
#define ITEM_ENIGMA_BERRY    208
#define ITEM_MICLE_BERRY     209
#define ITEM_CUSTAP_BERRY    210
#define ITEM_JABOCA_BERRY    211
#define ITEM_ROWAP_BERRY     212

#define IS_ITEM_BERRY(item) ((item >= ITEM_CHERI_BERRY && item <= ITEM_ROWAP_BERRY) || (item >= ITEM_ROSELI_BERRY && item <= ITEM_MARANGA_BERRY))
#define IS_ITEM_MAIL(item) ((item >= ITEM_GRASS_MAIL && item <= ITEM_BRICK_MAIL))

#define ITEM_BRIGHT_POWDER   213
#define ITEM_WHITE_HERB      214
#define ITEM_MACHO_BRACE     215
#define ITEM_EXP_SHARE       216
#define ITEM_QUICK_CLAW      217
#define ITEM_SOOTHE_BELL     218
#define ITEM_MENTAL_HERB     219
#define ITEM_CHOICE_BAND     220
#define ITEM_KINGS_ROCK      221
#define ITEM_SILVER_POWDER   222
#define ITEM_AMULET_COIN     223
#define ITEM_CLEANSE_TAG     224
#define ITEM_SOUL_DEW        225
#define ITEM_DEEP_SEA_TOOTH  226
#define ITEM_DEEP_SEA_SCALE  227
#define ITEM_SMOKE_BALL      228
#define ITEM_EVERSTONE       229
#define ITEM_FOCUS_BAND      230
#define ITEM_LUCKY_EGG       231
#define ITEM_SCOPE_LENS      232
#define ITEM_METAL_COAT      233
#define ITEM_LEFTOVERS       234
#define ITEM_DRAGON_SCALE    235
#define ITEM_LIGHT_BALL      236
#define ITEM_SOFT_SAND       237
#define ITEM_HARD_STONE      238
#define ITEM_MIRACLE_SEED    239
#define ITEM_BLACK_GLASSES   240
#define ITEM_BLACK_BELT      241
#define ITEM_MAGNET          242
#define ITEM_MYSTIC_WATER    243
#define ITEM_SHARP_BEAK      244
#define ITEM_POISON_BARB     245
#define ITEM_NEVER_MELT_ICE  246
#define ITEM_SPELL_TAG       247
#define ITEM_TWISTED_SPOON   248
#define ITEM_CHARCOAL        249
#define ITEM_DRAGON_FANG     250
#define ITEM_SILK_SCARF      251
#define ITEM_UP_GRADE        252
#define ITEM_SHELL_BELL      253
#define ITEM_SEA_INCENSE     254
#define ITEM_LAX_INCENSE     255
#define ITEM_LUCKY_PUNCH     256
#define ITEM_METAL_POWDER    257
#define ITEM_THICK_CLUB      258
#define ITEM_LEEK            259
#define ITEM_RED_SCARF       260
#define ITEM_BLUE_SCARF      261
#define ITEM_PINK_SCARF      262
#define ITEM_GREEN_SCARF     263
#define ITEM_YELLOW_SCARF    264
#define ITEM_WIDE_LENS       265
#define ITEM_MUSCLE_BAND     266
#define ITEM_WISE_GLASSES    267
#define ITEM_EXPERT_BELT     268
#define ITEM_LIGHT_CLAY      269
#define ITEM_LIFE_ORB        270
#define ITEM_POWER_HERB      271
#define ITEM_TOXIC_ORB       272
#define ITEM_FLAME_ORB       273
#define ITEM_QUICK_POWDER    274
#define ITEM_FOCUS_SASH      275
#define ITEM_ZOOM_LENS       276
#define ITEM_METRONOME       277
#define ITEM_IRON_BALL       278
#define ITEM_LAGGING_TAIL    279
#define ITEM_DESTINY_KNOT    280
#define ITEM_BLACK_SLUDGE    281
#define ITEM_ICY_ROCK        282
#define ITEM_SMOOTH_ROCK     283
#define ITEM_HEAT_ROCK       284
#define ITEM_DAMP_ROCK       285
#define ITEM_GRIP_CLAW       286
#define ITEM_CHOICE_SCARF    287
#define ITEM_STICKY_BARB     288
#define ITEM_POWER_BRACER    289
#define ITEM_POWER_BELT      290
#define ITEM_POWER_LENS      291
#define ITEM_POWER_BAND      292
#define ITEM_POWER_ANKLET    293
#define ITEM_POWER_WEIGHT    294
#define ITEM_SHED_SHELL      295
#define ITEM_BIG_ROOT        296
#define ITEM_CHOICE_SPECS    297

#define IS_ITEM_ARCEUS_PLATE(item) ((item >= ITEM_FLAME_PLATE && item <= ITEM_IRON_PLATE) || (item == ITEM_PIXIE_PLATE))

#define ITEM_FLAME_PLATE     298
#define ITEM_SPLASH_PLATE    299
#define ITEM_ZAP_PLATE       300
#define ITEM_MEADOW_PLATE    301
#define ITEM_ICICLE_PLATE    302
#define ITEM_FIST_PLATE      303
#define ITEM_TOXIC_PLATE     304
#define ITEM_EARTH_PLATE     305
#define ITEM_SKY_PLATE       306
#define ITEM_MIND_PLATE      307
#define ITEM_INSECT_PLATE    308
#define ITEM_STONE_PLATE     309
#define ITEM_SPOOKY_PLATE    310
#define ITEM_DRACO_PLATE     311
#define ITEM_DREAD_PLATE     312
#define ITEM_IRON_PLATE      313
#define ITEM_ODD_INCENSE     314
#define ITEM_ROCK_INCENSE    315
#define ITEM_FULL_INCENSE    316
#define ITEM_WAVE_INCENSE    317
#define ITEM_ROSE_INCENSE    318
#define ITEM_LUCK_INCENSE    319
#define ITEM_PURE_INCENSE    320
#define ITEM_PROTECTOR       321
#define ITEM_ELECTIRIZER     322
#define ITEM_MAGMARIZER      323
#define ITEM_DUBIOUS_DISC    324
#define ITEM_REAPER_CLOTH    325
#define ITEM_RAZOR_CLAW      326
#define ITEM_RAZOR_FANG      327
#define ITEM_TM01            328
#define ITEM_TM02            329
#define ITEM_TM03            330
#define ITEM_TM04            331
#define ITEM_TM05            332
#define ITEM_TM06            333
#define ITEM_TM07            334
#define ITEM_TM08            335
#define ITEM_TM09            336
#define ITEM_TM10            337
#define ITEM_TM11            338
#define ITEM_TM12            339
#define ITEM_TM13            340
#define ITEM_TM14            341
#define ITEM_TM15            342
#define ITEM_TM16            343
#define ITEM_TM17            344
#define ITEM_TM18            345
#define ITEM_TM19            346
#define ITEM_TM20            347
#define ITEM_TM21            348
#define ITEM_TM22            349
#define ITEM_TM23            350
#define ITEM_TM24            351
#define ITEM_TM25            352
#define ITEM_TM26            353
#define ITEM_TM27            354
#define ITEM_TM28            355
#define ITEM_TM29            356
#define ITEM_TM30            357
#define ITEM_TM31            358
#define ITEM_TM32            359
#define ITEM_TM33            360
#define ITEM_TM34            361
#define ITEM_TM35            362
#define ITEM_TM36            363
#define ITEM_TM37            364
#define ITEM_TM38            365
#define ITEM_TM39            366
#define ITEM_TM40            367
#define ITEM_TM41            368
#define ITEM_TM42            369
#define ITEM_TM43            370
#define ITEM_TM44            371
#define ITEM_TM45            372
#define ITEM_TM46            373
#define ITEM_TM47            374
#define ITEM_TM48            375
#define ITEM_TM49            376
#define ITEM_TM50            377
#define ITEM_TM51            378
#define ITEM_TM52            379
#define ITEM_TM53            380
#define ITEM_TM54            381
#define ITEM_TM55            382
#define ITEM_TM56            383
#define ITEM_TM57            384
#define ITEM_TM58            385
#define ITEM_TM59            386
#define ITEM_TM60            387
#define ITEM_TM61            388
#define ITEM_TM62            389
#define ITEM_TM63            390
#define ITEM_TM64            391
#define ITEM_TM65            392
#define ITEM_TM66            393
#define ITEM_TM67            394
#define ITEM_TM68            395
#define ITEM_TM69            396
#define ITEM_TM70            397
#define ITEM_TM71            398
#define ITEM_TM72            399
#define ITEM_TM73            400
#define ITEM_TM74            401
#define ITEM_TM75            402
#define ITEM_TM76            403
#define ITEM_TM77            404
#define ITEM_TM78            405
#define ITEM_TM79            406
#define ITEM_TM80            407
#define ITEM_TM81            408
#define ITEM_TM82            409
#define ITEM_TM83            410
#define ITEM_TM84            411
#define ITEM_TM85            412
#define ITEM_TM86            413
#define ITEM_TM87            414
#define ITEM_TM88            415
#define ITEM_TM89            416
#define ITEM_TM90            417
#define ITEM_TM91            418
#define ITEM_TM92            419
#define ITEM_HM01            420
#define ITEM_HM02            421
#define ITEM_HM03            422
#define ITEM_HM04            423
#define ITEM_HM05            424
#define ITEM_HM06            425
#define ITEM_HM07            426
#define ITEM_HM08            427

#define NUM_TMS (ITEM_TM92 - ITEM_TM01 + 1)
#define NUM_HMS (ITEM_HM08 - ITEM_HM01 + 1)

#define ITEM_EXPLORER_KIT    428
#define ITEM_LOOT_SACK       429
#define ITEM_RULE_BOOK       430
#define ITEM_POKE_RADAR      431
#define ITEM_POINT_CARD      432
#define ITEM_JOURNAL         433
#define ITEM_SEAL_CASE       434
#define ITEM_FASHION_CASE    435
#define ITEM_SEAL_BAG        436
#define ITEM_PAL_PAD         437
#define ITEM_WORKS_KEY       438
#define ITEM_OLD_CHARM       439
#define ITEM_GALACTIC_KEY    440
#define ITEM_RED_CHAIN       441
#define ITEM_TOWN_MAP        442
#define ITEM_VS_SEEKER       443
#define ITEM_COIN_CASE       444
#define ITEM_OLD_ROD         445
#define ITEM_GOOD_ROD        446
#define ITEM_SUPER_ROD       447
#define ITEM_SPRAYDUCK       448
#define ITEM_POFFIN_CASE     449
#define ITEM_BICYCLE         450
#define ITEM_SUITE_KEY       451
#define ITEM_OAKS_LETTER     452
#define ITEM_LUNAR_WING      453
#define ITEM_MEMBER_CARD     454
#define ITEM_AZURE_FLUTE     455
#define ITEM_SS_TICKET       456
#define ITEM_CONTEST_PASS    457
#define ITEM_MAGMA_STONE     458
#define ITEM_PARCEL          459
#define ITEM_COUPON_1        460
#define ITEM_COUPON_2        461
#define ITEM_COUPON_3        462
#define ITEM_STORAGE_KEY     463
#define ITEM_SECRET_MEDICINE 464
#define ITEM_VS_RECORDER     465
#define ITEM_GRACIDEA        466
#define ITEM_SECRET_KEY      467
#define ITEM_APRICORN_BOX    468
#define ITEM_UNOWN_REPORT    469
#define ITEM_BERRY_POTS      470
#define ITEM_DOWSING_MCHN    471
#define ITEM_BLUE_CARD       472
#define ITEM_SLOWPOKE_TAIL   473
#define ITEM_CLEAR_BELL      474
#define ITEM_CARD_KEY        475
#define ITEM_BASEMENT_KEY    476
#define ITEM_SQUIRT_BOTTLE   477
#define ITEM_RED_SCALE       478
#define ITEM_LOST_ITEM       479
#define ITEM_PASS            480
#define ITEM_MACHINE_PART    481
#define ITEM_SILVER_WING     482
#define ITEM_RAINBOW_WING    483
#define ITEM_MYSTERY_EGG     484
#define ITEM_RED_APRICORN    485
#define ITEM_YELLOW_APRICORN 486
#define ITEM_BLUE_APRICORN   487
#define ITEM_GREEN_APRICORN  488
#define ITEM_PINK_APRICORN   489
#define ITEM_WHITE_APRICORN  490
#define ITEM_BLACK_APRICORN  491
#define ITEM_FAST_BALL       492
#define ITEM_LEVEL_BALL      493
#define ITEM_LURE_BALL       494
#define ITEM_HEAVY_BALL      495
#define ITEM_LOVE_BALL       496
#define ITEM_FRIEND_BALL     497
#define ITEM_MOON_BALL       498
#define ITEM_SPORT_BALL      499
#define ITEM_PARK_BALL       500
#define ITEM_PHOTO_ALBUM     501
#define ITEM_GB_SOUNDS       502
#define ITEM_TIDAL_BELL      503
#define ITEM_RAGE_CANDY_BAR  504
#define ITEM_DATA_CARD_01    505
#define ITEM_DATA_CARD_02    506
#define ITEM_DATA_CARD_03    507
#define ITEM_DATA_CARD_04    508
#define ITEM_DATA_CARD_05    509
#define ITEM_DATA_CARD_06    510
#define ITEM_DATA_CARD_07    511
#define ITEM_DATA_CARD_08    512
#define ITEM_DATA_CARD_09    513
#define ITEM_DATA_CARD_10    514
#define ITEM_DATA_CARD_11    515
#define ITEM_DATA_CARD_12    516
#define ITEM_DATA_CARD_13    517
#define ITEM_DATA_CARD_14    518
#define ITEM_DATA_CARD_15    519
#define ITEM_DATA_CARD_16    520
#define ITEM_DATA_CARD_17    521
#define ITEM_DATA_CARD_18    522
#define ITEM_DATA_CARD_19    523
#define ITEM_DATA_CARD_20    524
#define ITEM_DATA_CARD_21    525
#define ITEM_DATA_CARD_22    526
#define ITEM_DATA_CARD_23    527
#define ITEM_DATA_CARD_24    528
#define ITEM_DATA_CARD_25    529
#define ITEM_DATA_CARD_26    530
#define ITEM_DATA_CARD_27    531
#define ITEM_JADE_ORB        532
#define ITEM_LOCK_CAPSULE    533
#define ITEM_RED_ORB         534
#define ITEM_BLUE_ORB        535
#define ITEM_ENIGMA_STONE    536

#define ITEM_MEGA_STONES_START 537

#define IS_ITEM_MEGA_STONE(item) (item >= ITEM_MEGA_STONES_START && item <= ITEM_DIANCITE)

//Mega Stones
#define ITEM_VENUSAURITE      (ITEM_MEGA_STONES_START)
#define ITEM_CHARIZARDITE_X   (ITEM_MEGA_STONES_START + 1)
#define ITEM_CHARIZARDITE_Y   (ITEM_MEGA_STONES_START + 2)
#define ITEM_BLASTOISINITE    (ITEM_MEGA_STONES_START + 3)
#define ITEM_BEEDRILLITE      (ITEM_MEGA_STONES_START + 4)
#define ITEM_PIDGEOTITE       (ITEM_MEGA_STONES_START + 5)
#define ITEM_ALAKAZITE        (ITEM_MEGA_STONES_START + 6)
#define ITEM_SLOWBRONITE      (ITEM_MEGA_STONES_START + 7)
#define ITEM_GENGARITE        (ITEM_MEGA_STONES_START + 8)
#define ITEM_KANGASKHANITE    (ITEM_MEGA_STONES_START + 9)
#define ITEM_PINSIRITE        (ITEM_MEGA_STONES_START + 10)
#define ITEM_GYARADOSITE      (ITEM_MEGA_STONES_START + 11)
#define ITEM_AERODACTYLITE    (ITEM_MEGA_STONES_START + 12)
#define ITEM_MEWTWONITE_X     (ITEM_MEGA_STONES_START + 13)
#define ITEM_MEWTWONITE_Y     (ITEM_MEGA_STONES_START + 14)
#define ITEM_AMPHAROSITE      (ITEM_MEGA_STONES_START + 15)
#define ITEM_STEELIXITE       (ITEM_MEGA_STONES_START + 16)
#define ITEM_SCIZORITE        (ITEM_MEGA_STONES_START + 17)
#define ITEM_HERACRONITE      (ITEM_MEGA_STONES_START + 18)
#define ITEM_HOUNDOOMINITE    (ITEM_MEGA_STONES_START + 19)
#define ITEM_TYRANITARITE     (ITEM_MEGA_STONES_START + 20)
#define ITEM_SCEPTILITE       (ITEM_MEGA_STONES_START + 21)
#define ITEM_BLAZIKENITE      (ITEM_MEGA_STONES_START + 22)
#define ITEM_SWAMPERTITE      (ITEM_MEGA_STONES_START + 23)
#define ITEM_GARDEVOIRITE     (ITEM_MEGA_STONES_START + 24)
#define ITEM_SABLENITE        (ITEM_MEGA_STONES_START + 25)
#define ITEM_MAWILITE         (ITEM_MEGA_STONES_START + 26)
#define ITEM_AGGRONITE        (ITEM_MEGA_STONES_START + 27)
#define ITEM_MEDICHAMITE      (ITEM_MEGA_STONES_START + 28)
#define ITEM_MANECTITE        (ITEM_MEGA_STONES_START + 29)
#define ITEM_SHARPEDONITE     (ITEM_MEGA_STONES_START + 30)
#define ITEM_CAMERUPTITE      (ITEM_MEGA_STONES_START + 31)
#define ITEM_ALTARIANITE      (ITEM_MEGA_STONES_START + 32)
#define ITEM_BANETTITE        (ITEM_MEGA_STONES_START + 33)
#define ITEM_ABSOLITE         (ITEM_MEGA_STONES_START + 34)
#define ITEM_GLALITITE        (ITEM_MEGA_STONES_START + 35)
#define ITEM_SALAMENCITE      (ITEM_MEGA_STONES_START + 36)
#define ITEM_METAGROSSITE     (ITEM_MEGA_STONES_START + 37)
#define ITEM_LATIASITE        (ITEM_MEGA_STONES_START + 38)
#define ITEM_LATIOSITE        (ITEM_MEGA_STONES_START + 39)
#define ITEM_LOPUNNITE        (ITEM_MEGA_STONES_START + 40)
#define ITEM_GARCHOMPITE      (ITEM_MEGA_STONES_START + 41)
#define ITEM_LUCARIONITE      (ITEM_MEGA_STONES_START + 42)
#define ITEM_ABOMASITE        (ITEM_MEGA_STONES_START + 43)
#define ITEM_GALLADITE        (ITEM_MEGA_STONES_START + 44)
#define ITEM_AUDINITE         (ITEM_MEGA_STONES_START + 45)
#define ITEM_DIANCITE         (ITEM_MEGA_STONES_START + 46)
#define ITEM_PIXIE_PLATE      (ITEM_MEGA_STONES_START + 47)

#define ITEM_MAX_MEGA_STONES  (ITEM_PIXIE_PLATE)

//Item expansion
#define ITEM_EXPANSION_START    (ITEM_PIXIE_PLATE + 1)

//Generation V
#define ITEM_ABSORB_BULB        (ITEM_PIXIE_PLATE + 1)
#define ITEM_AIR_BALLOON        (ITEM_PIXIE_PLATE + 2)
#define ITEM_BALM_MUSHROOM      (ITEM_PIXIE_PLATE + 3)
#define ITEM_BIG_NUGGET         (ITEM_PIXIE_PLATE + 4)
#define ITEM_BINDING_BAND       (ITEM_PIXIE_PLATE + 5)
#define ITEM_CASTELIACONE       (ITEM_PIXIE_PLATE + 6)
#define ITEM_CELL_BATTERY       (ITEM_PIXIE_PLATE + 7)
#define ITEM_COMET_SHARD        (ITEM_PIXIE_PLATE + 8)
#define ITEM_DREAM_BALL         (ITEM_PIXIE_PLATE + 9)
#define ITEM_EJECT_BUTTON       (ITEM_PIXIE_PLATE + 10)
#define ITEM_EVIOLITE           (ITEM_PIXIE_PLATE + 11)
#define ITEM_FLOAT_STONE        (ITEM_PIXIE_PLATE + 12)
#define ITEM_PEARL_STRING       (ITEM_PIXIE_PLATE + 13)
#define ITEM_PRISM_SCALE        (ITEM_PIXIE_PLATE + 14)
#define ITEM_RED_CARD           (ITEM_PIXIE_PLATE + 15)
#define ITEM_RING_TARGET        (ITEM_PIXIE_PLATE + 16)
#define ITEM_ROCKY_HELMET       (ITEM_PIXIE_PLATE + 17)
#define ITEM_SWEET_HEART        (ITEM_PIXIE_PLATE + 18)

//Generation VI
#define ITEM_ABILITY_CAPSULE    (ITEM_PIXIE_PLATE + 19)
#define ITEM_ASSAULT_VEST       (ITEM_PIXIE_PLATE + 20)
#define ITEM_LUMINOUS_MOSS      (ITEM_PIXIE_PLATE + 21)
#define ITEM_LUMIOSE_GALETTE    (ITEM_PIXIE_PLATE + 22)
#define ITEM_SACHET             (ITEM_PIXIE_PLATE + 23)
#define ITEM_SAFETY_GOGGLES     (ITEM_PIXIE_PLATE + 24)
#define ITEM_SHALOUR_SABLE      (ITEM_PIXIE_PLATE + 25)
#define ITEM_SNOWBALL           (ITEM_PIXIE_PLATE + 26)
#define ITEM_WEAKNESS_POLICY    (ITEM_PIXIE_PLATE + 27)
#define ITEM_WHIPPED_DREAM      (ITEM_PIXIE_PLATE + 28)

//Generation VII
#define ITEM_ADRENALINE_ORB     (ITEM_PIXIE_PLATE + 29)
#define ITEM_BEAST_BALL         (ITEM_PIXIE_PLATE + 30)
#define ITEM_BIG_MALASADA       (ITEM_PIXIE_PLATE + 31)
#define ITEM_BOTTLE_CAP         (ITEM_PIXIE_PLATE + 32)
#define ITEM_GOLD_BOTTLE_CAP    (ITEM_PIXIE_PLATE + 33)
#define ITEM_ELECTRIC_SEED      (ITEM_PIXIE_PLATE + 34)
#define ITEM_GRASSY_SEED        (ITEM_PIXIE_PLATE + 35)
#define ITEM_MISTY_SEED         (ITEM_PIXIE_PLATE + 36)
#define ITEM_PSYCHIC_SEED       (ITEM_PIXIE_PLATE + 37)
#define ITEM_ICE_STONE          (ITEM_PIXIE_PLATE + 38)
#define ITEM_PROTECTIVE_PADS    (ITEM_PIXIE_PLATE + 39)
#define ITEM_TERRAIN_EXTENDER   (ITEM_PIXIE_PLATE + 40)

//Generation VIII
#define ITEM_ABILITY_PATCH      (ITEM_PIXIE_PLATE + 41)
#define ITEM_BLACK_AUGURITE     (ITEM_PIXIE_PLATE + 42)
#define ITEM_BERRY_SWEET        (ITEM_PIXIE_PLATE + 43)
#define ITEM_CLOVER_SWEET       (ITEM_PIXIE_PLATE + 44)
#define ITEM_FLOWER_SWEET       (ITEM_PIXIE_PLATE + 45)
#define ITEM_LOVE_SWEET         (ITEM_PIXIE_PLATE + 46)
#define ITEM_RIBBON_SWEET       (ITEM_PIXIE_PLATE + 47)
#define ITEM_STAR_SWEET         (ITEM_PIXIE_PLATE + 48)
#define ITEM_STRAWBERRY_SWEET   (ITEM_PIXIE_PLATE + 49)
#define ITEM_BLUNDER_POLICY     (ITEM_PIXIE_PLATE + 50)
#define ITEM_CHIPPED_POT        (ITEM_PIXIE_PLATE + 51)
#define ITEM_CRACKED_POT        (ITEM_PIXIE_PLATE + 52)
#define ITEM_EJECT_PACK         (ITEM_PIXIE_PLATE + 53)
#define ITEM_EXP_CANDY_S        (ITEM_PIXIE_PLATE + 54)
#define ITEM_EXP_CANDY_M        (ITEM_PIXIE_PLATE + 55)
#define ITEM_EXP_CANDY_L        (ITEM_PIXIE_PLATE + 56)
#define ITEM_EXP_CANDY_XS       (ITEM_PIXIE_PLATE + 57)
#define ITEM_EXP_CANDY_XL       (ITEM_PIXIE_PLATE + 58)
#define ITEM_GALARICA_CUFF      (ITEM_PIXIE_PLATE + 59)
#define ITEM_GALARICA_TWIG      (ITEM_PIXIE_PLATE + 60)
#define ITEM_GALARICA_WREATH    (ITEM_PIXIE_PLATE + 61)
#define ITEM_HEAVY_DUTY_BOOTS   (ITEM_PIXIE_PLATE + 62)
#define ITEM_LINKING_CORD       (ITEM_PIXIE_PLATE + 63)
#define ITEM_MOOMOO_CHEESE      (ITEM_PIXIE_PLATE + 64)
#define ITEM_PEAT_BLOCK         (ITEM_PIXIE_PLATE + 65)
#define ITEM_ROOM_SERVICE       (ITEM_PIXIE_PLATE + 66)
#define ITEM_RUSTED_SHIELD      (ITEM_PIXIE_PLATE + 67)
#define ITEM_RUSTED_SWORD       (ITEM_PIXIE_PLATE + 68)
#define ITEM_SWEET_APPLE        (ITEM_PIXIE_PLATE + 69)
#define ITEM_TART_APPLE         (ITEM_PIXIE_PLATE + 70)
#define ITEM_THROAT_SPRAY       (ITEM_PIXIE_PLATE + 71)
#define ITEM_UTILITY_UMBRELLA   (ITEM_PIXIE_PLATE + 72)

//Generation IX
#define ITEM_ABILITY_SHIELD     (ITEM_PIXIE_PLATE + 73)
#define ITEM_AUSPICIOUS_ARMOR   (ITEM_PIXIE_PLATE + 74)
#define ITEM_BOOSTER_ENERGY     (ITEM_PIXIE_PLATE + 75)
#define ITEM_CLEAR_AMULET       (ITEM_PIXIE_PLATE + 76)
#define ITEM_COVERT_CLOAK       (ITEM_PIXIE_PLATE + 77)
#define ITEM_GIMMIGHOUL_COIN    (ITEM_PIXIE_PLATE + 78)
#define ITEM_LEADERS_CREST      (ITEM_PIXIE_PLATE + 79)
#define ITEM_LOADED_DICE        (ITEM_PIXIE_PLATE + 80)
#define ITEM_MALICIOUS_ARMOR    (ITEM_PIXIE_PLATE + 81)
#define ITEM_MIRROR_HERB        (ITEM_PIXIE_PLATE + 82)
#define ITEM_PUNCHING_GLOVE     (ITEM_PIXIE_PLATE + 83)

//Berries
#define ITEM_ROSELI_BERRY       (ITEM_PIXIE_PLATE + 84)
#define ITEM_KEE_BERRY          (ITEM_PIXIE_PLATE + 85)
#define ITEM_MARANGA_BERRY      (ITEM_PIXIE_PLATE + 86)

//Drives
#define ITEM_BURN_DRIVE         (ITEM_PIXIE_PLATE + 87)
#define ITEM_CHILL_DRIVE        (ITEM_PIXIE_PLATE + 88)
#define ITEM_DOUSE_DRIVE        (ITEM_PIXIE_PLATE + 89)
#define ITEM_SHOCK_DRIVE        (ITEM_PIXIE_PLATE + 90)

#define IS_ITEM_GENESECT_DRIVE(item) (item >= ITEM_BURN_DRIVE && item <= ITEM_SHOCK_DRIVE)

//Fossils
#define ITEM_COVER_FOSSIL       (ITEM_PIXIE_PLATE + 91)
#define ITEM_PLUME_FOSSIL       (ITEM_PIXIE_PLATE + 92)
#define ITEM_JAW_FOSSIL         (ITEM_PIXIE_PLATE + 93)
#define ITEM_SAIL_FOSSIL        (ITEM_PIXIE_PLATE + 94)
#define ITEM_FOSSILIZED_BIRD    (ITEM_PIXIE_PLATE + 95)
#define ITEM_FOSSILIZED_DINO    (ITEM_PIXIE_PLATE + 96)
#define ITEM_FOSSILIZED_DRAKE   (ITEM_PIXIE_PLATE + 97)
#define ITEM_FOSSILIZED_FISH    (ITEM_PIXIE_PLATE + 98)

//Gems
#define ITEM_NORMAL_GEM         (ITEM_PIXIE_PLATE + 99)
#define ITEM_FIGHTING_GEM       (ITEM_PIXIE_PLATE + 100)
#define ITEM_FLYING_GEM         (ITEM_PIXIE_PLATE + 101)
#define ITEM_POISON_GEM         (ITEM_PIXIE_PLATE + 102)
#define ITEM_GROUND_GEM         (ITEM_PIXIE_PLATE + 103)
#define ITEM_ROCK_GEM           (ITEM_PIXIE_PLATE + 104)
#define ITEM_BUG_GEM            (ITEM_PIXIE_PLATE + 105)
#define ITEM_GHOST_GEM          (ITEM_PIXIE_PLATE + 106)
#define ITEM_STEEL_GEM          (ITEM_PIXIE_PLATE + 107)
#define ITEM_FIRE_GEM           (ITEM_PIXIE_PLATE + 108)
#define ITEM_WATER_GEM          (ITEM_PIXIE_PLATE + 109)
#define ITEM_GRASS_GEM          (ITEM_PIXIE_PLATE + 110)
#define ITEM_ELECTRIC_GEM       (ITEM_PIXIE_PLATE + 111)
#define ITEM_PSYCHIC_GEM        (ITEM_PIXIE_PLATE + 112)
#define ITEM_ICE_GEM            (ITEM_PIXIE_PLATE + 113)
#define ITEM_DRAGON_GEM         (ITEM_PIXIE_PLATE + 114)
#define ITEM_DARK_GEM           (ITEM_PIXIE_PLATE + 115)
#define ITEM_FAIRY_GEM          (ITEM_PIXIE_PLATE + 116)

//Memories
#define IS_ITEM_MEMORY(item) (item >= ITEM_FIGHTING_MEMORY && item <= ITEM_FAIRY_MEMORY)

#define ITEM_FIGHTING_MEMORY    (ITEM_PIXIE_PLATE + 117)
#define ITEM_FLYING_MEMORY      (ITEM_PIXIE_PLATE + 118)
#define ITEM_POISON_MEMORY      (ITEM_PIXIE_PLATE + 119)
#define ITEM_GROUND_MEMORY      (ITEM_PIXIE_PLATE + 120)
#define ITEM_ROCK_MEMORY        (ITEM_PIXIE_PLATE + 121)
#define ITEM_BUG_MEMORY         (ITEM_PIXIE_PLATE + 122)
#define ITEM_GHOST_MEMORY       (ITEM_PIXIE_PLATE + 123)
#define ITEM_STEEL_MEMORY       (ITEM_PIXIE_PLATE + 124)
#define ITEM_FIRE_MEMORY        (ITEM_PIXIE_PLATE + 125)
#define ITEM_WATER_MEMORY       (ITEM_PIXIE_PLATE + 126)
#define ITEM_GRASS_MEMORY       (ITEM_PIXIE_PLATE + 127)
#define ITEM_ELECTRIC_MEMORY    (ITEM_PIXIE_PLATE + 128)
#define ITEM_PSYCHIC_MEMORY     (ITEM_PIXIE_PLATE + 129)
#define ITEM_ICE_MEMORY         (ITEM_PIXIE_PLATE + 130)
#define ITEM_DRAGON_MEMORY      (ITEM_PIXIE_PLATE + 131)
#define ITEM_DARK_MEMORY        (ITEM_PIXIE_PLATE + 132)
#define ITEM_FAIRY_MEMORY       (ITEM_PIXIE_PLATE + 133)

//Nectars
#define ITEM_RED_NECTAR         (ITEM_PIXIE_PLATE + 134)
#define ITEM_YELLOW_NECTAR      (ITEM_PIXIE_PLATE + 135)
#define ITEM_PINK_NECTAR        (ITEM_PIXIE_PLATE + 136)
#define ITEM_PURPLE_NECTAR      (ITEM_PIXIE_PLATE + 137)

//Plates
#define ITEM_BLANK_PLATE        (ITEM_PIXIE_PLATE + 138)
#define ITEM_LEGEND_PLATE       (ITEM_PIXIE_PLATE + 139)

//Relic Items
#define ITEM_RELIC_COPPER       (ITEM_PIXIE_PLATE + 140)
#define ITEM_RELIC_SILVER       (ITEM_PIXIE_PLATE + 141)
#define ITEM_RELIC_GOLD         (ITEM_PIXIE_PLATE + 142)
#define ITEM_RELIC_VASE         (ITEM_PIXIE_PLATE + 143)
#define ITEM_RELIC_BAND         (ITEM_PIXIE_PLATE + 144)
#define ITEM_RELIC_STATUE       (ITEM_PIXIE_PLATE + 145)
#define ITEM_RELIC_CROWN        (ITEM_PIXIE_PLATE + 146)

//Wings
#define ITEM_HEALTH_FEATHER     (ITEM_PIXIE_PLATE + 147)
#define ITEM_MUSCLE_FEATHER     (ITEM_PIXIE_PLATE + 148)
#define ITEM_RESIST_FEATHER     (ITEM_PIXIE_PLATE + 149)
#define ITEM_GENIUS_FEATHER     (ITEM_PIXIE_PLATE + 150)
#define ITEM_CLEVER_FEATHER     (ITEM_PIXIE_PLATE + 151)
#define ITEM_SWIFT_FEATHER      (ITEM_PIXIE_PLATE + 152)
#define ITEM_PRETTY_FEATHER     (ITEM_PIXIE_PLATE + 153)

//Key Items
#define ITEM_DNA_SPLICERS       (ITEM_PIXIE_PLATE + 154)
#define ITEM_REVEAL_GLASS       (ITEM_PIXIE_PLATE + 155)
#define ITEM_PRISON_BOTTLE      (ITEM_PIXIE_PLATE + 156)
#define ITEM_CATCHING_CHARM     (ITEM_PIXIE_PLATE + 157)
#define ITEM_EXP_CHARM          (ITEM_PIXIE_PLATE + 158)
#define ITEM_OVAL_CHARM         (ITEM_PIXIE_PLATE + 159)
#define ITEM_SHINY_CHARM        (ITEM_PIXIE_PLATE + 160)
#define ITEM_N_SOLARIZER        (ITEM_PIXIE_PLATE + 161)
#define ITEM_N_LUNARIZER        (ITEM_PIXIE_PLATE + 162)
#define ITEM_POKEMON_BOX_LINK   (ITEM_PIXIE_PLATE + 163)
#define ITEM_ZYGARDE_CUBE       (ITEM_PIXIE_PLATE + 164)
#define ITEM_SUN_FLUTE          (ITEM_PIXIE_PLATE + 165)
#define ITEM_MOON_FLUTE         (ITEM_PIXIE_PLATE + 166)
#define ITEM_LIGHT_STONE        (ITEM_PIXIE_PLATE + 167)
#define ITEM_DARK_STONE         (ITEM_PIXIE_PLATE + 168)
#define ITEM_ICEROOT_CARROT     (ITEM_PIXIE_PLATE + 169)
#define ITEM_SHADEROOT_CARROT   (ITEM_PIXIE_PLATE + 170)
#define ITEM_REINS_OF_UNITY     (ITEM_PIXIE_PLATE + 171)
#define ITEM_WOODEN_CROWN       (ITEM_PIXIE_PLATE + 172)
#define ITEM_ROTOM_CATALOG      (ITEM_PIXIE_PLATE + 173)
#define ITEM_ADAMANT_CRYSTAL    (ITEM_PIXIE_PLATE + 174)
#define ITEM_LUSTROUS_GLOBE     (ITEM_PIXIE_PLATE + 175)
#define ITEM_GRISEOUS_CORE      (ITEM_PIXIE_PLATE + 176)
#define ITEM_SCROLL_OF_DARKNESS (ITEM_PIXIE_PLATE + 177)
#define ITEM_SCROLL_OF_WATERS   (ITEM_PIXIE_PLATE + 178)
#define ITEM_MEGA_RING          (ITEM_PIXIE_PLATE + 179)

//Lets Go Pikachu
#define ITEM_AUTOGRAPH          (ITEM_PIXIE_PLATE + 180)
#define ITEM_GOLD_TEETH         (ITEM_PIXIE_PLATE + 181)
#define ITEM_KEY_STONE          (ITEM_PIXIE_PLATE + 182)
#define ITEM_LIFT_KEY           (ITEM_PIXIE_PLATE + 183)
#define ITEM_PEWTER_CRUNCHIES   (ITEM_PIXIE_PLATE + 184)
#define ITEM_SYLPH_SCOPE        (ITEM_PIXIE_PLATE + 185)
#define ITEM_TEA                (ITEM_PIXIE_PLATE + 186)

//Mints
#define IS_ITEM_NATURE_MINT(item) (item >= ITEM_LONELY_MINT && item <= ITEM_SERIOUS_MINT)

#define ITEM_LONELY_MINT        (ITEM_PIXIE_PLATE + 187)
#define ITEM_ADAMANT_MINT       (ITEM_PIXIE_PLATE + 188)
#define ITEM_NAUGHTY_MINT       (ITEM_PIXIE_PLATE + 189)
#define ITEM_BRAVE_MINT         (ITEM_PIXIE_PLATE + 190)
#define ITEM_BOLD_MINT          (ITEM_PIXIE_PLATE + 191)
#define ITEM_IMPISH_MINT        (ITEM_PIXIE_PLATE + 192)
#define ITEM_LAX_MINT           (ITEM_PIXIE_PLATE + 193)
#define ITEM_RELAXED_MINT       (ITEM_PIXIE_PLATE + 194)
#define ITEM_MODEST_MINT        (ITEM_PIXIE_PLATE + 195)
#define ITEM_MILD_MINT          (ITEM_PIXIE_PLATE + 196)
#define ITEM_RASH_MINT          (ITEM_PIXIE_PLATE + 197)
#define ITEM_QUIET_MINT         (ITEM_PIXIE_PLATE + 198)
#define ITEM_CALM_MINT          (ITEM_PIXIE_PLATE + 199)
#define ITEM_GENTLE_MINT        (ITEM_PIXIE_PLATE + 200)
#define ITEM_CAREFUL_MINT       (ITEM_PIXIE_PLATE + 201)
#define ITEM_SASSY_MINT         (ITEM_PIXIE_PLATE + 202)
#define ITEM_TIMID_MINT         (ITEM_PIXIE_PLATE + 203)
#define ITEM_HASTY_MINT         (ITEM_PIXIE_PLATE + 204)
#define ITEM_JOLLY_MINT         (ITEM_PIXIE_PLATE + 205)
#define ITEM_NAIVE_MINT         (ITEM_PIXIE_PLATE + 206)
#define ITEM_SERIOUS_MINT       (ITEM_PIXIE_PLATE + 207)

//Gen IX DLC
#define ITEM_FAIRY_FEATHER      (ITEM_PIXIE_PLATE + 208)
#define ITEM_SYRUPY_APPLE       (ITEM_PIXIE_PLATE + 209)
#define ITEM_UNREMARKABLE_TEACUP (ITEM_PIXIE_PLATE + 210)
#define ITEM_MASTERPIECE_TEACUP (ITEM_PIXIE_PLATE + 211)
#define ITEM_CORNERSTONE_MASK   (ITEM_PIXIE_PLATE + 212)
#define ITEM_WELLSPRING_MASK    (ITEM_PIXIE_PLATE + 213)
#define ITEM_HEARTHFLAME_MASK   (ITEM_PIXIE_PLATE + 214)
#define ITEM_METAL_ALLOY        (ITEM_PIXIE_PLATE + 215)

#define MAX_BASE_ITEM_NUM ITEM_METAL_ALLOY

// define your custom move effects below like this
// #define ITEM_CUSTOM_1 (MAX_BASE_ITEM_NUM + 1)



#define NUM_MEGA_STONES 48 // includes the pixie plate

#define IS_ITEM_TERRAIN_SEED(item) (item >= ITEM_ELECTRIC_SEED && item <= ITEM_PSYCHIC_SEED)

#define IS_ITEM_MASK(item) (item >= ITEM_CORNERSTONE_MASK && item <= ITEM_HEARTHFLAME_MASK)

#define NUM_UNKNOWN_SLOTS 22 // used to adjust in data/itemdata.c
#define NUM_UNKNOWN_SLOTS_EXPLORER_KIT (NUM_UNKNOWN_SLOTS+1) // used to adjust in data/itemdata.c

#define NEW_ITEM_MAX ITEM_METAL_ALLOY

#define BAG_SLOT_QUANTITY_MAX                    999

#ifdef REUSABLE_TMS
#define BAG_TMHM_QUANTITY_MAX                      1
#else
#define BAG_TMHM_QUANTITY_MAX                     99
#endif

#define POCKET_ITEMS        0
#define POCKET_MEDICINE     1
#define POCKET_BALLS        2
#define POCKET_TMHMS        3
#define POCKET_BERRIES      4
#define POCKET_MAIL         5
#define POCKET_BATTLE_ITEMS 6
#define POCKET_KEY_ITEMS    7
#define POCKETS_COUNT       8

#define BATTLE_POCKET_NONE 0
#define BATTLE_POCKET_POKE_BALLS 1
#define BATTLE_POCKET_BATTLE_ITEMS 2
#define BATTLE_POCKET_HP_RESTORE 4
#define BATTLE_POCKET_STATUS_HEALERS 8
#define BATTLE_POCKET_PP_RESTORE 16


#ifdef ITEM_POCKET_EXPANSION

// pixie plate + megas
#define NUM_BAG_ITEMS        165+32+NUM_MEGA_STONES
#define NUM_BAG_MEDICINE      40
#define NUM_BAG_BALLS         24+2
#define NUM_BAG_TMS_HMS      101
#define NUM_BAG_BERRIES       64
#define NUM_BAG_MAIL          12
#define NUM_BAG_BATTLE_ITEMS  30
#define NUM_BAG_KEY_ITEMS     50+42

#else

#define NUM_BAG_ITEMS        165
#define NUM_BAG_MEDICINE      40
#define NUM_BAG_BALLS         24
#define NUM_BAG_TMS_HMS      101
#define NUM_BAG_BERRIES       64
#define NUM_BAG_MAIL          12
#define NUM_BAG_BATTLE_ITEMS  30
#define NUM_BAG_KEY_ITEMS     50

#endif


#endif
