#ifndef CONSTANTS_MOVE_EFFECTS_H
#define CONSTANTS_MOVE_EFFECTS_H

#define MOVE_EFFECT_HIT                                       0
#define MOVE_EFFECT_STATUS_SLEEP                              1
#define MOVE_EFFECT_POISON_HIT                                2
#define MOVE_EFFECT_RECOVER_HALF_DAMAGE_DEALT                 3
#define MOVE_EFFECT_BURN_HIT                                  4
#define MOVE_EFFECT_FREEZE_HIT                                5
#define MOVE_EFFECT_PARALYZE_HIT                              6
#define MOVE_EFFECT_HALVE_DEFENSE                             7
#define MOVE_EFFECT_RECOVER_DAMAGE_SLEEP                      8
#define MOVE_EFFECT_COPY_MOVE                                 9
#define MOVE_EFFECT_ATK_UP                                   10
#define MOVE_EFFECT_DEF_UP                                   11
#define MOVE_EFFECT_SPEED_UP                                 12
#define MOVE_EFFECT_SP_ATK_UP                                13
#define MOVE_EFFECT_SP_DEF_UP                                14
#define MOVE_EFFECT_ACC_UP                                   15
#define MOVE_EFFECT_EVA_UP                                   16
#define MOVE_EFFECT_BYPASS_ACCURACY                          17
#define MOVE_EFFECT_ATK_DOWN                                 18
#define MOVE_EFFECT_DEF_DOWN                                 19
#define MOVE_EFFECT_SPEED_DOWN                               20
#define MOVE_EFFECT_SP_ATK_DOWN                              21
#define MOVE_EFFECT_SP_DEF_DOWN                              22
#define MOVE_EFFECT_ACC_DOWN                                 23
#define MOVE_EFFECT_EVA_DOWN                                 24
#define MOVE_EFFECT_RESET_STAT_CHANGES                       25
#define MOVE_EFFECT_BIDE                                     26
#define MOVE_EFFECT_CONTINUE_AND_CONFUSE_SELF                27
#define MOVE_EFFECT_FORCE_SWITCH                             28
#define MOVE_EFFECT_MULTI_HIT                                29
#define MOVE_EFFECT_CONVERSION                               30
#define MOVE_EFFECT_FLINCH_HIT                               31
#define MOVE_EFFECT_RESTORE_HALF_HP                          32
#define MOVE_EFFECT_STATUS_BADLY_POISON                      33
#define MOVE_EFFECT_INCREASE_PRIZE_MONEY                     34
#define MOVE_EFFECT_SET_LIGHT_SCREEN                         35
#define MOVE_EFFECT_RANDOM_PRIMARY_STATUS_HIT                36
#define MOVE_EFFECT_RECOVER_HEALTH_AND_SLEEP                 37
#define MOVE_EFFECT_ONE_HIT_KO                               38
#define MOVE_EFFECT_CHARGE_TURN_HIGH_CRIT                    39
#define MOVE_EFFECT_HALVE_HP                                 40
#define MOVE_EFFECT_40_DAMAGE_FLAT                           41
#define MOVE_EFFECT_BIND_HIT                                 42
#define MOVE_EFFECT_HIGH_CRITICAL                            43
#define MOVE_EFFECT_HIT_TWICE                                44
#define MOVE_EFFECT_CRASH_ON_MISS                            45
#define MOVE_EFFECT_PREVENT_STAT_REDUCTION                   46
#define MOVE_EFFECT_CRIT_UP_2                                47
#define MOVE_EFFECT_RECOIL_QUARTER_DAMAGE_DELT               48
#define MOVE_EFFECT_STATUS_CONFUSE                           49
#define MOVE_EFFECT_ATK_UP_2                                 50
#define MOVE_EFFECT_DEF_UP_2                                 51
#define MOVE_EFFECT_SPEED_UP_2                               52
#define MOVE_EFFECT_SP_ATK_UP_2                              53
#define MOVE_EFFECT_SP_DEF_UP_2                              54
#define MOVE_EFFECT_ACC_UP_2                                 55
#define MOVE_EFFECT_EVA_UP_2                                 56
#define MOVE_EFFECT_TRANSFORM                                57
#define MOVE_EFFECT_ATK_DOWN_2                               58
#define MOVE_EFFECT_DEF_DOWN_2                               59
#define MOVE_EFFECT_SPEED_DOWN_2                             60
#define MOVE_EFFECT_SP_ATK_DOWN_2                            61
#define MOVE_EFFECT_SP_DEF_DOWN_2                            62
#define MOVE_EFFECT_ACC_DOWN_2                               63
#define MOVE_EFFECT_EVA_DOWN_2                               64
#define MOVE_EFFECT_SET_REFLECT                              65
#define MOVE_EFFECT_STATUS_POISON                            66
#define MOVE_EFFECT_STATUS_PARALYZE                          67
#define MOVE_EFFECT_LOWER_ATTACK_HIT                         68
#define MOVE_EFFECT_LOWER_DEFENSE_HIT                        69
#define MOVE_EFFECT_LOWER_SPEED_HIT                          70
#define MOVE_EFFECT_LOWER_SP_ATK_HIT                         71
#define MOVE_EFFECT_LOWER_SP_DEF_HIT                         72
#define MOVE_EFFECT_LOWER_ACCURACY_HIT                       73
#define MOVE_EFFECT_LOWER_EVASION_HIT                        74
#define MOVE_EFFECT_CHARGE_TURN_HIGH_CRIT_FLINCH             75
#define MOVE_EFFECT_CONFUSE_HIT                              76
#define MOVE_EFFECT_POISON_MULTI_HIT                         77
#define MOVE_EFFECT_PRIORITY_NEG_1_BYPASS_ACCURACY           78
#define MOVE_EFFECT_SET_SUBSTITUTE                           79
#define MOVE_EFFECT_RECHARGE_AFTER                           80
#define MOVE_EFFECT_RAISE_ATK_WHEN_HIT                       81
#define MOVE_EFFECT_COPY_MOVE_FOR_BATTLE                     82
#define MOVE_EFFECT_CALL_RANDOM_MOVE                         83
#define MOVE_EFFECT_STATUS_LEECH_SEED                        84
#define MOVE_EFFECT_DO_NOTHING                               85
#define MOVE_EFFECT_DISABLE                                  86
#define MOVE_EFFECT_LEVEL_DAMAGE_FLAT                        87
#define MOVE_EFFECT_RANDOM_DAMAGE_1_TO_150_LEVEL             88
#define MOVE_EFFECT_COUNTER                                  89
#define MOVE_EFFECT_ENCORE                                   90
#define MOVE_EFFECT_AVERAGE_HP                               91
#define MOVE_EFFECT_DAMAGE_WHILE_ASLEEP                      92
#define MOVE_EFFECT_CONVERSION2                              93
#define MOVE_EFFECT_NEXT_ATTACK_ALWAYS_HITS                  94
#define MOVE_EFFECT_LEARN_MOVE_PERMANENT                     95
#define MOVE_EFFECT_UNUSED_96                                96
#define MOVE_EFFECT_USE_RANDOM_LEARNED_MOVE_SLEEP            97
#define MOVE_EFFECT_KO_MON_THAT_DEFEATED_USER                98
#define MOVE_EFFECT_INCREASE_POWER_WITH_LESS_HP              99
#define MOVE_EFFECT_DECREASE_LAST_MOVE_PP                   100
#define MOVE_EFFECT_LEAVE_WITH_1_HP                         101
#define MOVE_EFFECT_CURE_PARTY_STATUS                       102
#define MOVE_EFFECT_PRIORITY_1                              103
#define MOVE_EFFECT_HIT_THREE_TIMES_INCREMENT_BASE_POWER_10 104
#define MOVE_EFFECT_STEAL_HELD_ITEM                         105
#define MOVE_EFFECT_PREVENT_ESCAPE                          106
#define MOVE_EFFECT_STATUS_NIGHTMARE                        107
#define MOVE_EFFECT_EVA_UP_2_MINIMIZE                       108
#define MOVE_EFFECT_CURSE                                   109
#define MOVE_EFFECT_UNUSED_110                              110
#define MOVE_EFFECT_PROTECT                                 111
#define MOVE_EFFECT_SET_SPIKES                              112
#define MOVE_EFFECT_IGNORE_EVASION_REMOVE_GHOST_IMMUNE      113
#define MOVE_EFFECT_ALL_FAINT_3_TURNS                       114
#define MOVE_EFFECT_WEATHER_SANDSTORM                       115
#define MOVE_EFFECT_SURVIVE_WITH_1_HP                       116
#define MOVE_EFFECT_DOUBLE_POWER_EACH_TURN_LOCK_INTO        117
#define MOVE_EFFECT_ATK_UP_2_STATUS_CONFUSION               118
#define MOVE_EFFECT_DOUBLE_POWER_EACH_TURN                  119
#define MOVE_EFFECT_INFATUATE                               120
#define MOVE_EFFECT_POWER_BASED_ON_FRIENDSHIP               121
#define MOVE_EFFECT_RANDOM_POWER_MAYBE_HEAL                 122
#define MOVE_EFFECT_POWER_BASED_ON_LOW_FRIENDSHIP           123
#define MOVE_EFFECT_PREVENT_STATUS                          124
#define MOVE_EFFECT_THAW_AND_BURN_HIT                       125
#define MOVE_EFFECT_RANDOM_POWER_10_CASES                   126
#define MOVE_EFFECT_PASS_STATS_AND_STATUS                   127
#define MOVE_EFFECT_HIT_BEFORE_SWITCH                       128
#define MOVE_EFFECT_REMOVE_HAZARDS_AND_BINDING              129
#define MOVE_EFFECT_10_DAMAGE_FLAT                          130
#define MOVE_EFFECT_UNUSED_131                              131
#define MOVE_EFFECT_HEAL_HALF_MORE_IN_SUN                   132
#define MOVE_EFFECT_UNUSED_133                              133
#define MOVE_EFFECT_UNUSED_134                              134
#define MOVE_EFFECT_RANDOM_TYPE_BASED_ON_IVS                135
#define MOVE_EFFECT_WEATHER_RAIN                            136
#define MOVE_EFFECT_WEATHER_SUN                             137
#define MOVE_EFFECT_RAISE_DEF_HIT                           138
#define MOVE_EFFECT_RAISE_ATTACK_HIT                        139
#define MOVE_EFFECT_RAISE_ALL_STATS_HIT                     140
#define MOVE_EFFECT_UNUSED_141                              141
#define MOVE_EFFECT_MAX_ATK_LOSE_HALF_MAX_HP                142
#define MOVE_EFFECT_COPY_STAT_CHANGES                       143
#define MOVE_EFFECT_MIRROR_COAT                             144
#define MOVE_EFFECT_CHARGE_TURN_DEF_UP                      145
#define MOVE_EFFECT_FLINCH_DOUBLE_DAMAGE_FLY_OR_BOUNCE      146
#define MOVE_EFFECT_DOUBLE_DAMAGE_DIG                       147
#define MOVE_EFFECT_HIT_IN_3_TURNS                          148
#define MOVE_EFFECT_DOUBLE_DAMAGE_FLY_OR_BOUNCE             149
#define MOVE_EFFECT_FLINCH_MINIMIZE_DOUBLE_HIT              150
#define MOVE_EFFECT_CHARGE_TURN_SUN_SKIPS                   151
#define MOVE_EFFECT_THUNDER                                 152
#define MOVE_EFFECT_FLEE_FROM_WILD_BATTLE                   153
#define MOVE_EFFECT_BEAT_UP                                 154
#define MOVE_EFFECT_FLY                                     155
#define MOVE_EFFECT_DEF_UP_DOUBLE_ROLLOUT_POWER             156
#define MOVE_EFFECT_UNUSED_157                              157
#define MOVE_EFFECT_ALWAYS_FLINCH_FIRST_TURN_ONLY           158
#define MOVE_EFFECT_UPROAR                                  159
#define MOVE_EFFECT_STOCKPILE                               160
#define MOVE_EFFECT_SPIT_UP                                 161
#define MOVE_EFFECT_SWALLOW                                 162
#define MOVE_EFFECT_UNUSED_163                              163
#define MOVE_EFFECT_WEATHER_HAIL                            164
#define MOVE_EFFECT_TORMENT                                 165
#define MOVE_EFFECT_SP_ATK_UP_CAUSE_CONFUSION               166
#define MOVE_EFFECT_STATUS_BURN                             167
#define MOVE_EFFECT_FAINT_AND_ATK_SP_ATK_DOWN_2             168
#define MOVE_EFFECT_DOUBLE_POWER_WHEN_STATUSED              169
#define MOVE_EFFECT_HIT_LAST_WHIFF_IF_HIT                   170
#define MOVE_EFFECT_DOUBLE_POWER_AND_CURE_PARALYSIS         171
#define MOVE_EFFECT_MAKE_GLOBAL_TARGET                      172
#define MOVE_EFFECT_NATURE_POWER                            173
#define MOVE_EFFECT_SP_DEF_UP_DOUBLE_ELECTRIC_POWER         174
#define MOVE_EFFECT_TAUNT                                   175
#define MOVE_EFFECT_BOOST_ALLY_POWER_BY_50_PERCENT          176
#define MOVE_EFFECT_SWITCH_HELD_ITEMS                       177
#define MOVE_EFFECT_COPY_ABILITY                            178
#define MOVE_EFFECT_HEAL_IN_3_TURNS                         179
#define MOVE_EFFECT_USE_RANDOM_ALLY_MOVE                    180
#define MOVE_EFFECT_GROUND_TRAP_USER_CONTINUOUS_HEAL        181
#define MOVE_EFFECT_ATK_DEF_DOWN_HIT                        182
#define MOVE_EFFECT_MAGIC_COAT                              183
#define MOVE_EFFECT_RECYCLE                                 184
#define MOVE_EFFECT_DOUBLE_DAMAGE_IF_HIT                    185
#define MOVE_EFFECT_REMOVE_SCREENS                          186
#define MOVE_EFFECT_STATUS_SLEEP_NEXT_TURN                  187
#define MOVE_EFFECT_REMOVE_HELD_ITEM                        188
#define MOVE_EFFECT_SET_HP_EQUAL_TO_USER                    189
#define MOVE_EFFECT_DECREASE_POWER_WITH_LESS_USER_HP        190
#define MOVE_EFFECT_SWITCH_ABILITIES                        191
#define MOVE_EFFECT_MAKE_SHARED_MOVES_UNUSEABLE             192
#define MOVE_EFFECT_HEAL_STATUS                             193
#define MOVE_EFFECT_REMOVE_ALL_PP_ON_DEFEAT                 194
#define MOVE_EFFECT_STEAL_STATUS_MOVE                       195
#define MOVE_EFFECT_INCREASE_POWER_WITH_WEIGHT              196
#define MOVE_EFFECT_SECRET_POWER                            197
#define MOVE_EFFECT_RECOIL_THIRD                            198
#define MOVE_EFFECT_CONFUSE_ALL_ADJACENT                    199
#define MOVE_EFFECT_HIGH_CRITICAL_BURN_HIT                  200
#define MOVE_EFFECT_HALVE_ELECTRIC_DAMAGE                   201
#define MOVE_EFFECT_BADLY_POISON_HIT                        202
#define MOVE_EFFECT_CHANGE_TYPE_WITH_WEATHER                203
#define MOVE_EFFECT_USER_SP_ATK_DOWN_2                      204
#define MOVE_EFFECT_ATK_DEF_DOWN                            205
#define MOVE_EFFECT_DEF_SP_DEF_UP                           206
#define MOVE_EFFECT_HIT_FLY                                 207
#define MOVE_EFFECT_ATK_DEF_UP                              208
#define MOVE_EFFECT_HIGH_CRITICAL_POISON_HIT                209
#define MOVE_EFFECT_HALVE_FIRE_DAMAGE                       210
#define MOVE_EFFECT_SP_ATK_SP_DEF_UP                        211
#define MOVE_EFFECT_ATK_SPEED_UP                            212
#define MOVE_EFFECT_CAMOUFLAGE                              213
#define MOVE_EFFECT_HEAL_HALF_REMOVE_FLYING_TYPE            214
#define MOVE_EFFECT_GRAVITY                                 215
#define MOVE_EFFECT_IGNORE_EVATION_REMOVE_DARK_IMMUNE       216
#define MOVE_EFFECT_DOUBLE_POWER_HEAL_SLEEP                 217
#define MOVE_EFFECT_SPEED_DOWN_HIT                          218
#define MOVE_EFFECT_POWER_BASED_ON_LOW_SPEED                219
#define MOVE_EFFECT_FAINT_AND_FULL_HEAL_NEXT_MON            220
#define MOVE_EFFECT_DOUBLE_POWER_WHEN_BELOW_HALF            221
#define MOVE_EFFECT_NATURAL_GIFT                            222
#define MOVE_EFFECT_REMOVE_PROTECT                          223
#define MOVE_EFFECT_EAT_BERRY                               224
#define MOVE_EFFECT_DOUBLE_SPEED_3_TURNS                    225
#define MOVE_EFFECT_RANDOM_STAT_UP_2                        226
#define MOVE_EFFECT_METAL_BURST                             227
#define MOVE_EFFECT_SWITCH_HIT                              228
#define MOVE_EFFECT_DEF_SP_DEF_DOWN_HIT                     229
#define MOVE_EFFECT_DOUBLE_POWER_IF_HIT                     230
#define MOVE_EFFECT_DOUBLE_POWER_IF_TARGET_HIT              231
#define MOVE_EFFECT_PREVENT_ITEM_USE                        232
#define MOVE_EFFECT_FLING                                   233
#define MOVE_EFFECT_TRANSFER_STATUS                         234
#define MOVE_EFFECT_HIGHER_POWER_WHEN_LOW_PP                235
#define MOVE_EFFECT_PREVENT_HEALING                         236
#define MOVE_EFFECT_INCREASE_POWER_WITH_MORE_HP             237
#define MOVE_EFFECT_SWAP_ATK_DEF                            238
#define MOVE_EFFECT_SUPRESS_ABILITY                         239
#define MOVE_EFFECT_PREVENT_CRITS                           240
#define MOVE_EFFECT_USE_MOVE_FIRST                          241
#define MOVE_EFFECT_USE_LAST_USED_MOVE                      242
#define MOVE_EFFECT_SWAP_ATK_SP_ATK_STAT_CHANGES            243
#define MOVE_EFFECT_SWAP_DEF_SP_DEF_STAT_CHANGES            244
#define MOVE_EFFECT_INCREASE_POWER_WITH_MORE_STAT_UP        245
#define MOVE_EFFECT_FAIL_IF_NOT_USED_ALL_OTHER_MOVES        246
#define MOVE_EFFECT_SET_ABILITY_TO_INSOMNIA                 247
#define MOVE_EFFECT_HIT_FIRST_IF_TARGET_ATTACKING           248
#define MOVE_EFFECT_TOXIC_SPIKES                            249
#define MOVE_EFFECT_SWAP_STAT_CHANGES                       250
#define MOVE_EFFECT_RESTORE_HP_EVERY_TURN                   251
#define MOVE_EFFECT_GIVE_GROUND_IMMUNITY                    252
#define MOVE_EFFECT_RECOIL_BURN_HIT                         253
#define MOVE_EFFECT_STRUGGLE                                254
#define MOVE_EFFECT_DIVE                                    255
#define MOVE_EFFECT_DIG                                     256
#define MOVE_EFFECT_DOUBLE_DAMAGE_DIVE                      257
#define MOVE_EFFECT_REMOVE_HAZARDS_SCREENS_EVA_DOWN         258
#define MOVE_EFFECT_TRICK_ROOM                              259
#define MOVE_EFFECT_BLIZZARD                                260
#define MOVE_EFFECT_WHIRLPOOL                               261
#define MOVE_EFFECT_RECOIL_PARALYZE_HIT                     262
#define MOVE_EFFECT_BOUNCE                                  263
#define MOVE_EFFECT_UNUSED_264                              264
#define MOVE_EFFECT_SP_ATK_DOWN_2_OPPOSITE_GENDER           265
#define MOVE_EFFECT_STEALTH_ROCK                            266
#define MOVE_EFFECT_CHATTER                                 267
#define MOVE_EFFECT_JUDGMENT                                268
#define MOVE_EFFECT_RECOIL_HALF                             269
#define MOVE_EFFECT_FAINT_FULL_RESTORE_NEXT_MON             270
#define MOVE_EFFECT_LOWER_SP_DEF_2_HIT                      271
#define MOVE_EFFECT_SHADOW_FORCE                            272
#define MOVE_EFFECT_FLINCH_BURN_HIT                         273
#define MOVE_EFFECT_FLINCH_FREEZE_HIT                       274
#define MOVE_EFFECT_FLINCH_PARALYZE_HIT                     275
#define MOVE_EFFECT_RAISE_SP_ATK_HIT                        276

// new move effects:
#define MOVE_EFFECT_ATK_ACC_UP                              277
#define MOVE_EFFECT_GUARD_SPLIT                             278
#define MOVE_EFFECT_POWER_SPLIT                             279
#define MOVE_EFFECT_DOUBLE_POISONED_HIT                     280
#define MOVE_EFFECT_AUTOTOMIZE                              281
#define MOVE_EFFECT_ALWAYS_CRITICAL                         282
#define MOVE_EFFECT_SP_ATK_SP_DEF_SPEED_UP                  283
#define MOVE_EFFECT_CHANGE_TO_WATER_TYPE                    284
#define MOVE_EFFECT_RAISE_SPEED_HIT                         285
#define MOVE_EFFECT_ATK_DEF_ACC_UP                          286
#define MOVE_EFFECT_DOUBLE_DAMAGE_ON_STATUS                 287
#define MOVE_EFFECT_ATK_UP_SPEED_UP_2                       288
#define MOVE_EFFECT_DOUBLE_DAMAGE_WITHOUT_ITEM              289
#define MOVE_EFFECT_DEF_SP_DEF_DOWN_ATK_SP_ATK_SPEED_UP_2   290
#define MOVE_EFFECT_DEF_SP_DEF_SPEED_DOWN_HIT               291
#define MOVE_EFFECT_HEAVY_SLAM                              292
#define MOVE_EFFECT_CONFUSE_AND_CRASH_IF_MISS               293
#define MOVE_EFFECT_APPLY_TERRAINS                          294
#define MOVE_EFFECT_ATK_SP_ATK_UP                           295
#define MOVE_EFFECT_HIT_TWICE_AND_FLINCH                    296
#define MOVE_EFFECT_UP_TO_10_HITS                           297
#define MOVE_EFFECT_HIT_THREE_TIMES_INCREMENT_BASE_POWER_20 298
#define MOVE_EFFECT_HIT_THREE_TIMES                         299
#define MOVE_EFFECT_PSYBLADE                                300
#define MOVE_EFFECT_SLEEP_HIT                               301
#define MOVE_EFFECT_SPICY_EXTRACT                           302
#define MOVE_EFFECT_ATK_SP_ATK_SPEED_UP_2                   303
#define MOVE_EFFECT_SHED_TAIL                               304
#define MOVE_EFFECT_AFTER_YOU                               305
#define MOVE_EFFECT_QUASH                                   306
#define MOVE_EFFECT_TECHNO_BLAST                            307
#define MOVE_EFFECT_MULTI_ATTACK                            308
#define MOVE_EFFECT_IVY_CUDGEL                              309
#define MOVE_EFFECT_LEECH_SEED_HIT                          310
#define MOVE_EFFECT_SET_LIGHT_SCREEN_HIT                    311
#define MOVE_EFFECT_SET_REFLECT_HIT                         312
#define MOVE_EFFECT_RESET_STAT_CHANGES_HIT                  313
#define MOVE_EFFECT_CURE_PARTY_STATUS_HIT                   314
#define MOVE_EFFECT_RECOVER_FULL_DAMAGE_DEALT               315
#define MOVE_EFFECT_RAISE_EVA_HIT                           316
#define MOVE_EFFECT_RAISE_DEF_2_HIT                         317
#define MOVE_EFFECT_CHARGE_TURN_ATK_SP_ATK_SPEED_UP_2       318
#define MOVE_EFFECT_WEATHER_SNOW                            319
#define MOVE_EFFECT_HIT_AND_PREVENT_HEALING                 320
#define MOVE_EFFECT_INFERNAL_PARADE                         321
#define MOVE_EFFECT_BARB_BARRAGE                            322

//unused move effects
#define MOVE_EFFECT_UNUSED_323                              323
#define MOVE_EFFECT_UNUSED_324                              324
#define MOVE_EFFECT_UNUSED_325                              325
#define MOVE_EFFECT_UNUSED_326                              326
#define MOVE_EFFECT_UNUSED_327                              327
#define MOVE_EFFECT_UNUSED_328                              328
#define MOVE_EFFECT_UNUSED_329                              329
#define MOVE_EFFECT_UNUSED_330                              330
#define MOVE_EFFECT_UNUSED_331                              331
#define MOVE_EFFECT_UNUSED_332                              332
#define MOVE_EFFECT_UNUSED_333                              333
#define MOVE_EFFECT_UNUSED_334                              334
#define MOVE_EFFECT_UNUSED_335                              335
#define MOVE_EFFECT_UNUSED_336                              336
#define MOVE_EFFECT_UNUSED_337                              337
#define MOVE_EFFECT_UNUSED_338                              338
#define MOVE_EFFECT_UNUSED_339                              339
#define MOVE_EFFECT_UNUSED_340                              340
#define MOVE_EFFECT_UNUSED_341                              341
#define MOVE_EFFECT_UNUSED_342                              342
#define MOVE_EFFECT_UNUSED_343                              343
#define MOVE_EFFECT_UNUSED_344                              344
#define MOVE_EFFECT_UNUSED_345                              345
#define MOVE_EFFECT_UNUSED_346                              346
#define MOVE_EFFECT_UNUSED_347                              347
#define MOVE_EFFECT_UNUSED_348                              348
#define MOVE_EFFECT_UNUSED_349                              349
#define MOVE_EFFECT_UNUSED_350                              350
#define MOVE_EFFECT_UNUSED_351                              351
#define MOVE_EFFECT_UNUSED_352                              352
#define MOVE_EFFECT_UNUSED_353                              353
#define MOVE_EFFECT_UNUSED_354                              354
#define MOVE_EFFECT_UNUSED_355                              355
#define MOVE_EFFECT_UNUSED_356                              356
#define MOVE_EFFECT_UNUSED_357                              357
#define MOVE_EFFECT_UNUSED_358                              358
#define MOVE_EFFECT_UNUSED_359                              359
#define MOVE_EFFECT_UNUSED_360                              360
#define MOVE_EFFECT_UNUSED_361                              361
#define MOVE_EFFECT_UNUSED_362                              362
#define MOVE_EFFECT_UNUSED_363                              363
#define MOVE_EFFECT_UNUSED_364                              364
#define MOVE_EFFECT_UNUSED_365                              365
#define MOVE_EFFECT_UNUSED_366                              366
#define MOVE_EFFECT_UNUSED_367                              367
#define MOVE_EFFECT_UNUSED_368                              368
#define MOVE_EFFECT_UNUSED_369                              369
#define MOVE_EFFECT_UNUSED_370                              370
#define MOVE_EFFECT_UNUSED_371                              371
#define MOVE_EFFECT_UNUSED_372                              372
#define MOVE_EFFECT_UNUSED_373                              373
#define MOVE_EFFECT_UNUSED_374                              374
#define MOVE_EFFECT_UNUSED_375                              375
#define MOVE_EFFECT_UNUSED_376                              376
#define MOVE_EFFECT_UNUSED_377                              377
#define MOVE_EFFECT_UNUSED_378                              378
#define MOVE_EFFECT_UNUSED_379                              379
#define MOVE_EFFECT_UNUSED_380                              380
#define MOVE_EFFECT_UNUSED_381                              381
#define MOVE_EFFECT_UNUSED_382                              382
#define MOVE_EFFECT_UNUSED_383                              383
#define MOVE_EFFECT_UNUSED_384                              384
#define MOVE_EFFECT_UNUSED_385                              385
#define MOVE_EFFECT_UNUSED_386                              386
#define MOVE_EFFECT_UNUSED_387                              387
#define MOVE_EFFECT_UNUSED_388                              388
#define MOVE_EFFECT_UNUSED_389                              389
#define MOVE_EFFECT_UNUSED_390                              390
#define MOVE_EFFECT_UNUSED_391                              391
#define MOVE_EFFECT_UNUSED_392                              392
#define MOVE_EFFECT_UNUSED_393                              393
#define MOVE_EFFECT_UNUSED_394                              394
#define MOVE_EFFECT_UNUSED_395                              395
#define MOVE_EFFECT_UNUSED_396                              396
#define MOVE_EFFECT_UNUSED_397                              397
#define MOVE_EFFECT_UNUSED_398                              398
#define MOVE_EFFECT_UNUSED_399                              399
#define MOVE_EFFECT_UNUSED_400                              400
#define MOVE_EFFECT_UNUSED_401                              401
#define MOVE_EFFECT_UNUSED_402                              402
#define MOVE_EFFECT_UNUSED_403                              403
#define MOVE_EFFECT_UNUSED_404                              404
#define MOVE_EFFECT_UNUSED_405                              405
#define MOVE_EFFECT_UNUSED_406                              406
#define MOVE_EFFECT_UNUSED_407                              407
#define MOVE_EFFECT_UNUSED_408                              408
#define MOVE_EFFECT_UNUSED_409                              409
#define MOVE_EFFECT_UNUSED_410                              410
#define MOVE_EFFECT_UNUSED_411                              411
#define MOVE_EFFECT_UNUSED_412                              412
#define MOVE_EFFECT_UNUSED_413                              413
#define MOVE_EFFECT_UNUSED_414                              414
#define MOVE_EFFECT_UNUSED_415                              415
#define MOVE_EFFECT_UNUSED_416                              416
#define MOVE_EFFECT_UNUSED_417                              417
#define MOVE_EFFECT_UNUSED_418                              418
#define MOVE_EFFECT_UNUSED_419                              419
#define MOVE_EFFECT_UNUSED_420                              420
#define MOVE_EFFECT_UNUSED_421                              421
#define MOVE_EFFECT_UNUSED_422                              422
#define MOVE_EFFECT_UNUSED_423                              423
#define MOVE_EFFECT_UNUSED_424                              424
#define MOVE_EFFECT_UNUSED_425                              425
#define MOVE_EFFECT_UNUSED_426                              426
#define MOVE_EFFECT_UNUSED_427                              427
#define MOVE_EFFECT_UNUSED_428                              428
#define MOVE_EFFECT_UNUSED_429                              429
#define MOVE_EFFECT_UNUSED_430                              430
#define MOVE_EFFECT_UNUSED_431                              431
#define MOVE_EFFECT_UNUSED_432                              432
#define MOVE_EFFECT_UNUSED_433                              433
#define MOVE_EFFECT_UNUSED_434                              434
#define MOVE_EFFECT_UNUSED_435                              435
#define MOVE_EFFECT_UNUSED_436                              436
#define MOVE_EFFECT_UNUSED_437                              437
#define MOVE_EFFECT_UNUSED_438                              438
#define MOVE_EFFECT_UNUSED_439                              439
#define MOVE_EFFECT_UNUSED_440                              440
#define MOVE_EFFECT_UNUSED_441                              441
#define MOVE_EFFECT_UNUSED_442                              442
#define MOVE_EFFECT_UNUSED_443                              443
#define MOVE_EFFECT_UNUSED_444                              444
#define MOVE_EFFECT_UNUSED_445                              445
#define MOVE_EFFECT_UNUSED_446                              446
#define MOVE_EFFECT_UNUSED_447                              447
#define MOVE_EFFECT_UNUSED_448                              448
#define MOVE_EFFECT_UNUSED_449                              449
#define MOVE_EFFECT_UNUSED_450                              450
#define MOVE_EFFECT_UNUSED_451                              451
#define MOVE_EFFECT_UNUSED_452                              452
#define MOVE_EFFECT_UNUSED_453                              453
#define MOVE_EFFECT_UNUSED_454                              454
#define MOVE_EFFECT_UNUSED_455                              455
#define MOVE_EFFECT_UNUSED_456                              456
#define MOVE_EFFECT_UNUSED_457                              457
#define MOVE_EFFECT_UNUSED_458                              458
#define MOVE_EFFECT_UNUSED_459                              459
#define MOVE_EFFECT_UNUSED_460                              460
#define MOVE_EFFECT_UNUSED_461                              461
#define MOVE_EFFECT_UNUSED_462                              462
#define MOVE_EFFECT_UNUSED_463                              463
#define MOVE_EFFECT_UNUSED_464                              464
#define MOVE_EFFECT_UNUSED_465                              465
#define MOVE_EFFECT_UNUSED_466                              466
#define MOVE_EFFECT_UNUSED_467                              467
#define MOVE_EFFECT_UNUSED_468                              468
#define MOVE_EFFECT_UNUSED_469                              469
#define MOVE_EFFECT_UNUSED_470                              470
#define MOVE_EFFECT_UNUSED_471                              471
#define MOVE_EFFECT_UNUSED_472                              472
#define MOVE_EFFECT_UNUSED_473                              473
#define MOVE_EFFECT_UNUSED_474                              474
#define MOVE_EFFECT_UNUSED_475                              475
#define MOVE_EFFECT_UNUSED_476                              476
#define MOVE_EFFECT_UNUSED_477                              477
#define MOVE_EFFECT_UNUSED_478                              478
#define MOVE_EFFECT_UNUSED_479                              479
#define MOVE_EFFECT_UNUSED_480                              480
#define MOVE_EFFECT_UNUSED_481                              481
#define MOVE_EFFECT_UNUSED_482                              482
#define MOVE_EFFECT_UNUSED_483                              483
#define MOVE_EFFECT_UNUSED_484                              484
#define MOVE_EFFECT_UNUSED_485                              485
#define MOVE_EFFECT_UNUSED_486                              486
#define MOVE_EFFECT_UNUSED_487                              487
#define MOVE_EFFECT_UNUSED_488                              488
#define MOVE_EFFECT_UNUSED_489                              489
#define MOVE_EFFECT_UNUSED_490                              490
#define MOVE_EFFECT_UNUSED_491                              491
#define MOVE_EFFECT_UNUSED_492                              492
#define MOVE_EFFECT_UNUSED_493                              493
#define MOVE_EFFECT_UNUSED_494                              494
#define MOVE_EFFECT_UNUSED_495                              495
#define MOVE_EFFECT_UNUSED_496                              496
#define MOVE_EFFECT_UNUSED_497                              497
#define MOVE_EFFECT_UNUSED_498                              498
#define MOVE_EFFECT_UNUSED_499                              499
#define MOVE_EFFECT_UNUSED_500                              500
#define MOVE_EFFECT_UNUSED_501                              501
#define MOVE_EFFECT_UNUSED_502                              502
#define MOVE_EFFECT_UNUSED_503                              503
#define MOVE_EFFECT_UNUSED_504                              504
#define MOVE_EFFECT_UNUSED_505                              505
#define MOVE_EFFECT_UNUSED_506                              506
#define MOVE_EFFECT_UNUSED_507                              507
#define MOVE_EFFECT_UNUSED_508                              508
#define MOVE_EFFECT_UNUSED_509                              509
#define MOVE_EFFECT_UNUSED_510                              510
#define MOVE_EFFECT_UNUSED_511                              511
#define MOVE_EFFECT_UNUSED_512                              512
#define MOVE_EFFECT_UNUSED_513                              513
#define MOVE_EFFECT_UNUSED_514                              514
#define MOVE_EFFECT_UNUSED_515                              515
#define MOVE_EFFECT_UNUSED_516                              516
#define MOVE_EFFECT_UNUSED_517                              517
#define MOVE_EFFECT_UNUSED_518                              518
#define MOVE_EFFECT_UNUSED_519                              519
#define MOVE_EFFECT_UNUSED_520                              520
#define MOVE_EFFECT_UNUSED_521                              521
#define MOVE_EFFECT_UNUSED_522                              522
#define MOVE_EFFECT_UNUSED_523                              523
#define MOVE_EFFECT_UNUSED_524                              524
#define MOVE_EFFECT_UNUSED_525                              525
#define MOVE_EFFECT_UNUSED_526                              526
#define MOVE_EFFECT_UNUSED_527                              527
#define MOVE_EFFECT_UNUSED_528                              528
#define MOVE_EFFECT_UNUSED_529                              529
#define MOVE_EFFECT_UNUSED_530                              530
#define MOVE_EFFECT_UNUSED_531                              531
#define MOVE_EFFECT_UNUSED_532                              532
#define MOVE_EFFECT_UNUSED_533                              533
#define MOVE_EFFECT_UNUSED_534                              534
#define MOVE_EFFECT_UNUSED_535                              535
#define MOVE_EFFECT_UNUSED_536                              536
#define MOVE_EFFECT_UNUSED_537                              537
#define MOVE_EFFECT_UNUSED_538                              538
#define MOVE_EFFECT_UNUSED_539                              539
#define MOVE_EFFECT_UNUSED_540                              540
#define MOVE_EFFECT_UNUSED_541                              541
#define MOVE_EFFECT_UNUSED_542                              542
#define MOVE_EFFECT_UNUSED_543                              543
#define MOVE_EFFECT_UNUSED_544                              544
#define MOVE_EFFECT_UNUSED_545                              545
#define MOVE_EFFECT_UNUSED_546                              546
#define MOVE_EFFECT_UNUSED_547                              547
#define MOVE_EFFECT_UNUSED_548                              548
#define MOVE_EFFECT_UNUSED_549                              549
#define MOVE_EFFECT_UNUSED_550                              550
#define MOVE_EFFECT_UNUSED_551                              551
#define MOVE_EFFECT_UNUSED_552                              552
#define MOVE_EFFECT_UNUSED_553                              553
#define MOVE_EFFECT_UNUSED_554                              554
#define MOVE_EFFECT_UNUSED_555                              555
#define MOVE_EFFECT_UNUSED_556                              556
#define MOVE_EFFECT_UNUSED_557                              557
#define MOVE_EFFECT_UNUSED_558                              558
#define MOVE_EFFECT_UNUSED_559                              559
#define MOVE_EFFECT_UNUSED_560                              560
#define MOVE_EFFECT_UNUSED_561                              561
#define MOVE_EFFECT_UNUSED_562                              562
#define MOVE_EFFECT_UNUSED_563                              563
#define MOVE_EFFECT_UNUSED_564                              564
#define MOVE_EFFECT_UNUSED_565                              565
#define MOVE_EFFECT_UNUSED_566                              566
#define MOVE_EFFECT_UNUSED_567                              567
#define MOVE_EFFECT_UNUSED_568                              568
#define MOVE_EFFECT_UNUSED_569                              569
#define MOVE_EFFECT_UNUSED_570                              570
#define MOVE_EFFECT_UNUSED_571                              571
#define MOVE_EFFECT_UNUSED_572                              572
#define MOVE_EFFECT_UNUSED_573                              573
#define MOVE_EFFECT_UNUSED_574                              574
#define MOVE_EFFECT_UNUSED_575                              575
#define MOVE_EFFECT_UNUSED_576                              576
#define MOVE_EFFECT_UNUSED_577                              577
#define MOVE_EFFECT_UNUSED_578                              578
#define MOVE_EFFECT_UNUSED_579                              579
#define MOVE_EFFECT_UNUSED_580                              580
#define MOVE_EFFECT_UNUSED_581                              581
#define MOVE_EFFECT_UNUSED_582                              582
#define MOVE_EFFECT_UNUSED_583                              583
#define MOVE_EFFECT_UNUSED_584                              584
#define MOVE_EFFECT_UNUSED_585                              585
#define MOVE_EFFECT_UNUSED_586                              586
#define MOVE_EFFECT_UNUSED_587                              587
#define MOVE_EFFECT_UNUSED_588                              588
#define MOVE_EFFECT_UNUSED_589                              589
#define MOVE_EFFECT_UNUSED_590                              590
#define MOVE_EFFECT_UNUSED_591                              591
#define MOVE_EFFECT_UNUSED_592                              592
#define MOVE_EFFECT_UNUSED_593                              593
#define MOVE_EFFECT_UNUSED_594                              594
#define MOVE_EFFECT_UNUSED_595                              595
#define MOVE_EFFECT_UNUSED_596                              596
#define MOVE_EFFECT_UNUSED_597                              597
#define MOVE_EFFECT_UNUSED_598                              598
#define MOVE_EFFECT_UNUSED_599                              599
#define MOVE_EFFECT_UNUSED_600                              600
#define MOVE_EFFECT_UNUSED_601                              601
#define MOVE_EFFECT_UNUSED_602                              602
#define MOVE_EFFECT_UNUSED_603                              603
#define MOVE_EFFECT_UNUSED_604                              604
#define MOVE_EFFECT_UNUSED_605                              605
#define MOVE_EFFECT_UNUSED_606                              606
#define MOVE_EFFECT_UNUSED_607                              607
#define MOVE_EFFECT_UNUSED_608                              608
#define MOVE_EFFECT_UNUSED_609                              609
#define MOVE_EFFECT_UNUSED_610                              610
#define MOVE_EFFECT_UNUSED_611                              611
#define MOVE_EFFECT_UNUSED_612                              612
#define MOVE_EFFECT_UNUSED_613                              613
#define MOVE_EFFECT_UNUSED_614                              614
#define MOVE_EFFECT_UNUSED_615                              615
#define MOVE_EFFECT_UNUSED_616                              616
#define MOVE_EFFECT_UNUSED_617                              617
#define MOVE_EFFECT_UNUSED_618                              618
#define MOVE_EFFECT_UNUSED_619                              619
#define MOVE_EFFECT_UNUSED_620                              620
#define MOVE_EFFECT_UNUSED_621                              621
#define MOVE_EFFECT_UNUSED_622                              622
#define MOVE_EFFECT_UNUSED_623                              623
#define MOVE_EFFECT_UNUSED_624                              624
#define MOVE_EFFECT_UNUSED_625                              625
#define MOVE_EFFECT_UNUSED_626                              626
#define MOVE_EFFECT_UNUSED_627                              627
#define MOVE_EFFECT_UNUSED_628                              628
#define MOVE_EFFECT_UNUSED_629                              629
#define MOVE_EFFECT_UNUSED_630                              630
#define MOVE_EFFECT_UNUSED_631                              631
#define MOVE_EFFECT_UNUSED_632                              632
#define MOVE_EFFECT_UNUSED_633                              633
#define MOVE_EFFECT_UNUSED_634                              634
#define MOVE_EFFECT_UNUSED_635                              635
#define MOVE_EFFECT_UNUSED_636                              636
#define MOVE_EFFECT_UNUSED_637                              637
#define MOVE_EFFECT_UNUSED_638                              638
#define MOVE_EFFECT_UNUSED_639                              639
#define MOVE_EFFECT_UNUSED_640                              640
#define MOVE_EFFECT_UNUSED_641                              641
#define MOVE_EFFECT_UNUSED_642                              642
#define MOVE_EFFECT_UNUSED_643                              643
#define MOVE_EFFECT_UNUSED_644                              644
#define MOVE_EFFECT_UNUSED_645                              645
#define MOVE_EFFECT_UNUSED_646                              646
#define MOVE_EFFECT_UNUSED_647                              647
#define MOVE_EFFECT_UNUSED_648                              648
#define MOVE_EFFECT_UNUSED_649                              649
#define MOVE_EFFECT_UNUSED_650                              650
#define MOVE_EFFECT_UNUSED_651                              651
#define MOVE_EFFECT_UNUSED_652                              652
#define MOVE_EFFECT_UNUSED_653                              653
#define MOVE_EFFECT_UNUSED_654                              654
#define MOVE_EFFECT_UNUSED_655                              655
#define MOVE_EFFECT_UNUSED_656                              656
#define MOVE_EFFECT_UNUSED_657                              657
#define MOVE_EFFECT_UNUSED_658                              658
#define MOVE_EFFECT_UNUSED_659                              659
#define MOVE_EFFECT_UNUSED_660                              660
#define MOVE_EFFECT_UNUSED_661                              661
#define MOVE_EFFECT_UNUSED_662                              662
#define MOVE_EFFECT_UNUSED_663                              663
#define MOVE_EFFECT_UNUSED_664                              664
#define MOVE_EFFECT_UNUSED_665                              665
#define MOVE_EFFECT_UNUSED_666                              666
#define MOVE_EFFECT_UNUSED_667                              667
#define MOVE_EFFECT_UNUSED_668                              668
#define MOVE_EFFECT_UNUSED_669                              669
#define MOVE_EFFECT_UNUSED_670                              670
#define MOVE_EFFECT_UNUSED_671                              671
#define MOVE_EFFECT_UNUSED_672                              672
#define MOVE_EFFECT_UNUSED_673                              673
#define MOVE_EFFECT_UNUSED_674                              674
#define MOVE_EFFECT_UNUSED_675                              675
#define MOVE_EFFECT_UNUSED_676                              676
#define MOVE_EFFECT_UNUSED_677                              677
#define MOVE_EFFECT_UNUSED_678                              678
#define MOVE_EFFECT_UNUSED_679                              679
#define MOVE_EFFECT_UNUSED_680                              680
#define MOVE_EFFECT_UNUSED_681                              681
#define MOVE_EFFECT_UNUSED_682                              682
#define MOVE_EFFECT_UNUSED_683                              683
#define MOVE_EFFECT_UNUSED_684                              684
#define MOVE_EFFECT_UNUSED_685                              685
#define MOVE_EFFECT_UNUSED_686                              686
#define MOVE_EFFECT_UNUSED_687                              687
#define MOVE_EFFECT_UNUSED_688                              688
#define MOVE_EFFECT_UNUSED_689                              689
#define MOVE_EFFECT_UNUSED_690                              690
#define MOVE_EFFECT_UNUSED_691                              691
#define MOVE_EFFECT_UNUSED_692                              692
#define MOVE_EFFECT_UNUSED_693                              693
#define MOVE_EFFECT_UNUSED_694                              694
#define MOVE_EFFECT_UNUSED_695                              695
#define MOVE_EFFECT_UNUSED_696                              696
#define MOVE_EFFECT_UNUSED_697                              697
#define MOVE_EFFECT_UNUSED_698                              698
#define MOVE_EFFECT_UNUSED_699                              699
#define MOVE_EFFECT_UNUSED_700                              700
#define MOVE_EFFECT_UNUSED_701                              701
#define MOVE_EFFECT_UNUSED_702                              702
#define MOVE_EFFECT_UNUSED_703                              703
#define MOVE_EFFECT_UNUSED_704                              704
#define MOVE_EFFECT_UNUSED_705                              705
#define MOVE_EFFECT_UNUSED_706                              706
#define MOVE_EFFECT_UNUSED_707                              707
#define MOVE_EFFECT_UNUSED_708                              708
#define MOVE_EFFECT_UNUSED_709                              709
#define MOVE_EFFECT_UNUSED_710                              710
#define MOVE_EFFECT_UNUSED_711                              711
#define MOVE_EFFECT_UNUSED_712                              712
#define MOVE_EFFECT_UNUSED_713                              713
#define MOVE_EFFECT_UNUSED_714                              714
#define MOVE_EFFECT_UNUSED_715                              715
#define MOVE_EFFECT_UNUSED_716                              716
#define MOVE_EFFECT_UNUSED_717                              717
#define MOVE_EFFECT_UNUSED_718                              718
#define MOVE_EFFECT_UNUSED_719                              719
#define MOVE_EFFECT_UNUSED_720                              720
#define MOVE_EFFECT_UNUSED_721                              721
#define MOVE_EFFECT_UNUSED_722                              722
#define MOVE_EFFECT_UNUSED_723                              723
#define MOVE_EFFECT_UNUSED_724                              724
#define MOVE_EFFECT_UNUSED_725                              725
#define MOVE_EFFECT_UNUSED_726                              726
#define MOVE_EFFECT_UNUSED_727                              727
#define MOVE_EFFECT_UNUSED_728                              728
#define MOVE_EFFECT_UNUSED_729                              729
#define MOVE_EFFECT_UNUSED_730                              730
#define MOVE_EFFECT_UNUSED_731                              731
#define MOVE_EFFECT_UNUSED_732                              732
#define MOVE_EFFECT_UNUSED_733                              733
#define MOVE_EFFECT_UNUSED_734                              734
#define MOVE_EFFECT_UNUSED_735                              735
#define MOVE_EFFECT_UNUSED_736                              736
#define MOVE_EFFECT_UNUSED_737                              737
#define MOVE_EFFECT_UNUSED_738                              738
#define MOVE_EFFECT_UNUSED_739                              739
#define MOVE_EFFECT_UNUSED_740                              740
#define MOVE_EFFECT_UNUSED_741                              741
#define MOVE_EFFECT_UNUSED_742                              742
#define MOVE_EFFECT_UNUSED_743                              743
#define MOVE_EFFECT_UNUSED_744                              744
#define MOVE_EFFECT_UNUSED_745                              745
#define MOVE_EFFECT_UNUSED_746                              746
#define MOVE_EFFECT_UNUSED_747                              747
#define MOVE_EFFECT_UNUSED_748                              748
#define MOVE_EFFECT_UNUSED_749                              749
#define MOVE_EFFECT_UNUSED_750                              750
#define MOVE_EFFECT_UNUSED_751                              751
#define MOVE_EFFECT_UNUSED_752                              752
#define MOVE_EFFECT_UNUSED_753                              753
#define MOVE_EFFECT_UNUSED_754                              754
#define MOVE_EFFECT_UNUSED_755                              755
#define MOVE_EFFECT_UNUSED_756                              756
#define MOVE_EFFECT_UNUSED_757                              757
#define MOVE_EFFECT_UNUSED_758                              758
#define MOVE_EFFECT_UNUSED_759                              759
#define MOVE_EFFECT_UNUSED_760                              760
#define MOVE_EFFECT_UNUSED_761                              761
#define MOVE_EFFECT_UNUSED_762                              762
#define MOVE_EFFECT_UNUSED_763                              763
#define MOVE_EFFECT_UNUSED_764                              764
#define MOVE_EFFECT_UNUSED_765                              765
#define MOVE_EFFECT_UNUSED_766                              766
#define MOVE_EFFECT_UNUSED_767                              767
#define MOVE_EFFECT_UNUSED_768                              768
#define MOVE_EFFECT_UNUSED_769                              769
#define MOVE_EFFECT_UNUSED_770                              770
#define MOVE_EFFECT_UNUSED_771                              771
#define MOVE_EFFECT_UNUSED_772                              772
#define MOVE_EFFECT_UNUSED_773                              773
#define MOVE_EFFECT_UNUSED_774                              774
#define MOVE_EFFECT_UNUSED_775                              775
#define MOVE_EFFECT_UNUSED_776                              776
#define MOVE_EFFECT_UNUSED_777                              777
#define MOVE_EFFECT_UNUSED_778                              778
#define MOVE_EFFECT_UNUSED_779                              779
#define MOVE_EFFECT_UNUSED_780                              780
#define MOVE_EFFECT_UNUSED_781                              781
#define MOVE_EFFECT_UNUSED_782                              782
#define MOVE_EFFECT_UNUSED_783                              783
#define MOVE_EFFECT_UNUSED_784                              784
#define MOVE_EFFECT_UNUSED_785                              785
#define MOVE_EFFECT_UNUSED_786                              786
#define MOVE_EFFECT_UNUSED_787                              787
#define MOVE_EFFECT_UNUSED_788                              788
#define MOVE_EFFECT_UNUSED_789                              789
#define MOVE_EFFECT_UNUSED_790                              790
#define MOVE_EFFECT_UNUSED_791                              791
#define MOVE_EFFECT_UNUSED_792                              792
#define MOVE_EFFECT_UNUSED_793                              793
#define MOVE_EFFECT_UNUSED_794                              794
#define MOVE_EFFECT_UNUSED_795                              795
#define MOVE_EFFECT_UNUSED_796                              796
#define MOVE_EFFECT_UNUSED_797                              797
#define MOVE_EFFECT_UNUSED_798                              798
#define MOVE_EFFECT_UNUSED_799                              799
#define MOVE_EFFECT_UNUSED_800                              800
#define MOVE_EFFECT_UNUSED_801                              801
#define MOVE_EFFECT_UNUSED_802                              802
#define MOVE_EFFECT_UNUSED_803                              803
#define MOVE_EFFECT_UNUSED_804                              804
#define MOVE_EFFECT_UNUSED_805                              805
#define MOVE_EFFECT_UNUSED_806                              806
#define MOVE_EFFECT_UNUSED_807                              807
#define MOVE_EFFECT_UNUSED_808                              808
#define MOVE_EFFECT_UNUSED_809                              809
#define MOVE_EFFECT_UNUSED_810                              810
#define MOVE_EFFECT_UNUSED_811                              811
#define MOVE_EFFECT_UNUSED_812                              812
#define MOVE_EFFECT_UNUSED_813                              813
#define MOVE_EFFECT_UNUSED_814                              814
#define MOVE_EFFECT_UNUSED_815                              815
#define MOVE_EFFECT_UNUSED_816                              816
#define MOVE_EFFECT_UNUSED_817                              817
#define MOVE_EFFECT_UNUSED_818                              818
#define MOVE_EFFECT_UNUSED_819                              819
#define MOVE_EFFECT_UNUSED_820                              820
#define MOVE_EFFECT_UNUSED_821                              821
#define MOVE_EFFECT_UNUSED_822                              822
#define MOVE_EFFECT_UNUSED_823                              823
#define MOVE_EFFECT_UNUSED_824                              824
#define MOVE_EFFECT_UNUSED_825                              825
#define MOVE_EFFECT_UNUSED_826                              826
#define MOVE_EFFECT_UNUSED_827                              827
#define MOVE_EFFECT_UNUSED_828                              828
#define MOVE_EFFECT_UNUSED_829                              829
#define MOVE_EFFECT_UNUSED_830                              830
#define MOVE_EFFECT_UNUSED_831                              831
#define MOVE_EFFECT_UNUSED_832                              832
#define MOVE_EFFECT_UNUSED_833                              833
#define MOVE_EFFECT_UNUSED_834                              834
#define MOVE_EFFECT_UNUSED_835                              835
#define MOVE_EFFECT_UNUSED_836                              836
#define MOVE_EFFECT_UNUSED_837                              837
#define MOVE_EFFECT_UNUSED_838                              838
#define MOVE_EFFECT_UNUSED_839                              839
#define MOVE_EFFECT_UNUSED_840                              840
#define MOVE_EFFECT_UNUSED_841                              841
#define MOVE_EFFECT_UNUSED_842                              842
#define MOVE_EFFECT_UNUSED_843                              843
#define MOVE_EFFECT_UNUSED_844                              844
#define MOVE_EFFECT_UNUSED_845                              845
#define MOVE_EFFECT_UNUSED_846                              846
#define MOVE_EFFECT_UNUSED_847                              847
#define MOVE_EFFECT_UNUSED_848                              848
#define MOVE_EFFECT_UNUSED_849                              849
#define MOVE_EFFECT_UNUSED_850                              850
#define MOVE_EFFECT_UNUSED_851                              851
#define MOVE_EFFECT_UNUSED_852                              852
#define MOVE_EFFECT_UNUSED_853                              853
#define MOVE_EFFECT_UNUSED_854                              854
#define MOVE_EFFECT_UNUSED_855                              855
#define MOVE_EFFECT_UNUSED_856                              856
#define MOVE_EFFECT_UNUSED_857                              857
#define MOVE_EFFECT_UNUSED_858                              858
#define MOVE_EFFECT_UNUSED_859                              859
#define MOVE_EFFECT_UNUSED_860                              860
#define MOVE_EFFECT_UNUSED_861                              861
#define MOVE_EFFECT_UNUSED_862                              862
#define MOVE_EFFECT_UNUSED_863                              863
#define MOVE_EFFECT_UNUSED_864                              864
#define MOVE_EFFECT_UNUSED_865                              865
#define MOVE_EFFECT_UNUSED_866                              866
#define MOVE_EFFECT_UNUSED_867                              867
#define MOVE_EFFECT_UNUSED_868                              868
#define MOVE_EFFECT_UNUSED_869                              869
#define MOVE_EFFECT_UNUSED_870                              870
#define MOVE_EFFECT_UNUSED_871                              871
#define MOVE_EFFECT_UNUSED_872                              872
#define MOVE_EFFECT_UNUSED_873                              873
#define MOVE_EFFECT_UNUSED_874                              874
#define MOVE_EFFECT_UNUSED_875                              875
#define MOVE_EFFECT_UNUSED_876                              876
#define MOVE_EFFECT_UNUSED_877                              877
#define MOVE_EFFECT_UNUSED_878                              878
#define MOVE_EFFECT_UNUSED_879                              879
#define MOVE_EFFECT_UNUSED_880                              880
#define MOVE_EFFECT_UNUSED_881                              881
#define MOVE_EFFECT_UNUSED_882                              882
#define MOVE_EFFECT_UNUSED_883                              883
#define MOVE_EFFECT_UNUSED_884                              884
#define MOVE_EFFECT_UNUSED_885                              885
#define MOVE_EFFECT_UNUSED_886                              886
#define MOVE_EFFECT_UNUSED_887                              887
#define MOVE_EFFECT_UNUSED_888                              888
#define MOVE_EFFECT_UNUSED_889                              889
#define MOVE_EFFECT_UNUSED_890                              890
#define MOVE_EFFECT_UNUSED_891                              891
#define MOVE_EFFECT_UNUSED_892                              892
#define MOVE_EFFECT_UNUSED_893                              893
#define MOVE_EFFECT_UNUSED_894                              894
#define MOVE_EFFECT_UNUSED_895                              895
#define MOVE_EFFECT_UNUSED_896                              896
#define MOVE_EFFECT_UNUSED_897                              897
#define MOVE_EFFECT_UNUSED_898                              898
#define MOVE_EFFECT_UNUSED_899                              899

// null move effects
#define MOVE_EFFECT_ELECTRO_BALL                            900
#define MOVE_EFFECT_SKULK_OUT                               901
#define MOVE_EFFECT_CACKLE                                  902
#define MOVE_EFFECT_VENOM_DRENCH                            903


#define MOVE_TARGET_SELECTED             0x0000
#define MOVE_TARGET_DEPENDS              0x0001
#define MOVE_TARGET_RANDOM               0x0002
#define MOVE_TARGET_BOTH                 0x0004
#define MOVE_TARGET_FOES_AND_ALLY        0x0008
#define MOVE_TARGET_USER                 0x0010
#define MOVE_TARGET_USER_SIDE            0x0020
#define MOVE_TARGET_ACTIVE_FIELD         0x0040
#define MOVE_TARGET_OPPONENTS_FIELD      0x0080
#define MOVE_TARGET_ALLY                 0x0100
#define MOVE_TARGET_ACUPRESSURE          0x0200
#define MOVE_TARGET_ME_FIRST             0x0400

#endif
