#ifndef CONSTANTS_SPECIES_H
#define CONSTANTS_SPECIES_H

#define SPECIES_NONE           0
#define SPECIES_BULBASAUR      1
#define SPECIES_IVYSAUR        2
#define SPECIES_VENUSAUR       3
#define SPECIES_CHARMANDER     4
#define SPECIES_CHARMELEON     5
#define SPECIES_CHARIZARD      6
#define SPECIES_SQUIRTLE       7
#define SPECIES_WARTORTLE      8
#define SPECIES_BLASTOISE      9
#define SPECIES_CATERPIE       10
#define SPECIES_METAPOD        11
#define SPECIES_BUTTERFREE     12
#define SPECIES_WEEDLE         13
#define SPECIES_KAKUNA         14
#define SPECIES_BEEDRILL       15
#define SPECIES_PIDGEY         16
#define SPECIES_PIDGEOTTO      17
#define SPECIES_PIDGEOT        18
#define SPECIES_RATTATA        19
#define SPECIES_RATICATE       20
#define SPECIES_SPEAROW        21
#define SPECIES_FEAROW         22
#define SPECIES_EKANS          23
#define SPECIES_ARBOK          24
#define SPECIES_PIKACHU        25
#define SPECIES_RAICHU         26
#define SPECIES_SANDSHREW      27
#define SPECIES_SANDSLASH      28
#define SPECIES_NIDORAN_F      29
#define SPECIES_NIDORINA       30
#define SPECIES_NIDOQUEEN      31
#define SPECIES_NIDORAN_M      32
#define SPECIES_NIDORINO       33
#define SPECIES_NIDOKING       34
#define SPECIES_CLEFAIRY       35
#define SPECIES_CLEFABLE       36
#define SPECIES_VULPIX         37
#define SPECIES_NINETALES      38
#define SPECIES_JIGGLYPUFF     39
#define SPECIES_WIGGLYTUFF     40
#define SPECIES_ZUBAT          41
#define SPECIES_GOLBAT         42
#define SPECIES_ODDISH         43
#define SPECIES_GLOOM          44
#define SPECIES_VILEPLUME      45
#define SPECIES_PARAS          46
#define SPECIES_PARASECT       47
#define SPECIES_VENONAT        48
#define SPECIES_VENOMOTH       49
#define SPECIES_DIGLETT        50
#define SPECIES_DUGTRIO        51
#define SPECIES_MEOWTH         52
#define SPECIES_PERSIAN        53
#define SPECIES_PSYDUCK        54
#define SPECIES_GOLDUCK        55
#define SPECIES_MANKEY         56
#define SPECIES_PRIMEAPE       57
#define SPECIES_GROWLITHE      58
#define SPECIES_ARCANINE       59
#define SPECIES_POLIWAG        60
#define SPECIES_POLIWHIRL      61
#define SPECIES_POLIWRATH      62
#define SPECIES_ABRA           63
#define SPECIES_KADABRA        64
#define SPECIES_ALAKAZAM       65
#define SPECIES_MACHOP         66
#define SPECIES_MACHOKE        67
#define SPECIES_MACHAMP        68
#define SPECIES_BELLSPROUT     69
#define SPECIES_WEEPINBELL     70
#define SPECIES_VICTREEBEL     71
#define SPECIES_TENTACOOL      72
#define SPECIES_TENTACRUEL     73
#define SPECIES_GEODUDE        74
#define SPECIES_GRAVELER       75
#define SPECIES_GOLEM          76
#define SPECIES_PONYTA         77
#define SPECIES_RAPIDASH       78
#define SPECIES_SLOWPOKE       79
#define SPECIES_SLOWBRO        80
#define SPECIES_MAGNEMITE      81
#define SPECIES_MAGNETON       82
#define SPECIES_FARFETCHD      83
#define SPECIES_DODUO          84
#define SPECIES_DODRIO         85
#define SPECIES_SEEL           86
#define SPECIES_DEWGONG        87
#define SPECIES_GRIMER         88
#define SPECIES_MUK            89
#define SPECIES_SHELLDER       90
#define SPECIES_CLOYSTER       91
#define SPECIES_GASTLY         92
#define SPECIES_HAUNTER        93
#define SPECIES_GENGAR         94
#define SPECIES_ONIX           95
#define SPECIES_DROWZEE        96
#define SPECIES_HYPNO          97
#define SPECIES_KRABBY         98
#define SPECIES_KINGLER        99
#define SPECIES_VOLTORB        100
#define SPECIES_ELECTRODE      101
#define SPECIES_EXEGGCUTE      102
#define SPECIES_EXEGGUTOR      103
#define SPECIES_CUBONE         104
#define SPECIES_MAROWAK        105
#define SPECIES_HITMONLEE      106
#define SPECIES_HITMONCHAN     107
#define SPECIES_LICKITUNG      108
#define SPECIES_KOFFING        109
#define SPECIES_WEEZING        110
#define SPECIES_RHYHORN        111
#define SPECIES_RHYDON         112
#define SPECIES_CHANSEY        113
#define SPECIES_TANGELA        114
#define SPECIES_KANGASKHAN     115
#define SPECIES_HORSEA         116
#define SPECIES_SEADRA         117
#define SPECIES_GOLDEEN        118
#define SPECIES_SEAKING        119
#define SPECIES_STARYU         120
#define SPECIES_STARMIE        121
#define SPECIES_MR_MIME        122
#define SPECIES_SCYTHER        123
#define SPECIES_JYNX           124
#define SPECIES_ELECTABUZZ     125
#define SPECIES_MAGMAR         126
#define SPECIES_PINSIR         127
#define SPECIES_TAUROS         128
#define SPECIES_MAGIKARP       129
#define SPECIES_GYARADOS       130
#define SPECIES_LAPRAS         131
#define SPECIES_DITTO          132
#define SPECIES_EEVEE          133
#define SPECIES_VAPOREON       134
#define SPECIES_JOLTEON        135
#define SPECIES_FLAREON        136
#define SPECIES_PORYGON        137
#define SPECIES_OMANYTE        138
#define SPECIES_OMASTAR        139
#define SPECIES_KABUTO         140
#define SPECIES_KABUTOPS       141
#define SPECIES_AERODACTYL     142
#define SPECIES_SNORLAX        143
#define SPECIES_ARTICUNO       144
#define SPECIES_ZAPDOS         145
#define SPECIES_MOLTRES        146
#define SPECIES_DRATINI        147
#define SPECIES_DRAGONAIR      148
#define SPECIES_DRAGONITE      149
#define SPECIES_MEWTWO         150
#define SPECIES_MEW            151

#define SPECIES_CHIKORITA      152
#define SPECIES_BAYLEEF        153
#define SPECIES_MEGANIUM       154
#define SPECIES_CYNDAQUIL      155
#define SPECIES_QUILAVA        156
#define SPECIES_TYPHLOSION     157
#define SPECIES_TOTODILE       158
#define SPECIES_CROCONAW       159
#define SPECIES_FERALIGATR     160
#define SPECIES_SENTRET        161
#define SPECIES_FURRET         162
#define SPECIES_HOOTHOOT       163
#define SPECIES_NOCTOWL        164
#define SPECIES_LEDYBA         165
#define SPECIES_LEDIAN         166
#define SPECIES_SPINARAK       167
#define SPECIES_ARIADOS        168
#define SPECIES_CROBAT         169
#define SPECIES_CHINCHOU       170
#define SPECIES_LANTURN        171
#define SPECIES_PICHU          172
#define SPECIES_CLEFFA         173
#define SPECIES_IGGLYBUFF      174
#define SPECIES_TOGEPI         175
#define SPECIES_TOGETIC        176
#define SPECIES_NATU           177
#define SPECIES_XATU           178
#define SPECIES_MAREEP         179
#define SPECIES_FLAAFFY        180
#define SPECIES_AMPHAROS       181
#define SPECIES_BELLOSSOM      182
#define SPECIES_MARILL         183
#define SPECIES_AZUMARILL      184
#define SPECIES_SUDOWOODO      185
#define SPECIES_POLITOED       186
#define SPECIES_HOPPIP         187
#define SPECIES_SKIPLOOM       188
#define SPECIES_JUMPLUFF       189
#define SPECIES_AIPOM          190
#define SPECIES_SUNKERN        191
#define SPECIES_SUNFLORA       192
#define SPECIES_YANMA          193
#define SPECIES_WOOPER         194
#define SPECIES_QUAGSIRE       195
#define SPECIES_ESPEON         196
#define SPECIES_UMBREON        197
#define SPECIES_MURKROW        198
#define SPECIES_SLOWKING       199
#define SPECIES_MISDREAVUS     200
#define SPECIES_UNOWN          201
#define SPECIES_WOBBUFFET      202
#define SPECIES_GIRAFARIG      203
#define SPECIES_PINECO         204
#define SPECIES_FORRETRESS     205
#define SPECIES_DUNSPARCE      206
#define SPECIES_GLIGAR         207
#define SPECIES_STEELIX        208
#define SPECIES_SNUBBULL       209
#define SPECIES_GRANBULL       210
#define SPECIES_QWILFISH       211
#define SPECIES_SCIZOR         212
#define SPECIES_SHUCKLE        213
#define SPECIES_HERACROSS      214
#define SPECIES_SNEASEL        215
#define SPECIES_TEDDIURSA      216
#define SPECIES_URSARING       217
#define SPECIES_SLUGMA         218
#define SPECIES_MAGCARGO       219
#define SPECIES_SWINUB         220
#define SPECIES_PILOSWINE      221
#define SPECIES_CORSOLA        222
#define SPECIES_REMORAID       223
#define SPECIES_OCTILLERY      224
#define SPECIES_DELIBIRD       225
#define SPECIES_MANTINE        226
#define SPECIES_SKARMORY       227
#define SPECIES_HOUNDOUR       228
#define SPECIES_HOUNDOOM       229
#define SPECIES_KINGDRA        230
#define SPECIES_PHANPY         231
#define SPECIES_DONPHAN        232
#define SPECIES_PORYGON2       233
#define SPECIES_STANTLER       234
#define SPECIES_SMEARGLE       235
#define SPECIES_TYROGUE        236
#define SPECIES_HITMONTOP      237
#define SPECIES_SMOOCHUM       238
#define SPECIES_ELEKID         239
#define SPECIES_MAGBY          240
#define SPECIES_MILTANK        241
#define SPECIES_BLISSEY        242
#define SPECIES_RAIKOU         243
#define SPECIES_ENTEI          244
#define SPECIES_SUICUNE        245
#define SPECIES_LARVITAR       246
#define SPECIES_PUPITAR        247
#define SPECIES_TYRANITAR      248
#define SPECIES_LUGIA          249
#define SPECIES_HO_OH          250
#define SPECIES_CELEBI         251

#define SPECIES_TREECKO        252
#define SPECIES_GROVYLE        253
#define SPECIES_SCEPTILE       254
#define SPECIES_TORCHIC        255
#define SPECIES_COMBUSKEN      256
#define SPECIES_BLAZIKEN       257
#define SPECIES_MUDKIP         258
#define SPECIES_MARSHTOMP      259
#define SPECIES_SWAMPERT       260
#define SPECIES_POOCHYENA      261
#define SPECIES_MIGHTYENA      262
#define SPECIES_ZIGZAGOON      263
#define SPECIES_LINOONE        264
#define SPECIES_WURMPLE        265
#define SPECIES_SILCOON        266
#define SPECIES_BEAUTIFLY      267
#define SPECIES_CASCOON        268
#define SPECIES_DUSTOX         269
#define SPECIES_LOTAD          270
#define SPECIES_LOMBRE         271
#define SPECIES_LUDICOLO       272
#define SPECIES_SEEDOT         273
#define SPECIES_NUZLEAF        274
#define SPECIES_SHIFTRY        275
#define SPECIES_TAILLOW        276
#define SPECIES_SWELLOW        277
#define SPECIES_WINGULL        278
#define SPECIES_PELIPPER       279
#define SPECIES_RALTS          280
#define SPECIES_KIRLIA         281
#define SPECIES_GARDEVOIR      282
#define SPECIES_SURSKIT        283
#define SPECIES_MASQUERAIN     284
#define SPECIES_SHROOMISH      285
#define SPECIES_BRELOOM        286
#define SPECIES_SLAKOTH        287
#define SPECIES_VIGOROTH       288
#define SPECIES_SLAKING        289
#define SPECIES_NINCADA        290
#define SPECIES_NINJASK        291
#define SPECIES_SHEDINJA       292
#define SPECIES_WHISMUR        293
#define SPECIES_LOUDRED        294
#define SPECIES_EXPLOUD        295
#define SPECIES_MAKUHITA       296
#define SPECIES_HARIYAMA       297
#define SPECIES_AZURILL        298
#define SPECIES_NOSEPASS       299
#define SPECIES_SKITTY         300
#define SPECIES_DELCATTY       301
#define SPECIES_SABLEYE        302
#define SPECIES_MAWILE         303
#define SPECIES_ARON           304
#define SPECIES_LAIRON         305
#define SPECIES_AGGRON         306
#define SPECIES_MEDITITE       307
#define SPECIES_MEDICHAM       308
#define SPECIES_ELECTRIKE      309
#define SPECIES_MANECTRIC      310
#define SPECIES_PLUSLE         311
#define SPECIES_MINUN          312
#define SPECIES_VOLBEAT        313
#define SPECIES_ILLUMISE       314
#define SPECIES_ROSELIA        315
#define SPECIES_GULPIN         316
#define SPECIES_SWALOT         317
#define SPECIES_CARVANHA       318
#define SPECIES_SHARPEDO       319
#define SPECIES_WAILMER        320
#define SPECIES_WAILORD        321
#define SPECIES_NUMEL          322
#define SPECIES_CAMERUPT       323
#define SPECIES_TORKOAL        324
#define SPECIES_SPOINK         325
#define SPECIES_GRUMPIG        326
#define SPECIES_SPINDA         327
#define SPECIES_TRAPINCH       328
#define SPECIES_VIBRAVA        329
#define SPECIES_FLYGON         330
#define SPECIES_CACNEA         331
#define SPECIES_CACTURNE       332
#define SPECIES_SWABLU         333
#define SPECIES_ALTARIA        334
#define SPECIES_ZANGOOSE       335
#define SPECIES_SEVIPER        336
#define SPECIES_LUNATONE       337
#define SPECIES_SOLROCK        338
#define SPECIES_BARBOACH       339
#define SPECIES_WHISCASH       340
#define SPECIES_CORPHISH       341
#define SPECIES_CRAWDAUNT      342
#define SPECIES_BALTOY         343
#define SPECIES_CLAYDOL        344
#define SPECIES_LILEEP         345
#define SPECIES_CRADILY        346
#define SPECIES_ANORITH        347
#define SPECIES_ARMALDO        348
#define SPECIES_FEEBAS         349
#define SPECIES_MILOTIC        350
#define SPECIES_CASTFORM       351
#define SPECIES_KECLEON        352
#define SPECIES_SHUPPET        353
#define SPECIES_BANETTE        354
#define SPECIES_DUSKULL        355
#define SPECIES_DUSCLOPS       356
#define SPECIES_TROPIUS        357
#define SPECIES_CHIMECHO       358
#define SPECIES_ABSOL          359
#define SPECIES_WYNAUT         360
#define SPECIES_SNORUNT        361
#define SPECIES_GLALIE         362
#define SPECIES_SPHEAL         363
#define SPECIES_SEALEO         364
#define SPECIES_WALREIN        365
#define SPECIES_CLAMPERL       366
#define SPECIES_HUNTAIL        367
#define SPECIES_GOREBYSS       368
#define SPECIES_RELICANTH      369
#define SPECIES_LUVDISC        370
#define SPECIES_BAGON          371
#define SPECIES_SHELGON        372
#define SPECIES_SALAMENCE      373
#define SPECIES_BELDUM         374
#define SPECIES_METANG         375
#define SPECIES_METAGROSS      376
#define SPECIES_REGIROCK       377
#define SPECIES_REGICE         378
#define SPECIES_REGISTEEL      379
#define SPECIES_LATIAS         380
#define SPECIES_LATIOS         381
#define SPECIES_KYOGRE         382
#define SPECIES_GROUDON        383
#define SPECIES_RAYQUAZA       384
#define SPECIES_JIRACHI        385
#define SPECIES_DEOXYS         386

#define SPECIES_TURTWIG        387
#define SPECIES_GROTLE         388
#define SPECIES_TORTERRA       389
#define SPECIES_CHIMCHAR       390
#define SPECIES_MONFERNO       391
#define SPECIES_INFERNAPE      392
#define SPECIES_PIPLUP         393
#define SPECIES_PRINPLUP       394
#define SPECIES_EMPOLEON       395
#define SPECIES_STARLY         396
#define SPECIES_STARAVIA       397
#define SPECIES_STARAPTOR      398
#define SPECIES_BIDOOF         399
#define SPECIES_BIBAREL        400
#define SPECIES_KRICKETOT      401
#define SPECIES_KRICKETUNE     402
#define SPECIES_SHINX          403
#define SPECIES_LUXIO          404
#define SPECIES_LUXRAY         405
#define SPECIES_BUDEW          406
#define SPECIES_ROSERADE       407
#define SPECIES_CRANIDOS       408
#define SPECIES_RAMPARDOS      409
#define SPECIES_SHIELDON       410
#define SPECIES_BASTIODON      411
#define SPECIES_BURMY          412
#define SPECIES_WORMADAM       413
#define SPECIES_MOTHIM         414
#define SPECIES_COMBEE         415
#define SPECIES_VESPIQUEN      416
#define SPECIES_PACHIRISU      417
#define SPECIES_BUIZEL         418
#define SPECIES_FLOATZEL       419
#define SPECIES_CHERUBI        420
#define SPECIES_CHERRIM        421
#define SPECIES_SHELLOS        422
#define SPECIES_GASTRODON      423
#define SPECIES_AMBIPOM        424
#define SPECIES_DRIFLOON       425
#define SPECIES_DRIFBLIM       426
#define SPECIES_BUNEARY        427
#define SPECIES_LOPUNNY        428
#define SPECIES_MISMAGIUS      429
#define SPECIES_HONCHKROW      430
#define SPECIES_GLAMEOW        431
#define SPECIES_PURUGLY        432
#define SPECIES_CHINGLING      433
#define SPECIES_STUNKY         434
#define SPECIES_SKUNTANK       435
#define SPECIES_BRONZOR        436
#define SPECIES_BRONZONG       437
#define SPECIES_BONSLY         438
#define SPECIES_MIME_JR        439
#define SPECIES_HAPPINY        440
#define SPECIES_CHATOT         441
#define SPECIES_SPIRITOMB      442
#define SPECIES_GIBLE          443
#define SPECIES_GABITE         444
#define SPECIES_GARCHOMP       445
#define SPECIES_MUNCHLAX       446
#define SPECIES_RIOLU          447
#define SPECIES_LUCARIO        448
#define SPECIES_HIPPOPOTAS     449
#define SPECIES_HIPPOWDON      450
#define SPECIES_SKORUPI        451
#define SPECIES_DRAPION        452
#define SPECIES_CROAGUNK       453
#define SPECIES_TOXICROAK      454
#define SPECIES_CARNIVINE      455
#define SPECIES_FINNEON        456
#define SPECIES_LUMINEON       457
#define SPECIES_MANTYKE        458
#define SPECIES_SNOVER         459
#define SPECIES_ABOMASNOW      460
#define SPECIES_WEAVILE        461
#define SPECIES_MAGNEZONE      462
#define SPECIES_LICKILICKY     463
#define SPECIES_RHYPERIOR      464
#define SPECIES_TANGROWTH      465
#define SPECIES_ELECTIVIRE     466
#define SPECIES_MAGMORTAR      467
#define SPECIES_TOGEKISS       468
#define SPECIES_YANMEGA        469
#define SPECIES_LEAFEON        470
#define SPECIES_GLACEON        471
#define SPECIES_GLISCOR        472
#define SPECIES_MAMOSWINE      473
#define SPECIES_PORYGON_Z      474
#define SPECIES_GALLADE        475
#define SPECIES_PROBOPASS      476
#define SPECIES_DUSKNOIR       477
#define SPECIES_FROSLASS       478
#define SPECIES_ROTOM          479
#define SPECIES_UXIE           480
#define SPECIES_MESPRIT        481
#define SPECIES_AZELF          482
#define SPECIES_DIALGA         483
#define SPECIES_PALKIA         484
#define SPECIES_HEATRAN        485
#define SPECIES_REGIGIGAS      486
#define SPECIES_GIRATINA       487
#define SPECIES_CRESSELIA      488
#define SPECIES_PHIONE         489
#define SPECIES_MANAPHY        490
#define SPECIES_DARKRAI        491
#define SPECIES_SHAYMIN        492
#define SPECIES_ARCEUS         493
#define SPECIES_EGG 494
#define SPECIES_BAD_EGG 495
#define SPECIES_DEOXYS_ATTACK 496
#define SPECIES_DEOXYS_DEFENSE 497
#define SPECIES_DEOXYS_SPEED 498
#define SPECIES_WORMADAM_SANDY 499
#define SPECIES_WORMADAM_TRASHY 500
#define SPECIES_GIRATINA_ORIGIN 501
#define SPECIES_SHAYMIN_SKY 502
#define SPECIES_ROTOM_HEAT 503
#define SPECIES_ROTOM_WASH 504
#define SPECIES_ROTOM_FROST 505
#define SPECIES_ROTOM_FAN 506
#define SPECIES_ROTOM_MOW 507
#define SPECIES_508 508
#define SPECIES_509 509
#define SPECIES_510 510
#define SPECIES_511 511
#define SPECIES_512 512
#define SPECIES_513 513
#define SPECIES_514 514
#define SPECIES_515 515
#define SPECIES_516 516
#define SPECIES_517 517
#define SPECIES_518 518
#define SPECIES_519 519
#define SPECIES_520 520
#define SPECIES_521 521
#define SPECIES_522 522
#define SPECIES_523 523
#define SPECIES_524 524
#define SPECIES_525 525
#define SPECIES_526 526
#define SPECIES_527 527
#define SPECIES_528 528
#define SPECIES_529 529
#define SPECIES_530 530
#define SPECIES_531 531
#define SPECIES_532 532
#define SPECIES_533 533
#define SPECIES_534 534
#define SPECIES_535 535
#define SPECIES_536 536
#define SPECIES_537 537
#define SPECIES_538 538
#define SPECIES_539 539
#define SPECIES_540 540
#define SPECIES_541 541
#define SPECIES_542 542
#define SPECIES_543 543
#define SPECIES_VICTINI 544
#define SPECIES_SNIVY 545
#define SPECIES_SERVINE 546
#define SPECIES_SERPERIOR 547
#define SPECIES_TEPIG 548
#define SPECIES_PIGNITE 549
#define SPECIES_EMBOAR 550
#define SPECIES_OSHAWOTT 551
#define SPECIES_DEWOTT 552
#define SPECIES_SAMUROTT 553
#define SPECIES_PATRAT 554
#define SPECIES_WATCHOG 555
#define SPECIES_LILLIPUP 556
#define SPECIES_HERDIER 557
#define SPECIES_STOUTLAND 558
#define SPECIES_PURRLOIN 559
#define SPECIES_LIEPARD 560
#define SPECIES_PANSAGE 561
#define SPECIES_SIMISAGE 562
#define SPECIES_PANSEAR 563
#define SPECIES_SIMISEAR 564
#define SPECIES_PANPOUR 565
#define SPECIES_SIMIPOUR 566
#define SPECIES_MUNNA 567
#define SPECIES_MUSHARNA 568
#define SPECIES_PIDOVE 569
#define SPECIES_TRANQUILL 570
#define SPECIES_UNFEZANT 571
#define SPECIES_BLITZLE 572
#define SPECIES_ZEBSTRIKA 573
#define SPECIES_ROGGENROLA 574
#define SPECIES_BOLDORE 575
#define SPECIES_GIGALITH 576
#define SPECIES_WOOBAT 577
#define SPECIES_SWOOBAT 578
#define SPECIES_DRILBUR 579
#define SPECIES_EXCADRILL 580
#define SPECIES_AUDINO 581
#define SPECIES_TIMBURR 582
#define SPECIES_GURDURR 583
#define SPECIES_CONKELDURR 584
#define SPECIES_TYMPOLE 585
#define SPECIES_PALPITOAD 586
#define SPECIES_SEISMITOAD 587
#define SPECIES_THROH 588
#define SPECIES_SAWK 589
#define SPECIES_SEWADDLE 590
#define SPECIES_SWADLOON 591
#define SPECIES_LEAVANNY 592
#define SPECIES_VENIPEDE 593
#define SPECIES_WHIRLIPEDE 594
#define SPECIES_SCOLIPEDE 595
#define SPECIES_COTTONEE 596
#define SPECIES_WHIMSICOTT 597
#define SPECIES_PETILIL 598
#define SPECIES_LILLIGANT 599
#define SPECIES_BASCULIN 600
#define SPECIES_SANDILE 601
#define SPECIES_KROKOROK 602
#define SPECIES_KROOKODILE 603
#define SPECIES_DARUMAKA 604
#define SPECIES_DARMANITAN 605
#define SPECIES_MARACTUS 606
#define SPECIES_DWEBBLE 607
#define SPECIES_CRUSTLE 608
#define SPECIES_SCRAGGY 609
#define SPECIES_SCRAFTY 610
#define SPECIES_SIGILYPH 611
#define SPECIES_YAMASK 612
#define SPECIES_COFAGRIGUS 613
#define SPECIES_TIRTOUGA 614
#define SPECIES_CARRACOSTA 615
#define SPECIES_ARCHEN 616
#define SPECIES_ARCHEOPS 617
#define SPECIES_TRUBBISH 618
#define SPECIES_GARBODOR 619
#define SPECIES_ZORUA 620
#define SPECIES_ZOROARK 621
#define SPECIES_MINCCINO 622
#define SPECIES_CINCCINO 623
#define SPECIES_GOTHITA 624
#define SPECIES_GOTHORITA 625
#define SPECIES_GOTHITELLE 626
#define SPECIES_SOLOSIS 627
#define SPECIES_DUOSION 628
#define SPECIES_REUNICLUS 629
#define SPECIES_DUCKLETT 630
#define SPECIES_SWANNA 631
#define SPECIES_VANILLITE 632
#define SPECIES_VANILLISH 633
#define SPECIES_VANILLUXE 634
#define SPECIES_DEERLING 635
#define SPECIES_SAWSBUCK 636
#define SPECIES_EMOLGA 637
#define SPECIES_KARRABLAST 638
#define SPECIES_ESCAVALIER 639
#define SPECIES_FOONGUS 640
#define SPECIES_AMOONGUSS 641
#define SPECIES_FRILLISH 642
#define SPECIES_JELLICENT 643
#define SPECIES_ALOMOMOLA 644
#define SPECIES_JOLTIK 645
#define SPECIES_GALVANTULA 646
#define SPECIES_FERROSEED 647
#define SPECIES_FERROTHORN 648
#define SPECIES_KLINK 649
#define SPECIES_KLANG 650
#define SPECIES_KLINKLANG 651
#define SPECIES_TYNAMO 652
#define SPECIES_EELEKTRIK 653
#define SPECIES_EELEKTROSS 654
#define SPECIES_ELGYEM 655
#define SPECIES_BEHEEYEM 656
#define SPECIES_LITWICK 657
#define SPECIES_LAMPENT 658
#define SPECIES_CHANDELURE 659
#define SPECIES_AXEW 660
#define SPECIES_FRAXURE 661
#define SPECIES_HAXORUS 662
#define SPECIES_CUBCHOO 663
#define SPECIES_BEARTIC 664
#define SPECIES_CRYOGONAL 665
#define SPECIES_SHELMET 666
#define SPECIES_ACCELGOR 667
#define SPECIES_STUNFISK 668
#define SPECIES_MIENFOO 669
#define SPECIES_MIENSHAO 670
#define SPECIES_DRUDDIGON 671
#define SPECIES_GOLETT 672
#define SPECIES_GOLURK 673
#define SPECIES_PAWNIARD 674
#define SPECIES_BISHARP 675
#define SPECIES_BOUFFALANT 676
#define SPECIES_RUFFLET 677
#define SPECIES_BRAVIARY 678
#define SPECIES_VULLABY 679
#define SPECIES_MANDIBUZZ 680
#define SPECIES_HEATMOR 681
#define SPECIES_DURANT 682
#define SPECIES_DEINO 683
#define SPECIES_ZWEILOUS 684
#define SPECIES_HYDREIGON 685
#define SPECIES_LARVESTA 686
#define SPECIES_VOLCARONA 687
#define SPECIES_COBALION 688
#define SPECIES_TERRAKION 689
#define SPECIES_VIRIZION 690
#define SPECIES_TORNADUS 691
#define SPECIES_THUNDURUS 692
#define SPECIES_RESHIRAM 693
#define SPECIES_ZEKROM 694
#define SPECIES_LANDORUS 695
#define SPECIES_KYUREM 696
#define SPECIES_KELDEO 697
#define SPECIES_MELOETTA 698
#define SPECIES_GENESECT 699
#define SPECIES_CHESPIN 700
#define SPECIES_QUILLADIN 701
#define SPECIES_CHESNAUGHT 702
#define SPECIES_FENNEKIN 703
#define SPECIES_BRAIXEN 704
#define SPECIES_DELPHOX 705
#define SPECIES_FROAKIE 706
#define SPECIES_FROGADIER 707
#define SPECIES_GRENINJA 708
#define SPECIES_BUNNELBY 709
#define SPECIES_DIGGERSBY 710
#define SPECIES_FLETCHLING 711
#define SPECIES_FLETCHINDER 712
#define SPECIES_TALONFLAME 713
#define SPECIES_SCATTERBUG 714
#define SPECIES_SPEWPA 715
#define SPECIES_VIVILLON 716  // Icy Snow Pattern
#define SPECIES_LITLEO 717
#define SPECIES_PYROAR 718
#define SPECIES_FLABEBE 719  // Red Flower
#define SPECIES_FLOETTE 720  // Red Flower
#define SPECIES_FLORGES 721  // Red Flower
#define SPECIES_SKIDDO 722
#define SPECIES_GOGOAT 723
#define SPECIES_PANCHAM 724
#define SPECIES_PANGORO 725
#define SPECIES_FURFROU 726
#define SPECIES_ESPURR 727
#define SPECIES_MEOWSTIC 728
#define SPECIES_HONEDGE 729
#define SPECIES_DOUBLADE 730
#define SPECIES_AEGISLASH 731
#define SPECIES_SPRITZEE 732
#define SPECIES_AROMATISSE 733
#define SPECIES_SWIRLIX 734
#define SPECIES_SLURPUFF 735
#define SPECIES_INKAY 736
#define SPECIES_MALAMAR 737
#define SPECIES_BINACLE 738
#define SPECIES_BARBARACLE 739
#define SPECIES_SKRELP 740
#define SPECIES_DRAGALGE 741
#define SPECIES_CLAUNCHER 742
#define SPECIES_CLAWITZER 743
#define SPECIES_HELIOPTILE 744
#define SPECIES_HELIOLISK 745
#define SPECIES_TYRUNT 746
#define SPECIES_TYRANTRUM 747
#define SPECIES_AMAURA 748
#define SPECIES_AURORUS 749
#define SPECIES_SYLVEON 750
#define SPECIES_HAWLUCHA 751
#define SPECIES_DEDENNE 752
#define SPECIES_CARBINK 753
#define SPECIES_GOOMY 754
#define SPECIES_SLIGGOO 755
#define SPECIES_GOODRA 756
#define SPECIES_KLEFKI 757
#define SPECIES_PHANTUMP 758
#define SPECIES_TREVENANT 759
#define SPECIES_PUMPKABOO 760
#define SPECIES_GOURGEIST 761
#define SPECIES_BERGMITE 762
#define SPECIES_AVALUGG 763
#define SPECIES_NOIBAT 764
#define SPECIES_NOIVERN 765
#define SPECIES_XERNEAS 766
#define SPECIES_YVELTAL 767
#define SPECIES_ZYGARDE 768
#define SPECIES_DIANCIE 769
#define SPECIES_HOOPA 770
#define SPECIES_VOLCANION 771
#define SPECIES_ROWLET 772
#define SPECIES_DARTRIX 773
#define SPECIES_DECIDUEYE 774
#define SPECIES_LITTEN 775
#define SPECIES_TORRACAT 776
#define SPECIES_INCINEROAR 777
#define SPECIES_POPPLIO 778
#define SPECIES_BRIONNE 779
#define SPECIES_PRIMARINA 780
#define SPECIES_PIKIPEK 781
#define SPECIES_TRUMBEAK 782
#define SPECIES_TOUCANNON 783
#define SPECIES_YUNGOOS 784
#define SPECIES_GUMSHOOS 785
#define SPECIES_GRUBBIN 786
#define SPECIES_CHARJABUG 787
#define SPECIES_VIKAVOLT 788
#define SPECIES_CRABRAWLER 789
#define SPECIES_CRABOMINABLE 790
#define SPECIES_ORICORIO 791
#define SPECIES_CUTIEFLY 792
#define SPECIES_RIBOMBEE 793
#define SPECIES_ROCKRUFF 794
#define SPECIES_LYCANROC 795
#define SPECIES_WISHIWASHI 796
#define SPECIES_MAREANIE 797
#define SPECIES_TOXAPEX 798
#define SPECIES_MUDBRAY 799
#define SPECIES_MUDSDALE 800
#define SPECIES_DEWPIDER 801
#define SPECIES_ARAQUANID 802
#define SPECIES_FOMANTIS 803
#define SPECIES_LURANTIS 804
#define SPECIES_MORELULL 805
#define SPECIES_SHIINOTIC 806
#define SPECIES_SALANDIT 807
#define SPECIES_SALAZZLE 808
#define SPECIES_STUFFUL 809
#define SPECIES_BEWEAR 810
#define SPECIES_BOUNSWEET 811
#define SPECIES_STEENEE 812
#define SPECIES_TSAREENA 813
#define SPECIES_COMFEY 814
#define SPECIES_ORANGURU 815
#define SPECIES_PASSIMIAN 816
#define SPECIES_WIMPOD 817
#define SPECIES_GOLISOPOD 818
#define SPECIES_SANDYGAST 819
#define SPECIES_PALOSSAND 820
#define SPECIES_PYUKUMUKU 821
#define SPECIES_TYPE_NULL 822
#define SPECIES_SILVALLY 823
#define SPECIES_MINIOR 824
#define SPECIES_KOMALA 825
#define SPECIES_TURTONATOR 826
#define SPECIES_TOGEDEMARU 827
#define SPECIES_MIMIKYU 828
#define SPECIES_BRUXISH 829
#define SPECIES_DRAMPA 830
#define SPECIES_DHELMISE 831
#define SPECIES_JANGMO_O 832
#define SPECIES_HAKAMO_O 833
#define SPECIES_KOMMO_O 834
#define SPECIES_TAPU_KOKO 835
#define SPECIES_TAPU_LELE 836
#define SPECIES_TAPU_BULU 837
#define SPECIES_TAPU_FINI 838
#define SPECIES_COSMOG 839
#define SPECIES_COSMOEM 840
#define SPECIES_SOLGALEO 841
#define SPECIES_LUNALA 842
#define SPECIES_NIHILEGO 843
#define SPECIES_BUZZWOLE 844
#define SPECIES_PHEROMOSA 845
#define SPECIES_XURKITREE 846
#define SPECIES_CELESTEELA 847
#define SPECIES_KARTANA 848
#define SPECIES_GUZZLORD 849
#define SPECIES_NECROZMA 850
#define SPECIES_MAGEARNA 851
#define SPECIES_MARSHADOW 852
#define SPECIES_POIPOLE 853
#define SPECIES_NAGANADEL 854
#define SPECIES_STAKATAKA 855
#define SPECIES_BLACEPHALON 856
#define SPECIES_ZERAORA 857
#define SPECIES_MELTAN 858
#define SPECIES_MELMETAL 859
#define SPECIES_GROOKEY 860
#define SPECIES_THWACKEY 861
#define SPECIES_RILLABOOM 862
#define SPECIES_SCORBUNNY 863
#define SPECIES_RABOOT 864
#define SPECIES_CINDERACE 865
#define SPECIES_SOBBLE 866
#define SPECIES_DRIZZILE 867
#define SPECIES_INTELEON 868
#define SPECIES_SKWOVET 869
#define SPECIES_GREEDENT 870
#define SPECIES_ROOKIDEE 871
#define SPECIES_CORVISQUIRE 872
#define SPECIES_CORVIKNIGHT 873
#define SPECIES_BLIPBUG 874
#define SPECIES_DOTTLER 875
#define SPECIES_ORBEETLE 876
#define SPECIES_NICKIT 877
#define SPECIES_THIEVUL 878
#define SPECIES_GOSSIFLEUR 879
#define SPECIES_ELDEGOSS 880
#define SPECIES_WOOLOO 881
#define SPECIES_DUBWOOL 882
#define SPECIES_CHEWTLE 883
#define SPECIES_DREDNAW 884
#define SPECIES_YAMPER 885
#define SPECIES_BOLTUND 886
#define SPECIES_ROLYCOLY 887
#define SPECIES_CARKOL 888
#define SPECIES_COALOSSAL 889
#define SPECIES_APPLIN 890
#define SPECIES_FLAPPLE 891
#define SPECIES_APPLETUN 892
#define SPECIES_SILICOBRA 893
#define SPECIES_SANDACONDA 894
#define SPECIES_CRAMORANT 895
#define SPECIES_ARROKUDA 896
#define SPECIES_BARRASKEWDA 897
#define SPECIES_TOXEL 898
#define SPECIES_TOXTRICITY 899
#define SPECIES_SIZZLIPEDE 900
#define SPECIES_CENTISKORCH 901
#define SPECIES_CLOBBOPUS 902
#define SPECIES_GRAPPLOCT 903
#define SPECIES_SINISTEA 904
#define SPECIES_POLTEAGEIST 905
#define SPECIES_HATENNA 906
#define SPECIES_HATTREM 907
#define SPECIES_HATTERENE 908
#define SPECIES_IMPIDIMP 909
#define SPECIES_MORGREM 910
#define SPECIES_GRIMMSNARL 911
#define SPECIES_OBSTAGOON 912
#define SPECIES_PERRSERKER 913
#define SPECIES_CURSOLA 914
#define SPECIES_SIRFETCHD 915
#define SPECIES_MR_RIME 916
#define SPECIES_RUNERIGUS 917
#define SPECIES_MILCERY 918
#define SPECIES_ALCREMIE 919
#define SPECIES_FALINKS 920
#define SPECIES_PINCURCHIN 921
#define SPECIES_SNOM 922
#define SPECIES_FROSMOTH 923
#define SPECIES_STONJOURNER 924
#define SPECIES_EISCUE 925
#define SPECIES_INDEEDEE 926
#define SPECIES_MORPEKO 927
#define SPECIES_CUFANT 928
#define SPECIES_COPPERAJAH 929
#define SPECIES_DRACOZOLT 930
#define SPECIES_ARCTOZOLT 931
#define SPECIES_DRACOVISH 932
#define SPECIES_ARCTOVISH 933
#define SPECIES_DURALUDON 934
#define SPECIES_DREEPY 935
#define SPECIES_DRAKLOAK 936
#define SPECIES_DRAGAPULT 937
#define SPECIES_ZACIAN 938
#define SPECIES_ZAMAZENTA 939
#define SPECIES_ETERNATUS 940
#define SPECIES_KUBFU 941
#define SPECIES_URSHIFU 942
#define SPECIES_ZARUDE 943
#define SPECIES_REGIELEKI 944
#define SPECIES_REGIDRAGO 945
#define SPECIES_GLASTRIER 946
#define SPECIES_SPECTRIER 947
#define SPECIES_CALYREX 948
#define SPECIES_WYRDEER 949
#define SPECIES_KLEAVOR 950
#define SPECIES_URSALUNA 951
#define SPECIES_BASCULEGION 952
#define SPECIES_SNEASLER 953
#define SPECIES_OVERQWIL 954
#define SPECIES_ENAMORUS 955
#define SPECIES_SPRIGATITO 956
#define SPECIES_FLORAGATO 957
#define SPECIES_MEOWSCARADA 958
#define SPECIES_FUECOCO 959
#define SPECIES_CROCALOR 960
#define SPECIES_SKELEDIRGE 961
#define SPECIES_QUAXLY 962
#define SPECIES_QUAXWELL 963
#define SPECIES_QUAQUAVAL 964
#define SPECIES_LECHONK 965
#define SPECIES_OINKOLOGNE 966
#define SPECIES_TAROUNTULA 967
#define SPECIES_SPIDOPS 968
#define SPECIES_NYMBLE 969
#define SPECIES_LOKIX 970
#define SPECIES_PAWMI 971
#define SPECIES_PAWMO 972
#define SPECIES_PAWMOT 973
#define SPECIES_TANDEMAUS 974
#define SPECIES_MAUSHOLD 975
#define SPECIES_FIDOUGH 976
#define SPECIES_DACHSBUN 977
#define SPECIES_SMOLIV 978
#define SPECIES_DOLLIV 979
#define SPECIES_ARBOLIVA 980
#define SPECIES_SQUAWKABILLY 981
#define SPECIES_NACLI 982
#define SPECIES_NACLSTACK 983
#define SPECIES_GARGANACL 984
#define SPECIES_CHARCADET 985
#define SPECIES_ARMAROUGE 986
#define SPECIES_CERULEDGE 987
#define SPECIES_TADBULB 988
#define SPECIES_BELLIBOLT 989
#define SPECIES_WATTREL 990
#define SPECIES_KILOWATTREL 991
#define SPECIES_MASCHIFF 992
#define SPECIES_MABOSSTIFF 993
#define SPECIES_SHROODLE 994
#define SPECIES_GRAFAIAI 995
#define SPECIES_BRAMBLIN 996
#define SPECIES_BRAMBLEGHAST 997
#define SPECIES_TOEDSCOOL 998
#define SPECIES_TOEDSCRUEL 999
#define SPECIES_KLAWF 1000
#define SPECIES_CAPSAKID 1001
#define SPECIES_SCOVILLAIN 1002
#define SPECIES_RELLOR 1003
#define SPECIES_RABSCA 1004
#define SPECIES_FLITTLE 1005
#define SPECIES_ESPATHRA 1006
#define SPECIES_TINKATINK 1007
#define SPECIES_TINKATUFF 1008
#define SPECIES_TINKATON 1009
#define SPECIES_WIGLETT 1010
#define SPECIES_WUGTRIO 1011
#define SPECIES_BOMBIRDIER 1012
#define SPECIES_FINIZEN 1013
#define SPECIES_PALAFIN 1014
#define SPECIES_VAROOM 1015
#define SPECIES_REVAVROOM 1016
#define SPECIES_CYCLIZAR 1017
#define SPECIES_ORTHWORM 1018
#define SPECIES_GLIMMET 1019
#define SPECIES_GLIMMORA 1020
#define SPECIES_GREAVARD 1021
#define SPECIES_HOUNDSTONE 1022
#define SPECIES_FLAMIGO 1023
#define SPECIES_CETODDLE 1024
#define SPECIES_CETITAN 1025
#define SPECIES_VELUZA 1026
#define SPECIES_DONDOZO 1027
#define SPECIES_TATSUGIRI 1028
#define SPECIES_ANNIHILAPE 1029
#define SPECIES_CLODSIRE 1030
#define SPECIES_FARIGIRAF 1031
#define SPECIES_DUDUNSPARCE 1032
#define SPECIES_KINGAMBIT 1033
#define SPECIES_GREAT_TUSK 1034
#define SPECIES_SCREAM_TAIL 1035
#define SPECIES_BRUTE_BONNET 1036
#define SPECIES_FLUTTER_MANE 1037
#define SPECIES_SLITHER_WING 1038
#define SPECIES_SANDY_SHOCKS 1039
#define SPECIES_IRON_TREADS 1040
#define SPECIES_IRON_BUNDLE 1041
#define SPECIES_IRON_HANDS 1042
#define SPECIES_IRON_JUGULIS 1043
#define SPECIES_IRON_MOTH 1044
#define SPECIES_IRON_THORNS 1045
#define SPECIES_FRIGIBAX 1046
#define SPECIES_ARCTIBAX 1047
#define SPECIES_BAXCALIBUR 1048
#define SPECIES_GIMMIGHOUL 1049
#define SPECIES_GHOLDENGO 1050
#define SPECIES_WO_CHIEN 1051
#define SPECIES_CHIEN_PAO 1052
#define SPECIES_TING_LU 1053
#define SPECIES_CHI_YU 1054
#define SPECIES_ROARING_MOON 1055
#define SPECIES_IRON_VALIANT 1056
#define SPECIES_KORAIDON 1057
#define SPECIES_MIRAIDON 1058
#define SPECIES_WALKING_WAKE 1059
#define SPECIES_IRON_LEAVES 1060
#define SPECIES_DIPPLIN 1061
#define SPECIES_POLTCHAGEIST 1062
#define SPECIES_SINISTCHA 1063
#define SPECIES_OKIDOGI 1064
#define SPECIES_MUNKIDORI 1065
#define SPECIES_FEZANDIPITI 1066
#define SPECIES_OGERPON 1067
#define SPECIES_ARCHALUDON 1068
#define SPECIES_HYDRAPPLE 1069
#define SPECIES_GOUGING_FIRE 1070
#define SPECIES_RAGING_BOLT 1071
#define SPECIES_IRON_BOULDER 1072
#define SPECIES_IRON_CROWN 1073
#define SPECIES_TERAPAGOS 1074
#define SPECIES_PECHARUNT 1075

#define MAX_CANONICAL_MON_NUM (SPECIES_PECHARUNT)

// define your fakemons below like this
// #define SPECIES_FAKEMON_NAME1 (MAX_CANONICAL_MON_NUM + 1)

#define MUM_OF_FAKEMONS 0

#define MAX_MON_NUM (SPECIES_PECHARUNT + MUM_OF_FAKEMONS)

//mega
#define SPECIES_MEGA_START (MAX_MON_NUM + 1) // 1076

#define SPECIES_MEGA_VENUSAUR (SPECIES_MEGA_START)
#define SPECIES_MEGA_CHARIZARD_X (SPECIES_MEGA_START + 1)
#define SPECIES_MEGA_CHARIZARD_Y (SPECIES_MEGA_START + 2)
#define SPECIES_MEGA_BLASTOISE (SPECIES_MEGA_START + 3)
#define SPECIES_MEGA_BEEDRILL (SPECIES_MEGA_START + 4)
#define SPECIES_MEGA_PIDGEOT (SPECIES_MEGA_START + 5)
#define SPECIES_MEGA_ALAKAZAM (SPECIES_MEGA_START + 6)
#define SPECIES_MEGA_SLOWBRO (SPECIES_MEGA_START + 7)
#define SPECIES_MEGA_GENGAR (SPECIES_MEGA_START + 8)
#define SPECIES_MEGA_KANGASKHAN (SPECIES_MEGA_START + 9)
#define SPECIES_MEGA_PINSIR (SPECIES_MEGA_START + 10)
#define SPECIES_MEGA_GYARADOS (SPECIES_MEGA_START + 11)
#define SPECIES_MEGA_AERODACTYL (SPECIES_MEGA_START + 12)
#define SPECIES_MEGA_MEWTWO_X (SPECIES_MEGA_START + 13)
#define SPECIES_MEGA_MEWTWO_Y (SPECIES_MEGA_START + 14)
#define SPECIES_MEGA_AMPHAROS (SPECIES_MEGA_START + 15)
#define SPECIES_MEGA_STEELIX (SPECIES_MEGA_START + 16)
#define SPECIES_MEGA_SCIZOR (SPECIES_MEGA_START + 17)
#define SPECIES_MEGA_HERACROSS (SPECIES_MEGA_START + 18)
#define SPECIES_MEGA_HOUNDOOM (SPECIES_MEGA_START + 19)
#define SPECIES_MEGA_TYRANITAR (SPECIES_MEGA_START + 20)
#define SPECIES_MEGA_SCEPTILE (SPECIES_MEGA_START + 21)
#define SPECIES_MEGA_BLAZIKEN (SPECIES_MEGA_START + 22)
#define SPECIES_MEGA_SWAMPERT (SPECIES_MEGA_START + 23)
#define SPECIES_MEGA_GARDEVOIR (SPECIES_MEGA_START + 24)
#define SPECIES_MEGA_SABLEYE (SPECIES_MEGA_START + 25)
#define SPECIES_MEGA_MAWILE (SPECIES_MEGA_START + 26)
#define SPECIES_MEGA_AGGRON (SPECIES_MEGA_START + 27)
#define SPECIES_MEGA_MEDICHAM (SPECIES_MEGA_START + 28)
#define SPECIES_MEGA_MANECTRIC (SPECIES_MEGA_START + 29)
#define SPECIES_MEGA_SHARPEDO (SPECIES_MEGA_START + 30)
#define SPECIES_MEGA_CAMERUPT (SPECIES_MEGA_START + 31)
#define SPECIES_MEGA_ALTARIA (SPECIES_MEGA_START + 32)
#define SPECIES_MEGA_BANETTE (SPECIES_MEGA_START + 33)
#define SPECIES_MEGA_ABSOL (SPECIES_MEGA_START + 34)
#define SPECIES_MEGA_GLALIE (SPECIES_MEGA_START + 35)
#define SPECIES_MEGA_SALAMENCE (SPECIES_MEGA_START + 36)
#define SPECIES_MEGA_METAGROSS (SPECIES_MEGA_START + 37)
#define SPECIES_MEGA_LATIAS (SPECIES_MEGA_START + 38)
#define SPECIES_MEGA_LATIOS (SPECIES_MEGA_START + 39)
#define SPECIES_MEGA_RAYQUAZA (SPECIES_MEGA_START + 40)
#define SPECIES_MEGA_LOPUNNY (SPECIES_MEGA_START + 41)
#define SPECIES_MEGA_GARCHOMP (SPECIES_MEGA_START + 42)
#define SPECIES_MEGA_LUCARIO (SPECIES_MEGA_START + 43)
#define SPECIES_MEGA_ABOMASNOW (SPECIES_MEGA_START + 44)
#define SPECIES_MEGA_GALLADE (SPECIES_MEGA_START + 45)
#define SPECIES_MEGA_AUDINO (SPECIES_MEGA_START + 46)
#define SPECIES_MEGA_DIANCIE (SPECIES_MEGA_START + 47)

#define MAX_MEGA_NUM (SPECIES_MEGA_DIANCIE)


//primals
#define SPECIES_PRIMAL_START (MAX_MEGA_NUM + 1) // 1124

#define SPECIES_KYOGRE_PRIMAL (SPECIES_PRIMAL_START)
#define SPECIES_GROUDON_PRIMAL (SPECIES_PRIMAL_START + 1)

#define MAX_PRIMAL_NUM (SPECIES_GROUDON_PRIMAL)


//alolans
#define SPECIES_ALOLAN_REGIONAL_START (MAX_PRIMAL_NUM + 1) // 1126

#define SPECIES_RATTATA_ALOLAN (SPECIES_ALOLAN_REGIONAL_START)
#define SPECIES_RATICATE_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 1)
#define SPECIES_RAICHU_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 2)
#define SPECIES_SANDSHREW_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 3)
#define SPECIES_SANDSLASH_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 4)
#define SPECIES_VULPIX_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 5)
#define SPECIES_NINETALES_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 6)
#define SPECIES_DIGLETT_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 7)
#define SPECIES_DUGTRIO_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 8)
#define SPECIES_MEOWTH_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 9)
#define SPECIES_PERSIAN_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 10)
#define SPECIES_GEODUDE_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 11)
#define SPECIES_GRAVELER_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 12)
#define SPECIES_GOLEM_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 13)
#define SPECIES_GRIMER_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 14)
#define SPECIES_MUK_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 15)
#define SPECIES_EXEGGUTOR_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 16)
#define SPECIES_MAROWAK_ALOLAN (SPECIES_ALOLAN_REGIONAL_START + 17)

//totems
#define SPECIES_RATICATE_ALOLAN_LARGE (SPECIES_ALOLAN_REGIONAL_START + 18)
#define SPECIES_MAROWAK_ALOLAN_LARGE (SPECIES_ALOLAN_REGIONAL_START + 19)
#define SPECIES_GUMSHOOS_LARGE (SPECIES_ALOLAN_REGIONAL_START + 20)
#define SPECIES_VIKAVOLT_LARGE (SPECIES_ALOLAN_REGIONAL_START + 21)
#define SPECIES_RIBOMBEE_LARGE (SPECIES_ALOLAN_REGIONAL_START + 22)
#define SPECIES_ARAQUANID_LARGE (SPECIES_ALOLAN_REGIONAL_START + 23)
#define SPECIES_LURANTIS_LARGE (SPECIES_ALOLAN_REGIONAL_START + 24)
#define SPECIES_SALAZZLE_LARGE (SPECIES_ALOLAN_REGIONAL_START + 25)
#define SPECIES_TOGEDEMARU_LARGE (SPECIES_ALOLAN_REGIONAL_START + 26)
#define SPECIES_MIMIKYU_LARGE (SPECIES_ALOLAN_REGIONAL_START + 27)
#define SPECIES_MIMIKYU_BUSTED_LARGE (SPECIES_ALOLAN_REGIONAL_START + 28)
#define SPECIES_KOMMO_O_LARGE (SPECIES_ALOLAN_REGIONAL_START + 29)


#define MAX_ALOLAN_REGIONAL_NUM (SPECIES_KOMMO_O_LARGE)


//galarians
#define SPECIES_GALARIAN_REGIONAL_START (MAX_ALOLAN_REGIONAL_NUM + 1) // 1156

#define SPECIES_MEOWTH_GALARIAN (SPECIES_GALARIAN_REGIONAL_START)
#define SPECIES_PONYTA_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 1)
#define SPECIES_RAPIDASH_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 2)
#define SPECIES_SLOWPOKE_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 3)
#define SPECIES_SLOWBRO_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 4)
#define SPECIES_FARFETCHD_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 5)
#define SPECIES_WEEZING_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 6)
#define SPECIES_MR_MIME_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 7)
#define SPECIES_ARTICUNO_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 8)
#define SPECIES_ZAPDOS_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 9)
#define SPECIES_MOLTRES_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 10)
#define SPECIES_SLOWKING_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 11)
#define SPECIES_CORSOLA_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 12)
#define SPECIES_ZIGZAGOON_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 13)
#define SPECIES_LINOONE_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 14)
#define SPECIES_DARUMAKA_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 15)
#define SPECIES_DARMANITAN_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 16)
#define SPECIES_YAMASK_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 17)
#define SPECIES_STUNFISK_GALARIAN (SPECIES_GALARIAN_REGIONAL_START + 18)

#define MAX_GALARIAN_REGIONAL_NUM (SPECIES_STUNFISK_GALARIAN)


//misc forms
#define SPECIES_MISC_FORM_START (MAX_GALARIAN_REGIONAL_NUM + 1) // 1175

#define SPECIES_PIKACHU_COSPLAY (SPECIES_MISC_FORM_START)
#define SPECIES_PIKACHU_ROCK_STAR (SPECIES_MISC_FORM_START + 1)
#define SPECIES_PIKACHU_BELLE (SPECIES_MISC_FORM_START + 2)
#define SPECIES_PIKACHU_POP_STAR (SPECIES_MISC_FORM_START + 3)
#define SPECIES_PIKACHU_PH_D (SPECIES_MISC_FORM_START + 4)
#define SPECIES_PIKACHU_LIBRE (SPECIES_MISC_FORM_START + 5)

#define SPECIES_PIKACHU_ORIGINAL_CAP (SPECIES_MISC_FORM_START + 6)
#define SPECIES_PIKACHU_HOENN_CAP (SPECIES_MISC_FORM_START + 7)
#define SPECIES_PIKACHU_SINNOH_CAP (SPECIES_MISC_FORM_START + 8)
#define SPECIES_PIKACHU_UNOVA_CAP (SPECIES_MISC_FORM_START + 9)
#define SPECIES_PIKACHU_KALOS_CAP (SPECIES_MISC_FORM_START + 10)
#define SPECIES_PIKACHU_ALOLA_CAP (SPECIES_MISC_FORM_START + 11)
#define SPECIES_PIKACHU_PARTNER_CAP (SPECIES_MISC_FORM_START + 12)
#define SPECIES_PIKACHU_WORLD_CAP (SPECIES_MISC_FORM_START + 13)

#define SPECIES_CASTFORM_SUNNY (SPECIES_MISC_FORM_START + 14)
#define SPECIES_CASTFORM_RAINY (SPECIES_MISC_FORM_START + 15)
#define SPECIES_CASTFORM_SNOWY (SPECIES_MISC_FORM_START + 16)

#define SPECIES_CHERRIM_SUNSHINE (SPECIES_MISC_FORM_START + 17)
#define SPECIES_SHELLOS_EAST_SEA (SPECIES_MISC_FORM_START + 18)
#define SPECIES_GASTRODON_EAST_SEA (SPECIES_MISC_FORM_START + 19)

#define SPECIES_DIALGA_ORIGIN (SPECIES_MISC_FORM_START + 20)
#define SPECIES_PALKIA_ORIGIN (SPECIES_MISC_FORM_START + 21)

#define SPECIES_BASCULIN_BLUE_STRIPED (SPECIES_MISC_FORM_START + 22)
#define SPECIES_BASCULIN_WHITE_STRIPED (SPECIES_MISC_FORM_START + 23)

#define SPECIES_DARMANITAN_ZEN_MODE (SPECIES_MISC_FORM_START + 24)
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN (SPECIES_MISC_FORM_START + 25)

#define SPECIES_DEERLING_SUMMER (SPECIES_MISC_FORM_START + 26)
#define SPECIES_DEERLING_AUTUMN (SPECIES_MISC_FORM_START + 27)
#define SPECIES_DEERLING_WINTER (SPECIES_MISC_FORM_START + 28)

#define SPECIES_SAWSBUCK_SUMMER (SPECIES_MISC_FORM_START + 29)
#define SPECIES_SAWSBUCK_AUTUMN (SPECIES_MISC_FORM_START + 30)
#define SPECIES_SAWSBUCK_WINTER (SPECIES_MISC_FORM_START + 31)

#define SPECIES_TORNADUS_THERIAN (SPECIES_MISC_FORM_START + 32)
#define SPECIES_THUNDURUS_THERIAN (SPECIES_MISC_FORM_START + 33)
#define SPECIES_LANDORUS_THERIAN (SPECIES_MISC_FORM_START + 34)

#define SPECIES_KYUREM_WHITE (SPECIES_MISC_FORM_START + 35)
#define SPECIES_KYUREM_BLACK (SPECIES_MISC_FORM_START + 36)

#define SPECIES_KELDEO_RESOLUTE (SPECIES_MISC_FORM_START + 37)
#define SPECIES_MELOETTA_PIROUETTE (SPECIES_MISC_FORM_START + 38)

#define SPECIES_GENESECT_DOUSE_DRIVE (SPECIES_MISC_FORM_START + 39)
#define SPECIES_GENESECT_SHOCK_DRIVE (SPECIES_MISC_FORM_START + 40)
#define SPECIES_GENESECT_BURN_DRIVE (SPECIES_MISC_FORM_START + 41)
#define SPECIES_GENESECT_CHILL_DRIVE (SPECIES_MISC_FORM_START + 42)

#define SPECIES_GRENINJA_BATTLE_BOND (SPECIES_MISC_FORM_START + 43)
#define SPECIES_GRENINJA_ASH (SPECIES_MISC_FORM_START + 44)

#define SPECIES_VIVILLON_POLAR (SPECIES_MISC_FORM_START + 45)
#define SPECIES_VIVILLON_TUNDRA (SPECIES_MISC_FORM_START + 46)
#define SPECIES_VIVILLON_CONTINENTAL (SPECIES_MISC_FORM_START + 47)
#define SPECIES_VIVILLON_GARDEN (SPECIES_MISC_FORM_START + 48)
#define SPECIES_VIVILLON_ELEGANT (SPECIES_MISC_FORM_START + 49)
#define SPECIES_VIVILLON_MEADOW (SPECIES_MISC_FORM_START + 50)
#define SPECIES_VIVILLON_MODERN (SPECIES_MISC_FORM_START + 51)
#define SPECIES_VIVILLON_MARINE (SPECIES_MISC_FORM_START + 52)
#define SPECIES_VIVILLON_ARCHIPELAGO (SPECIES_MISC_FORM_START + 53)
#define SPECIES_VIVILLON_HIGH_PLAINS (SPECIES_MISC_FORM_START + 54)
#define SPECIES_VIVILLON_SANDSTORM (SPECIES_MISC_FORM_START + 55)
#define SPECIES_VIVILLON_RIVER (SPECIES_MISC_FORM_START + 56)
#define SPECIES_VIVILLON_MONSOON (SPECIES_MISC_FORM_START + 57)
#define SPECIES_VIVILLON_SAVANNA (SPECIES_MISC_FORM_START + 58)
#define SPECIES_VIVILLON_SUN (SPECIES_MISC_FORM_START + 59)
#define SPECIES_VIVILLON_OCEAN (SPECIES_MISC_FORM_START + 60)
#define SPECIES_VIVILLON_JUNGLE (SPECIES_MISC_FORM_START + 61)
#define SPECIES_VIVILLON_FANCY (SPECIES_MISC_FORM_START + 62)
#define SPECIES_VIVILLON_POKE_BALL (SPECIES_MISC_FORM_START + 63)

#define SPECIES_FLABEBE_YELLOW_FLOWER (SPECIES_MISC_FORM_START + 64)
#define SPECIES_FLABEBE_ORANGE_FLOWER (SPECIES_MISC_FORM_START + 65)
#define SPECIES_FLABEBE_BLUE_FLOWER (SPECIES_MISC_FORM_START + 66)
#define SPECIES_FLABEBE_WHITE_FLOWER (SPECIES_MISC_FORM_START + 67)

#define SPECIES_FLOETTE_YELLOW_FLOWER (SPECIES_MISC_FORM_START + 68)
#define SPECIES_FLOETTE_ORANGE_FLOWER (SPECIES_MISC_FORM_START + 69)
#define SPECIES_FLOETTE_BLUE_FLOWER (SPECIES_MISC_FORM_START + 70)
#define SPECIES_FLOETTE_WHITE_FLOWER (SPECIES_MISC_FORM_START + 71)
#define SPECIES_FLOETTE_ETERNAL_FLOWER (SPECIES_MISC_FORM_START + 72)

#define SPECIES_FLORGES_YELLOW_FLOWER (SPECIES_MISC_FORM_START + 73)
#define SPECIES_FLORGES_ORANGE_FLOWER (SPECIES_MISC_FORM_START + 74)
#define SPECIES_FLORGES_BLUE_FLOWER (SPECIES_MISC_FORM_START + 75)
#define SPECIES_FLORGES_WHITE_FLOWER (SPECIES_MISC_FORM_START + 76)

#define SPECIES_FURFROU_HEART (SPECIES_MISC_FORM_START + 77)
#define SPECIES_FURFROU_STAR (SPECIES_MISC_FORM_START + 78)
#define SPECIES_FURFROU_DIAMOND (SPECIES_MISC_FORM_START + 79)
#define SPECIES_FURFROU_DEBUTANTE (SPECIES_MISC_FORM_START + 80)
#define SPECIES_FURFROU_MATRON (SPECIES_MISC_FORM_START + 81)
#define SPECIES_FURFROU_DANDY (SPECIES_MISC_FORM_START + 82)
#define SPECIES_FURFROU_LA_REINE (SPECIES_MISC_FORM_START + 83)
#define SPECIES_FURFROU_KABUKI (SPECIES_MISC_FORM_START + 84)
#define SPECIES_FURFROU_PHARAOH (SPECIES_MISC_FORM_START + 85)

#define SPECIES_AEGISLASH_BLADE (SPECIES_MISC_FORM_START + 86)

#define SPECIES_PUMPKABOO_SMALL (SPECIES_MISC_FORM_START + 87)
#define SPECIES_PUMPKABOO_LARGE (SPECIES_MISC_FORM_START + 88)
#define SPECIES_PUMPKABOO_SUPER (SPECIES_MISC_FORM_START + 89)

#define SPECIES_GOURGEIST_SMALL (SPECIES_MISC_FORM_START + 90)
#define SPECIES_GOURGEIST_LARGE (SPECIES_MISC_FORM_START + 91)
#define SPECIES_GOURGEIST_SUPER (SPECIES_MISC_FORM_START + 92)

#define SPECIES_XERNEAS_ACTIVE (SPECIES_MISC_FORM_START + 93)

#define SPECIES_ZYGARDE_10 (SPECIES_MISC_FORM_START + 94)
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT (SPECIES_MISC_FORM_START + 95)
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT (SPECIES_MISC_FORM_START + 96)
#define SPECIES_ZYGARDE_10_COMPLETE (SPECIES_MISC_FORM_START + 97)
#define SPECIES_ZYGARDE_50_COMPLETE (SPECIES_MISC_FORM_START + 98)

#define SPECIES_HOOPA_UNBOUND (SPECIES_MISC_FORM_START + 99)

#define SPECIES_ORICORIO_POM_POM (SPECIES_MISC_FORM_START + 100)
#define SPECIES_ORICORIO_PAU (SPECIES_MISC_FORM_START + 101)
#define SPECIES_ORICORIO_SENSU (SPECIES_MISC_FORM_START + 102)

#define SPECIES_ROCKRUFF_OWN_TEMPO (SPECIES_MISC_FORM_START + 103)
#define SPECIES_LYCANROC_MIDNIGHT (SPECIES_MISC_FORM_START + 104)
#define SPECIES_LYCANROC_DUSK (SPECIES_MISC_FORM_START + 105)

#define SPECIES_WISHIWASHI_SCHOOL (SPECIES_MISC_FORM_START + 106)

#define SPECIES_MINIOR_METEOR_ORANGE (SPECIES_MISC_FORM_START + 107)
#define SPECIES_MINIOR_METEOR_YELLOW (SPECIES_MISC_FORM_START + 108)
#define SPECIES_MINIOR_METEOR_GREEN (SPECIES_MISC_FORM_START + 109)
#define SPECIES_MINIOR_METEOR_BLUE (SPECIES_MISC_FORM_START + 110)
#define SPECIES_MINIOR_METEOR_INDIGO (SPECIES_MISC_FORM_START + 111)
#define SPECIES_MINIOR_METEOR_VIOLET (SPECIES_MISC_FORM_START + 112)
#define SPECIES_MINIOR_CORE_RED (SPECIES_MISC_FORM_START + 113)
#define SPECIES_MINIOR_CORE_ORANGE (SPECIES_MISC_FORM_START + 114)
#define SPECIES_MINIOR_CORE_YELLOW (SPECIES_MISC_FORM_START + 115)
#define SPECIES_MINIOR_CORE_GREEN (SPECIES_MISC_FORM_START + 116)
#define SPECIES_MINIOR_CORE_BLUE (SPECIES_MISC_FORM_START + 117)
#define SPECIES_MINIOR_CORE_INDIGO (SPECIES_MISC_FORM_START + 118)
#define SPECIES_MINIOR_CORE_VIOLET (SPECIES_MISC_FORM_START + 119)

#define SPECIES_MIMIKYU_BUSTED (SPECIES_MISC_FORM_START + 120)

#define SPECIES_NECROZMA_DUSK_MANE (SPECIES_MISC_FORM_START + 121)
#define SPECIES_NECROZMA_DAWN_WINGS (SPECIES_MISC_FORM_START + 122)
#define SPECIES_NECROZMA_ULTRA_DUSK_MANE (SPECIES_MISC_FORM_START + 123)
#define SPECIES_NECROZMA_ULTRA_DAWN_WINGS (SPECIES_MISC_FORM_START + 124)

#define SPECIES_MAGEARNA_ORIGINAL (SPECIES_MISC_FORM_START + 125)

#define SPECIES_PIKACHU_PARTNER (SPECIES_MISC_FORM_START + 126)
#define SPECIES_EEVEE_PARTNER (SPECIES_MISC_FORM_START + 127)

#define SPECIES_CRAMORANT_GULPING (SPECIES_MISC_FORM_START + 128)
#define SPECIES_CRAMORANT_GORGING (SPECIES_MISC_FORM_START + 129)

#define SPECIES_TOXTRICITY_LOW_KEY (SPECIES_MISC_FORM_START + 130)

#define SPECIES_SINISTEA_ANTIQUE (SPECIES_MISC_FORM_START + 131)
#define SPECIES_POLTEAGEIST_ANTIQUE (SPECIES_MISC_FORM_START + 132)

#define SPECIES_ALCREMIE_BERRY_SWEET (SPECIES_MISC_FORM_START + 133)
#define SPECIES_ALCREMIE_LOVE_SWEET (SPECIES_MISC_FORM_START + 134)
#define SPECIES_ALCREMIE_STAR_SWEET (SPECIES_MISC_FORM_START + 135)
#define SPECIES_ALCREMIE_CLOVER_SWEET (SPECIES_MISC_FORM_START + 136)
#define SPECIES_ALCREMIE_FLOWER_SWEET (SPECIES_MISC_FORM_START + 137)
#define SPECIES_ALCREMIE_RIBBON_SWEET (SPECIES_MISC_FORM_START + 138)
#define SPECIES_ALCREMIE_FILLER_1 (SPECIES_MISC_FORM_START + 139)
#define SPECIES_ALCREMIE_FILLER_2 (SPECIES_MISC_FORM_START + 140)

#define SPECIES_EISCUE_NOICE_FACE (SPECIES_MISC_FORM_START + 141)
#define SPECIES_MORPEKO_HANGRY (SPECIES_MISC_FORM_START + 142)

#define SPECIES_ZACIAN_CROWNED (SPECIES_MISC_FORM_START + 143)
#define SPECIES_ZAMAZENTA_CROWNED (SPECIES_MISC_FORM_START + 144)

#define SPECIES_ETERNATUS_ETERNAMAX (SPECIES_MISC_FORM_START + 145)
#define SPECIES_URSHIFU_RAPID_STRIKE (SPECIES_MISC_FORM_START + 146)
#define SPECIES_ZARUDE_DADA (SPECIES_MISC_FORM_START + 147)

#define SPECIES_CALYREX_ICE_RIDER (SPECIES_MISC_FORM_START + 148)
#define SPECIES_CALYREX_SHADOW_RIDER (SPECIES_MISC_FORM_START + 149)

#define SPECIES_ENAMORUS_THERIAN (SPECIES_MISC_FORM_START + 150)

#define MAX_MISC_FORM_NUM (SPECIES_ENAMORUS_THERIAN)

//hisuian
#define SPECIES_HISUIAN_REGIONAL_START (MAX_MISC_FORM_NUM + 1) // 1326

#define SPECIES_GROWLITHE_HISUIAN (SPECIES_HISUIAN_REGIONAL_START)
#define SPECIES_ARCANINE_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 1)
#define SPECIES_VOLTORB_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 2)
#define SPECIES_ELECTRODE_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 3)
#define SPECIES_TYPHLOSION_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 4)
#define SPECIES_QWILFISH_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 5)
#define SPECIES_SNEASEL_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 6)
#define SPECIES_SAMUROTT_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 7)
#define SPECIES_LILLIGANT_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 8)
#define SPECIES_ZORUA_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 9)
#define SPECIES_ZOROARK_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 10)
#define SPECIES_BRAVIARY_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 11)
#define SPECIES_SLIGGOO_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 12)
#define SPECIES_GOODRA_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 13)
#define SPECIES_AVALUGG_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 14)
#define SPECIES_DECIDUEYE_HISUIAN (SPECIES_HISUIAN_REGIONAL_START + 15)

//nobles
#define SPECIES_KLEAVOR_LORD (SPECIES_HISUIAN_REGIONAL_START + 16)
#define SPECIES_LILLIGANT_LADY (SPECIES_HISUIAN_REGIONAL_START + 17)
#define SPECIES_ARCANINE_LORD (SPECIES_HISUIAN_REGIONAL_START + 18)
#define SPECIES_ELECTRODE_LORD (SPECIES_HISUIAN_REGIONAL_START + 19)
#define SPECIES_AVALUGG_LORD (SPECIES_HISUIAN_REGIONAL_START + 20)

#define MAX_HISUIAN_REGIONAL_NUM (SPECIES_AVALUGG_LORD)

#define SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START (MAX_HISUIAN_REGIONAL_NUM + 1) // 1347

#define SPECIES_UNFEZANT_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START)
#define SPECIES_FRILLISH_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 1)
#define SPECIES_JELLICENT_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 2)
#define SPECIES_PYROAR_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 3)
#define SPECIES_MEOWSTIC_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 4)
#define SPECIES_INDEEDEE_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 5)
#define SPECIES_BASCULEGION_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 6)

#define MAX_SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_NUM (SPECIES_BASCULEGION_FEMALE)

#define SPECIES_PALDEAN_FORMS_START (MAX_SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_NUM + 1) // 1354

#define SPECIES_MAUSHOLD_FAMILY_OF_THREE (SPECIES_PALDEAN_FORMS_START)
#define SPECIES_SQUAWKABILLY_BLUE_PLUMAGE (SPECIES_PALDEAN_FORMS_START + 1)
#define SPECIES_SQUAWKABILLY_YELLOW_PLUMAGE (SPECIES_PALDEAN_FORMS_START + 2)
#define SPECIES_SQUAWKABILLY_WHITE_PLUMAGE (SPECIES_PALDEAN_FORMS_START + 3)
#define SPECIES_PALAFIN_HERO (SPECIES_PALDEAN_FORMS_START + 4)
#define SPECIES_TATSUGIRI_DROOPY (SPECIES_PALDEAN_FORMS_START + 5)
#define SPECIES_TATSUGIRI_STRETCHY (SPECIES_PALDEAN_FORMS_START + 6)
#define SPECIES_DUDUNSPARCE_THREE_SEGMENT (SPECIES_PALDEAN_FORMS_START + 7)
#define SPECIES_GIMMIGHOUL_ROAMING (SPECIES_PALDEAN_FORMS_START + 8)
#define SPECIES_WOOPER_PALDEAN (SPECIES_PALDEAN_FORMS_START + 9)
#define SPECIES_TAUROS_COMBAT (SPECIES_PALDEAN_FORMS_START + 10)
#define SPECIES_TAUROS_BLAZE (SPECIES_PALDEAN_FORMS_START + 11)
#define SPECIES_TAUROS_AQUA (SPECIES_PALDEAN_FORMS_START + 12)
#define SPECIES_OINKOLOGNE_FEMALE (SPECIES_PALDEAN_FORMS_START + 13)
#define SPECIES_REVAVROOM_SEGIN (SPECIES_PALDEAN_FORMS_START + 14)
#define SPECIES_REVAVROOM_SCHEDAR (SPECIES_PALDEAN_FORMS_START + 15)
#define SPECIES_REVAVROOM_NAVI (SPECIES_PALDEAN_FORMS_START + 16)
#define SPECIES_REVAVROOM_RUCHBAH (SPECIES_PALDEAN_FORMS_START + 17)
#define SPECIES_REVAVROOM_CAPH (SPECIES_PALDEAN_FORMS_START + 18)
#define SPECIES_KORAIDON_LIMITED_BUILD (SPECIES_PALDEAN_FORMS_START + 19)
#define SPECIES_KORAIDON_SPRINTING_BUILD (SPECIES_PALDEAN_FORMS_START + 20)
#define SPECIES_KORAIDON_SWIMMING_BUILD (SPECIES_PALDEAN_FORMS_START + 21)
#define SPECIES_KORAIDON_GLIDING_BUILD (SPECIES_PALDEAN_FORMS_START + 22)
#define SPECIES_MIRAIDON_LOW_POWER_MODE (SPECIES_PALDEAN_FORMS_START + 23)
#define SPECIES_MIRAIDON_DRIVE_MODE (SPECIES_PALDEAN_FORMS_START + 24)
#define SPECIES_MIRAIDON_AQUATIC_MODE (SPECIES_PALDEAN_FORMS_START + 25)
#define SPECIES_MIRAIDON_GLIDE_MODE (SPECIES_PALDEAN_FORMS_START + 26)
#define SPECIES_POLTCHAGEIST_MASTERPIECE (SPECIES_PALDEAN_FORMS_START + 27)
#define SPECIES_SINISTCHA_MASTERPIECE (SPECIES_PALDEAN_FORMS_START + 28)
#define SPECIES_OGERPON_WELLSPRING_MASK (SPECIES_PALDEAN_FORMS_START + 29)
#define SPECIES_OGERPON_HEARTHFLAME_MASK (SPECIES_PALDEAN_FORMS_START + 30)
#define SPECIES_OGERPON_CORNERSTONE_MASK (SPECIES_PALDEAN_FORMS_START + 31)
#define SPECIES_OGERPON_TEAL_MASK_TERASTAL (SPECIES_PALDEAN_FORMS_START + 32)
#define SPECIES_OGERPON_WELLSPRING_MASK_TERASTAL (SPECIES_PALDEAN_FORMS_START + 33)
#define SPECIES_OGERPON_HEARTHFLAME_MASK_TERASTAL (SPECIES_PALDEAN_FORMS_START + 34)
#define SPECIES_OGERPON_CORNERSTONE_MASK_TERASTAL (SPECIES_PALDEAN_FORMS_START + 35)
#define SPECIES_URSALUNA_BLOODMOON (SPECIES_PALDEAN_FORMS_START + 36)
#define SPECIES_TERAPAGOS_TERASTAL (SPECIES_PALDEAN_FORMS_START + 37)
#define SPECIES_TERAPAGOS_STELLAR (SPECIES_PALDEAN_FORMS_START + 38)

#define MAX_SPECIES_INCLUDING_FORMS (SPECIES_TERAPAGOS_STELLAR)  // 1393


#endif
