#ifndef CONSTANTS_WEATHER_NUMBERS_H
#define CONSTANTS_WEATHER_NUMBERS_H

//#define WEATHER_SYS_SUNNY            (0)
//#define WEATHER_SYS_CLOUDY           (1)
//#define WEATHER_SYS_RAIN             (2)
//#define WEATHER_SYS_HEAVY_RAIN       (3)
//#define WEATHER_SYS_THUNDER          (4)
//#define WEATHER_SYS_SNOW             (5)
//#define WEATHER_SYS_SNOWSTORM        (6)
//#define WEATHER_SYS_BLIZZARD         (7)
//#define WEATHER_SYS_FOG              (8)
//#define WEATHER_SYS_VOLCANIC_ASH     (9)
//#define WEATHER_SYS_SANDSTORM       (10)
//#define WEATHER_SYS_DIAMOND_DUST    (11)
//#define WEATHER_SYS_xC              (12)
//#define WEATHER_SYS_xD              (13)
//#define WEATHER_SYS_MIST1           (14)
//#define WEATHER_SYS_MIST2           (15)
//#define WEATHER_SYS_FLASH           (16)
//#define WEATHER_SYS_SPARK_EFF       (17)
//#define WEATHER_SYS_FOGS            (18)
//#define WEATHER_SYS_FOGM            (19)
//#define WEATHER_SYS_RAINBOW         (20)
//#define WEATHER_SYS_SNOW_STORM_BG   (21)
//#define WEATHER_SYS_STORM           (22)

#define WEATHER_SYS_NORMAL (0)
#define WEATHER_SYS_RAIN (1)
#define WEATHER_SYS_HEAVY_RAIN (2)
#define WEATHER_SYS_THUNDER (3)
#define WEATHER_SYS_STORM (4)
#define WEATHER_SYS_SNOW (5)
#define WEATHER_SYS_SNOWSTORM (6)
#define WEATHER_SYS_SANDSTORM (7)
#define WEATHER_SYS_DIAMOND_DUST (8)
#define WEATHER_SYS_MIST1 (9)
#define WEATHER_SYS_MIST2 (10)
#define WEATHER_SYS_FLASH (11)
#define WEATHER_SYS_FLASH_2 (12)
#define WEATHER_SYS_LOW_LIGHT (13)


#define WEATHER_SYS_x1000         (1000)
#define WEATHER_SYS_HIGH_SUN      (1001)
#define WEATHER_SYS_TRICK_ROOM    (1002)

#endif
