tools\blz -d filesys\overlay\overlay_0000.bin
tools\blz -d filesys\overlay\overlay_0001.bin
tools\blz -d filesys\overlay\overlay_0002.bin
tools\blz -d filesys\overlay\overlay_0003.bin
tools\blz -d filesys\overlay\overlay_0004.bin
tools\blz -d filesys\overlay\overlay_0005.bin
tools\blz -d filesys\overlay\overlay_0006.bin
tools\blz -d filesys\overlay\overlay_0007.bin
tools\blz -d filesys\overlay\overlay_0008.bin
tools\blz -d filesys\overlay\overlay_0009.bin
tools\blz -d filesys\overlay\overlay_0010.bin
tools\blz -d filesys\overlay\overlay_0011.bin
tools\blz -d filesys\overlay\overlay_0012.bin
tools\blz -d filesys\overlay\overlay_0013.bin
tools\blz -d filesys\overlay\overlay_0014.bin
tools\blz -d filesys\overlay\overlay_0015.bin
tools\blz -d filesys\overlay\overlay_0016.bin
tools\blz -d filesys\overlay\overlay_0017.bin
tools\blz -d filesys\overlay\overlay_0018.bin
tools\blz -d filesys\overlay\overlay_0019.bin
tools\blz -d filesys\overlay\overlay_0020.bin
tools\blz -d filesys\overlay\overlay_0021.bin
tools\blz -d filesys\overlay\overlay_0022.bin
tools\blz -d filesys\overlay\overlay_0023.bin
tools\blz -d filesys\overlay\overlay_0024.bin
tools\blz -d filesys\overlay\overlay_0025.bin
tools\blz -d filesys\overlay\overlay_0026.bin
tools\blz -d filesys\overlay\overlay_0027.bin
tools\blz -d filesys\overlay\overlay_0028.bin
tools\blz -d filesys\overlay\overlay_0029.bin
tools\blz -d filesys\overlay\overlay_0030.bin
tools\blz -d filesys\overlay\overlay_0031.bin
tools\blz -d filesys\overlay\overlay_0032.bin
tools\blz -d filesys\overlay\overlay_0033.bin
tools\blz -d filesys\overlay\overlay_0034.bin
::tools\blz -d filesys\overlay\overlay_0035.bin
tools\blz -d filesys\overlay\overlay_0036.bin
tools\blz -d filesys\overlay\overlay_0037.bin
tools\blz -d filesys\overlay\overlay_0038.bin
tools\blz -d filesys\overlay\overlay_0039.bin
tools\blz -d filesys\overlay\overlay_0040.bin
tools\blz -d filesys\overlay\overlay_0041.bin
tools\blz -d filesys\overlay\overlay_0042.bin
tools\blz -d filesys\overlay\overlay_0043.bin
tools\blz -d filesys\overlay\overlay_0044.bin
tools\blz -d filesys\overlay\overlay_0045.bin
tools\blz -d filesys\overlay\overlay_0046.bin
tools\blz -d filesys\overlay\overlay_0047.bin
tools\blz -d filesys\overlay\overlay_0048.bin
tools\blz -d filesys\overlay\overlay_0049.bin
tools\blz -d filesys\overlay\overlay_0050.bin
tools\blz -d filesys\overlay\overlay_0051.bin
tools\blz -d filesys\overlay\overlay_0052.bin
tools\blz -d filesys\overlay\overlay_0053.bin
tools\blz -d filesys\overlay\overlay_0054.bin
tools\blz -d filesys\overlay\overlay_0055.bin
tools\blz -d filesys\overlay\overlay_0056.bin
tools\blz -d filesys\overlay\overlay_0057.bin
tools\blz -d filesys\overlay\overlay_0058.bin
tools\blz -d filesys\overlay\overlay_0059.bin
tools\blz -d filesys\overlay\overlay_0060.bin
tools\blz -d filesys\overlay\overlay_0061.bin
tools\blz -d filesys\overlay\overlay_0062.bin
tools\blz -d filesys\overlay\overlay_0063.bin
tools\blz -d filesys\overlay\overlay_0064.bin
tools\blz -d filesys\overlay\overlay_0065.bin
tools\blz -d filesys\overlay\overlay_0066.bin
tools\blz -d filesys\overlay\overlay_0067.bin
tools\blz -d filesys\overlay\overlay_0068.bin
tools\blz -d filesys\overlay\overlay_0069.bin
tools\blz -d filesys\overlay\overlay_0070.bin
tools\blz -d filesys\overlay\overlay_0071.bin
tools\blz -d filesys\overlay\overlay_0072.bin
tools\blz -d filesys\overlay\overlay_0073.bin
tools\blz -d filesys\overlay\overlay_0074.bin
tools\blz -d filesys\overlay\overlay_0075.bin
tools\blz -d filesys\overlay\overlay_0076.bin
tools\blz -d filesys\overlay\overlay_0077.bin
tools\blz -d filesys\overlay\overlay_0078.bin
tools\blz -d filesys\overlay\overlay_0079.bin
tools\blz -d filesys\overlay\overlay_0080.bin
tools\blz -d filesys\overlay\overlay_0081.bin
tools\blz -d filesys\overlay\overlay_0082.bin
tools\blz -d filesys\overlay\overlay_0083.bin
tools\blz -d filesys\overlay\overlay_0084.bin
tools\blz -d filesys\overlay\overlay_0085.bin
tools\blz -d filesys\overlay\overlay_0086.bin
tools\blz -d filesys\overlay\overlay_0087.bin
tools\blz -d filesys\overlay\overlay_0088.bin
tools\blz -d filesys\overlay\overlay_0089.bin
tools\blz -d filesys\overlay\overlay_0090.bin
tools\blz -d filesys\overlay\overlay_0091.bin
tools\blz -d filesys\overlay\overlay_0092.bin
tools\blz -d filesys\overlay\overlay_0093.bin
tools\blz -d filesys\overlay\overlay_0094.bin
tools\blz -d filesys\overlay\overlay_0095.bin
tools\blz -d filesys\overlay\overlay_0096.bin
tools\blz -d filesys\overlay\overlay_0097.bin
tools\blz -d filesys\overlay\overlay_0098.bin
tools\blz -d filesys\overlay\overlay_0099.bin
tools\blz -d filesys\overlay\overlay_0100.bin
tools\blz -d filesys\overlay\overlay_0101.bin
tools\blz -d filesys\overlay\overlay_0102.bin
tools\blz -d filesys\overlay\overlay_0103.bin
tools\blz -d filesys\overlay\overlay_0104.bin
tools\blz -d filesys\overlay\overlay_0105.bin
tools\blz -d filesys\overlay\overlay_0106.bin
tools\blz -d filesys\overlay\overlay_0107.bin
tools\blz -d filesys\overlay\overlay_0108.bin
tools\blz -d filesys\overlay\overlay_0109.bin
tools\blz -d filesys\overlay\overlay_0110.bin
tools\blz -d filesys\overlay\overlay_0111.bin
tools\blz -d filesys\overlay\overlay_0112.bin
tools\blz -d filesys\overlay\overlay_0113.bin
tools\blz -d filesys\overlay\overlay_0114.bin
tools\blz -d filesys\overlay\overlay_0115.bin
tools\blz -d filesys\overlay\overlay_0116.bin
tools\blz -d filesys\overlay\overlay_0117.bin
tools\blz -d filesys\overlay\overlay_0118.bin
tools\blz -d filesys\overlay\overlay_0119.bin
tools\blz -d filesys\overlay\overlay_0120.bin
tools\blz -d filesys\overlay\overlay_0121.bin
tools\blz -d filesys\overlay\overlay_0122.bin
tools\blz -d filesys\overlay\overlay_0123.bin
::tools\blz -d filesys\overlay\overlay_0124.bin
tools\blz -d filesys\overlay\overlay_0125.bin
tools\blz -d filesys\overlay\overlay_0126.bin
tools\blz -d filesys\overlay\overlay_0127.bin
tools\blz -d filesys\overlay\overlay_0128.bin
tools\arm9dec "filesys\arm9.bin" "arm9.bin"
for %%F in ("arm9.bin") do @if %%~zF==0 (del /f "%%F") else (copy arm9.bin filesys\arm9.bin & del /f "%%F")