.ifndef SCR_SEQ_D25R0101_H_
.definelabel SCR_SEQ_D25R0101_H_, 0

.equ _EV_scr_seq_D25R0101_000, 0

.equ obj_D25R0101_mount_2, 0
.equ obj_D25R0101_mount_2_2, 1
.equ obj_D25R0101_fire, 2
.equ obj_D25R0101_fire_2, 3
.equ obj_D25R0101_mania, 4
.equ obj_D25R0101_monstarball, 5
.equ obj_D25R0101_monstarball_2, 6
.equ obj_D25R0101_monstarball_3, 7
.equ obj_D25R0101_monstarball_4, 8

.endif //SCR_SEQ_D25R0101_H_
