.ifndef SCR_SEQ_T11_H_
.definelabel SCR_SEQ_T11_H_, 0

.equ _EV_scr_seq_T11_000, 0
.equ _EV_scr_seq_T11_001, 1
.equ _EV_scr_seq_T11_002, 2
.equ _EV_scr_seq_T11_003, 3
.equ _EV_scr_seq_T11_004, 4
.equ _EV_scr_seq_T11_005, 5
.equ _EV_scr_seq_T11_006, 6
.equ _EV_scr_seq_T11_007, 7
.equ _EV_scr_seq_T11_008, 8
.equ _EV_scr_seq_T11_009, 9
.equ _EV_scr_seq_T11_010, 10
.equ _EV_scr_seq_T11_011, 11
.equ _EV_scr_seq_T11_012, 12
.equ _EV_scr_seq_T11_013, 13
.equ _EV_scr_seq_T11_014, 14
.equ _EV_scr_seq_T11_015, 15
.equ _EV_scr_seq_T11_016, 16

.equ obj_T11_gsboy1, 0
.equ obj_T11_gsgirl2, 1
.equ obj_T11_gswoman2, 2
.equ obj_T11_gsbigman, 3
.equ obj_T11_gsman1, 4
.equ obj_T11_gsboy2, 5
.equ obj_T11_gswoman1, 6
.equ obj_T11_gsmiddleman1, 7
.equ obj_T11_gsmiddleman1_2, 8
.equ obj_T11_gsmiddleman1_3, 9

.endif //SCR_SEQ_T11_H_
