.ifndef SCR_SEQ_T21_H_
.definelabel SCR_SEQ_T21_H_, 0

.equ _EV_scr_seq_T21_000, 0
.equ _EV_scr_seq_T21_001, 1
.equ _EV_scr_seq_T21_002, 2
.equ _EV_scr_seq_T21_003, 3
.equ _EV_scr_seq_T21_004, 4
.equ _EV_scr_seq_T21_005, 5
.equ _EV_scr_seq_T21_006, 6
.equ _EV_scr_seq_T21_007, 7
.equ _EV_scr_seq_T21_008, 8
.equ _EV_scr_seq_T21_009, 9
.equ _EV_scr_seq_T21_010, 10

.equ obj_T21_gsoldman1, 0
.equ obj_T21_gsboy1, 1
.equ obj_T21_gswoman1, 2
.equ obj_T21_gsbigman, 3
.equ obj_T21_gsrivel, 4
.equ obj_T21_gsmiddleman1, 5

.endif //SCR_SEQ_T21_H_
