.ifndef SCR_SEQ_T06_H_
.definelabel SCR_SEQ_T06_H_, 0

.equ _EV_scr_seq_T06_000, 0
.equ _EV_scr_seq_T06_001, 1
.equ _EV_scr_seq_T06_002, 2
.equ _EV_scr_seq_T06_003, 3
.equ _EV_scr_seq_T06_004, 4
.equ _EV_scr_seq_T06_005, 5
.equ _EV_scr_seq_T06_006, 6
.equ _EV_scr_seq_T06_007, 7
.equ _EV_scr_seq_T06_008, 8
.equ _EV_scr_seq_T06_009, 9
.equ _EV_scr_seq_T06_010, 10
.equ _EV_scr_seq_T06_011, 11
.equ _EV_scr_seq_T06_012, 12
.equ _EV_scr_seq_T06_013, 13

.equ obj_T06_gsoldman1, 0
.equ obj_T06_gsmiddleman1, 1
.equ obj_T06_gswoman1, 2
.equ obj_T06_gsman1, 3
.equ obj_T06_follower_mon_static_machop, 4
.equ obj_T06_breakrock, 5
.equ obj_T06_breakrock_2, 6
.equ obj_T06_breakrock_3, 7
.equ obj_T06_breakrock_4, 8
.equ obj_T06_breakrock_5, 9
.equ obj_T06_breakrock_6, 10
.equ obj_T06_tree, 11
.equ obj_T06_monstarball, 12
.equ obj_T06_monstarball_2, 13
.equ obj_T06_gsmiddleman1_2, 14
.equ obj_T06_follower_mon_static_suicune, 15
.equ obj_T06_minaki, 16
.equ obj_T06_minaki_2, 17
.equ obj_T06_daigo, 18

.endif //SCR_SEQ_T06_H_
