.ifndef SCR_SEQ_D47_H_
.definelabel SCR_SEQ_D47_H_, 0

.equ _EV_scr_seq_D47_000, 0
.equ _EV_scr_seq_D47_001, 1
.equ _EV_scr_seq_D47_002, 2
.equ _EV_scr_seq_D47_003, 3
.equ _EV_scr_seq_D47_004, 4
.equ _EV_scr_seq_D47_005, 5
.equ _EV_scr_seq_D47_006, 6
.equ _EV_scr_seq_D47_007, 7
.equ _EV_scr_seq_D47_008, 8
.equ _EV_scr_seq_D47_009, 9
.equ _EV_scr_seq_D47_010, 10
.equ _EV_scr_seq_D47_011, 11
.equ _EV_scr_seq_D47_012, 12
.equ _EV_scr_seq_D47_013, 13
.equ _EV_scr_seq_D47_014, 14
.equ _EV_scr_seq_D47_015, 15
.equ _EV_scr_seq_D47_016, 16

.equ obj_D47_gsman1, 0
.equ obj_D47_gsgentleman, 1
.equ obj_D47_follower_mon_static_jigglypuff, 2
.equ obj_D47_follower_mon_static_kangaskhan, 3
.equ obj_D47_middlewoman1_2, 4
.equ obj_D47_gsbabyboy1, 5
.equ obj_D47_gsoldman1, 6
.equ obj_D47_gswoman1, 7
.equ obj_D47_gswoman2, 8
.equ obj_D47_follower_mon_static_butterfree, 9
.equ obj_D47_follower_mon_static_slowpoke, 10
.equ obj_D47_gsbabygirl1, 11
.equ obj_D47_gsmiddleman1, 12
.equ obj_D47_workman, 13
.equ obj_D47_workman_2, 14

.endif //SCR_SEQ_D47_H_
