.ifndef SCR_SEQ_T07_H_
.definelabel SCR_SEQ_T07_H_, 0

.equ _EV_scr_seq_T07_000, 0
.equ _EV_scr_seq_T07_001, 1
.equ _EV_scr_seq_T07_002, 2
.equ _EV_scr_seq_T07_003, 3
.equ _EV_scr_seq_T07_004, 4
.equ _EV_scr_seq_T07_005, 5
.equ _EV_scr_seq_T07_006, 6
.equ _EV_scr_seq_T07_007, 7
.equ _EV_scr_seq_T07_008, 8
.equ _EV_scr_seq_T07_009, 9
.equ _EV_scr_seq_T07_010, 10
.equ _EV_scr_seq_T07_011, 11
.equ _EV_scr_seq_T07_012, 12
.equ _EV_scr_seq_T07_013, 13
.equ _EV_scr_seq_T07_014, 14
.equ _EV_scr_seq_T07_015, 15
.equ _EV_scr_seq_T07_016, 16
.equ _EV_scr_seq_T07_017, 17
.equ _EV_scr_seq_T07_018, 18

.equ obj_T07_gsbigman, 0
.equ obj_T07_follower_mon_static_poliwrath, 1
.equ obj_T07_gsboy1, 2
.equ obj_T07_gswoman2, 3
.equ obj_T07_gsgirl1, 4
.equ obj_T07_gswoman1, 5
.equ obj_T07_gsboy2, 6
.equ obj_T07_gsoldman1, 7
.equ obj_T07_gsoldman1_2, 8
.equ obj_T07_gsleader12, 9
.equ obj_T07_gsleader6, 10
.equ obj_T07_tree, 11
.equ obj_T07_monstarball, 12
.equ obj_T07_gsmiddleman1, 13

.endif //SCR_SEQ_T07_H_
