.ifndef SCR_SEQ_R15_H_
.definelabel SCR_SEQ_R15_H_, 0

.equ _EV_scr_seq_R15_000, 0

.equ obj_R15_gsboy1, 0
.equ obj_R15_gsboy1_2, 1
.equ obj_R15_middlewoman1_2, 2
.equ obj_R15_gsbabygirl1, 3
.equ obj_R15_gsbabygirl1_2, 4
.equ obj_R15_middlewoman1_2_2, 5
.equ obj_R15_gsmiddleman1, 6
.equ obj_R15_middlewoman1_2_3, 7
.equ obj_R15_gsboy1_3, 8
.equ obj_R15_gsboy1_4, 9
.equ obj_R15_tree, 10
.equ obj_R15_monstarball, 11
.equ obj_R15_monstarball_2, 12

.endif //SCR_SEQ_R15_H_
