.ifndef SCR_SEQ_D03R0103_H_
.definelabel SCR_SEQ_D03R0103_H_, 0

.equ _EV_scr_seq_D03R0103_000, 0
.equ _EV_scr_seq_D03R0103_001, 1

.equ obj_D03R0103_monstarball, 0
.equ obj_D03R0103_monstarball_2, 1
.equ obj_D03R0103_monstarball_3, 2
.equ obj_D03R0103_monstarball_4, 3
.equ obj_D03R0103_monstarball_5, 4
.equ obj_D03R0103_breakrock, 5
.equ obj_D03R0103_breakrock_2, 6
.equ obj_D03R0103_breakrock_3, 7
.equ obj_D03R0103_breakrock_4, 8
.equ obj_D03R0103_breakrock_5, 9
.equ obj_D03R0103_breakrock_6, 10
.equ obj_D03R0103_breakrock_7, 11
.equ obj_D03R0103_breakrock_8, 12
.equ obj_D03R0103_breakrock_9, 13
.equ obj_D03R0103_follower_mon_static_mewtwo, 14
.equ obj_D03R0103_breakrock_10, 15

.endif //SCR_SEQ_D03R0103_H_
