.ifndef SCR_SEQ_R09_H_
.definelabel SCR_SEQ_R09_H_, 0

.equ _EV_scr_seq_R09_000, 0

.equ obj_R09_campboy_2, 0
.equ obj_R09_picnicgirl_2, 1
.equ obj_R09_campboy_2_2, 2
.equ obj_R09_mount_2, 3
.equ obj_R09_mount_2_2, 4
.equ obj_R09_picnicgirl_2_2, 5
.equ obj_R09_tree, 6
.equ obj_R09_tree_2, 7
.equ obj_R09_tree_3, 8
.equ obj_R09_tree_4, 9
.equ obj_R09_tree_5, 10
.equ obj_R09_tree_6, 11
.equ obj_R09_tree_7, 12
.equ obj_R09_monstarball, 13
.equ obj_R09_monstarball_2, 14
.equ obj_R09_monstarball_3, 15
.equ obj_R09_monstarball_4, 16

.endif //SCR_SEQ_R09_H_
