#ifndef CONSTANTS_ITEM_BALL_H
#define CONSTANTS_ITEM_BALL_H

#include "../../config.h"

#define ITEM_BALL_START 1

#define ITEM_MASTER_BALL     (ITEM_BALL_START)
#define ITEM_ULTRA_BALL      (ITEM_BALL_START + 1)
#define ITEM_GREAT_BALL      (ITEM_BALL_START + 2)
#define ITEM_POKE_BALL       (ITEM_BALL_START + 3)
#define ITEM_SAFARI_BALL     (ITEM_BALL_START + 4)
#define ITEM_NET_BALL        (ITEM_BALL_START + 5)
#define ITEM_DIVE_BALL       (ITEM_BALL_START + 6)
#define ITEM_NEST_BALL       (ITEM_BALL_START + 7)
#define ITEM_REPEAT_BALL     (ITEM_BALL_START + 8)
#define ITEM_TIMER_BALL      (ITEM_BALL_START + 9)
#define ITEM_LUXURY_BALL     (ITEM_BALL_START + 10)
#define ITEM_PREMIER_BALL    (ITEM_BALL_START + 11)
#define ITEM_DUSK_BALL       (ITEM_BALL_START + 12)
#define ITEM_HEAL_BALL       (ITEM_BALL_START + 13)
#define ITEM_QUICK_BALL      (ITEM_BALL_START + 14)
#define ITEM_CHERISH_BALL    (ITEM_BALL_START + 15)
#define ITEM_FAST_BALL       (ITEM_BALL_START + 491)
#define ITEM_LEVEL_BALL      (ITEM_BALL_START + 492)
#define ITEM_LURE_BALL       (ITEM_BALL_START + 493)
#define ITEM_HEAVY_BALL      (ITEM_BALL_START + 494)
#define ITEM_LOVE_BALL       (ITEM_BALL_START + 495)
#define ITEM_FRIEND_BALL     (ITEM_BALL_START + 496)
#define ITEM_MOON_BALL       (ITEM_BALL_START + 497)
#define ITEM_SPORT_BALL      (ITEM_BALL_START + 498)
#define ITEM_PARK_BALL       (ITEM_BALL_START + 499)

#define ITEM_BALL_END        ITEM_CHERISH_BALL
#define IS_ITEM_BALL(item) ((item >= ITEM_BALL_START && item <= ITEM_BALL_END) || (item >= ITEM_FAST_BALL && item <= ITEM_PARK_BALL))
#define NUM_BALLS ((ITEM_BALL_END - ITEM_BALL_START) + (ITEM_FAST_BALL - ITEM_PARK_BALL) + 1)

#endif