#ifndef CONNSTANTS_ITEM_FEATHER_H
#define CONNSTANTS_ITEM_FEATHER_H

#include "../../config.h"

#define ITEM_FEATHER_START      731

#define ITEM_HEALTH_FEATHER     (ITEM_FEATHER_START + 0)
#define ITEM_MUSCLE_FEATHER     (ITEM_FEATHER_START + 1)
#define ITEM_RESIST_FEATHER     (ITEM_FEATHER_START + 2)
#define ITEM_GENIUS_FEATHER     (ITEM_FEATHER_START + 3)
#define ITEM_CLEVER_FEATHER     (ITEM_FEATHER_START + 4)
#define ITEM_SWIFT_FEATHER      (ITEM_FEATHER_START + 5)
#define ITEM_PRETTY_FEATHER     (ITEM_FEATHER_START + 6)

#define ITEM_FEATHER_END        ITEM_PRETTY_FEATHER
#define IS_ITEM_FEATHER(item) (item >= ITEM_FEATHER_START && item <= ITEM_FEATHER_END)
#define NUM_FEATHERS (ITEM_FEATHER_END - ITEM_FEATHER_START + 1)

#endif