#ifndef CONSTANTS_ITEM_FOSSIL_H
#define CONSTANTS_ITEM_FOSSIL_H

#include "../../config.h"

#define ITEM_FOSSIL_START    99

#define ITEM_ROOT_FOSSIL     (ITEM_FOSSIL_START)
#define ITEM_CLAW_FOSSIL     (ITEM_FOSSIL_START + 1)
#define ITEM_HELIX_FOSSIL    (ITEM_FOSSIL_START + 2)
#define ITEM_DOME_FOSSIL     (ITEM_FOSSIL_START + 3)
#define ITEM_OLD_AMBER       (ITEM_FOSSIL_START + 4)
#define ITEM_ARMOR_FOSSIL    (ITEM_FOSSIL_START + 5)
#define ITEM_SKULL_FOSSIL    (ITEM_FOSSIL_START + 6)
#define ITEM_COVER_FOSSIL    (ITEM_FOSSIL_START + 576)
#define ITEM_PLUME_FOSSIL    (ITEM_FOSSIL_START + 577)
#define ITEM_JAW_FOSSIL      (ITEM_FOSSIL_START + 578)
#define ITEM_SAIL_FOSSIL     (ITEM_FOSSIL_START + 579)

#define ITEM_FOSSIL_END      ITEM_SKULL_FOSSIL
#define IS_ITEM_FOSSIL(item) ((item >= ITEM_FOSSIL_START && item <= ITEM_FOSSIL_END) || (item >= ITEM_COVER_FOSSIL && item <= ITEM_SAIL_FOSSIL))
#define NUM_FOSSILS ((ITEM_FOSSIL_END - ITEM_FOSSIL_START) + (ITEM_SAIL_FOSSIL - ITEM_COVER_FOSSIL) + 1)

#endif