#ifndef CONSTANTS_ITEM_GENESECT_DRIVE_H
#define CONSTANTS_ITEM_GENESECT_DRIVE_H

#include "../../config.h"

#define ITEM_GENESECT_DRIVE_START (ITEM_PIXIE_PLATE + 87)

#define ITEM_BURN_DRIVE         (ITEM_GENESECT_DRIVE_START)
#define ITEM_CHILL_DRIVE        (ITEM_GENESECT_DRIVE_START + 1)
#define ITEM_DOUSE_DRIVE        (ITEM_GENESECT_DRIVE_START + 2)
#define ITEM_SHOCK_DRIVE        (ITEM_GENESECT_DRIVE_START + 3)

#define ITEM_GENESECT_DRIVE_END ITEM_SHOCK_DRIVE
#define IS_ITEM_GENESECT_DRIVE(item) (item >= ITEM_GENESECT_DRIVE_START && item <= ITEM_GENESECT_DRIVE_END)
#define NUM_GENESECT_DRIVES (ITEM_GENESECT_DRIVE_END - ITEM_GENESECT_DRIVE_START + 1)

#endif

