#ifndef CONSTANTS_ITEM_INCENSE_H
#define CONSTANTS_ITEM_INCENSE_H

#include "../../config.h"

#define ITEM_INCENSE_START    314

#define ITEM_ODD_INCENSE     (ITEM_INCENSE_START)
#define ITEM_ROCK_INCENSE    (ITEM_INCENSE_START + 1)
#define ITEM_FULL_INCENSE    (ITEM_INCENSE_START + 2)
#define ITEM_WAVE_INCENSE    (ITEM_INCENSE_START + 3)
#define ITEM_ROSE_INCENSE    (ITEM_INCENSE_START + 4)
#define ITEM_LUCK_INCENSE    (ITEM_INCENSE_START + 5)
#define ITEM_PURE_INCENSE    (ITEM_INCENSE_START + 6)

#define ITEM_INCENSE_END      ITEM_PURE_INCENSE
#define IS_ITEM_INCENSE(item) ((item >= ITEM_INCENSE_START && item <= ITEM_INCENSE_END))
#define NUM_INCENSES (ITEM_INCENSE_END - ITEM_INCENSE_START + 1)

#endif