#ifndef CONSTANTS_ITEM_MEGA_STONE_H
#define CONSTANTS_ITEM_MEGA_STONE_H

#include "../../config.h"

#define ITEM_MEGA_STONE_START 537

#define ITEM_VENUSAURITE      (ITEM_MEGA_STONE_START)
#define ITEM_CHARIZARDITE_X   (ITEM_MEGA_STONE_START + 1)
#define ITEM_CHARIZARDITE_Y   (ITEM_MEGA_STONE_START + 2)
#define ITEM_BLASTOISINITE    (ITEM_MEGA_STONE_START + 3)
#define ITEM_BEEDRILLITE      (ITEM_MEGA_STONE_START + 4)
#define ITEM_PIDGEOTITE       (ITEM_MEGA_STONE_START + 5)
#define ITEM_ALAKAZITE        (ITEM_MEGA_STONE_START + 6)
#define ITEM_SLOWBRONITE      (ITEM_MEGA_STONE_START + 7)
#define ITEM_GENGARITE        (ITEM_MEGA_STONE_START + 8)
#define ITEM_KANGASKHANITE    (ITEM_MEGA_STONE_START + 9)
#define ITEM_PINSIRITE        (ITEM_MEGA_STONE_START + 10)
#define ITEM_GYARADOSITE      (ITEM_MEGA_STONE_START + 11)
#define ITEM_AERODACTYLITE    (ITEM_MEGA_STONE_START + 12)
#define ITEM_MEWTWONITE_X     (ITEM_MEGA_STONE_START + 13)
#define ITEM_MEWTWONITE_Y     (ITEM_MEGA_STONE_START + 14)
#define ITEM_AMPHAROSITE      (ITEM_MEGA_STONE_START + 15)
#define ITEM_STEELIXITE       (ITEM_MEGA_STONE_START + 16)
#define ITEM_SCIZORITE        (ITEM_MEGA_STONE_START + 17)
#define ITEM_HERACRONITE      (ITEM_MEGA_STONE_START + 18)
#define ITEM_HOUNDOOMINITE    (ITEM_MEGA_STONE_START + 19)
#define ITEM_TYRANITARITE     (ITEM_MEGA_STONE_START + 20)
#define ITEM_SCEPTILITE       (ITEM_MEGA_STONE_START + 21)
#define ITEM_BLAZIKENITE      (ITEM_MEGA_STONE_START + 22)
#define ITEM_SWAMPERTITE      (ITEM_MEGA_STONE_START + 23)
#define ITEM_GARDEVOIRITE     (ITEM_MEGA_STONE_START + 24)
#define ITEM_SABLENITE        (ITEM_MEGA_STONE_START + 25)
#define ITEM_MAWILITE         (ITEM_MEGA_STONE_START + 26)
#define ITEM_AGGRONITE        (ITEM_MEGA_STONE_START + 27)
#define ITEM_MEDICHAMITE      (ITEM_MEGA_STONE_START + 28)
#define ITEM_MANECTITE        (ITEM_MEGA_STONE_START + 29)
#define ITEM_SHARPEDONITE     (ITEM_MEGA_STONE_START + 30)
#define ITEM_CAMERUPTITE      (ITEM_MEGA_STONE_START + 31)
#define ITEM_ALTARIANITE      (ITEM_MEGA_STONE_START + 32)
#define ITEM_BANETTITE        (ITEM_MEGA_STONE_START + 33)
#define ITEM_ABSOLITE         (ITEM_MEGA_STONE_START + 34)
#define ITEM_GLALITITE        (ITEM_MEGA_STONE_START + 35)
#define ITEM_SALAMENCITE      (ITEM_MEGA_STONE_START + 36)
#define ITEM_METAGROSSITE     (ITEM_MEGA_STONE_START + 37)
#define ITEM_LATIASITE        (ITEM_MEGA_STONE_START + 38)
#define ITEM_LATIOSITE        (ITEM_MEGA_STONE_START + 39)
#define ITEM_LOPUNNITE        (ITEM_MEGA_STONE_START + 40)
#define ITEM_GARCHOMPITE      (ITEM_MEGA_STONE_START + 41)
#define ITEM_LUCARIONITE      (ITEM_MEGA_STONE_START + 42)
#define ITEM_ABOMASITE        (ITEM_MEGA_STONE_START + 43)
#define ITEM_GALLADITE        (ITEM_MEGA_STONE_START + 44)
#define ITEM_AUDINITE         (ITEM_MEGA_STONE_START + 45)
#define ITEM_DIANCITE         (ITEM_MEGA_STONE_START + 46)

#define ITEM_MEGA_STONE_END   ITEM_DIANCITE
#define IS_ITEM_MEGA_STONE(item) (item >= ITEM_MEGA_STONE_START && item <= ITEM_MEGA_STONE_END)
#define NUM_MEGA_STONES (ITEM_MEGA_STONE_END - ITEM_MEGA_STONE_START + 1)

#define ITEM_MAX_MEGA_STONES  (ITEM_MEGA_STONE_END + 1)

#endif