#ifndef CONSTANTS_ITEM_MEMORY_H
#define CONSTANTS_ITEM_MEMORY_H

#include "../../config.h"

#define ITEM_MEMORY_START     701

#define ITEM_FIGHTING_MEMORY    (ITEM_MEMORY_START)
#define ITEM_FLYING_MEMORY      (ITEM_MEMORY_START + 1)
#define ITEM_POISON_MEMORY      (ITEM_MEMORY_START + 2)
#define ITEM_GROUND_MEMORY      (ITEM_MEMORY_START + 3)
#define ITEM_ROCK_MEMORY        (ITEM_MEMORY_START + 4)
#define ITEM_BUG_MEMORY         (ITEM_MEMORY_START + 5)
#define ITEM_GHOST_MEMORY       (ITEM_MEMORY_START + 6)
#define ITEM_STEEL_MEMORY       (ITEM_MEMORY_START + 7)
#define ITEM_FIRE_MEMORY        (ITEM_MEMORY_START + 8)
#define ITEM_WATER_MEMORY       (ITEM_MEMORY_START + 9)
#define ITEM_GRASS_MEMORY       (ITEM_MEMORY_START + 10)
#define ITEM_ELECTRIC_MEMORY    (ITEM_MEMORY_START + 11)
#define ITEM_PSYCHIC_MEMORY     (ITEM_MEMORY_START + 12)
#define ITEM_ICE_MEMORY         (ITEM_MEMORY_START + 13)
#define ITEM_DRAGON_MEMORY      (ITEM_MEMORY_START + 14)
#define ITEM_DARK_MEMORY        (ITEM_MEMORY_START + 15)
#define ITEM_FAIRY_MEMORY       (ITEM_MEMORY_START + 16)

#define ITEM_MEMORY_END         ITEM_FAIRY_MEMORY
#define IS_ITEM_MEMORY(item) (item >= ITEM_MEMORY_START && item <= ITEM_MEMORY_END)
#define NUM_MEMORIES (ITEM_MEMORY_END - ITEM_MEMORY_START + 1)

#endif // CONSTANTS_ITEM_MEMORY_H