#ifndef CONSTANTS_ITEM_NATURE_MINT_H
#define CONSTANTS_ITEM_NATURE_MINT_H

#include "../../config.h"

#define ITEM_NATURE_MINT_START  771

#define ITEM_LONELY_MINT        (ITEM_NATURE_MINT_START)
#define ITEM_ADAMANT_MINT       (ITEM_NATURE_MINT_START + 1)
#define ITEM_NAUGHTY_MINT       (ITEM_NATURE_MINT_START + 2)
#define ITEM_BRAVE_MINT         (ITEM_NATURE_MINT_START + 3)
#define ITEM_BOLD_MINT          (ITEM_NATURE_MINT_START + 4)
#define ITEM_IMPISH_MINT        (ITEM_NATURE_MINT_START + 5)
#define ITEM_LAX_MINT           (ITEM_NATURE_MINT_START + 6)
#define ITEM_RELAXED_MINT       (ITEM_NATURE_MINT_START + 7)
#define ITEM_MODEST_MINT        (ITEM_NATURE_MINT_START + 8)
#define ITEM_MILD_MINT          (ITEM_NATURE_MINT_START + 9)
#define ITEM_RASH_MINT          (ITEM_NATURE_MINT_START + 10)
#define ITEM_QUIET_MINT         (ITEM_NATURE_MINT_START + 11)
#define ITEM_CALM_MINT          (ITEM_NATURE_MINT_START + 12)
#define ITEM_GENTLE_MINT        (ITEM_NATURE_MINT_START + 13)
#define ITEM_CAREFUL_MINT       (ITEM_NATURE_MINT_START + 14)
#define ITEM_SASSY_MINT         (ITEM_NATURE_MINT_START + 15)
#define ITEM_TIMID_MINT         (ITEM_NATURE_MINT_START + 16)
#define ITEM_HASTY_MINT         (ITEM_NATURE_MINT_START + 17)
#define ITEM_JOLLY_MINT         (ITEM_NATURE_MINT_START + 18)
#define ITEM_NAIVE_MINT         (ITEM_NATURE_MINT_START + 19)
#define ITEM_SERIOUS_MINT       (ITEM_NATURE_MINT_START + 20)

#define ITEM_NATURE_MINT_END    ITEM_SERIOUS_MINT
#define IS_ITEM_NATURE_MINT(item) (item >= ITEM_NATURE_MINT_START && item <= ITEM_NATURE_MINT_END)
#define NUM_NATURE_MINTS (ITEM_NATURE_MINT_END - ITEM_NATURE_MINT_START + 1)

#endif // CONSTANTS_ITEM_NATURE_MINT_H