#ifndef CONSTANTS_ITEM_PLATE_H
#define CONSTANTS_ITEM_PLATE_H

#include "../../config.h"

#define ITEM_PLATE_START    298
#define ITEM_FLAME_PLATE     (ITEM_PLATE_START)
#define ITEM_SPLASH_PLATE    (ITEM_PLATE_START + 1)
#define ITEM_ZAP_PLATE       (ITEM_PLATE_START + 2)
#define ITEM_MEADOW_PLATE    (ITEM_PLATE_START + 3)
#define ITEM_ICICLE_PLATE    (ITEM_PLATE_START + 4)
#define ITEM_FIST_PLATE      (ITEM_PLATE_START + 5)
#define ITEM_TOXIC_PLATE     (ITEM_PLATE_START + 6)
#define ITEM_EARTH_PLATE     (ITEM_PLATE_START + 7)
#define ITEM_SKY_PLATE       (ITEM_PLATE_START + 8)
#define ITEM_MIND_PLATE      (ITEM_PLATE_START + 9)
#define ITEM_INSECT_PLATE    (ITEM_PLATE_START + 10)
#define ITEM_STONE_PLATE     (ITEM_PLATE_START + 11)
#define ITEM_SPOOKY_PLATE    (ITEM_PLATE_START + 12)
#define ITEM_DRACO_PLATE     (ITEM_PLATE_START + 13)
#define ITEM_DREAD_PLATE     (ITEM_PLATE_START + 14)
#define ITEM_IRON_PLATE      (ITEM_PLATE_START + 15)
#define ITEM_PIXIE_PLATE     (ITEM_PLATE_START + 286) //because of item expansion

#define ITEM_PLATE_END      ITEM_IRON_PLATE
#define IS_ITEM_PLATE(item) ((item >= ITEM_PLATE_START && item <= ITEM_PLATE_END) || (item == ITEM_PIXIE_PLATE))
#define NUM_PLATES (ITEM_PLATE_END - ITEM_PLATE_START + 2) // +2 for Pixie Plate

#endif