#ifndef CONSTANTS_ITEM_PLATE_H
#define CONSTANTS_ITEM_PLATE_H

#include "../../config.h"

#define ITEM_PLATES_START    298
#define ITEM_FLAME_PLATE     (ITEM_PLATES_START)
#define ITEM_SPLASH_PLATE    (ITEM_PLATES_START + 1)
#define ITEM_ZAP_PLATE       (ITEM_PLATES_START + 2)
#define ITEM_MEADOW_PLATE    (ITEM_PLATES_START + 3)
#define ITEM_ICICLE_PLATE    (ITEM_PLATES_START + 4)
#define ITEM_FIST_PLATE      (ITEM_PLATES_START + 5)
#define ITEM_TOXIC_PLATE     (ITEM_PLATES_START + 6)
#define ITEM_EARTH_PLATE     (ITEM_PLATES_START + 7)
#define ITEM_SKY_PLATE       (ITEM_PLATES_START + 8)
#define ITEM_MIND_PLATE      (ITEM_PLATES_START + 9)
#define ITEM_INSECT_PLATE    (ITEM_PLATES_START + 10)
#define ITEM_STONE_PLATE     (ITEM_PLATES_START + 11)
#define ITEM_SPOOKY_PLATE    (ITEM_PLATES_START + 12)
#define ITEM_DRACO_PLATE     (ITEM_PLATES_START + 13)
#define ITEM_DREAD_PLATE     (ITEM_PLATES_START + 14)
#define ITEM_IRON_PLATE      (ITEM_PLATES_START + 15)
#define ITEM_PIXIE_PLATE     (ITEM_MEGA_STONES_START + 47)

#define ITEM_PLATES_END      ITEM_IRON_PLATE
#define IS_ITEM_PLATE(item) ((item >= ITEM_PLATES_START && item <= ITEM_PLATES_END) || (item == ITEM_PIXIE_PLATE))
#define NUM_PLATES (ITEM_PLATES_END - ITEM_PLATES_START + 2) // +2 for Pixie Plate

#endif