#ifndef CONSTANTS_ITEM_RELIC_ITEM_H
#define CONSTANTS_ITEM_RELIC_ITEM_H

#include "../../config.h"

#define ITEM_RELIC_ITEM_START       724

//Relic Items
#define ITEM_RELIC_COPPER       (ITEM_RELIC_ITEM_START + 0)
#define ITEM_RELIC_SILVER       (ITEM_RELIC_ITEM_START + 1)
#define ITEM_RELIC_GOLD         (ITEM_RELIC_ITEM_START + 2)
#define ITEM_RELIC_VASE         (ITEM_RELIC_ITEM_START + 3)
#define ITEM_RELIC_BAND         (ITEM_RELIC_ITEM_START + 4)
#define ITEM_RELIC_STATUE       (ITEM_RELIC_ITEM_START + 5)
#define ITEM_RELIC_CROWN        (ITEM_RELIC_ITEM_START + 6)

#define ITEM_RELIC_ITEM_END         ITEM_RELIC_CROWN
#define IS_ITEM_RELIC_ITEM(item) (item >= ITEM_RELIC_ITEM_START && item <= ITEM_RELIC_ITEM_END)
#define NUM_RELIC_ITEMS (ITEM_RELIC_ITEM_END - ITEM_RELIC_ITEM_START + 1)

#endif