#ifndef CONSTANTS_ITEMS_TM_H
#define CONSTANTS_ITEMS_TM_H

#include "../../config.h"

#define ITEM_TM_START        328

#define ITEM_TM01            (ITEM_TM_START)
#define ITEM_TM02            (ITEM_TM_START + 1)
#define ITEM_TM03            (ITEM_TM_START + 2)
#define ITEM_TM04            (ITEM_TM_START + 3)
#define ITEM_TM05            (ITEM_TM_START + 4)
#define ITEM_TM06            (ITEM_TM_START + 5)
#define ITEM_TM07            (ITEM_TM_START + 6)
#define ITEM_TM08            (ITEM_TM_START + 7)
#define ITEM_TM09            (ITEM_TM_START + 8)
#define ITEM_TM10            (ITEM_TM_START + 9)
#define ITEM_TM11            (ITEM_TM_START + 10)
#define ITEM_TM12            (ITEM_TM_START + 11)
#define ITEM_TM13            (ITEM_TM_START + 12)
#define ITEM_TM14            (ITEM_TM_START + 13)
#define ITEM_TM15            (ITEM_TM_START + 14)
#define ITEM_TM16            (ITEM_TM_START + 15)
#define ITEM_TM17            (ITEM_TM_START + 16)
#define ITEM_TM18            (ITEM_TM_START + 17)
#define ITEM_TM19            (ITEM_TM_START + 18)
#define ITEM_TM20            (ITEM_TM_START + 19)
#define ITEM_TM21            (ITEM_TM_START + 20)
#define ITEM_TM22            (ITEM_TM_START + 21)
#define ITEM_TM23            (ITEM_TM_START + 22)
#define ITEM_TM24            (ITEM_TM_START + 23)
#define ITEM_TM25            (ITEM_TM_START + 24)
#define ITEM_TM26            (ITEM_TM_START + 25)
#define ITEM_TM27            (ITEM_TM_START + 26)
#define ITEM_TM28            (ITEM_TM_START + 27)
#define ITEM_TM29            (ITEM_TM_START + 28)
#define ITEM_TM30            (ITEM_TM_START + 29)
#define ITEM_TM31            (ITEM_TM_START + 30)
#define ITEM_TM32            (ITEM_TM_START + 31)
#define ITEM_TM33            (ITEM_TM_START + 32)
#define ITEM_TM34            (ITEM_TM_START + 33)
#define ITEM_TM35            (ITEM_TM_START + 34)
#define ITEM_TM36            (ITEM_TM_START + 35)
#define ITEM_TM37            (ITEM_TM_START + 36)
#define ITEM_TM38            (ITEM_TM_START + 37)
#define ITEM_TM39            (ITEM_TM_START + 38)
#define ITEM_TM40            (ITEM_TM_START + 39)
#define ITEM_TM41            (ITEM_TM_START + 40)
#define ITEM_TM42            (ITEM_TM_START + 41)
#define ITEM_TM43            (ITEM_TM_START + 42)
#define ITEM_TM44            (ITEM_TM_START + 43)
#define ITEM_TM45            (ITEM_TM_START + 44)
#define ITEM_TM46            (ITEM_TM_START + 45)
#define ITEM_TM47            (ITEM_TM_START + 46)
#define ITEM_TM48            (ITEM_TM_START + 47)
#define ITEM_TM49            (ITEM_TM_START + 48)
#define ITEM_TM50            (ITEM_TM_START + 49)
#define ITEM_TM51            (ITEM_TM_START + 50)
#define ITEM_TM52            (ITEM_TM_START + 51)
#define ITEM_TM53            (ITEM_TM_START + 52)
#define ITEM_TM54            (ITEM_TM_START + 53)
#define ITEM_TM55            (ITEM_TM_START + 54)
#define ITEM_TM56            (ITEM_TM_START + 55)
#define ITEM_TM57            (ITEM_TM_START + 56)
#define ITEM_TM58            (ITEM_TM_START + 57)
#define ITEM_TM59            (ITEM_TM_START + 58)
#define ITEM_TM60            (ITEM_TM_START + 59)
#define ITEM_TM61            (ITEM_TM_START + 60)
#define ITEM_TM62            (ITEM_TM_START + 61)
#define ITEM_TM63            (ITEM_TM_START + 62)
#define ITEM_TM64            (ITEM_TM_START + 63)
#define ITEM_TM65            (ITEM_TM_START + 64)
#define ITEM_TM66            (ITEM_TM_START + 65)
#define ITEM_TM67            (ITEM_TM_START + 66)
#define ITEM_TM68            (ITEM_TM_START + 67)
#define ITEM_TM69            (ITEM_TM_START + 68)
#define ITEM_TM70            (ITEM_TM_START + 69)
#define ITEM_TM71            (ITEM_TM_START + 70)
#define ITEM_TM72            (ITEM_TM_START + 71)
#define ITEM_TM73            (ITEM_TM_START + 72)
#define ITEM_TM74            (ITEM_TM_START + 73)
#define ITEM_TM75            (ITEM_TM_START + 74)
#define ITEM_TM76            (ITEM_TM_START + 75)
#define ITEM_TM77            (ITEM_TM_START + 76)
#define ITEM_TM78            (ITEM_TM_START + 77)
#define ITEM_TM79            (ITEM_TM_START + 78)
#define ITEM_TM80            (ITEM_TM_START + 79)
#define ITEM_TM81            (ITEM_TM_START + 80)
#define ITEM_TM82            (ITEM_TM_START + 81)
#define ITEM_TM83            (ITEM_TM_START + 82)
#define ITEM_TM84            (ITEM_TM_START + 83)
#define ITEM_TM85            (ITEM_TM_START + 84)
#define ITEM_TM86            (ITEM_TM_START + 85)
#define ITEM_TM87            (ITEM_TM_START + 86)
#define ITEM_TM88            (ITEM_TM_START + 87)
#define ITEM_TM89            (ITEM_TM_START + 88)
#define ITEM_TM90            (ITEM_TM_START + 89)
#define ITEM_TM91            (ITEM_TM_START + 90)
#define ITEM_TM92            (ITEM_TM_START + 91)

#define ITEM_TM_END          ITEM_TM92
#define IS_ITEM_TM(item) ((item >= ITEM_TM_START && item <= ITEM_TM_END))
#define NUM_TMS (ITEM_TM_END - ITEM_TM_START + 1)

#endif