.ifndef SCR_SEQ_R13_H_
.definelabel SCR_SEQ_R13_H_, 0

.equ _EV_scr_seq_R13_000, 0
.equ _EV_scr_seq_R13_001, 1
.equ _EV_scr_seq_R13_002, 2

.equ obj_R13_mount_2, 0
.equ obj_R13_gsman2, 1
.equ obj_R13_gswoman2, 2
.equ obj_R13_gsmiddleman1, 3
.equ obj_R13_gsmiddleman1_2, 4
.equ obj_R13_campboy_2, 5
.equ obj_R13_campboy_2_2, 6
.equ obj_R13_picnicgirl_2, 7
.equ obj_R13_picnicgirl_2_2, 8
.equ obj_R13_gsman2_2, 9
.equ obj_R13_gsman2_3, 10
.equ obj_R13_tree, 11
.equ obj_R13_gswoman1, 17

.endif //SCR_SEQ_R13_H_
