.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0

.equ obj_EVERYWHERE_rock, 0
.equ obj_EVERYWHERE_breakrock, 1
.equ obj_EVERYWHERE_breakrock_2, 2
.equ obj_EVERYWHERE_breakrock_3, 3
.equ obj_EVERYWHERE_monstarball, 4
.equ obj_EVERYWHERE_monstarball_2, 5
.equ obj_EVERYWHERE_monstarball_3, 6
.equ obj_EVERYWHERE_monstarball_4, 7
.equ obj_EVERYWHERE_monstarball_5, 8
.equ obj_EVERYWHERE_breakrock_4, 9

.endif //SCR_SEQ_EVERYWHERE_H_
