.ifndef SCR_SEQ_R45_H_
.definelabel SCR_SEQ_R45_H_, 0

.equ _EV_scr_seq_R45_000, 0
.equ _EV_scr_seq_R45_001, 1
.equ _EV_scr_seq_R45_002, 2
.equ _EV_scr_seq_R45_003, 3
.equ _EV_scr_seq_R45_004, 4

.equ obj_R45_mount_2, 0
.equ obj_R45_gsman3, 1
.equ obj_R45_mount_2_2, 2
.equ obj_R45_gswoman3, 3
.equ obj_R45_gsfighter, 4
.equ obj_R45_mount_2_3, 5
.equ obj_R45_mount_2_4, 6
.equ obj_R45_bonguri, 7
.equ obj_R45_monstarball, 8
.equ obj_R45_monstarball_2, 9
.equ obj_R45_monstarball_3, 10
.equ obj_R45_monstarball_4, 11
.equ obj_R45_monstarball_5, 12
.equ obj_R45_gsman1, 13
.equ obj_R45_gsmiddleman1, 14

.endif //SCR_SEQ_R45_H_
