.ifndef SCR_SEQ_R32_H_
.definelabel SCR_SEQ_R32_H_, 0

.equ _EV_scr_seq_R32_000, 0
.equ _EV_scr_seq_R32_001, 1
.equ _EV_scr_seq_R32_002, 2
.equ _EV_scr_seq_R32_003, 3
.equ _EV_scr_seq_R32_004, 4
.equ _EV_scr_seq_R32_005, 5
.equ _EV_scr_seq_R32_006, 6
.equ _EV_scr_seq_R32_007, 7
.equ _EV_scr_seq_R32_008, 8
.equ _EV_scr_seq_R32_009, 9

.equ obj_R32_gsbigman, 0
.equ obj_R32_gsmiddleman1, 1
.equ obj_R32_tree, 2
.equ obj_R32_gsboy2, 3
.equ obj_R32_picnicgirl_2, 4
.equ obj_R32_fishing_2, 5
.equ obj_R32_fishing_2_2, 6
.equ obj_R32_fishing_2_3, 7
.equ obj_R32_campboy_2, 8
.equ obj_R32_gsboy2_2, 9
.equ obj_R32_gsbigman_2, 10
.equ obj_R32_gsman2, 11
.equ obj_R32_monstarball, 12
.equ obj_R32_monstarball_2, 13
.equ obj_R32_gsgirl1, 14
.equ obj_R32_breakrock, 15
.equ obj_R32_monstarball_3, 16
.equ obj_R32_monstarball_4, 17
.equ obj_R32_gsmiddleman1_2, 18

.endif //SCR_SEQ_R32_H_
