.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0

.equ obj_EVERYWHERE_rock, 0
.equ obj_EVERYWHERE_ice, 1
.equ obj_EVERYWHERE_ice_2, 2
.equ obj_EVERYWHERE_ice_3, 3
.equ obj_EVERYWHERE_ice_4, 4
.equ obj_EVERYWHERE_ice_5, 5
.equ obj_EVERYWHERE_ice_6, 6
.equ obj_EVERYWHERE_monstarball, 7
.equ obj_EVERYWHERE_monstarball_2, 8

.endif //SCR_SEQ_EVERYWHERE_H_
