.ifndef SCR_SEQ_R43_H_
.definelabel SCR_SEQ_R43_H_, 0

.equ _EV_scr_seq_R43_000, 0
.equ _EV_scr_seq_R43_001, 1
.equ _EV_scr_seq_R43_002, 2
.equ _EV_scr_seq_R43_003, 3

.equ obj_R43_campboy_2, 0
.equ obj_R43_picnicgirl_2, 1
.equ obj_R43_mania, 2
.equ obj_R43_mania_2, 3
.equ obj_R43_mania_3, 4
.equ obj_R43_fishing_2, 5
.equ obj_R43_bonguri, 6
.equ obj_R43_monstarball, 7
.equ obj_R43_tree, 8

.endif //SCR_SEQ_R43_H_
