.ifndef SCR_SEQ_P01R0306_H_
.definelabel SCR_SEQ_P01R0306_H_, 0

.equ _EV_scr_seq_P01R0306_000, 0
.equ _EV_scr_seq_P01R0306_001, 1
.equ _EV_scr_seq_P01R0306_002, 2
.equ _EV_scr_seq_P01R0306_003, 3

.equ obj_P01R0306_gsgentleman, 0
.equ obj_P01R0306_gsmiddleman1, 1
.equ obj_P01R0306_gsbabygirl1, 2
.equ obj_P01R0306_gsbabygirl1_2, 3
.equ obj_P01R0306_gsbabygirl1_3, 4
.equ obj_P01R0306_gsassistantm, 5
.equ obj_P01R0306_mystery_2, 6
.equ obj_P01R0306_middlewoman1_2, 7
.equ obj_P01R0306_gsmiddleman1_2, 8

.endif //SCR_SEQ_P01R0306_H_
