.ifndef SCR_SEQ_T22_H_
.definelabel SCR_SEQ_T22_H_, 0

.equ _EV_scr_seq_T22_000, 0
.equ _EV_scr_seq_T22_001, 1
.equ _EV_scr_seq_T22_002, 2
.equ _EV_scr_seq_T22_003, 3
.equ _EV_scr_seq_T22_004, 4
.equ _EV_scr_seq_T22_005, 5
.equ _EV_scr_seq_T22_006, 6
.equ _EV_scr_seq_T22_007, 7
.equ _EV_scr_seq_T22_008, 8
.equ _EV_scr_seq_T22_009, 9
.equ _EV_scr_seq_T22_010, 10
.equ _EV_scr_seq_T22_011, 11
.equ _EV_scr_seq_T22_012, 12
.equ _EV_scr_seq_T22_013, 13
.equ _EV_scr_seq_T22_014, 14

.equ obj_T22_gsgirl3, 0
.equ obj_T22_gsman1, 1
.equ obj_T22_gsbigman, 2
.equ obj_T22_gsoldwoman1, 3
.equ obj_T22_gsboy2, 4
.equ obj_T22_monstarball, 5
.equ obj_T22_monstarball_2, 6
.equ obj_T22_dancer, 7
.equ obj_T22_bonguri, 8
.equ obj_T22_breakrock, 9
.equ obj_T22_juggrer, 10
.equ obj_T22_gswoman3, 11
.equ obj_T22_gsbabyboy1, 12

.endif //SCR_SEQ_T22_H_
