.ifndef SCR_SEQ_T24GYM0101_H_
.definelabel SCR_SEQ_T24GYM0101_H_, 0

.equ _EV_scr_seq_T24GYM0101_000, 0
.equ _EV_scr_seq_T24GYM0101_001, 1
.equ _EV_scr_seq_T24GYM0101_002, 2
.equ _EV_scr_seq_T24GYM0101_003, 3

.equ obj_T24GYM0101_gsleader5, 0
.equ obj_T24GYM0101_gsfighter, 1
.equ obj_T24GYM0101_gsfighter_2, 2
.equ obj_T24GYM0101_gsfighter_3, 3
.equ obj_T24GYM0101_gsfighter_4, 4

.endif //SCR_SEQ_T24GYM0101_H_
