.ifndef SCR_SEQ_W19_H_
.definelabel SCR_SEQ_W19_H_, 0

.equ _EV_scr_seq_W19_000, 0
.equ _EV_scr_seq_W19_001, 1
.equ _EV_scr_seq_W19_002, 2
.equ _EV_scr_seq_W19_003, 3
.equ _EV_scr_seq_W19_004, 4
.equ _EV_scr_seq_W19_005, 5

.equ obj_W19_gsswimmerm, 0
.equ obj_W19_gsswimmerm_2, 1
.equ obj_W19_gsswimmerm_3, 2
.equ obj_W19_gsswimmerw, 3
.equ obj_W19_stop, 4
.equ obj_W19_stop_2, 5
.equ obj_W19_stop_3, 6
.equ obj_W19_stop_4, 7
.equ obj_W19_breakrock, 8
.equ obj_W19_breakrock_2, 9
.equ obj_W19_breakrock_3, 10
.equ obj_W19_breakrock_4, 11
.equ obj_W19_breakrock_5, 12
.equ obj_W19_workman, 13
.equ obj_W19_workman_2, 14
.equ obj_W19_workman_3, 15
.equ obj_W19_workman_4, 16
.equ obj_W19_monstarball, 17

.endif //SCR_SEQ_W19_H_
