.ifndef SCR_SEQ_T26_H_
.definelabel SCR_SEQ_T26_H_, 0

.equ _EV_scr_seq_T26_000, 0
.equ _EV_scr_seq_T26_001, 1
.equ _EV_scr_seq_T26_002, 2
.equ _EV_scr_seq_T26_003, 3
.equ _EV_scr_seq_T26_004, 4
.equ _EV_scr_seq_T26_005, 5
.equ _EV_scr_seq_T26_006, 6
.equ _EV_scr_seq_T26_007, 7
.equ _EV_scr_seq_T26_008, 8
.equ _EV_scr_seq_T26_009, 9
.equ _EV_scr_seq_T26_010, 10
.equ _EV_scr_seq_T26_011, 11
.equ _EV_scr_seq_T26_012, 12

.equ obj_T26_seaman_2, 0
.equ obj_T26_gsboy1, 1
.equ obj_T26_seaman_2_2, 2
.equ obj_T26_gsrivel, 3
.equ obj_T26_monstarball, 4
.equ obj_T26_seaman_2_3, 5
.equ obj_T26_gswoman2, 6
.equ obj_T26_gsmiddleman1, 7
.equ obj_T26_gsmiddleman1_2, 5

.endif //SCR_SEQ_T26_H_
