.ifndef SCR_SEQ_R26_H_
.definelabel SCR_SEQ_R26_H_, 0

.equ _EV_scr_seq_R26_000, 0
.equ _EV_scr_seq_R26_001, 1
.equ _EV_scr_seq_R26_002, 2
.equ _EV_scr_seq_R26_003, 3

.equ obj_R26_fishing_2, 0
.equ obj_R26_mystery_2, 1
.equ obj_R26_gswoman3, 2
.equ obj_R26_gsman3, 3
.equ obj_R26_gsman3_2, 4
.equ obj_R26_gswoman3_2, 5
.equ obj_R26_monstarball, 6
.equ obj_R26_bonguri, 7
.equ obj_R26_gsmiddleman1, 8

.endif //SCR_SEQ_R26_H_
