.ifndef SCR_SEQ_T02_H_
.definelabel SCR_SEQ_T02_H_, 0

.equ _EV_scr_seq_T02_000, 0
.equ _EV_scr_seq_T02_001, 1
.equ _EV_scr_seq_T02_002, 2
.equ _EV_scr_seq_T02_003, 3
.equ _EV_scr_seq_T02_004, 4
.equ _EV_scr_seq_T02_005, 5
.equ _EV_scr_seq_T02_006, 6
.equ _EV_scr_seq_T02_007, 7
.equ _EV_scr_seq_T02_008, 8
.equ _EV_scr_seq_T02_009, 9
.equ _EV_scr_seq_T02_010, 10
.equ _EV_scr_seq_T02_011, 11

.equ obj_T02_gsoldman1, 0
.equ obj_T02_gsoldman1_2, 1
.equ obj_T02_gsbigman, 2
.equ obj_T02_gsboy1, 3
.equ obj_T02_tree, 4
.equ obj_T02_tree_2, 5
.equ obj_T02_gsmiddleman1, 6
.equ obj_T02_gsoldman1_3, 7

.endif //SCR_SEQ_T02_H_
