.ifndef SCR_SEQ_D35R0103_H_
.definelabel SCR_SEQ_D35R0103_H_, 0

.equ _EV_scr_seq_D35R0103_000, 0
.equ _EV_scr_seq_D35R0103_001, 1
.equ _EV_scr_seq_D35R0103_002, 2
.equ _EV_scr_seq_D35R0103_003, 3
.equ _EV_scr_seq_D35R0103_004, 4
.equ _EV_scr_seq_D35R0103_005, 5
.equ _EV_scr_seq_D35R0103_006, 6
.equ _EV_scr_seq_D35R0103_007, 7
.equ _EV_scr_seq_D35R0103_008, 8
.equ _EV_scr_seq_D35R0103_009, 9
.equ _EV_scr_seq_D35R0103_010, 10
.equ _EV_scr_seq_D35R0103_011, 11
.equ _EV_scr_seq_D35R0103_012, 12
.equ _EV_scr_seq_D35R0103_013, 13
.equ _EV_scr_seq_D35R0103_014, 14

.equ obj_D35R0103_wataru, 0
.equ obj_D35R0103_follower_mon_static_dragonite, 1
.equ obj_D35R0103_rocketm, 2
.equ obj_D35R0103_rocketm_2, 3
.equ obj_D35R0103_rocketm_3, 4
.equ obj_D35R0103_babyboy1_9, 5
.equ obj_D35R0103_babyboy1_9_2, 6
.equ obj_D35R0103_rocketm_4, 7
.equ obj_D35R0103_rkanbuw, 8
.equ obj_D35R0103_follower_mon_static_electrode, 9
.equ obj_D35R0103_follower_mon_static_electrode_2, 10
.equ obj_D35R0103_follower_mon_static_electrode_3, 11
.equ obj_D35R0103_follower_mon_static_electrode_4, 12
.equ obj_D35R0103_follower_mon_static_electrode_5, 13
.equ obj_D35R0103_follower_mon_static_electrode_6, 14
.equ obj_D35R0103_monstarball, 15
.equ obj_D35R0103_follower_mon_static_murkrow, 16
.equ obj_D35R0103_follower_mon_static_murkrow_2, 17
.equ obj_D35R0103_follower_mon_static_murkrow_3, 18

.endif //SCR_SEQ_D35R0103_H_
