.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0

.equ obj_EVERYWHERE_monstarball, 0
.equ obj_EVERYWHERE_monstarball_2, 1
.equ obj_EVERYWHERE_monstarball_3, 2
.equ obj_EVERYWHERE_breakrock, 3
.equ obj_EVERYWHERE_breakrock_2, 4
.equ obj_EVERYWHERE_breakrock_3, 5
.equ obj_EVERYWHERE_breakrock_4, 6
.equ obj_EVERYWHERE_breakrock_5, 7
.equ obj_EVERYWHERE_breakrock_6, 8
.equ obj_EVERYWHERE_breakrock_7, 9
.equ obj_EVERYWHERE_breakrock_8, 10
.equ obj_EVERYWHERE_breakrock_9, 11
.equ obj_EVERYWHERE_breakrock_10, 12
.equ obj_EVERYWHERE_breakrock_11, 13
.equ obj_EVERYWHERE_breakrock_12, 14
.equ obj_EVERYWHERE_breakrock_13, 15
.equ obj_EVERYWHERE_breakrock_14, 16
.equ obj_EVERYWHERE_breakrock_15, 17
.equ obj_EVERYWHERE_monstarball_4, 18

.endif //SCR_SEQ_EVERYWHERE_H_
