.ifndef SCR_SEQ_D49_H_
.definelabel SCR_SEQ_D49_H_, 0

.equ _EV_scr_seq_D49_000, 0
.equ _EV_scr_seq_D49_001, 1
.equ _EV_scr_seq_D49_002, 2
.equ _EV_scr_seq_D49_003, 3
.equ _EV_scr_seq_D49_004, 4
.equ _EV_scr_seq_D49_005, 5
.equ _EV_scr_seq_D49_006, 6
.equ _EV_scr_seq_D49_007, 7
.equ _EV_scr_seq_D49_008, 8
.equ _EV_scr_seq_D49_009, 9
.equ _EV_scr_seq_D49_010, 10
.equ _EV_scr_seq_D49_011, 11
.equ _EV_scr_seq_D49_012, 12
.equ _EV_scr_seq_D49_013, 13
.equ _EV_scr_seq_D49_014, 14
.equ _EV_scr_seq_D49_015, 15
.equ _EV_scr_seq_D49_016, 16
.equ _EV_scr_seq_D49_017, 17
.equ _EV_scr_seq_D49_018, 18
.equ _EV_scr_seq_D49_019, 19
.equ _EV_scr_seq_D49_020, 20
.equ _EV_scr_seq_D49_021, 21
.equ _EV_scr_seq_D49_022, 22
.equ _EV_scr_seq_D49_023, 23

.equ obj_D49_thlonowner, 0
.equ obj_D49_follower_mon_static_poliwrath, 1
.equ obj_D49_gsboy2, 2
.equ obj_D49_gsgirl1, 3
.equ obj_D49_follower_mon_static_meowth, 4
.equ obj_D49_gsman3, 5
.equ obj_D49_follower_mon_static_psyduck, 6
.equ obj_D49_follower_mon_static_slowpoke, 7
.equ obj_D49_follower_mon_static_oddish, 8
.equ obj_D49_middlewoman1_2, 9
.equ obj_D49_follower_mon_static_pidgey, 10
.equ obj_D49_gswoman1, 11
.equ obj_D49_follower_mon_static_slowbro, 12
.equ obj_D49_gsman3_2, 13
.equ obj_D49_follower_mon_static_machop, 14
.equ obj_D49_follower_mon_static_farfetchd, 15
.equ obj_D49_gsmiddleman1, 16
.equ obj_D49_gsmiddleman1_2, 17
.equ obj_D49_shopm1_2, 18

.endif //SCR_SEQ_D49_H_
