.ifndef SCR_SEQ_R12_H_
.definelabel SCR_SEQ_R12_H_, 0

.equ _EV_scr_seq_R12_000, 0
.equ _EV_scr_seq_R12_001, 1
.equ _EV_scr_seq_R12_002, 2
.equ _EV_scr_seq_R12_003, 3
.equ _EV_scr_seq_R12_004, 4
.equ _EV_scr_seq_R12_005, 5

.equ obj_R12_fishing_2, 0
.equ obj_R12_fishing_2_2, 1
.equ obj_R12_gsman2, 2
.equ obj_R12_gsman2_2, 3
.equ obj_R12_gswoman2, 4
.equ obj_R12_fishing_2_3, 5
.equ obj_R12_fishing_2_4, 6
.equ obj_R12_gsman2_3, 7
.equ obj_R12_fishing_2_5, 8
.equ obj_R12_monstarball, 9
.equ obj_R12_monstarball_2, 10
.equ obj_R12_tree, 11
.equ obj_R12_tree_2, 12
.equ obj_R12_gsmiddleman1, 13
.equ obj_R12_gswoman1, 0
.equ obj_R12_kabigon, 15
.equ obj_R12_gsbabyboy1, 16
.equ obj_R12_gsbabyboy1_2, 17
.equ obj_R12_gsbabyboy1_3, 18

.endif //SCR_SEQ_R12_H_
