.ifndef SCR_SEQ_R27_H_
.definelabel SCR_SEQ_R27_H_, 0

.equ _EV_scr_seq_R27_000, 0
.equ _EV_scr_seq_R27_001, 1
.equ _EV_scr_seq_R27_002, 2
.equ _EV_scr_seq_R27_003, 3
.equ _EV_scr_seq_R27_004, 4

.equ obj_R27_gsbigman, 0
.equ obj_R27_gswoman3, 1
.equ obj_R27_gsman3, 2
.equ obj_R27_gsman2, 3
.equ obj_R27_gsman3_2, 4
.equ obj_R27_mystery_2, 5
.equ obj_R27_gswoman3_2, 6
.equ obj_R27_monstarball, 7
.equ obj_R27_monstarball_2, 8
.equ obj_R27_monstarball_3, 9

.endif //SCR_SEQ_R27_H_
