.ifndef SCR_SEQ_T03_H_
.definelabel SCR_SEQ_T03_H_, 0

.equ _EV_scr_seq_T03_000, 0
.equ _EV_scr_seq_T03_001, 1
.equ _EV_scr_seq_T03_002, 2
.equ _EV_scr_seq_T03_003, 3
.equ _EV_scr_seq_T03_004, 4
.equ _EV_scr_seq_T03_005, 5
.equ _EV_scr_seq_T03_006, 6
.equ _EV_scr_seq_T03_007, 7
.equ _EV_scr_seq_T03_008, 8
.equ _EV_scr_seq_T03_009, 9
.equ _EV_scr_seq_T03_010, 10
.equ _EV_scr_seq_T03_011, 11
.equ _EV_scr_seq_T03_012, 12
.equ _EV_scr_seq_T03_013, 13

.equ obj_T03_gsoldman1, 0
.equ obj_T03_gswoman3, 1
.equ obj_T03_gsbabyboy1, 2
.equ obj_T03_breakrock, 3
.equ obj_T03_bonguri, 4
.equ obj_T03_bonguri_2, 5
.equ obj_T03_monstarball, 6
.equ obj_T03_gsmiddleman1, 7
.equ obj_T03_daigo, 8
.equ obj_T03_follower_mon_static_latios, 9
.equ obj_T03_follower_mon_static_latias, 10

.endif //SCR_SEQ_T03_H_
