.ifndef SCR_SEQ_D02R0104_H_
.definelabel SCR_SEQ_D02R0104_H_, 0

.equ _EV_scr_seq_D02R0104_000, 0
.equ _EV_scr_seq_D02R0104_001, 1
.equ _EV_scr_seq_D02R0104_002, 2
.equ _EV_scr_seq_D02R0104_003, 3
.equ _EV_scr_seq_D02R0104_004, 4
.equ _EV_scr_seq_D02R0104_005, 5

.equ obj_D02R0104_follower_mon_static_clefairy, 0
.equ obj_D02R0104_follower_mon_static_clefairy_2, 1
.equ obj_D02R0104_follower_mon_static_clefairy_3, 2
.equ obj_D02R0104_follower_mon_static_clefairy_4, 3
.equ obj_D02R0104_follower_mon_static_clefairy_5, 4
.equ obj_D02R0104_follower_mon_static_clefairy_6, 5
.equ obj_D02R0104_monstarball, 6

.endif //SCR_SEQ_D02R0104_H_
