.ifndef SCR_SEQ_T05_H_
.definelabel SCR_SEQ_T05_H_, 0

.equ _EV_scr_seq_T05_000, 0
.equ _EV_scr_seq_T05_001, 1
.equ _EV_scr_seq_T05_002, 2
.equ _EV_scr_seq_T05_003, 3
.equ _EV_scr_seq_T05_004, 4
.equ _EV_scr_seq_T05_005, 5
.equ _EV_scr_seq_T05_006, 6
.equ _EV_scr_seq_T05_007, 7

.equ obj_T05_gswoman1, 0
.equ obj_T05_gsboy1, 1
.equ obj_T05_gsoldman1, 2
.equ obj_T05_gsmiddleman1, 3

.endif //SCR_SEQ_T05_H_
