.ifndef SCR_SEQ_R31_H_
.definelabel SCR_SEQ_R31_H_, 0

.equ _EV_scr_seq_R31_000, 0
.equ _EV_scr_seq_R31_001, 1
.equ _EV_scr_seq_R31_002, 2
.equ _EV_scr_seq_R31_003, 3
.equ _EV_scr_seq_R31_004, 4
.equ _EV_scr_seq_R31_005, 5

.equ obj_R31_gsman1, 0
.equ obj_R31_tree, 1
.equ obj_R31_gsbigman, 2
.equ obj_R31_tree_2, 3
.equ obj_R31_gsboy1, 4
.equ obj_R31_gsboy3, 5
.equ obj_R31_monstarball, 6
.equ obj_R31_monstarball_2, 7
.equ obj_R31_bonguri, 8

.endif //SCR_SEQ_R31_H_
