.ifndef SCR_SEQ_T07R0201_H_
.definelabel SCR_SEQ_T07R0201_H_, 0

.equ _EV_scr_seq_T07R0201_000, 0
.equ _EV_scr_seq_T07R0201_001, 1
.equ _EV_scr_seq_T07R0201_002, 2
.equ _EV_scr_seq_T07R0201_003, 3
.equ _EV_scr_seq_T07R0201_004, 4
.equ _EV_scr_seq_T07R0201_005, 5

.equ obj_T07R0201_gsoldwoman1, 0
.equ obj_T07R0201_follower_mon_static_meowth, 1
.equ obj_T07R0201_follower_mon_static_clefairy, 2
.equ obj_T07R0201_follower_mon_static_nidoran_f, 3

.endif //SCR_SEQ_T07R0201_H_
