.ifndef SCR_SEQ_R11_H_
.definelabel SCR_SEQ_R11_H_, 0

.equ _EV_scr_seq_R11_000, 0
.equ _EV_scr_seq_R11_001, 1
.equ _EV_scr_seq_R11_002, 2
.equ _EV_scr_seq_R11_003, 3

.equ obj_R11_mystery_2, 0
.equ obj_R11_mystery_2_2, 1
.equ obj_R11_gsboy2, 2
.equ obj_R11_gsboy2_2, 3
.equ obj_R11_kabigon, 4
.equ obj_R11_bonguri, 5
.equ obj_R11_monstarball, 6
.equ obj_R11_gsbabyboy1, 7
.equ obj_R11_gsbabyboy1_2, 8
.equ obj_R11_gsbabyboy1_3, 9

.endif //SCR_SEQ_R11_H_
