.ifndef SCR_SEQ_W20_H_
.definelabel SCR_SEQ_W20_H_, 0

.equ _EV_scr_seq_W20_000, 0
.equ _EV_scr_seq_W20_001, 1

.equ obj_W20_gsswimmerm, 0
.equ obj_W20_campboy_2, 1
.equ obj_W20_picnicgirl_2, 2
.equ obj_W20_picnicgirl_2_2, 3
.equ obj_W20_gsman2, 4
.equ obj_W20_gsman2_2, 5
.equ obj_W20_gsswimmerw, 6
.equ obj_W20_gsswimmerw_2, 7
.equ obj_W20_gsswimmerm_2, 8
.equ obj_W20_gsswimmerm_3, 9
.equ obj_W20_gsswimmerw_3, 10
.equ obj_W20_gsswimmerw_4, 11

.endif //SCR_SEQ_W20_H_
