.ifndef SCR_SEQ_R30_H_
.definelabel SCR_SEQ_R30_H_, 0

.equ _EV_scr_seq_R30_000, 0
.equ _EV_scr_seq_R30_001, 1
.equ _EV_scr_seq_R30_002, 2
.equ _EV_scr_seq_R30_003, 3
.equ _EV_scr_seq_R30_004, 4
.equ _EV_scr_seq_R30_005, 5
.equ _EV_scr_seq_R30_006, 6
.equ _EV_scr_seq_R30_007, 7
.equ _EV_scr_seq_R30_008, 8
.equ _EV_scr_seq_R30_009, 9
.equ _EV_scr_seq_R30_010, 10

.equ obj_R30_gsman1, 0
.equ obj_R30_gsgirl2, 1
.equ obj_R30_tree, 2
.equ obj_R30_gsboy3, 3
.equ obj_R30_gsboy2, 4
.equ obj_R30_gsboy2_2, 5
.equ obj_R30_follower_mon_static_rattata, 6
.equ obj_R30_follower_mon_static_pidgey, 7
.equ obj_R30_gsboy2_3, 8
.equ obj_R30_monstarball, 9
.equ obj_R30_monstarball_2, 10
.equ obj_R30_bonguri, 11
.equ obj_R30_bonguri_2, 12
.equ obj_R30_gsmiddleman1, 13
.equ obj_R30_gsboy3_2, 14

.endif //SCR_SEQ_R30_H_
