.ifndef SCR_SEQ_D18R0101_H_
.definelabel SCR_SEQ_D18R0101_H_, 0

.equ _EV_scr_seq_D18R0101_000, 0
.equ _EV_scr_seq_D18R0101_001, 1
.equ _EV_scr_seq_D18R0101_002, 2
.equ _EV_scr_seq_D18R0101_003, 3

.equ obj_D18R0101_gsrivel, 0
.equ obj_D18R0101_minaki, 1
.equ obj_D18R0101_gsleader4, 2
.equ obj_D18R0101_fire, 3
.equ obj_D18R0101_fire_2, 4
.equ obj_D18R0101_follower_mon_static_suicune, 5
.equ obj_D18R0101_follower_mon_static_raikou, 6
.equ obj_D18R0101_follower_mon_static_entei, 7
.equ obj_D18R0101_breakrock, 8
.equ obj_D18R0101_breakrock_2, 9
.equ obj_D18R0101_breakrock_3, 10
.equ obj_D18R0101_monstarball, 11
.equ obj_D18R0101_monstarball_2, 12
.equ obj_D18R0101_follower_mon_static_suicune_2, 13

.endif //SCR_SEQ_D18R0101_H_
