.ifndef SCR_SEQ_R44_H_
.definelabel SCR_SEQ_R44_H_, 0

.equ _EV_scr_seq_R44_000, 0
.equ _EV_scr_seq_R44_001, 1
.equ _EV_scr_seq_R44_002, 2

.equ obj_R44_mystery_2, 0
.equ obj_R44_fishing_2, 1
.equ obj_R44_fishing_2_2, 2
.equ obj_R44_gswoman3, 3
.equ obj_R44_gsman3, 4
.equ obj_R44_mania, 5
.equ obj_R44_gsman2, 6
.equ obj_R44_bonguri, 7
.equ obj_R44_monstarball, 8
.equ obj_R44_monstarball_2, 9
.equ obj_R44_monstarball_3, 10
.equ obj_R44_gsmiddleman1, 0

.endif //SCR_SEQ_R44_H_
