.ifndef SCR_SEQ_R37_H_
.definelabel SCR_SEQ_R37_H_, 0

.equ _EV_scr_seq_R37_000, 0
.equ _EV_scr_seq_R37_001, 1
.equ _EV_scr_seq_R37_002, 2
.equ _EV_scr_seq_R37_003, 3

.equ obj_R37_gsbabygirl1, 0
.equ obj_R37_gsbabygirl1_2, 1
.equ obj_R37_mystery_2, 2
.equ obj_R37_gsbabyboy1, 3
.equ obj_R37_bonguri, 4
.equ obj_R37_bonguri_2, 5
.equ obj_R37_bonguri_3, 6
.equ obj_R37_gswoman2, 7
.equ obj_R37_gswoman2_2, 8

.endif //SCR_SEQ_R37_H_
