Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 0
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 2:
	MecScript 
	LockAll 
	Message 9
	OpenTouchScreen 
	YesNoTouchScreen 0x800C
	CloseTouchScreen 
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
End 


Script 3:
	MecScript 
	LockAll 
	CMD_151 
	Message 12
	CMD_257 94
	CloseMessage 
	CMD_587 
	CMD_449 97 2
	CloseMessage 
	ReleaseAll 
End 


