Script 1:
	SetFlag 439
	SetVar 0x4125 0
	CompareVarValue 0x4077 4
	JumpIf DIFFERENT Function#1
	ClearFlag 439
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 7
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 3:
	CompareVarValue 0x4077 4
	JumpIf EQUAL Function#2
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 6
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 4:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 8
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


