Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	PlayCry 131 0
	WaitCry 
	SetFlag 164
	WildBattleSp 131 20 0
	ClearFlag 164
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	SetFlag 2744
	ReleaseAll 
End 


Script 2:
	CheckFlag 164
	JumpIf EQUAL Function#2
End 


Script 3:
	CheckFlag 2744
	JumpIf EQUAL Function#3
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#4
	ClearFlag 778
Jump Function#5


