Action 1:
	WalkUp 0x2
End


Action 2:
	WalkDownFastSite 0x1
End


Action 3:
	Freeze8 0x6
	WalkUpFast 0x1
End


Action 4:
	Freeze8 0x5
	WalkLeftFast 0x2
End


Action 5:
	WalkLeftFast 0x1
	WalkUpFast 0x6
End


Action 6:
	Freeze8 0x5
	WalkRightFast 0x2
End


Action 7:
	WalkRightFast 0x1
	WalkUpFast 0x6
End


Action 8:
	LookRight 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
End


Action 9:
	WalkRight 0x2
End


Action 10:
	WalkDown 0x2
End


Action 11:
	WalkUp 0x2
End


Action 12:
	WalkLeft 0x2
End


Action 13:
	LookUp 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
	LookRight 0x1
	Freeze2 0x1
End


Action 14:
	LookRight 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
End


Action 15:
	LookLeft 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
	LookRight 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
End


Action 16:
	LookDown 0x1
	Freeze2 0x1
	LookRight 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
End


Action 17:
	LookUp 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
	LookRight 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
End


Action 18:
	LookRight 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
	LookRight 0x1
	Freeze2 0x1
End


Action 19:
	LookLeft 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
	LookRight 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
End


Action 20:
	LookDown 0x1
	Freeze2 0x1
	LookRight 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
End


Action 21:
	WalkUp 0x1
End


