Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CompareVarValue 0x4002 1
	JumpIf GREATER/EQUAL Function#1
	Message 0
	OpenTouchScreen 
	YesNoTouchScreen 0x800C
	CloseTouchScreen 
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	CompareVarValue 0x800C 1
	JumpIf GREATER/EQUAL Function#3
End 


Script 2:
	CMD_147 34 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#4
	CheckFlag 2404
	JumpIf EQUAL Function#5
Jump Function#4


