Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 0
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 2:
	NationalDex 2 0x4000
	CompareVarValue 0x4000 1
	JumpIf EQUAL Function#1
	SetOWPosition Overworld.1 30 1 30 Up
	SetOWPosition Overworld.2 30 1 30 Up
	SetOWPosition Overworld.3 30 1 30 Up
	SetOWPosition Overworld.4 30 1 30 Up
	SetOWPosition Overworld.5 30 1 30 Up
	SetOWPosition Overworld.6 30 1 30 Up
End 


