Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CompareVarValue 0x40CB 6
	JumpIf GREATER/EQUAL Function#1
	CompareVarValue 0x40CB 4
	JumpIf EQUAL Function#2
	Message 4
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	Message 0
	CloseMessage 
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#3
	Movement Overworld.1 Action#1
Jump Function#4


Script 3:
	CompareVarValue 0x40CB 4
	JumpIf GREATER/EQUAL Function#5
End 


