Action 1:
	Exclamation 0x1
	Freeze8 0x1
	LookRight 0x2
	LookLeft 0x2
	LookRight 0x2
	LockDir 0x1
	JumpLeft2 0x1
	ReleaseDir 0x1
End


Action 2:
	LookUp 0x2
	WalkUpVeryFast 0x2
	LookRight 0x2
	WalkRightVeryFast 0x4
	LookDown 0x2
	WalkDownVeryFast 0x1
End


Action 3:
	Freeze16 0x1
	LookRight 0x2
	WalkRightFast 0x1
	LookUp 0x2
End


Action 4:
	LookUp 0x2
	WalkUpVeryFast 0x7
End


Action 5:
	LookDown 0x2
	Freeze16 0x1
	Exclamation 0x1
End


Action 6:
	LookRight 0x2
	JumpRight 0x1
End


Action 7:
	Exclamation 0x1
	Freeze8 0x1
	LookLeft 0x2
	LookRight 0x2
	LookLeft 0x2
	LockDir 0x1
	JumpRight2 0x1
	ReleaseDir 0x1
End


Action 8:
	LookUp 0x2
	WalkUpVeryFast 0x2
	LookLeft 0x2
	WalkLeftVeryFast 0x4
	LookDown 0x2
	WalkDownVeryFast 0x1
End


Action 9:
	Freeze16 0x1
	LookLeft 0x2
	WalkLeftFast 0x1
	LookUp 0x2
End


Action 10:
	LookUp 0x2
	WalkUpVeryFast 0x3
	LookRight 0x2
	WalkRightVeryFast 0x4
	LookUp 0x2
	WalkUpVeryFast 0x4
End


