Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CheckFlag 309
	JumpIf EQUAL Function#1
	TextPlayerName 0
	GenderMessage 0 1
	SetVar 0x8004 44
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	CommonScript 2033
	SetFlag 309
	Message 2
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 3
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


