Action 1:
	LookDown 0x1
End


Action 2:
	Exclamation 0x1
	WalkDownFast 0x1
	WalkRightFast 0x2
	WalkUpFast 0x3
	WalkRightFast 0x5
	WalkUpFast 0x2
End


Action 3:
	Freeze32 0x2
	WalkUpFast 0x1
	LookDown 0x1
	Freeze16 0x1
	LookRight 0x1
End


Action 4:
	Freeze32 0x4
	LookDown 0x1
End


Action 5:
	WalkDownFast 0x2
	WalkLeftFast 0x5
	LookUp 0x1
End


Action 6:
	Freeze8 0x7
	LookDown 0x1
End


Action 7:
	WalkDownFast 0x3
	WalkLeftFast 0x2
	WalkUpFast 0x1
	WalkDownFastSite 0x1
End


Action 8:
	WalkLeftFastSite 0x1
	Freeze2 0x1
	WalkLeftFastSite 0x1
	Freeze2 0x1
	WalkLeftFastSite 0x1
End


Action 9:
	LookUp 0x1
End


