Script 1:
	PlayFanfare 1500
	LockAll 
	CMD_779 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 2
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 2:
	CheckFlag 164
	JumpIf EQUAL Function#2
	CheckFlag 249
	JumpIf EQUAL Function#3
End 


Script 3:
	SetIconBoard 0 1 2 0x800C
	ShowBoard 3
	WaitBoard 
	CloseBoard 0x800C
	CommonScript 2000
End 


Script 4:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard 
	BoardMessage 1 0x800C
	CommonScript 2000
End 


