Action 1:
	DisappearTrue 0x1
End


Action 2:
	Exclamation 0x1
End


Action 3:
	WalkLeftFast 0x2
	WalkUpFast 0x1
	WalkLeftFast 0x1
End


Action 4:
	Freeze8 0x1
	DisappearFalse 0x1
	WalkLeftFast 0x2
	WalkUpFast 0x1
	WalkLeftFastSite 0x1
End


Action 5:
	WalkLeftFast 0x2
	WalkUpFast 0x1
	WalkLeftFast 0x2
End


Action 6:
	Freeze8 0x1
	DisappearFalse 0x1
	WalkLeftFast 0x2
	WalkUpFast 0x1
	WalkLeftFast 0x1
End


Action 7:
	WalkLeftFast 0x3
End


Action 8:
	Freeze8 0x1
	DisappearFalse 0x1
	WalkLeftFast 0x2
End


Action 9:
	WalkLeftFast 0x4
End


Action 10:
	Freeze8 0x1
	DisappearFalse 0x1
	WalkLeftFast 0x3
End


Action 11:
	WalkRightFastSite 0x1
End


Action 12:
	JumpLeftSite 0x2
End


Action 13:
	WaitWalkBackDown 0x1
	WaitWalkBackLeft 0x6
	DisappearTrue 0x1
End


Action 14:
	Freeze2 0x1
	WalkLeftVeryFast 0x1
	WalkDownVeryFast 0x1
	WalkLeftVeryFast 0x6
	DisappearTrue 0x1
End


Action 15:
	WalkLeftFast 0x2
	WalkDownFast 0x1
	WalkLeftFast 0x1
End


Action 16:
	Freeze8 0x1
	DisappearFalse 0x1
	WalkLeftFast 0x2
	WalkDownFast 0x1
	WalkLeftFastSite 0x1
End


Action 17:
	WalkLeftFast 0x2
	WalkDownFast 0x1
	WalkLeftFast 0x2
End


Action 18:
	Freeze8 0x1
	DisappearFalse 0x1
	WalkLeftFast 0x2
	WalkDownFast 0x1
	WalkLeftFast 0x1
End


Action 19:
	WaitWalkBackDown 0x1
	WaitWalkBackLeft 0x5
	DisappearTrue 0x1
End


Action 20:
	Freeze2 0x1
	WalkLeftVeryFast 0x1
	WalkDownVeryFast 0x1
	WalkLeftVeryFast 0x5
	DisappearTrue 0x1
End


Action 21:
	WaitWalkBackDown 0x1
	WaitWalkBackLeft 0x4
	WaitWalkBackUp 0x1
	WaitWalkBackLeft 0x2
	DisappearTrue 0x1
End


Action 22:
	Freeze2 0x1
	WalkLeftVeryFast 0x1
	WalkDownVeryFast 0x1
	WalkLeftVeryFast 0x4
	WalkUpVeryFast 0x1
	WalkLeftVeryFast 0x2
	DisappearTrue 0x1
End


Action 23:
	WaitWalkBackDown 0x1
	WaitWalkBackLeft 0x3
	WaitWalkBackUp 0x1
	WaitWalkBackLeft 0x2
	DisappearTrue 0x1
End


Action 24:
	Freeze2 0x1
	WalkLeftVeryFast 0x1
	WalkDownVeryFast 0x1
	WalkLeftVeryFast 0x3
	WalkUpVeryFast 0x1
	WalkLeftVeryFast 0x2
	DisappearTrue 0x1
End


Action 25:
	WalkLeftVeryFastSite 0x1
End


Action 26:
	WaitWalkBackUp 0x1
	WaitWalkBackLeft 0x6
	DisappearTrue 0x1
End


Action 27:
	Freeze2 0x1
	WalkLeftVeryFast 0x1
	WalkUpVeryFast 0x1
	WalkLeftVeryFast 0x6
	DisappearTrue 0x1
End


Action 28:
	WaitWalkBackUp 0x1
	WaitWalkBackLeft 0x5
	DisappearTrue 0x1
End


Action 29:
	Freeze2 0x1
	WalkLeftVeryFast 0x1
	WalkUpVeryFast 0x1
	WalkLeftVeryFast 0x5
	DisappearTrue 0x1
End


