Action 1:
	LookLeft 0x1
End


Action 2:
	LookUp 0x1
End


Action 3:
	WalkLeftFastSite 0x1
End


Action 4:
	WalkDownFast 0x1
	WalkLeftFast 0x4
End


Action 5:
	WalkDownFast 0x1
	WalkLeftFast 0x1
End


Action 6:
	LookLeft 0x1
End


Action 7:
	WalkRightFast 0x1
	WalkDownFast 0x2
	WalkLeftFast 0x2
End


