Action 1:
	Exclamation 0x1
	RunDown 0x3
	RunRight 0x2
	LookDown 0x1
End


Action 2:
	Freeze8 0x6
	LookDown 0x1
	Exclamation 0x1
	RunDown 0x3
	RunLeft 0x1
	LookDown 0x1
End


Action 3:
	Freeze8 0x6
	LookUp 0x1
	Exclamation 0x1
	RunUp 0x4
	RunRight 0x1
	LookUp 0x1
End


Action 4:
	Exclamation 0x1
	RunUp 0x4
	RunLeft 0x2
	LookUp 0x1
End


Action 5:
	Freeze4 0x3
	RunLeft 0x2
	RunUp 0x3
	LookDown 0x1
End


Action 6:
	RunRight 0x1
	RunUp 0x3
End


Action 7:
	Freeze4 0x3
	RunLeft 0x1
	RunDown 0x4
End


Action 8:
	RunRight 0x2
	RunDown 0x4
	LookUp 0x1
End


