Script 1:
	PlayFanfare 1500
	LockAll 
	SetVar 0x8000 1
Jump Function#1


Script 2:
	PlayFanfare 1500
	LockAll 
	SetVar 0x8000 1
Jump Function#2


Script 3:
	PlayFanfare 1500
	LockAll 
	SetVar 0x8000 2
Jump Function#3


Script 4:
	PlayFanfare 1500
	LockAll 
	SetVar 0x8000 5
Jump Function#4


Script 5:
	PlayFanfare 1500
	LockAll 
	SetVar 0x8000 4
Jump Function#5


Script 6:
	PlayFanfare 1500
	LockAll 
	SetVar 0x8000 6
Jump Function#6


