Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 0
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 1
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 3:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	PlayCry 21 0
	Message 2
	WaitCry 
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 4:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	PlayCry 19 0
	Message 3
	WaitCry 
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


