Script 1:
	SetVar 0x8007 0
	CommonScript 2002
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CheckFlag 371
	JumpIf EQUAL Function#1
	Message 0
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 3:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 2
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 4:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 3
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


