Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 0
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 1
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 3:
	PlayFanfare 1500
	LockAll 
	Message 2
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 4:
	PlayFanfare 1500
	LockAll 
	Message 3
	ShowMoney 20 2
Jump Function#1


