Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	GetElevatorFloor 0x4113
	SetVarFromVariable 0x8008 0x4113
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#1
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#2
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#3
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#4
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#5
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#6
End 


