Action 1:
	WalkUpFast 0x3
	WalkDownFastSite 0x1
End


Action 2:
	WalkUpFast 0x1
	WalkLeftFast 0x1
	WalkUpFast 0x3
	WalkDownFastSite 0x1
End


Action 3:
	Freeze8 0x1
	WalkUpFastSite 0x1
End


Action 4:
	WalkRightFast 0x1
	WalkUpFast 0x1
	LookDown 0x1
End


Action 5:
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
End


Action 6:
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
End


Action 7:
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
End


