Action 1:
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
End


Action 2:
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
End


Action 3:
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
End


Action 4:
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
End


Action 5:
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
End


Action 6:
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
End


Action 7:
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
End


Action 8:
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
End


