Action 1:
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
End


Action 2:
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
End


Action 3:
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
End


