Action 1:
	LookDown 0x2
	LookLeft 0x2
	LookUp 0x2
	LookRight 0x2
	LookDown 0x2
	LookLeft 0x2
	LookUp 0x2
	LookRight 0x2
	LookDown 0x2
	LookLeft 0x2
	LookUp 0x2
	LookRight 0x2
	LookDown 0x2
	LookLeft 0x2
	LookUp 0x2
	LookRight 0x1
	DisappearTrue 0x0
End


