Action 1:
	WalkUpFast 0x2
	WalkDownFastSite 0x1
End


Action 2:
	LookDown 0x1
	WalkDownFast 0x1
	JumpDownSlow 0x3
End


Action 3:
	WalkRightFast 0x1
	WalkUpFast 0x1
	LookDown 0x1
End


Action 4:
	WalkDownFast 0x2
	WalkDownFastSite 0x1
End


