Action 1:
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
End


Action 2:
	Exclamation 0x1
	WalkLeftFast 0x5
	WalkUpFast 0x1
End


Action 3:
	WalkUpFast 0x1
End


Action 4:
	LockDir 0x1
	WalkDown 0x1
	ReleaseDir 0x1
End


Action 5:
	LookRight 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
	LookRight 0x1
	Freeze2 0x1
	LookDown 0x1
	Freeze2 0x1
	LookLeft 0x1
	Freeze2 0x1
	LookUp 0x1
	Freeze2 0x1
End


Action 6:
	WalkDownFast 0x2
	WalkLeftFast 0x1
	WalkDownFast 0x7
End


Action 7:
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
End


Action 8:
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
End


Action 9:
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
End


Action 10:
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
End


Action 11:
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
End


Action 12:
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
End


Action 13:
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
End


Action 14:
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
	LookDown 0x1
	LookRight 0x1
	LookUp 0x1
	LookLeft 0x1
End


Action 15:
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
End


Action 16:
	WalkDownVeryFast 0x8
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	WalkRightVeryFast 0x15
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	WalkUpVeryFast 0x1
	WalkDownFastSite 0x1
End


Action 17:
	Freeze8 0x1
	WaitWalkBackLeft 0x1
	WaitWalkBackDown 0x8
	WalkRightFastSite 0x1
	Freeze4 0x1
	WaitWalkBackRight 0x15
	WalkUpFastSite 0x1
End


Action 18:
	Freeze8 0x1
	WaitWalkBackRight 0x1
	WaitWalkBackDown 0x8
	WalkRightFastSite 0x1
	Freeze4 0x1
	WaitWalkBackRight 0x15
	WalkUpFastSite 0x1
End


Action 19:
	WalkLeftVeryFast 0x2
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	WalkDownVeryFast 0x3
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	WalkRightVeryFast 0x2
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	WalkDownVeryFast 0x5
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	WalkRightVeryFast 0x15
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	WalkUpVeryFast 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
End


Action 20:
	WalkDownVeryFast 0x1
	WalkRightVeryFast 0x1
	WalkLeftVeryFastSite 0x1
	Freeze8 0x2
	WalkDownVeryFastSite 0x1
	Freeze8 0x2
	WalkLeftVeryFast 0x1
	WaitWalkBackDown 0x6
	WalkRightFastSite 0x1
	Freeze4 0x1
	WaitWalkBackRight 0x15
	WalkUpFastSite 0x1
End


Action 21:
	Freeze8 0x1
	WaitWalkBackDown 0x9
	WalkRightFastSite 0x1
	Freeze4 0x1
	WaitWalkBackRight 0x15
	WalkUpFastSite 0x1
End


Action 22:
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
	LookLeft 0x1
	LookUp 0x1
	LookRight 0x1
	LookDown 0x1
End


Action 23:
	WalkUpFast 0x2
End


Action 24:
	WalkUpFast 0x1
End


