Action 1:
	Exclamation 0x1
End


Action 2:
	WalkLeftFast 0x9
	LookUp 0x1
End


Action 3:
	LookRight 0x1
	Freeze4 0x6
	Freeze8 0x7
	LookDown 0x1
End


Action 4:
	WalkLeftFastSite 0x2
End


Action 5:
	LockDir 0x1
	RunLeft 0x1
	Freeze8 0x2
	WalkLeft 0x2
	ReleaseDir 0x1
	WalkLeftVeryFast 0x9
End


Action 6:
	WalkUpFast 0x2
	WalkDownFastSite 0x1
End


Action 7:
	WalkLeftFast 0x9
	LookDown 0x1
End


Action 8:
	LookRight 0x1
	Freeze4 0x6
	Freeze8 0x7
	LookUp 0x1
End


Action 9:
	WalkLeftFast 0x3
End


Action 10:
	WalkLeftFast 0x1
	WalkUpFast 0x1
	WalkLeftFast 0x2
End


Action 11:
	WalkLeftFast 0x1
	WalkUpFast 0x2
	WalkLeftFast 0x2
End


