Script 1:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CheckFlag 123
	JumpIf EQUAL Function#1
	Message 0
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CheckFlag 128
	JumpIf EQUAL Function#2
	Message 3
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 3:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	PlayCry 83 0
	Message 8
	WaitCry 
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


