Script 1:
	SetVar 0x8007 3
	CommonScript 2002
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	Message 0
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Script 3:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CountPCFreeSpace 0x800C
	CompareVarValue 0x800C 540
	JumpIf DIFFERENT Function#1
Jump Function#2


Script 4:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CheckBadge 4 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#3
	Message 2
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


