Script 1:
	SetVar 0x8007 0
	CommonScript 2002
End 


Script 2:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#1
	Message 1
Jump Function#2


Script 3:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#3
	Message 5
Jump Function#4


Script 4:
	PlayFanfare 1500
	LockAll 
	FacePlayer 
	CompareVarValue 0x4077 3
	JumpIf DIFFERENT Function#5
	Message 3
Jump Function#6


