Function 1:
	Message 1
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Function 2:
	Message 2
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Function 3:
	Message 3
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Function 4:
	Message 4
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Function 5:
	Message 5
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


Function 6:
	Message 6
	WaitButton 
	CloseMessage 
	ReleaseAll 
End 


