Action 1:
	LookDown 0x2
	LookLeft 0x2
	LookUp 0x2
	LookRight 0x2
	LookDown 0x2
	LookLeft 0x2
	LookUp 0x2
	LookRight 0x2
	LookDown 0x2
	LookLeft 0x2
	LookUp 0x2
	LookRight 0x2
	LookDown 0x2
	LookLeft 0x2
	LookUp 0x2
	LookRight 0x1
	DisappearTrue 0x0
End


Action 2:
	LookLeft 0x1
	Exclamation 0x1
	WalkLeftFast 0x2
End


Action 3:
	Freeze8 0x5
	LookRight 0x1
End


Action 4:
	LookLeft 0x1
	Exclamation 0x1
	WalkLeftFast 0x1
End


Action 5:
	Freeze8 0x4
	LookRight 0x1
End


Action 6:
	WalkRightFast 0x2
	LookDown 0x1
End


Action 7:
	LookLeft 0x1
	Exclamation 0x1
End


Action 8:
	Freeze8 0x2
	LookRight 0x1
End


Action 9:
	WalkRightFast 0x1
	LookDown 0x1
End


Action 10:
	LookDown 0x1
End


