import os
import pathlib
import sys
from string import Template

FILE_OUTPUT = """#include "../../include/battle.h"
#include "../../include/test_battle.h"
#include "../../include/constants/species.h"
#include "../../include/constants/moves.h"
#include "../../include/constants/item.h"
#include "../../include/constants/ability.h"
#include "../../include/constants/battle_message_constants.h"

#ifdef DEBUG_BATTLE_SCENARIOS
const struct TestBattleScenario BattleTests[] = {

#define GET_TEST_CASE_ONLY

${tests}

};
#endif // DEBUG_BATTLE_SCENARIOS
"""


def keywords_in_string(string: str, keywords: list[str]) -> bool:
    for keyword in keywords:
        if keyword.lower() in string.lower():
            return True
    return False


def keywords_in_file(file_path: str, keywords: list[str]) -> bool:
    try:
        with open(file_path, "r") as file:
            file_contents = file.read()
            return keywords_in_string(file_path, keywords) or keywords_in_string(
                file_contents, keywords
            )
    except (IOError, UnicodeDecodeError):
        print(f"Could not read file: {file_path}")
        return False


def write_test_battle_header(test_count):
    out_path = "include/constants/generated/test_battle.h"
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, "w") as f:
        f.write("// AUTO-GENERATED FILE — DO NOT EDIT\n")
        f.write("// Generated by build_tests.py\n\n")
        f.write("#ifndef GENERATED_TESTBATTLE_CONSTANTS_H\n")
        f.write("#define GENERATED_TESTBATTLE_CONSTANTS_H\n\n")
        f.write(f"#define TEST_BATTLE_TOTAL_TESTS {test_count}\n\n")
        f.write("#endif // GENERATED_TESTBATTLE_CONSTANTS_H\n")


def main() -> None:
    filter_keywords = sys.argv[1:]
    template = Template(FILE_OUTPUT)
    data_folder = pathlib.Path(os.path.join(os.getcwd(), "data"))
    build_folder = pathlib.Path(os.path.join(os.getcwd(), "build", "battle_tests"))
    battle_tests_root_folder = pathlib.Path(data_folder, "battle_tests")
    files = battle_tests_root_folder.rglob("*c")

    if len(filter_keywords) > 0:
        files = list(filter(lambda x: keywords_in_file(str(x), filter_keywords), files))

    test_files = [
        f'#include "../../data/{os.path.relpath(file, data_folder)}"'
        for file in sorted(files)
    ]

    tests = "\n".join(test_files)

    os.makedirs(build_folder, exist_ok=True)
    with open(os.path.join(build_folder, "BattleTests.c"), "w") as file:
        file.write(template.substitute({"tests": tests}))

    write_test_battle_header(len(test_files))


if __name__ == "__main__":
    main()
